### ISSUE TITLE
bug: CascadingParameter is null

### ISSUE THREAD

**Issue by kibela2210** [dotnetcore/BootstrapBlazor#1009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i try pass CascadingParameter  from mainlayout to index
but it no work 
it just happen in this template

### Expected Behavior

please tell me about this

### .NET Version

7.0

**Comment by ArgoZhang** [comment]
@kibela2210 I don't quite follow you. which component or which class?

**Comment by kibela2210** [comment]
<Main>
        <CascadingValue Value="@abc" >
            @Body
        </CascadingValue>
    </Main>
 i input value in mainLayout like this with 
public int abc{ get; set; } = 100;
then get CascadingParameter int Index
 [CascadingParameter]
    public int abc{ get; set; }
But abc is null in Index

**Comment by kibela2210** [comment]
<Main>
        <CascadingValue Value="@concac" >
            @Body
        </CascadingValue>
    </Main>

**Comment by kibela2210** [comment]
<Main>
        <CascadingValue Value="@abc" >
            @Body
        </CascadingValue>
    </Main>

**Comment by kibela2210** [comment]
> @kibela2210 I don't quite follow you. which component or which class?

component or class is the same

**Comment by ArgoZhang** [comment]
@kibela2210 could you provider a repo project? thanks

**Comment by kibela2210** [comment]
> @kibela2210 could you provider a repo project? thanks

https://github.com/kibela2210/demo.git

this is example for my case

**Comment by Vision-Zhang** [comment]
@kibela2210 Try the CascadingValue tag written on the outermost layer

**Comment by kibela2210** [comment]
> @kibela2210 Try the CascadingValue tag written on the outermost layer

thank you! it worked <#

**Comment by smithlogi** [comment]
> [@kibela2210](https://github.com/kibela2210) Try the CascadingValue tag written on the outermost layer

worked, but i don't know why...
