### ISSUE TITLE
Upgrade to Bootstrap CSS v5.0

### ISSUE THREAD

**Issue by hxmcn** [dotnetcore/BootstrapBlazor#101]
Bootstrap CSS has release v5.0  about 2 months ago, the latest version is 5.0.2:
https://github.com/twbs/bootstrap/releases/tag/v5.0.2

Our product needs new features of Bootstrap 5, when will BootstrapBlazor take bootstrap v5?

**Comment by ArgoZhang** [comment]
thanks for contacting us. We plan to upgrade to bootstrap V5 next month. later I will create a new milestone for this

**Comment by hxmcn** [comment]
Got it, thanks for your quick response! @ArgoZhang

**Comment by ArgoZhang** [comment]
@hxmcn hi, I pushed some commits into the `dev-bs5` branch. you can track it follow this branch.

**Comment by ArgoZhang** [comment]
@hxmcn hi, now dev-bs5 is ready to merge into the dev branch. but `summernote` component not compatible with bootstrap v5. so this component can not upgrade to v5.

**Comment by ArgoZhang** [comment]
@hxmcn it's done.
