### ISSUE TITLE
feat: 建议图表在StateHasChanged之后能够自动触发对OnInitAsync的调用，目前每次需要显示地调用Reload才能刷新

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#1016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

1. 建议在调用了StateHasChanged之后能够自动触发对OnInitAsync的调用来刷新图表数据。
2. 把`@ref="BarChart1"`这样的代码隐藏规避掉，在内部实现，不必让开发者显示地绑定，这样代码就会非常简洁。

全程就不用出现一堆声明和调用，类似：
```
    private Chart BarChart1 { get; set; }
    private Chart PieChart { get; set; }
    private Chart BarChart2 { get; set; }

        await BarChart1.Reload();
        await PieChart.Reload();
        await BarChart2.Reload();

```

**Comment by ArgoZhang** [comment]
@bigsinger 我考虑了一下

**Comment by ArgoZhang** [comment]
@bigsinger 这个问题我考虑了一下。解释如下：

1. 性能考虑

比如使用者通过使用级联传参的方式使用会导致后代组件（此时后代组件内可能有 `Chart` 组件）这时 `StateHasChanged` 时其实是不需要触发 `OnInitAsnc` 重新获取数据，重新渲染 HTML UI 的。目前的设计大大提高了性能 （出于这样的考虑，所以设计的时候就是使用 `ref` 显示调用重绘组件的）

2. 目前使用者有一定的基数

如果按照你的建议去更改，老用户升级后会报错，或者由于使用不当导致 double render 这也是不合理的

所以暂时维持原状

**Comment by bigsinger** [comment]
> @bigsinger 这个问题我考虑了一下。解释如下：
> 
> 1. 性能考虑
> 
> 比如使用者通过使用级联传参的方式使用会导致后代组件（此时后代组件内可能有 `Chart` 组件）隐式调用 `StateHasChanged` 这时 `Chart` 组件自身的 `StateHasChanged` 其实是不需要触发 `OnInitAsnc` 重新获取数据，重新渲染 HTML UI 的。目前的设计大大提高了性能 （出于这样的考虑，所以设计的时候就设计成使用 `ref` 显示调用重绘组件的）
> 
> 2. 目前使用者有一定的基数
> 
> 如果按照你的建议去更改，老用户升级后会报错，或者由于使用不当导致 double render 这也是不合理的
> 
> 所以暂时维持原状

实现方式不一定局限于此。  目前先这样用着，期待会有更好的方式。

**Comment by ArgoZhang** [comment]
@bigsinger 听你这口气，感觉还有更好的方法啊。大佬不要藏着掖着，帮忙贡献啊

**Comment by bigsinger** [comment]
目前优化了一下，简单的方案如下：
```
/// <summary>
/// 优化：无须为图表控件绑定变量，业务代码更加简洁。在需要重新初始化图表的时候调用 StateHasChanged 即可自动刷新。
/// </summary>
public class MyChart : BootstrapBlazor.Components.Chart {
    bool isUserRender = false;
    protected override async Task OnAfterRenderAsync(bool firstRender) {
        if (isUserRender) {
            await Reload();
            return;
        } else if (!firstRender) {
            isUserRender = true;
        }
        await base.OnAfterRenderAsync(firstRender);
    }
}
```

业务层面只需要变更数据源即可。
```
<MyChart ChartType="ChartType.Line" OnInitAsync='() => Task.FromResult(Helper.dsAmount)' />
```
变更后调用下  `await InvokeAsync(StateHasChanged);`  即可。

再也不用大量绑定变量了，极大简化业务代码。需要的人可以借鉴参考。
