### ISSUE TITLE
feat: 饼图添加ChartDataset未设置label时自动使用，而不是显示"未设置"

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#1026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

例如如下饼图数据源：
```
        ds.Labels = orderDic.Keys;
        ds.Data.Add(new ChartDataset { Data = list.Cast<object>() });
```
运行后鼠标悬停在某块会显示“未设置”。

建议：ChartDataset 里没有设置label时可以使用ds.Labels里的，按索引顺序使用即可。

当然这个倒不是严重的问题，作者看情况吧。

**Comment by azlis** [comment]
新增一个option ShowPieScales 默认false怎么样

**Comment by ArgoZhang** [comment]
@azlis 这个我觉得可以做一下。是不是没给值 就不显示了。不需要显示一个 `未设置`

**Comment by bigsinger** [comment]
> @azlis 这个我觉得可以做一下。是不是没给值 就不显示了。不需要显示一个 `未设置`

赞同，可以不显示，没有意义。

**Comment by azlis** [comment]
update in pr #1074
