### ISSUE TITLE
feat(Chart): do not show scales and grid by default Pie/Doughnut

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#1027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

```
        ds.Options.ShowXLine = false;
        ds.Options.ShowYLine = false;
        ds.Options.ShowXScales = false;
        ds.Options.ShowYScales = false;
```
饼图不需要XY坐标轴以及网格，可以在内部默认处理掉。

如果不好通用设计，可以从ChartDataSource派生一个类，然后默认处理饼图的配置，简化使用。

**Comment by bigsinger** [comment]
如果不好通用设计，可以从ChartDataSource派生一个类，然后默认处理饼图的配置，简化使用。

**Comment by ArgoZhang** [comment]
@bigsinger 这些参数要保持与 `Chart.js` 一致
@azlis

**Comment by bigsinger** [comment]
> 

我上面列举的就是现存的参数，没有改过，只是建议内部默认掉即可。

**Comment by azlis** [comment]
新增一个option ShowPieScales 默认false怎么样

**Comment by ArgoZhang** [comment]
> 新增一个option ShowPieScales 默认false怎么样

这些参数默认值与 `Chart.js` 官网的保持一致就可以啦。对初学者跟高级使用者都友好，千万别改默认值

**Comment by bigsinger** [comment]
> > 新增一个option ShowPieScales 默认false怎么样
> 
> 这些参数默认值与 `Chart.js` 官网的保持一致就可以啦。对初学者跟高级使用者都友好，千万别改默认值

不是很赞同。  初学者必须通过官网demo才可以写得来的，只要官网文档和示例源码够清楚，入门是很简单的事情。

**Comment by ArgoZhang** [comment]
> > > 新增一个option ShowPieScales 默认false怎么样
> > 
> > 
> > 这些参数默认值与 `Chart.js` 官网的保持一致就可以啦。对初学者跟高级使用者都友好，千万别改默认值
> 
> 不是很赞同。 初学者必须通过官网demo才可以写得来的，只要官网文档和示例源码够清楚，入门是很简单的事情。

这个不是你赞同不赞同的问题，而是保持一致的问题。不能为了照顾新手，而改变游戏规则。原版默认值是 true 为了照顾新手，我们的组件改成 false 相反给精通 `Chart.js` 的人带来新坑跟迷惑

**Comment by bigsinger** [comment]
> > > > 新增一个option ShowPieScales 默认false怎么样
> > > 
> > > 
> > > 这些参数默认值与 `Chart.js` 官网的保持一致就可以啦。对初学者跟高级使用者都友好，千万别改默认值
> > 
> > 
> > 不是很赞同。 初学者必须通过官网demo才可以写得来的，只要官网文档和示例源码够清楚，入门是很简单的事情。
> 
> 这个不是你赞同不赞同的问题，而是保持一致的问题。不能为了照顾新手，而改变游戏规则。原版默认值是 true 为了照顾新手，我们的组件改成 false 相反给精通 `Chart.js` 的人带来新坑跟迷惑

1、实在不能理解饼图带有网格以及xy坐标轴的意义点在哪里？相反出现这些特征才会让人困惑。
2、如果从一致性的角度出发。https://github.com/dotnetcore/BootstrapBlazor给出的饼图的图片示例效果与https://app.blazor.zone/charts/pie文档的图片示例效果也不一致，这种不一致也会让人困惑。

**Comment by ArgoZhang** [comment]
@bigsinger 这个我也太清楚，这个组件是 @azlis 大佬维护呢，如果 `Chart.js` 默认是不显示的，那么我们也应该不显示，保持一致，如果我们默认显示了，我们就要改，如果 `Chart.js` 默认是显示的，大佬可以去他们的仓库提交 Issue

**Comment by ArgoZhang** [comment]
尽量访问 www.blazor.zone 而不要访问 app.blazor.zone 那个是我们的测试环境。没更新

**Comment by ArgoZhang** [comment]
@azlis 我记得 `Chart.js` V3 版本 pie 确实是没有网格线跟坐标的。是不是 4.2 版本他们改了默认值

**Comment by ArgoZhang** [comment]
@bigsinger 你的疑问是合理的。我们确认一下。

**Comment by bigsinger** [comment]
> ArgoZhang



> @bigsinger 你的疑问是合理的。我们确认一下。

感谢理解。我本身发现这个问题以及自己可以解决，但是坚持提议是为了BootstrapBlazor可以做得更出色，谢谢理解，也谢谢提供这么方便的组件。

**Comment by ArgoZhang** [comment]
@bigsinger 没关系的。建议是合理的。我们都会采纳的。但是确实我们更新了 chart.js 包版本，我们再确认一下。能做的我们都是尽量满足你们的需求

**Comment by ArgoZhang** [comment]
@bigsinger 已确认，他们官网的是默认没有网格线跟坐标的。我们调整一下

**Comment by ArgoZhang** [comment]
@bigsinger @azlis 已发包 `Chart v7.5.2`
