### ISSUE TITLE
feat: 给饼图的一些建议

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#1028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

1. 自动计算百分比，当然也可以设计是否计算百分比由参数配置来定，可选，默认计算。百分比小数点后保留2位有效数字。
2. 饼图在某块悬停时显示两个内容：数量、百分比。这样方便看原始数据的数量以及占比情况，百分比记得追加一个百分号%，阅读体验更好。这样ChartDataset的Label也可以不用设置了，因为一个是数量，一个是百分比。
3. 饼图按照数量多少（或占比多少）从高到低排序，更符合使用习惯。
4. 配置一个选项：`keepTopN`  一般来说我们看占比，对于前N个排名的感兴趣，后面非常小的可以忽略不计的，可以统一放到一个`Others`里面即可。  keepTopN<=0时表示不处理，大于零时才处理。

综上，使用者只需要提供一个原始序列的数据和一个keepTopN（也可以不设置，默认为0），然后内部实现就是先排序，然后取前N个，剩余的归到`Others`，然后计算百分比。然后参考[feat: 饼图以下的选项默认掉 · Issue #1027 · dotnetcore/BootstrapBlazor](https://github.com/dotnetcore/BootstrapBlazor/issues/1027)  ，这样无论使用和展示体验都非常好。

**Comment by azlis** [comment]
Chart组件的功能来源于开源JS组件库Chart.JS，可以参考[Chart.JS官方文档](https://www.chartjs.com.cn/docs/)。
如果想要实现更加细致化的图表操作，可以参考BootstrapBlazor官方网站中的```折线图Demo```[通过JS生成Chart](https://www.blazor.zone/charts/line#LineChartJS)。

**Comment by bigsinger** [comment]
> Chart组件的功能来源于开源JS组件库Chart.JS，可以参考[Chart.JS官方文档](https://www.chartjs.com.cn/docs/)。 如果想要实现更加细致化的图表操作，可以参考BootstrapBlazor官方网站中的`折线图Demo`[通过JS生成Chart](https://www.blazor.zone/charts/line#LineChartJS)。

@ArgoZhang @azlis 
我可能没有表述清楚，这里解释下：

1. 描述的是饼图的建议，与折线图无关。
2. 这些建议与chart.js不存在冲突，目前在业务代码层已经实现了，但是可以在BootstrapBlazor组件中封装掉，这样易用性和显示效果都会好很多。

**Comment by bigsinger** [comment]
> > Chart组件的功能来源于开源JS组件库Chart.JS，可以参考[Chart.JS官方文档](https://www.chartjs.com.cn/docs/)。 如果想要实现更加细致化的图表操作，可以参考BootstrapBlazor官方网站中的`折线图Demo`[通过JS生成Chart](https://www.blazor.zone/charts/line#LineChartJS)。
> 
> @ArgoZhang @azlis 我可能没有表述清楚，这里解释下：
> 
> 1. 描述的是饼图的建议，与折线图无关。
> 2. 这些建议与chart.js不存在冲突，目前在业务代码层已经实现了，但是可以在BootstrapBlazor组件中封装掉，这样易用性和显示效果都会好很多。

1、实在不能理解饼图带有网格以及xy坐标轴的意义点在哪里？相反出现这些特征才会让人困惑。
2、如果从一致性的角度出发。https://github.com/dotnetcore/BootstrapBlazor给出的饼图的图片示例效果与https://app.blazor.zone/charts/pie文档的图片示例效果也不一致，这种不一致也会让人困惑。
