### ISSUE TITLE
Script purpose

### ISSUE THREAD

**Issue by david-c-stein** [dotnetcore/BootstrapBlazor#103]
### Describe the bug
It is unclear to me the purpose of the following included scripts

### Further technical details
Scripts are located in:
BootstrapBlazor/src/BootstrapBlazor.Server/Pages/_Host.cshtml

    ...
    <environment include="Staging,Production">
        <script>
            var _hmt = _hmt || [];
            (function () {
                var hm = document.createElement("script");
                hm.src = "https://hm.baidu.com/hm.js?f147c9b2e3e0cc2b629c6390e5ffe377";
                var s = document.getElementsByTagName("script")[0];
                s.parentNode.insertBefore(hm, s);
            })();
        </script>
    </environment>
    ...
    <environment include="Staging,Production">
        <script src="https://wwads.cn/js/makemoney.js" type="text/javascript" async></script>
    </environment>

**Comment by ArgoZhang** [comment]
@david-c-stein hi this is an AD script for the website. It has nothing to do with the project. thank you for contacting us
