### ISSUE TITLE
bug: Table的高度在上方的查询框折叠后不会自动拉伸，在6.x的时候是可以的

### ISSUE THREAD

**Issue by tench** [dotnetcore/BootstrapBlazor#1068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

折叠前：
![image](https://user-images.githubusercontent.com/5379654/233009587-12198c27-6d26-4d69-8a54-f3da5abda855.png)

折叠后：
![image](https://user-images.githubusercontent.com/5379654/233010119-25efc479-057d-4233-b841-b814893b53bc.png)

### .NET Version

6

**Comment by ArgoZhang** [comment]
@tench 提供复现例子

**Comment by tench** [comment]
> @tench 提供复现例子

没有特殊的，就是Table  size 是TableSize.Compact，查询方式是 SearchMode.Top ，表格本身没有设置高度，放在Tab页面里，Tab页的高度是动态的，根据浏览器的大小自动变更 
`.tabs-body {
    background-color: #fff;
    overflow: auto;
    height: calc(100vh - 90px-70px);
}
`

**Comment by tench** [comment]
版本退回去后的效果：
![image](https://user-images.githubusercontent.com/5379654/233242039-c911eb38-83e3-4038-b91f-72224425f323.png)
![image](https://user-images.githubusercontent.com/5379654/233242218-2d20fd52-8e5b-4911-b7fd-47a67a07c452.png)

**Comment by ArgoZhang** [comment]
@tench 请提供复现工程，帮我们节约点时间，第一次就知道是什么问题啦。所有 Issue 都要提供 demo

**Comment by tench** [comment]
> 
不好意思， 终于有时间弄了一下。下面是demo：
[TableDemo.zip](https://github.com/dotnetcore/BootstrapBlazor/files/11303287/TableDemo.zip)

**Comment by ArgoZhang** [comment]
@tench 已下载，稍等回复

**Comment by ArgoZhang** [comment]
@tench 没发现任何 问题啊？

**Comment by tench** [comment]
情况如下：
![image](https://user-images.githubusercontent.com/5379654/233884958-6944624d-25e3-4622-85e6-35d9a892bec6.png)
![image](https://user-images.githubusercontent.com/5379654/233885063-dbb66d5e-f39e-4363-9879-817e325775d6.png)

**Comment by ArgoZhang** [comment]
@tench 截图中 1-20 条，当页应该显示 20条 你这里为啥显示的只有 7 条？

**Comment by tench** [comment]
有滚动条，我的notebook设置的分辨率只有1600X900，所以显示的内容较少。
![image](https://user-images.githubusercontent.com/5379654/233888801-41824a1d-8296-44a0-a05a-c7fae12ba75a.png)

**Comment by tench** [comment]
我好象找到一个地方，旧版的列表部分会根据当前位置自动变更高度。
## 折叠前：
![image](https://user-images.githubusercontent.com/5379654/233889646-1c52f7d8-32bb-49e5-9689-66aed0f7194a.png)
## 折叠后：
![image](https://user-images.githubusercontent.com/5379654/233889809-2357e8eb-9b66-47e8-9f12-1d312ca615d7.png)

**Comment by ArgoZhang** [comment]
请完善复现例子，复现例子与截图明显不一致

**Comment by wapco** [comment]
我也遇到这个问题，终于有人提issues了

**Comment by ArgoZhang** [comment]
> 我也遇到这个问题，终于有人提issues了

复现例子不对，无法修复

**Comment by wapco** [comment]
[Demo地址](https://test-aigo-smgr.oss-cn-hangzhou.aliyuncs.com/BootstrapBlazorApp.rar)

我来提供下吧，很容易复现的，访问/table页面，然后点击收缩搜索框，底下的表格不会自动适应高度。6.x的时候是可以自适应。

**Comment by ArgoZhang** [comment]
@wapco 给可以的例子，不是给不可以的例子。现在 Search 是动画收缩，下面如果给高度会导致整个网页出现滚动条。整个页面抖动

**Comment by wapco** [comment]
我这个demo可以运行并复现了。如果还原到6.x的版本，则高度会正常改变。这个问题不大，所以我没提issues，如果比较麻烦，就不改了吧

**Comment by ArgoZhang** [comment]
@tench @wapco 无效沟通，关闭 Issue

**Comment by ArgoZhang** [comment]
link #1146

**Comment by ArgoZhang** [comment]
@tench @wapco 已更新新 issue https://github.com/dotnetcore/BootstrapBlazor/issues/1146

**Comment by tench** [comment]
> 

收到，谢谢
