### ISSUE TITLE
bug: <title>Chrome 69或其他低版本浏览器，使用封装的bootstrap.js 5.2.3渲染表格时报错，页面一直在闪

### ISSUE THREAD

**Issue by ZenCN** [dotnetcore/BootstrapBlazor#1078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Chrome 69或其他低版本浏览器，使用封装的bootstrap.js 5.2.3渲染表格时报错，页面一直在闪，提示：Unexcepted token，bootstrap 5.2.2版本没有问题

### Expected Behavior

Chrome 69或其他低版本浏览器，使用封装的bootstrap.js 5.2.3渲染表格时报错，页面一直在闪，提示：Unexcepted token，bootstrap 5.2.2版本没有问题

**Comment by ZenCN** [comment]
经测试，BootstrapBlazor 7.0.3 以上版本，在低版本浏览器（如Chrome 69）blazor.bundle.min.js渲染table表格时报错，请楼猪有时间看下，感激涕零！

**Comment by densen2014** [comment]
注意文字表达

**Comment by densen2014** [comment]
有条件的话, f12截图看一下错误, 很有可能是低版本浏览器未支持某些es5/es6标准.

**Comment by ArgoZhang** [comment]
说实话，我看不懂 

`Chrome 69或其他低版本浏览器，使用封装的bootstrap.js 5.2.3渲染表格时报错`

这个跟我们组件有啥关系？

**Comment by ArgoZhang** [comment]
请重新组织语言，如果使用我们 `BootstrapBlazor` 组件请提供测试工程 已经环境版本号如 Chrome 69
