### ISSUE TITLE
table组件数据源；Markdown编辑器无法显示图片；

### ISSUE THREAD

**Issue by 632575987** [dotnetcore/BootstrapBlazor#108]
# Table组件
### 用nuget更新bootstrapblazor到最新版本后之前datatable绑定到数据源不能用了：

```csharp

DataTableDynamicContext = new DataTableDynamicContext(tmpDt)；

```
**（现在构造函数中需要两个参数）**

# Markdown组件貌似有点问题

1. 不能显示图片（直接把图片地址输到浏览器可以正常看到图片，说明图片地址是有效的）；

2. Markdown中的超链接不可点；

3. Markdown显示出来的字体好像有点奇怪，字体不清晰

**Comment by ArgoZhang** [comment]
@632575987 

### Table

请描述清楚，你是报 bug 还是功能需求？

**Comment by 632575987** [comment]
bug

**Comment by 632575987** [comment]
> @632575987
> 
> ### Table
> 请描述清楚，你是报 bug 还是功能需求？

Bug
