### ISSUE TITLE
doc: 官网的一些建议：

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#1081]
### Document describing which component

受益于本组件，也做一下反馈权当做给本组件的一点贡献。
1、在快速上手一节。  把服务端模式+客户端模式+类库安装，统一归类到一个页面里说清楚即可，可以叫【安装使用】，凡是涉及到首次使用需要做的，就在这里面一把说清楚，不要太零散和分散。而且要前置，就是让使用者可以第一时间以最快速的方式用起来。甚至注意事项也可以放进去。

2、https://www.blazor.zone/install-server  这个里面：
BootstrapBlazor 目前支持 net5/net6

NET7不支持？

3、更新日志的传送门过去是主版本的更新历史，就是版本号对不上。

4、页脚底部的，服务1200人在线那个可以删除了，人数太少，反而觉得太小众不可靠，干脆就不要写了。

5、【手风琴效果】开关打开或关闭看不出有什么变化。

6、每个组件的示例代码目前只贴了部分核心代码，直接拿来用不一定可行。建议贴最小可用的完整代码。

7、每个文档建议用markdown的方式布局，在右侧显示当前页面的大纲节点，阅读起来更好。

祝越来越好，我也会在以后的博客中尽量宣传本组件，以后有建议会继续提。

**Comment by ArgoZhang** [comment]
@bigsinger 建议参与改正，我们能力有限，几百个例子，改一版就要 6 个多月。已经被你们这种建议改好几版本了。

**Comment by ArgoZhang** [comment]
比如每个文档都用 md 来做，这个建议就非常好。但是我们就没能力实现

**Comment by bigsinger** [comment]
那第6点可以忽略。

md格式我认为是一次性的，不会每次更新都必须大动的，或者说以后新写的或者需要更新时按照md格式来，历史的先不动，这样可以在精力有限的情况下逐步过渡，而且不影响已有的内容。

**Comment by ArgoZhang** [comment]
@bigsinger 可以加群申请管理员。文档这块交给你来维护的。

**Comment by bigsinger** [comment]
> @bigsinger 可以加群申请管理员。文档这块交给你来维护的。

我先接受你的这个建议：
`文档类的建议不建议你提供建议`

**Comment by ArgoZhang** [comment]
> ### Document describing which component
> 受益于本组件，也做一下反馈权当做给本组件的一点贡献。 1、在快速上手一节。 把服务端模式+客户端模式+类库安装，统一归类到一个页面里说清楚即可，可以叫【安装使用】，凡是涉及到首次使用需要做的，就在这里面一把说清楚，不要太零散和分散。而且要前置，就是让使用者可以第一时间以最快速的方式用起来。甚至注意事项也可以放进去。
> 
> 2、https://www.blazor.zone/install-server 这个里面： BootstrapBlazor 目前支持 net5/net6
> 
> NET7不支持？
> 
> 3、更新日志的传送门过去是主版本的更新历史，就是版本号对不上。
> 
> 4、页脚底部的，服务1200人在线那个可以删除了，人数太少，反而觉得太小众不可靠，干脆就不要写了。
> 
> 5、【手风琴效果】开关打开或关闭看不出有什么变化。
> 
> 6、每个组件的示例代码目前只贴了部分核心代码，直接拿来用不一定可行。建议贴最小可用的完整代码。
> 
> 7、每个文档建议用markdown的方式布局，在右侧显示当前页面的大纲节点，阅读起来更好。
> 
> 祝越来越好，我也会在以后的博客中尽量宣传本组件，以后有建议会继续提。


1. 能否帮我们提交 PR 我们 CMP 审核通过就可以啦
2. 我们稍后更改
3. 更新是一个链接。新版本移到 Github 了老版本在 Gitee 是有点问题，但是问题不大
4. 1200人 企业应用很高了。你可以自己尝试做一个系统。你试试看你能否抗住 1200 人
5. 手风琴效果就是 这个项展开，原来已展开项目就会自动关闭，网站完全没有问题。你看不出变化这个不算建议
6. 基本每个组件尽量做到 CV 可用。但是无论你怎么做，总是有人 CV 无法可用，这里涉及到太多的东西了。你可以尝试着自己做一个复杂的组件，然后做一个 CV 可用的文档，你就会体会其中辛酸，我们的目标也是 CV 可用
7. MD 文档建议你来完成。也是为我们做贡献

**Comment by j4587698** [comment]
md的文档肯定是不可行的，因为实际上目前文档都是代码，可以运行的。md怎么运行代码呢？
第6点也是同样的问题，实际上目前的文档里的源码都是例子里直接截取的，所以需要一个方法，可以把例子直接变成可以CV的代码，如果你有好办法，欢迎提供。
目前我们想了好多办法，都没法实现，全部改成文档更不现实，没有精力维护这么庞大的内容。如果强行改，最后的结果就是文档跟实际完全脱节。
当然如果大佬能来给我们贡献文档，我们会非常非常欢迎，文档完全可以按照你最喜欢的样子来做。

**Comment by ArgoZhang** [comment]
@j4587698 你先不要上来就说不行。可能 @bigsinger 这位大佬是可以的。

**Comment by bigsinger** [comment]
> 



> md的文档肯定是不可行的，因为实际上目前文档都是代码，可以运行的。md怎么运行代码呢？ 第6点也是同样的问题，实际上目前的文档里的源码都是例子里直接截取的，所以需要一个方法，可以把例子直接变成可以CV的代码，如果你有好办法，欢迎提供。 目前我们想了好多办法，都没法实现，全部改成文档更不现实，没有精力维护这么庞大的内容。如果强行改，最后的结果就是文档跟实际完全脱节。 当然如果大佬能来给我们贡献文档，我们会非常非常欢迎，文档完全可以按照你最喜欢的样子来做。

GitHub的评论、GitHubPages博客、CSDN博客，都是md格式的。
```
代码啊代码
```

**Comment by ArgoZhang** [comment]
@bigsinger 所以大佬快来帮我们实现啊

**Comment by j4587698** [comment]
> > 
> 
> > md的文档肯定是不可行的，因为实际上目前文档都是代码，可以运行的。md怎么运行代码呢？ 第6点也是同样的问题，实际上目前的文档里的源码都是例子里直接截取的，所以需要一个方法，可以把例子直接变成可以CV的代码，如果你有好办法，欢迎提供。 目前我们想了好多办法，都没法实现，全部改成文档更不现实，没有精力维护这么庞大的内容。如果强行改，最后的结果就是文档跟实际完全脱节。 当然如果大佬能来给我们贡献文档，我们会非常非常欢迎，文档完全可以按照你最喜欢的样子来做。
> 
> GitHub的评论、GitHubPages博客、CSDN博客，都是md格式的。
> 
> ```
> 代码啊代码
> ```

你能在你说的任意一个地方用md写一段blazor代码然后让它跑起来吗？

**Comment by ArgoZhang** [comment]
@bigsinger 要什么好的建议跟框架吗？可以加我 QQ 5196060 我拉你进讨论组我们可以谈，这个也是帮我们提高文档质量与水平
