### ISSUE TITLE
how to hide default button on table when ShowExtendButtons

### ISSUE THREAD

**Issue by kibela2210** [dotnetcore/BootstrapBlazor#1090]
### Which class is this unit test associated with?

![image](https://user-images.githubusercontent.com/130828292/233817719-0213d2d0-51d2-4584-b333-270ac82b2c8d.png)

how to hide button edit and delete when use custom button on table

**Comment by j4587698** [comment]
You can use `ShowEditButtonCallback` and `ShowDeleteButtonCallback` hide the default button.

**Comment by azlis** [comment]
```ShowExtendEditButton```
```ShowExtendDeleteButton```

**Comment by kibela2210** [comment]
> `ShowExtendEditButton` `ShowExtendDeleteButton`

thank you <3
