### ISSUE TITLE
How to show/hide <Card /> Component

### ISSUE THREAD

**Issue by kibela2210** [dotnetcore/BootstrapBlazor#1091]
### Which class is this unit test associated with?

how to hide <Card /> component with condition and 
when hide component DOM is not allowed to appear

**Comment by ArgoZhang** [comment]
@kibela2210 

```
if(Show) {
    <Card />
}
```

**Comment by kibela2210** [comment]
![image](https://user-images.githubusercontent.com/130828292/233824895-b53e97e9-4e18-40af-814c-28a0fc1ba012.png)

when i update IsLooked, button on Table dont change stage
how to do this

**Comment by ArgoZhang** [comment]
@kibela2210  i guest it's maybe missing `StateHasChanged`
