### ISSUE TITLE
组件UI语言回落bug, 发布到Linux找不到语言资源,标签显示为资源标签名

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#110]
vs2022,调试console运行正常,wsl调试运行以及发布到centos7都出现这个bug

**console运行**
![QQ图片20210812172849](https://user-images.githubusercontent.com/8428709/129224464-a57d8017-14a1-47ac-8cae-45f6daebf6dc.png)

**wsl调试运行以及发布到centos7**
![QQ图片20210812172843](https://user-images.githubusercontent.com/8428709/129224468-3e452ca1-acd5-4736-82b7-2e4b3d0c7281.png)

测试工程
https://github.com/densen2014/BootstrapBlazorDemo/tree/master/test/test

**Comment by ArgoZhang** [comment]
@densen2014 已修复
