### ISSUE TITLE
Component Tab e TabItem

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#1109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm using the component Tab with a TabItem and before this component had a Parameter named Key, but this parameter doesnt exist more and I dont have any other parameter that I can identify the tabItem that is clicked, its possible have this parameter back or some parameter similar?

### Describe the solution you'd like

a parameter named Key on tabitem

**Comment by ArgoZhang** [comment]
@gmondin hi. could you provider a demo project for us?

**Comment by gmondin** [comment]
Hi, before changes the tabItem, I was using like this:

<Tab @ref="_tab" OnClickTab="@OnClickTab">
 <TabItem Key="0" >

so in my code I was using the Key to identify the tab and search some data:

  private async Task OnClickTab(TabItem item)
  {
    int.TryParse(item.Key?.ToString(), out int keyItem);
    if (keyItem == 1) await GetData();
  }

now I dont have more the Key on the TabItem and I dont have any parameter to identify the tabItem, only the Text, that I cant use, first, because is not nice to use, second because my project is multi language.

I dont know when this changes, but something on the last releases of the version 6 and the new version 7.5.5

Thank you very much

**Comment by ArgoZhang** [comment]
@gmondin hi. sorry for the delay reply

`OnClickTab` callback marked as `Obsolete`. Please use the new parameter `OnClickTabItemAsync`. The first argument is what you want
