### ISSUE TITLE
New 'Calendar Heat' map

### ISSUE THREAD

**Issue by pomeara** [dotnetcore/BootstrapBlazor#111]
Hi Argo,

I would like to display a heat-map to a calendar control to do things such as show booking times etc....  see the picture below:

![image](https://user-images.githubusercontent.com/8163710/131204793-63da7127-2acf-4156-9fe5-81769127bae0.png)

this project does something similar [heatmap](https://cal-heatmap.com/#start)

**Comment by ArgoZhang** [comment]
@pomeara it looks not complex. what's can I do for you?

**Comment by pomeara** [comment]
it looks like a nice new control to add to bb
