### ISSUE TITLE
MultiSelect 组件OnSearchTextChanged后加载的列表数据点击勾选无法显示在输入框内

### ISSUE THREAD

**Issue by ryuu312** [dotnetcore/BootstrapBlazor#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![D0{IBHB3( GQ47E_LRI}G5](https://user-images.githubusercontent.com/23396432/234793497-90328b73-691c-421d-b446-31fcf18c484f.png)

这个MultiSelect因为数据默认太多，有2W多条，所以页面载入的时候只载入了200条，后面通过组件里自带的搜索功能搜索出来的数据，点击的时候不会自动添加到上面文本框内

**Comment by ArgoZhang** [comment]
@ryuu312 不提供例子，不予处理 Issue 不合格 Issue
