### ISSUE TITLE
quest: not trigger OnValid callback

### ISSUE THREAD

**Issue by Intekai** [dotnetcore/BootstrapBlazor#1141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

hello, I have upgraded to the latest version and captcha does not work it does not generate any events

**Comment by Intekai** [comment]
not run  OnValid="@OnValid" event

<Captcha GetImageName="@GetImageName" @ref="Captcha" OnValid="@OnValid" />

 private void OnValid(bool ret)
    {
        if (ret)
        {
                DisablePostButton = false;
                StateHasChanged();
        }
    }

**Comment by ArgoZhang** [comment]
@Intekai  use `OnValidAsync`
