### ISSUE TITLE
feat(Table): auto reset body height on FixHeader mode

### ISSUE THREAD

**Issue by ArgoZhang** [dotnetcore/BootstrapBlazor#1146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

搜索栏初始化是转圈的，要先计算高度，转圈结束后再次计算，展开收缩时需要再次计算

**Comment by ArgoZhang** [comment]
搜索栏初始化是转圈的，要先计算高度，转圈结束后再次计算，展开收缩时需要再次计算，涉及到 `Table` `Collapse` `Card` 三个组件联合工作

**Comment by ArgoZhang** [comment]
@wapco

根据你提供的例子  https://test-aigo-smgr.oss-cn-hangzhou.aliyuncs.com/BootstrapBlazorApp.rar 使用新模板重新创建项目，根据你实际项目代码，增加两个外围样式如下：

```
.tabs-body {
    max-height: calc(100vh - 90px - 40px);
    overflow: hidden;
}

.table-auto-height {
    height: calc(100% - 46.2px);
}
```

视频效果如下

https://github.com/dotnetcore/BootstrapBlazor/assets/22001478/3f4623b0-bd5f-4e73-babc-bb28fcc8c163


更新后的项目代码如下：



[BootstrapBlazorApp1.zip](https://github.com/dotnetcore/BootstrapBlazor/files/11550498/BootstrapBlazorApp1.zip)

**Comment by tench** [comment]
最新的7.9.1又失效了，7.8.11可以的

**Comment by ArgoZhang** [comment]
@tench 收到，我修复一下，我弄个例子到官网，以后失效了，我自己就知道啦

**Comment by tench** [comment]
收到，谢谢
