### ISSUE TITLE
feat(BarcodeReader): support for setting camera at initialization

### ISSUE THREAD

**Issue by ArgoZhang** [dotnetcore/BootstrapBlazor#1149]
That would be a real relief and makes the component perfect for our purposes.
Many Thanks for your effort!

_Originally posted by @SalvatoreFonti in https://github.com/dotnetcore/BootstrapBlazor/discussions/283#discussioncomment-5740921_

**Comment by ArgoZhang** [comment]
@SalvatoreFonti https://www.nuget.org/packages/BootstrapBlazor.BarCode/7.1.3 released. please have a try

add `DefaultInitDeviceIndex` parameter for your requirement.

**Comment by SalvatoreFonti** [comment]
With version 7.1.3 it runs perfectly. Thanks alot! However, Visual Studio 2022 updates to version 7.1.4 and the following error message appears:
Razor.server.js:1 [2023-05-02T14:15:40.777Z] Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:5010/_content/BootstrapBlazor.BarCode/Components/BarcodeReader/BarcodeReader.razor.js
TypeError: Failed to fetch dynamically imported module: https://localhost:5010/_content/BootstrapBlazor.BarCode/Components/BarcodeReader/BarcodeReader.razor.js
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at BootstrapBlazor.Components.BarcodeReader.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by ArgoZhang** [comment]
@SalvatoreFonti which version of `BootstrapBlazor` in your project

**Comment by SalvatoreFonti** [comment]
with Version 7.1.4 BootstrabBlazor 7.0.0.

![grafik](https://user-images.githubusercontent.com/37700136/235708875-f0f23e6e-e33d-4f6b-aaf2-73bd5111fa51.png)

**Comment by ArgoZhang** [comment]
@SalvatoreFonti Has this problem been solved? What can I do for you? Upgrading to the latest version `BootstrapBlazor` will be fine

**Comment by SalvatoreFonti** [comment]
I installed BootstrapBlazor 7.6.0 first then BootstrapBlazor.Barcode 7.1.4 and everything is fine. 
Thanks for your help!
