### ISSUE TITLE
bug(MultiSelect): 动态筛选数据后无法选择

### ISSUE THREAD

**Issue by ZenCN** [dotnetcore/BootstrapBlazor#1194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

官网列子也有同样的问题，地址：https://www.blazor.zone/multiselects#Search  
在搜索文本框框中输入“连云港”会从动态数据源检索到对应选项，但是无法选择，可能是搜索后没有重新绑定选择框的事件？
![image](https://user-images.githubusercontent.com/9545096/235617451-446dba9d-5a22-4b24-9839-5b342f1b9aea.png)

**Comment by ArgoZhang** [comment]
@ZenCN release `7.6.1-beta01`

**Comment by ZenCN** [comment]
拴Q
