### ISSUE TITLE
bug:  throw exception when click Clear button

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#1200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Cannot read properties of undefined (reading 'clear') TypeError: Cannot read properties of undefined (reading 'clear') at clear (https://www.blazor.zone/_content/BootstrapBlazor.BarCode/Components/QRCode/QRCode.razor.js:11:15) at Module.update (https://www.blazor.zone/_content/BootstrapBlazor.BarCode/Components/QRCode/QRCode.razor.js:59:9) at https://www.blazor.zone/_framework/blazor.server.js:1:3506 at new Promise () at Ft.beginInvokeJSFromDotNet (https://www.blazor.zone/_framework/blazor.server.js:1:3480) at Ft._invokeClientMethod (https://www.blazor.zone/_framework/blazor.server.js:1:75066) at Ft._processIncomingData (https://www.blazor.zone/_framework/blazor.server.js:1:72690) at Ft.connection.onreceive (https://www.blazor.zone/_framework/blazor.server.js:1:67003) at i.onmessage (https://www.blazor.zone/_framework/blazor.server.js:1:51316)

**Comment by ArgoZhang** [comment]
@bigsinger 发布 `v7.1.5`  https://www.nuget.org/packages/BootstrapBlazor.BarCode/7.1.5
