### ISSUE TITLE
bug: font-awesome not found 404

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

提示：to load resource: the server responded with a status of 404 (Not Found)

http://localhost:5033/_content/BootstrapBlazor.FontAwesome/css/font-awesome.min.css  找不到。

![image](https://user-images.githubusercontent.com/14847818/236974715-2a089636-03c3-4c2e-b443-adbb9f75723c.png)

重现方式：新建demo（server模式）

_Host.cshtml：
```
@page "/"
@using Microsoft.AspNetCore.Components.Web
@namespace BlazorApp1.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="~/" />

    <link href="_content/BootstrapBlazor.FontAwesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="_content/BootstrapBlazor/css/bootstrap.blazor.bundle.min.css" rel="stylesheet">

    <link href="css/site.css" rel="stylesheet" />
    <link href="BlazorApp1.styles.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="favicon.png"/>
    <component type="typeof(HeadOutlet)" render-mode="ServerPrerendered" />
</head>
<body>
    <component type="typeof(App)" render-mode="ServerPrerendered" />

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_content/BootstrapBlazor/js/bootstrap.blazor.bundle.min.js"></script>
    <script src="_framework/blazor.server.js"></script>
</body>
</html>

```

### .NET Version

7.0

**Comment by densen2014** [comment]
https://www.cnblogs.com/densen2014/p/17357815.html

参考一下，最好提供zip或者完整工程链接。FontAwesome包引用了吗？

**Comment by ArgoZhang** [comment]
@bigsinger 这几天太忙了。等我有空我复现一下。如果能复现我修复一下

**Comment by ArgoZhang** [comment]
Issue 认真按照格式填写，帮我减少一点工作量

**Comment by bigsinger** [comment]
> https://www.cnblogs.com/densen2014/p/17357815.html
> 
> 参考一下，最好提供zip或者完整工程链接。FontAwesome包引用了吗？

感谢，确实可以解决。 

@ArgoZhang 官网文档里可以更新下，这个在初次接入的时候好像没提及这个。

BootstrapBlazor.FontAwesome

**Comment by ArgoZhang** [comment]
@bigsinger 太笼统了，具体哪个文档？或者你看的是哪个文档？你可以 PR 上了改文档还是非常简单的。

**Comment by bigsinger** [comment]
> @bigsinger 太笼统了，具体哪个文档？或者你看的是哪个文档？你可以 PR 上了改文档还是非常简单的。

官网的开发文档：https://www.blazor.zone/introduction

**Comment by bigsinger** [comment]
@ArgoZhang 不急的，工程已经能正常用了，只不过一些小的优化，可以慢慢改进。

**Comment by ArgoZhang** [comment]
@bigsinger 简介里不可能写你提到的这个问题，人家可能不用这个图标库的。相对应的问题肯定归到相对应的文档上

https://www.blazor.zone/fa-icons

**Comment by bigsinger** [comment]
但是官网的教程：https://www.blazor.zone/install-server  是这样的：
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/14847818/20fa0b40-8efe-489a-8d05-bd080dcab6d3)

就需要引用 BootstrapBlazor.FontAwesome 包 ，那个注释很容易被忽略，如果要添加`<link href="_content/BootstrapBlazor.FontAwesome/css/font-awesome.min.css" rel="stylesheet">`  就要添加  BootstrapBlazor.FontAwesome 包。

这样会清晰一些。
