### ISSUE TITLE
bug(Select): Select Component Search Not Working

### ISSUE THREAD

**Issue by KHANFAIZAN05** [dotnetcore/BootstrapBlazor#1243]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

On Blazor Server  Select Component Search Not Working . i am not able to type the text string on search input that we enable by  ShowSearch=true   **it is not filtering select option based on search text**

### Expected Behavior

*it should be filtering select option based on search text*

### Steps To Reproduce

-

### Exceptions (if any)

-

### .NET Version

7

### Anything else?

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/33517444/8f49a407-d7b9-4304-b9b8-da83940043f5)

**Comment by ArgoZhang** [comment]
@KHANFAIZAN05 Hi. Please provider a simple demo project for repro this issue. I need to take a look at your code

**Comment by KHANFAIZAN05** [comment]
@ArgoZhang Thanks For Replying...  here is the sample demo Project Link

https://github.com/KHANFAIZAN05/Blazor-Select.git

**Comment by ArgoZhang** [comment]
@KHANFAIZAN05 link #1248

**Comment by KHANFAIZAN05** [comment]
@ArgoZhang  thanks 👍
