### ISSUE TITLE
能否在Table的Excel模式中允许显示Detail

### ISSUE THREAD

**Issue by light499960904** [dotnetcore/BootstrapBlazor#126]
现在的情况是开启了Excel模式以后不能使用Detail
或者说允许在非Excel模式下 能编辑所有的Cell
类似于下图
![image](https://user-images.githubusercontent.com/27767203/137445119-2a43e091-0dc2-4fb6-b92e-5b4391708ab3.png)

**Comment by ArgoZhang** [comment]
@light499960904 编辑时明细行也要编辑吗？还是只要显示即可？

**Comment by ArgoZhang** [comment]
目前 Detail 是模板生成的无法控制，这个功能无法实现
