### ISSUE TITLE
bug: Chart inside Dialog

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#1263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

after update the Charts for .NET 7, I started have problems to open the charts on a dialog, when is on the page, its works, but if some problems, on a Dialog its not working or taking so long to open.
I saw also that on a page, if the chart is not load on the first load, sometimes doesnt load.
Example, if a show the chart after select a item on the table, the chart is not loading, but if I the chart is opened before, like a fake chart and change the data after the select is working good.

I cant tell which version started have problems, because since the begin of the year that was working normally and last month I upgrade the project for .net 7.

Thank you very much

### .NET Version

.NET 7

**Comment by ArgoZhang** [comment]
@gmondin Hi. could you provider a demo that Chart component on a Dialog?

**Comment by gmondin** [comment]
I made like this and has the same problem, example:

<Card IsCollapsible="true" Collapsed="_collapsed" HeaderText="@_LocalLocalizer[nameof(Dynamic.Dashboard.Shared.Resources.Resource.AnaliseProduzione)]">
    <BodyTemplate>
      <div class="row">
        <div class="col-12">
          <div class="text-danger">@_LocalLocalizer[nameof(Dynamic.Dashboard.Shared.Resources.Resource.Test)]</div>
        </div>
        <div class="col-12">
          <Chart ChartType="ChartType.Line" OnInitAsync="() => OnInit(0f, false)" @ref="@_chart" LoadingText="Loading" />
          <Divider />
        </div>        
      </div>
    </BodyTemplate>
  </Card>

@code {
private bool _collapsed = true; //if I started collapsed, the chart is not showing or sometimes show but after take more than minute, if I started uncollapsed, the chart is showing normally, independent if I have selected or not on the grid
    private Random Randomer { get; } = new ();

    private int LineDatasetCount = 2;

    private int LineDataCount = 7;

    private Task<ChartDataSource> OnInit(float tension, bool hasNull)
    {
        var ds = new ChartDataSource();
        ds.Options.Title = "Line Chart";
        ds.Options.X.Title = "days";
        ds.Options.Y.Title = "Numerical value";
        ds.Labels = Enumerable.Range(1, LineDataCount).Select(i => i.ToString());
        for (var index = 0; index < LineDatasetCount; index++)
        {
            ds.Data.Add(new ChartDataset()
            {
                Tension = tension,
                Label = $"Set {index}",
                Data = Enumerable.Range(1, LineDataCount).Select((i, index) => (index == 2 && hasNull) ? null! : (object)Randomer.Next(20, 37))
            });
        }
        return Task.FromResult(ds);
    }
}

**Comment by ArgoZhang** [comment]
@gmondin could you provider a full demo project?

**Comment by ArgoZhang** [comment]
@gmondin no response auto close issue
