### ISSUE TITLE
feat: Select rows by code on Table

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#1264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

After take the list for the table, I'm set on the _selectedRows the firstrow selected on my Table, but the table doesnt show the row selected, doesnt change de color of the row, its possible make this?

### Describe the solution you'd like

Select the rows by code, changing also the color of the rows.

**Comment by ArgoZhang** [comment]
@gmondin https://www.blazor.zone/tables/selection#Normal

use `bind-SelectedRows`
