### ISSUE TITLE
Data type of  bool?

### ISSUE THREAD

**Issue by gruan01** [dotnetcore/BootstrapBlazor#129]
### `DisplayText' of  `bool?`  not show, and can't read it's real value.

Model define:
~~~
        /// <summary>
        /// 
        /// </summary>
        [Display(Name = "是否有效")]
        public bool? IsValid { get; set; }
~~~

~~~
    <TableColumns>
...
        <TableColumn @bind-Field="@context.IsValid" Searchable="true" />
    </TableColumns>
~~~

### Exceptions (if any)

![bool? 的DisplayText 读取不到](https://upload-images.jianshu.io/upload_images/3436768-4ff5ae36335affaa.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### Further technical details
- BootstrapBlazor version 5.14.8
- The IDE VS2019

**Comment by ArgoZhang** [comment]
@gruan01 thank you for contacting us.
the `Swtich` component must have a value `True` or `False`
in this case, strongly suggest you use `Select` instead of `Switch`. when it is null you can show `Please pickup ...`

**Comment by gruan01** [comment]
It's auto generated by `Searchable="true" `
~~~
<TableColumn @bind-Field="@context.IsValid" Searchable="true" />
~~~

**Comment by ArgoZhang** [comment]
@gruan01 You need to customize this parameter with `SearchTemplate`
