### ISSUE TITLE
DateTimeRange 报空引用异常

### ISSUE THREAD

**Issue by mayamoon** [dotnetcore/BootstrapBlazor#130]
### Describe the bug
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'QORPgY0JE9QcqfAjQ24RI6pJeHqgWhl3y8N72poVw8M'.

System.NullReferenceException: Object reference not set to an instance of an object.
   at BootstrapBlazor.Components.DateTimeRange.OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

### Further technical details
- BootstrapBlazor version 5.27.2
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version VS2019

**Comment by mayamoon** [comment]
我发现是Value为NULL了,应该在初始化的时候判断一下,如果Value为NULL,应该new一个对象

**Comment by mayamoon** [comment]
另外我建议打包的时候将.pdb文件带上,这样才能知道具体哪一行出错了.否则都是靠猜想

**Comment by ArgoZhang** [comment]
@mayamoon 感谢大佬提交 Issue 这个能否提交一个 PR

**Comment by ArgoZhang** [comment]
@mayamoon  pdb 文件打包是不包含的。但是有专门的包。 nuget 上已经提供了

**Comment by mayamoon** [comment]
Value一定要给值,所以这个其实是设计理念和方式的问题,所以我关闭掉这个ISSUE
