### ISSUE TITLE
编辑弹窗中保存按钮是否显示

### ISSUE THREAD

**Issue by hfmaicy** [dotnetcore/BootstrapBlazor#1309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

给编辑弹窗中保存按钮添加一个是否显示的设置，以便达到可以新增查看 但是不能修改的效果

**Comment by ArgoZhang** [comment]
@hfmaicy 信息不全，描述缺失上下文。请提供更多更详细的信息。我需要知道你的应用场景与逻辑

**Comment by hfmaicy** [comment]
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/76253651/38427286-c13e-4ae6-9e6f-c6c52c4b0e55)

**Comment by hfmaicy** [comment]
编辑弹窗  在新增的时候 显示下方保存按钮 在编辑时 不显示下方保存按钮

**Comment by ArgoZhang** [comment]
@hfmaicy 感觉你这个需求不是 `EditDialog` 需要支持的功能，你需要一个 `DiaplayDialog` 不仅没有保存，里面的所有东西都不能编辑

**Comment by ArgoZhang** [comment]
@hfmaicy 无响应自动关闭
