### ISSUE TITLE
分页样式错乱

### ISSUE THREAD

**Issue by ShaoHans** [dotnetcore/BootstrapBlazor#1314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

如图所示：
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/20715749/07b64ddc-137c-4073-b1c1-f6d982f91774)

在Edge和谷歌浏览器上都是一样的效果，Edge版本： 113.0.1774.50 (正式版本) (64 位)，谷歌版本：113.0.5672.127(正式版本)(64 位)。

部分代码如下：
`<Table TItem="Round" IsStriped="true" IsBordered="true"
                   IsPagination="true" PageItemsSource="@CommonData.PageItemsSource" PageItems="20" OnQueryAsync="@OnQueryAsync">`

### .NET Version

.net 7.0

### Anything else?

BootstrapBlazor的版本是7.6.6

**Comment by ArgoZhang** [comment]
@ShaoHans 无效 Issue 怎么复现？截图哪里来的？

**Comment by ShaoHans** [comment]
今天用了你的框架，使用了Table的分页功能，发现样式错乱

**Comment by ShaoHans** [comment]
无效Issue？这就是你的态度？我看码云上也有人在2022年提过一样的问题：https://gitee.com/LongbowEnterprise/BootstrapBlazor/issues/I5IA1K，说明它是一个确实存在的bug

**Comment by ArgoZhang** [comment]
这不是态度问题。每天想你们这样提交 Issue 都处理。我啥也不用干了。你能不能按照格式要求提交 issue ? 是你寻求帮助，还来指责我的态度？我们面对是所有使用者。而不是为你一个人服务。不要浪费我们的时间
