### ISSUE TITLE
feat: 树形表格在部分展开情况下修改某行数据保存后会自动刷新导致工作状态变更不易使用

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#1321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

修改一条数据保存，就会自动重置，导致之前的工作状态被打乱需要重新展开操作。请问有没有更好的方法？

### Describe the solution you'd like

修改一条数据保存，就会自动重置，导致之前的工作状态被打乱需要重新展开操作。请问有没有更好的方法？

**Comment by bigsinger** [comment]
另外补充下，官网的这个示例在操作的时候，有异常发生：https://www.blazor.zone/tables/tree

**Comment by bigsinger** [comment]
如果树形表格可以借鉴Excel-items的刷新模式就完美了，https://www.blazor.zone/tables/excel

**Comment by ArgoZhang** [comment]
@bigsinger 能付按照 Issue 格式提供复现步骤与 Demo 不要描述一下就完事了。这种 issue 我们很花时间与经理来处理。所以一般优先级别很低

**Comment by ArgoZhang** [comment]
@bigsinger 如何操作弹出这个错误框的？

**Comment by bigsinger** [comment]
@ArgoZhang 点击红框处
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/14847818/a11cde4b-a3ee-4b90-aab1-32755f748f7d)

**Comment by bigsinger** [comment]
是官网，谷歌浏览器访问，没有特别的。
