### ISSUE TITLE
feat: 当异常信息超长时关闭按钮找不到无法关闭需要等待其自动消失

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/14847818/a2f836ce-897f-47e4-b214-3ea560c0dd37)

类似这种异常信息，当超级长的时候，就不会出现有关闭按钮，无法手动关闭，需要等待其自动消失，因为这个时间较长，所以还蛮浪费时间的，希望可以看看。  同时还会覆盖页面，导致无法做其他操作。

### Describe the solution you'd like

类似这种异常信息，当超级长的时候，就不会出现有关闭按钮，无法手动关闭，需要等待其自动消失，因为这个时间较长，所以还蛮浪费时间的，希望可以看看。

**Comment by ArgoZhang** [comment]
@bigsinger 正常的业务系统就不应该出现这个弹窗，如果看到这个弹窗说明代码有问题，是需要处理。不过最近有计划改进一下这个异常捕获机制，先在开发环境恢复到原始状态
