### ISSUE TITLE
Longbow.BootstrapBlazorUITemplate vs 2021 extension

### ISSUE THREAD

**Issue by pomeara** [dotnetcore/BootstrapBlazor#133]
Hi @ArgoZhang,

I tried to use the .visx estension in Visual Studio 2021 but it only works with 2019 which I no longer install.

Is it possible to update the extension or provide a way to get this working in VS2021 please

This is the extension I am trying to use 

https://marketplace.visualstudio.com/items?itemName=Longbow.BootstrapBlazorUITemplate

I am also curious if this is using the latest bootstrap or still back on the previos bootstrap version

**Comment by ArgoZhang** [comment]
@pomeara hi. are you sure vs2021? I think that should be vs2022. you will find what you want at the following link
https://marketplace.visualstudio.com/items?itemName=Longbow.BootstrapBlazorUITemplate2022
