### ISSUE TITLE
项目模板支持Server only模式和WebAssembly only模式

### ISSUE THREAD

**Issue by dengyakui** [dotnetcore/BootstrapBlazor#134]
### Is your feature request related to a problem? Please describe.
当前的模版创建之后，解决方案中默认既包含了 Server模式，也有WebAssembly 模式两套启动项目， 其中页面逻辑部分均放置在了Shared项目中。而WebAssembly项目默认并没有使用HttpClient作为通信服务，会导致初学者上手时有所困惑。

在实际项目中， 我们通常会选择固定的一种项目类型，而Pages部分更倾向于放在原生的Server或WebAssembly项目下。
在当前的项目模板中，引用到某些 Server only/WebAssembly only 的组件时， 例如 LocalStorageService，
BrowserStorageService，如果将包的引用放置在了Shared项目中，会导致编译时会提示 RuntimeIdentifier之类的 错误信息。
因为有些组件是区分WebAssembly/Server only的。

### Describe the solution you'd like
-  命令行模式支持：希望能在初始化项目的时候，提供参数，直接创建 Server only/ WebAssembly only的模版，类似dotnet sdk中提供的方式
- visualstudio 创建项目时，希望提供 Server模式/WebAssemble模式的选择

**Comment by ArgoZhang** [comment]
@dengyakui 与 Gitee Issue 重复，暂时关闭这个
