### ISSUE TITLE
bug: Table Custom Filter Style Bug

### ISSUE THREAD

**Issue by 1340896123** [dotnetcore/BootstrapBlazor#1347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/1340896123/KrasERP

https://github.com/dotnetcore/BootstrapBlazor/assets/24859474/f2dc4047-5c36-4fc5-9879-2ea69e2b71b3

**Comment by ArgoZhang** [comment]
@1340896123 

你自定义过滤组件 

```
<Select Items="@Items" @bind-Value="@Value" IsPopover="true" OnSelectedItemChanged="_ => OnFilterValueChanged()"></Select>
```
