### ISSUE TITLE
feat: bootstrapblazor支持maui，但是使用wpf，winform，还有Photino blazor的时候，按照mauiblazor的操作步骤，总是出现错误，希望能够支持这几种开发模式

### ISSUE THREAD

**Issue by aslyr** [dotnetcore/BootstrapBlazor#1350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

按照maui的步骤会出现以下错误：
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfiguration' while attempting to activate 'Microsoft.Extensions.DependencyInjection.ConfigureOptions`1[BootstrapBlazor.Components.BootstrapBlazorOptions]'.
但是使用masablazor,antdesign没有问题。

### Describe the solution you'd like

可以参照masablazor的模板，更新bootstrapblazor模板，添加生成wpf app,winform app, photino app，maui app的项目模板

**Comment by densen2014** [comment]
试试 https://github.com/densen2014/BlazorMaui

**Comment by aslyr** [comment]
> 试试 https://github.com/densen2014/BlazorMaui

maui项目都没问题，我说的是winform，photino项目报错

**Comment by ArgoZhang** [comment]
@aslyr 给我一个 demo 工程。帮你看看

**Comment by densen2014** [comment]
> > 试试 https://github.com/densen2014/BlazorMaui
> 
> maui项目都没问题，我说的是winform，photino项目报错

里面有 Windows (Winforms/WPF/WinUI3)、Android、iOS、macOS 和 Linux

**Comment by ArgoZhang** [comment]
@densen2014 @aslyr 哪里报错了？不要让我猜可以吗？提交 Issue 你起码要提供报错的 Demo 跟报错的截图，堆栈信息，不让我怎么修啊？

**Comment by aslyr** [comment]
[BootStrapBlazorPhotinoTest.zip](https://github.com/dotnetcore/BootstrapBlazor/files/11648361/BootStrapBlazorPhotinoTest.zip)

**Comment by aslyr** [comment]
这个是提个feature,没说算bug,启动就报System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfiguration' while attempting to activate 'Microsoft.Extensions.DependencyInjection.ConfigureOptions`1[BootstrapBlazor.Components.BootstrapBlazorOptions]'.这个错误

**Comment by aslyr** [comment]
> > > 试试 https://github.com/densen2014/BlazorMaui
> > 
> > 
> > maui项目都没问题，我说的是winform，photino项目报错
> 
> 里面有 Windows (Winforms/WPF/WinUI3)、Android、iOS、macOS 和 Linux

不错，这个项目内容很好，winform也没报错，谢谢！

**Comment by ArgoZhang** [comment]
@aslyr Issue 不一定是 bug 是你遇到问题需要我们帮助，所以你提交 Issue 要有复现问题的 Demo 这样我们才能复现检查是组件有缺陷，还是你的代码有步骤缺少。不能光说一个结果，或者类似这种话 `总是出现错误`，我们很难排查问题

**Comment by aslyr** [comment]
> @aslyr Issue 不一定是 bug 是你遇到问题需要我们帮助，所以你提交 Issue 要有复现问题的 Demo 这样我们才能复现检查是组件有缺陷，还是你的代码有步骤缺少。不能光说一个结果，或者类似这种话 `总是出现错误`，我们很难排查问题

谢谢大神指教，demo已上传，masa和photinoblazor没问题，加上bootstrapblazor就有问题了，提这个功能实现呢，也是希望bootstrapblazor dotnet模板能够把winform、wpf、maui这几个添加进去像masa项目模板那样用起来很方便。

**Comment by ArgoZhang** [comment]
@aslyr 嗯嗯。看到你的 Demo 了。问题是你用的这个框架没有注入 IConfiguration 这个服务，我们组件是依赖这个服务的，我们组件支持全局配置，而不是像他们那些组件很多属性都要一个组件一个组件的设置，我们支持从配置文件设置整个网站的所有组件的某个属性，所以不存在，什么行，什么不行，没有可比性。我更新一下组件库，如果外面的框架没有注入这个服务，使用默认值设置就好了。感谢提交 issue 这个问题是我们设计时候没有考虑到的

**Comment by ArgoZhang** [comment]
@densen2014 @aslyr 已发布 `v7.7.1-beta03` 兼容了某些不注入 `IConfiguration` 的框架
