### ISSUE TITLE
quest: Items/OnQueryAsync of Table component

### ISSUE THREAD

**Issue by fdb-jharcourt** [dotnetcore/BootstrapBlazor#1354]
### Which class is this unit test associated with?

I have put the following on my Razor page:
```
<Table TItem="Session" Items="@Sessions" PageItemsSource="@PageItemsSource" 
  IsFixedHeader="true"
  ShowSkeleton="true" HeaderStyle="TableHeaderStyle.Light" IsBordered="true"
  IsStriped="true" TableSize="TableSize.Compact" IsPagination="true" 
  PageItems="10" OnQueryAsync="@OnQueryAsync" ClickToSelect="true"
  OnClickRowCallback="@ClickRow" ShowLoading="true" >
  <TableColumns>
    <TableColumn Text="Session Id" @bind-Field="@context.SessionId" Visible="false" />
    <TableColumn Text="Session Name" @bind-Field="@context.SessionName" />
    <TableColumn Text="Created By" @bind-Field="@context.CreatedBy" Width="250" Sortable="true" Filterable="true" />
    <TableColumn Text="Created Date" @bind-Field="@context.CreatedDate" Width="200" Sortable="true" />
    <TableColumn Text="Last Modified Date" @bind-Field="@context.LastModifiedDate" Width="200" Sortable="true" />
  </TableColumns>
</Table>
```
The "item=@Sessions" list references a "List\<Session\> Sessions" containing Session objects.   But I can't get it to page, sort or filter.  Is there something that I'm missing?  When I put a breakpoint in the "OnQueryAsync" method, It does not stop at the breakpoint. The table fills in fine with my data.   I've asked other people to review my code, and they can't seem to get it to work either.  
And while this does show up on the page: 
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/30418071/57a708df-0804-4495-b605-88f9000f4244)

This does NOT (taken from one of your documentation):
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/30418071/f0d650b2-824a-45ff-a8ec-99e03c26fb5b)

Any help in getting it to work would be appreciated.

**Comment by ArgoZhang** [comment]
@fdb-jharcourt Hi, if you wanna use the filter/search/pagination etc function you must use the `OnQueryAsync` callback.

`Items` parameter design for the quick display of the data source.

**Comment by fdb-jharcourt** [comment]
Thank you for your response. It turns out that I had "Items="@Sessions" in the Table definition.  I guess that is incompatible with sorting/filtering/paging.  
It **almost** works now.  I have to figure out how to do a case insensitive filter.  It must use StringComparison.OrdinalIgnoreCase somewhere, yes?  Is it possible?

**Comment by ArgoZhang** [comment]
@fdb-jharcourt yes. some database support cases are insensitive too. you can setting it in database

**Comment by fdb-jharcourt** [comment]
Thank you again.  I would **very** much like to see an example of that!   I don't see that in the documentation.

**Comment by ArgoZhang** [comment]
@fdb-jharcourt hi. there is no example. Our website has no database

links

https://learn.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver16&WT.mc_id=DT-MVP-5004174
https://learn.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-database-collation?view=sql-server-ver16&WT.mc_id=DT-MVP-5004174
