### ISSUE TITLE
bug: VisualStudio模板默认创建的项目运行后server模式的风格丢失

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#1359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

如图，server模式不如webassembly模式的导航选中高亮好看，不知道是不是有问题？

server模式：
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/14847818/99e0716f-5f2e-47a0-946c-bb65769d2672)

webassembly模式：
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/14847818/c6d02144-0cfb-4c4f-bbb7-979b8dbd9cf3)

### .NET Version

7

**Comment by ArgoZhang** [comment]
@bigsinger 这都是样式问题，wasm 模式少加载了一个自定义样式文件，你不能所有问题都是 bug 啊。大佬能否注意一下分类

**Comment by bigsinger** [comment]
感觉还是wasm的好看一些

**Comment by ArgoZhang** [comment]
@bigsinger 这些细节样式问题，仁者见仁智者见智，个人喜好而已。没必要强求的。
