### ISSUE TITLE
Default value in PageItemsSource

### ISSUE THREAD

**Issue by InfDev** [dotnetcore/BootstrapBlazor#136]
You can provide a default value for the PageItemsSource by setting it first. Then, before displaying the list, use PageItemsSource.OrderBy (x => x) .ToArray ();

**Comment by ArgoZhang** [comment]
@InfDev sure. it's a great idea

**Comment by ArgoZhang** [comment]
@InfDev hi, sorry for the delayed response. please take a look for https://github.com/dotnetcore/BootstrapBlazor/commit/7e0006fef9e6ff38d33a1132da6878d2222a10a6
