### ISSUE TITLE
download component not work under .net6

### ISSUE THREAD

**Issue by yuandongxiao** [dotnetcore/BootstrapBlazor#137]
### Describe the bug
download component not work under .net6

### To Reproduce
change framework to .net6 . It reports error as Microsoft.JSInterop.JSException:"t.replace is not a funtion at Function.base64DecToArr"

### Further technical details
- BootstrapBlazor version 5.19
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version 2022

**Comment by ArgoZhang** [comment]
@yuandongxiao thanks for contacting us. it fixed v6.0.1
