### ISSUE TITLE
bug: The 'ClickToSelect' function of the table component has become ineffective

### ISSUE THREAD

**Issue by mswang2005** [dotnetcore/BootstrapBlazor#1374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Starting from version 7.6, the 'ClickToSelect' function of the table component has become ineffective. Even if it is set to 'True', the function still does not work.

**Comment by ArgoZhang** [comment]
@mswang2005 thank you for contacting us. let me repro this issue then fix it.
