### ISSUE TITLE
feat: CherryMarkdown组件不支持单栏模式

### ISSUE THREAD

**Issue by JiaFeiMiao-K-Cat** [dotnetcore/BootstrapBlazor#1375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`EditorSettings`中`DefaultModel = "editOnly"`或`DefaultModel = "previewOnly"`均显示为双栏模式, 
但在工具栏中关闭预览可正常切换为单栏模式

### .NET Version

7.0.302

**Comment by JiaFeiMiao-K-Cat** [comment]
[minimalistic repro project](https://github.com/JiaFeiMiao-K-Cat/CherryMarkdownBugReport)

**Comment by ArgoZhang** [comment]
@JiaFeiMiao-K-Cat release new package `v7.2.1`
