### ISSUE TITLE
Edit Button on Table When row not selected

### ISSUE THREAD

**Issue by ricardopdv** [dotnetcore/BootstrapBlazor#139]
On table, when row is not selected, and we press the edit button, component is showing a save popup error. 
It's not a correct behavior. 
Or it's show a not selected item popup  or the button must be disabled. same with delete button.

Suggestion: make the toolbar edit and delete buttons disabled or optionally invisible by parameter.

**Comment by ArgoZhang** [comment]
@ricardopdv thank you to contact us. could you provide some sample code? I wanna know your code.

**Comment by ArgoZhang** [comment]
@ricardopdv thanks please take a look for 6.0.13 it's done!
