### ISSUE TITLE
Line pointStyle

### ISSUE THREAD

**Issue by zhangjiechina001** [dotnetcore/BootstrapBlazor#1397]
### Which class is this unit test associated with?

作者您好，请问有没有设置折线图pointStyle的属性

**Comment by ArgoZhang** [comment]
@zhangjiechina001 帮你找一下

**Comment by ArgoZhang** [comment]
@zhangjiechina001 发布新版本 `7.5.4`

**Comment by zhangjiechina001** [comment]
收到，非常感谢！



---Original---
From: "Argo ***@***.***&gt;
Date: Fri, Jun 16, 2023 21:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dotnetcore/BootstrapBlazor] Line pointStyle (Issue #1397)




 
@zhangjiechina001 发布新版本 7.5.4
