### ISSUE TITLE
Table组件下使用Popover组件弹窗无法及时刷新

### ISSUE THREAD

**Issue by ZenCN** [dotnetcore/BootstrapBlazor#1398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

将Popover组件放到TableColumn的Template下，表格加载后，Code列可以正常显示弹窗，但是删除表格"第1行"后，"第2行"弹窗显示的Popover是原来删除的"第1行"的内容（我这边是内网开发环境无法截图，请见谅），相关代码提供如下：

```
<TableColumn @bind-Field="@context.Code">
    <Template Context=v>
          <Popover Placement="Placement.Top" Title="@v.Row.Title" Content="@v.Row.Content" IsHtml="true">
              <span>@v.Value</span>
          </Popover>
    </Template>
</TableColumn>
```

**Comment by ArgoZhang** [comment]
@ZenCN 感谢提交 issue 我马上试一下，如果能复现我就修复一下，稍等给您回复

**Comment by ArgoZhang** [comment]
@ZenCN 我这里未能复现，所有功能都是正常的，你可以试试更新到最新版 

`v7.7.2-beta04`

**Comment by ZenCN** [comment]
> @ZenCN 我这里未能复现，所有功能都是正常的，你可以试试更新到最新版
> 
> `v7.7.2-beta04`

跪谢，测试版`v7.7.2-beta04` 确实修复了那个Bug，我用的版本是`v7.7.1`（以后找不到解决方案再尝试升级到测试版试试）
