### ISSUE TITLE
bug: 父组件修改绑定对象的值，子组件不刷新

### ISSUE THREAD

**Issue by ZenCN** [dotnetcore/BootstrapBlazor#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

问题描述：父组件修改绑定ParentValue对象的AuthCode值，子组件不刷新，需要手动触发子组件的事件，才会刷新（比如改变TestComponent里面Input组件的值，AuthCode 会立即刷新显示），试过找不到途径触发TestComponent的StateHasChange方法使其刷新，Option里面也没有
测试版本：v7.7.2

```
[Paramater]
public TestClass ParentValue {get; set;}
private DialogOption Option {get; set;}

/// 显示对话框
private async Task ShowDialog() {
    Option = new DialogOption()
    {
        Title = ‘生成授权码’,
        BodyContext = ParentValue,
        BodyTemplate =  BootstrapDynamicComponent.CreateComponent<TestComponent>(new Dictionary<string, object?>
        {
            [nameof(TestComponent.Value)] = ParentValue,
            [nameof(TestComponent.ValueChanged)] = EventCallback.Factory.Create<TestClass?>(this, v => ParentValue = v)
        }).Render(),
        FooterTemplate = BootstrapDynamicComponent.CreateComponent<Button>(new Dictionary<string, object?>
        {
            [nameof(Button.Text)] = "生成授权码",
            [nameof(Button.OnClick)] = EventCallback.Factory.Create<MouseEventArgs>(this, async () => {
                  ParentValue.AuthCode = "3F4H5G";
                  InvokeAsync(StateHasChanged);  // 使用无效，对话框不刷新，AuthCode 不显示 3F4H5G
                  Option.BodyContext  = ParentValue;  // 使用无效，对话框不刷新，AuthCode 不显示 3F4H5G
            })
        }).Render()
    };
    await DialogService.Show(Option);
}
```

**Comment by ArgoZhang** [comment]
@ZenCN 请提供复现例子 zip 下载包或者 仓库地址都可以

**Comment by ZenCN** [comment]
其实就是一个很简单的问题，Dialog组件，Show之后，点击自定义按钮（比如确认按钮）修改对话框的数据（比如DialogOption的Title）同时不关闭对话框，对话框里面的数据不会刷新，一会我可已写一个demo

**Comment by ArgoZhang** [comment]
@ZenCN 写例子的初衷并不仅仅是为了复现你们口中的 bug 还可以看你们的项目环境配置与代码是否正确。很多 Issue 你们提供的代码片段是你们认为的问题点，但是真正的问题可能并不在这里

**Comment by ZenCN** [comment]
我尽量提供代码，上午已找到方法突破网络封锁，正在些写例子

**Comment by ZenCN** [comment]
Demo地址 https://github.com/ZenCN/BlazorServerAppDemo.git

**Comment by ZenCN** [comment]
> Demo地址 https://github.com/ZenCN/BlazorServerAppDemo.git



> @ZenCN 写例子的初衷并不仅仅是为了复现你们口中的 bug 还可以看你们的项目环境配置与代码是否正确。很多 Issue 你们提供的代码片段是你们认为的问题点，但是真正的问题可能并不在这里，你的这个问题看起来是你使用不对造成的

Demo地址 https://github.com/ZenCN/BlazorServerAppDemo.git

**Comment by ZenCN** [comment]
> Demo地址 https://github.com/ZenCN/BlazorServerAppDemo.git

**Comment by ArgoZhang** [comment]
@ZenCN 你这个代码我看了。用的完全不对。一言难尽。你再看看例子。理解一下 `BodyContext` 用法，可以看看源码。我这里打字无法解释

**Comment by ZenCN** [comment]
好的，谢谢
