### ISSUE TITLE
[6.0.5 開始] AutoComplete 會擲出例外

### ISSUE THREAD

**Issue by carlcyber** [dotnetcore/BootstrapBlazor#141]
從 6.0.5 開始，新建一個空白 Blazor Server 專案並加入 AutoComplete 會擲出此例外。

Exception:
>	System.NullReferenceException: 'Object reference not set to an instance of an object.'

Stack:
>	BlazorApp1.dll!BlazorApp1.Pages.Pages__Host.ExecuteAsync() Line 8	C#
>	[External Code]	

Index.razor
```
@page "/"

<AutoComplete @bind-Value="@TestValue" Items="TestItems"></AutoComplete>

@code {
	string TestValue { get; set; }
	string[] TestItems { get; set; } = new[]
	{
		"Test1", "Test2", "Test3"
	};
}
```

**Comment by ArgoZhang** [comment]
@carlcyber 感谢大佬提交 Issue 联系作者，请检查一下 `App.razor` 是否增加了 `BootstrapBlazorRoot` 节点

```
<BootstrapBlazorRoot>
    <Router>
        ...
    </Router>
</BootstrapBlazorRoot>
```

**Comment by ArgoZhang** [comment]
@carlcyber 
https://www.blazor.zone/install-server
或者使用 微软市场中的模板创建项目
https://marketplace.visualstudio.com/items?itemName=Longbow.BootstrapBlazorUITemplate

**Comment by carlcyber** [comment]
> @carlcyber 感谢大佬提交 Issue 联系作者，请检查一下 `App.razor` 是否增加了 `BootstrapBlazorRoot` 节点
> 
> ```
> <BootstrapBlazorRoot>
>     <Router>
>         ...
>     </Router>
> </BootstrapBlazorRoot>
> ```

謝謝指教，問題已解決。
