### ISSUE TITLE
How to custom show/hide ShowExtendEditButton

### ISSUE THREAD

**Issue by kibela2210** [dotnetcore/BootstrapBlazor#1415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the table, I want to custom show/hide ExtendEditButton, How to do that?

### Expected Behavior

none

### .NET Version

7.0

### Anything else?

none

**Comment by ArgoZhang** [comment]
@kibela2210 thank you for contacting us

you can use `ShowEditButtonCallback` or `ShowExtendEditButton` to control the `Edit Button` inline the row.
