### ISSUE TITLE
树形数据表格 如何在删除和添加后 及时更新数据， 还有就是如何 不考虑性能 一次吧字表数据全部展开

### ISSUE THREAD

**Issue by 17513273271** [dotnetcore/BootstrapBlazor#142]
![image](https://user-images.githubusercontent.com/52708053/144588668-1a09d359-99d4-4366-91ef-ff29365c7795.png)

**Comment by ArgoZhang** [comment]
@17513273271 目前这个 Tree 不是我做的。是网友提交的。所以我需要看看这个怎么才能达到你需要的效果。

**Comment by ArgoZhang** [comment]
@17513273271 gitee 那边有相同的正在准备做这个
