### ISSUE TITLE
菜单点击事件 不触发了

### ISSUE THREAD

**Issue by 17513273271** [dotnetcore/BootstrapBlazor#144]
![image](https://user-images.githubusercontent.com/52708053/144811427-c6596e5f-3edf-4239-821f-4dda5587ef63.png)

**Comment by ArgoZhang** [comment]
@17513273271 大佬能否去 Gitee 提交 Issue 这里太卡了。不经常上来看

**Comment by ArgoZhang** [comment]
@17513273271 已修复
