### ISSUE TITLE
InternalTableColumn.InheritValue 的设计目的

### ISSUE THREAD

**Issue by gruan01** [dotnetcore/BootstrapBlazor#147]
###  InternalTableColumn.InheritValue 的疑惑

请问该方法的设计目的是 A / B 中的哪一个？
A， 从 `AutoGenerateClassAttribute` 里提取默认值 到 `AutoGenerateColumnAttribute `, 
B， 强制使用 `AutoGenerateClassAttribute`  指定的值？

~~~
        private static void InheritValue(AutoGenerateClassAttribute source, ITableColumn dest)
        {
            if (source.Align != Alignment.None) dest.Align = source.Align;
            if (source.TextWrap) dest.TextWrap = source.TextWrap;
            if (!source.Editable) dest.Editable = source.Editable;
            if (source.Filterable) dest.Filterable = source.Filterable;
            if (source.Readonly) dest.Readonly = source.Readonly;
            if (source.Searchable) dest.Searchable = source.Searchable;
            if (source.ShowTips) dest.ShowTips = source.ShowTips;
            if (source.Sortable) dest.Sortable = source.Sortable;
            if (source.TextEllipsis) dest.TextEllipsis = source.TextEllipsis;
        }
~~~
从方法名上看， 应该是 A。
但是，如果同时存在 `AutoGenerateClassAttribute` 和 `AutoGenerateColumnAttribute`, 实际上产生的结果 B。

期望的值应该是 `AutoGenerateClassAttribute` 做为默认值， 如果提供了 `AutoGenerateColumnAttribute`, 则用 `AutoGenerateColumnAttribute` 为准。

由于C# 的 Attribute 不支持 Nullable 类型的数据，如果要达成上面的期望， 这个地方可能需要重新设计。

### Further technical details
- BootstrapBlazor version  6.1.2
- net6
- vs 2019

**Comment by ArgoZhang** [comment]
@gruan01 大佬分析的很对，这块目前逻辑并不是一次性设计出来的。而是网友们拼凑出来的。所以并不理想。但是又一直没有时间重新设计整理。而且涉及的东西又比较多。大原则是就近原则。TableColumn 覆盖 ColumnAttribute 覆盖 ClassAttribute
