### ISSUE TITLE
动态表格的删除回调没有作用

### ISSUE THREAD

**Issue by lionliujia** [dotnetcore/BootstrapBlazor#149]
在非excel模式下，动态表格的删除回调没有作用，设置了IsExcel="true" 以后就可以了。

cs:

`

protected override void OnInitialized()

        {

            UserData.Columns.Add(nameof(SiteItem.id), typeof(int));

            UserData.Columns.Add(nameof(SiteItem.url), typeof(string));

            UserData.Columns.Add(nameof(SiteItem.keyword), typeof(string));

            UserData.Columns.Add(nameof(SiteItem.direction), typeof(string));

            UserData.Columns.Add(nameof(SiteItem.state), typeof(string));

            refresh();      //get data from mysql

            DataTableDynamicContext = new DataTableDynamicContext(UserData);  

            DataTableDynamicContext.OnChanged = args =>

            {

                if (args.ChangedType == DynamicItemChangedType.Add)  // add type works fine

                {

                    ShowAddDialog();  

                    StateHasChanged();

                }

                if (args.ChangedType == DynamicItemChangedType.Delete)  //<============= DO NOT WORK HERE 
 
                {

                    ..............................

                   ....................

                    StateHasChanged();

                }

                return Task.CompletedTask;

            };

        }
`

razor:
`
< Table TItem="DynamicObject" 

       DynamicContext="DataTableDynamicContext" 

       IsMultipleSelect="true" 

       IsBordered="true"

       //IsExcel="true"    <================= when use this mode, it works fine

       IsStriped="true" 

       ShowToolbar="true" 

       ShowExtendButtons="true"  />

`

**Comment by ArgoZhang** [comment]
release 6.2.3
