### ISSUE TITLE
步骤条在界面更新后样式错乱

### ISSUE THREAD

**Issue by O-o0O** [dotnetcore/BootstrapBlazor#151]
### Describe the bug
如图
![image](https://user-images.githubusercontent.com/40439081/149293326-f6a3f393-b8ef-4e6f-ad9e-5518f7bbd5c4.png)
![image](https://user-images.githubusercontent.com/40439081/149293487-05c21a5e-567b-49c9-a166-9929d7bbba41.png)
https://www.blazor.zone/stepss
在界面中点击重置按钮即会复现。

**Comment by ArgoZhang** [comment]
@O-o0O 这个组件重写
