### ISSUE TITLE
bundleconfig.json

### ISSUE THREAD

**Issue by DanPFW** [dotnetcore/BootstrapBlazor#152]
I'm trying to convert from the version 5x code to the version 6x code.  I'm having issues with display (colors, fonts, etc) of the left nav (side, nav).  I include the BootstrapBlazor project in my solution, in place of the package, so I'm override some of the settings that can't be overridden using the package.

It would appear there is an issue with /Layout/Layout.css being built into the solution.  I did notice the filenames are slightly different in this revision.  Is there an issue with this?

**Comment by ArgoZhang** [comment]
@DanPFW

It is strongly recommended to create a project with the latest template and compare the differences with the old version

https://marketplace.visualstudio.com/items?itemName=Longbow.BootstrapBlazorUITemplate

**Comment by DanPFW** [comment]
the differences are in the base "BootstrapBlazor" project.

**Comment by ArgoZhang** [comment]
@DanPFW Has the problem been solved? What can I do for you?
