### ISSUE TITLE
feat(Camera): supports different resolutions

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#1520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Camera supports different resolutions, like VGA,HD...

**Comment by densen2014** [comment]
需要分别指定预览界面高宽以及截图实际像素， 等提交审核完成后再pr文档

**Comment by ArgoZhang** [comment]
有 PR 了吗？
