### ISSUE TITLE
bug(Steps): items always empty

### ISSUE THREAD

**Issue by sanjusss** [dotnetcore/BootstrapBlazor#1543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

在`Steps`的第一个[示例](https://www.blazor.zone/stepss)中，没有显示出步骤条。
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/8220722/695ca72a-43ee-492c-877f-388a0c46cf40)
在`Steps.OnParametersSet`的[源码](https://github.com/dotnetcore/BootstrapBlazor/blob/main/src/BootstrapBlazor/Components/Step/Steps.razor.cs)中，清空了输入的`Items`属性。
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/8220722/20f1bfab-2c72-4352-b7dd-cce4d26d6b49)

**Comment by ArgoZhang** [comment]
@sanjusss 感谢提交 PR 请签署一下 CLA 后期这个组件我要更新甚至重做一下，会类似 Tab 把 Body 也集成进来，目前只有头不好用
