### ISSUE TITLE
Editor: Define the `picture` in `insert`

### ISSUE THREAD

**Issue by JoeZhou2** [dotnetcore/BootstrapBlazor#1545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I use the Editor in MAUI, but it looks like the picture picker has a image link box. I think it is not necessary for most case. Maybe we can replace it with a simple one, just pick local picture.

### Describe the solution you'd like

Using a simple picture picker to replace the current one.

**Comment by densen2014** [comment]
Please give us clear component information and related screenshots with detailed reproduction steps, without relevant information we cannot guess what you want to express. 

If there is no further information, this issue will be closed after 7 days

**Comment by densen2014** [comment]
@JoeZhou2

**Comment by JoeZhou2** [comment]
@densen2014 This weekend I check this entry, I think it may not the BootstrapBlazor part, it is from SummerNote. Maybe I will change the SummerNote.js to fix it. Thanks.
