### ISSUE TITLE
bug: Editor component can't close correctly when ShowSubmit is true

### ISSUE THREAD

**Issue by bingoabs** [dotnetcore/BootstrapBlazor#1548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

* When using the Editor, if using the default setting `ShowSubmit="true"`, the `dispose` action is not correct.

* The scene is like that,
1.  Environment, `Visual Studio 2022 Profressional`, `.Net 6.0`, `MAUI`, `BootstrapBlazor==7.8.5`, `BootstrapBlazor.SummerNote == 7.3.3`
2.  `Editor` using the configuration `ShowSubmit="true"`, it is the default setting
3.  After finishing the editing work, first click the submit button, then click the custom button(not in Editor) in same page to go to another page
4. It can go to another page, but raise the error `TypeError: Cannot read property 'closest' of null`

### Expected Behavior

* Checking the source code in `BootstrapBlazor/src/extensions/components/BootstrapBlazor.SummerNote/Component/Editor/Editor.razor.js`

* It looks like when `ShowSubmit="true"`

> 1. When click the submit button, it will destroy the submit tool tip in line:57

> 2. And when dispose, it try to destroy  the submit tool tip again in line:163

* So repeating to destroy the submit raises the error. Set  `ShowSubmit="false"` can fix this problem, but it is not good performance. Thanks.

**Comment by ArgoZhang** [comment]
@bingoabs hi. thank you for contacting us. this bug has been fixed and released `7.3.4`
