### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by Vikas8881** [dotnetcore/BootstrapBlazor#156]
Hi, Can anyone suggest to me how can I customize validation errors in this control?

                <EditorItem @bind-Field="@context.Business_name" PlaceHolder="Enter Business Name" Text="Business Name"/>
           Currently its show like Business_name field is required i want to show this like Business Name is Required or custom Text

Thankyou

**Comment by ArgoZhang** [comment]
@Vikas8881 hi, for now not support yet. it'll be supported next version

**Comment by Vikas8881** [comment]
@ArgoZhang Thank you for your response. and thanks for making this awesome and brilliant components

**Comment by ArgoZhang** [comment]
@Vikas8881 you are welcome. you can find more sample code from https://www.blazor.zone/validateforms#CustomDisplsyError
