### ISSUE TITLE
用 vs2022 创建模板后 导航栏丢失

### ISSUE THREAD

**Issue by anan1213095357** [dotnetcore/BootstrapBlazor#159]
![image](https://user-images.githubusercontent.com/43770875/155562343-38e9efb1-9eb7-484f-9142-83c42f8d3dba.png)
引入样式后
![image](https://user-images.githubusercontent.com/43770875/155562487-d5056389-2d24-40dc-817d-570bb1def72f.png)
这里似乎不支持 这样子
![image](https://user-images.githubusercontent.com/43770875/155562595-b1920165-2ec8-4f2c-b79c-b8956a3b9c79.png)

**Comment by anan1213095357** [comment]
我的环境是 .net6

**Comment by densen2014** [comment]
请按组件文档走一遍
https://www.blazor.zone/install-server

官网是
https://www.blazor.zone/index

QQ群
795206915

**Comment by anan1213095357** [comment]
> 请按组件文档走一遍
> https://www.blazor.zone/install-server
> 
> 官网是
> https://www.blazor.zone/index
> 
> QQ群
> 795206915

是的，我新建了两三个项目。均碰见导航栏丢失的情况。

**Comment by YSMC-W** [comment]
你这个我没有看懂，建议使用我们提供的框架创建项目
https://www.blazor.zone/template

**Comment by ArgoZhang** [comment]
@anan1213095357 提交一个 demo 上来吧。看看你哪一步做错了

**Comment by and9527** [comment]
這樣就會出現了
![image](https://user-images.githubusercontent.com/6825409/180387423-00a2102c-d768-435b-8266-3e8b9ea8d4be.png)
