### ISSUE TITLE
Where to put CascadingAuthenticationState for identity ?

### ISSUE THREAD

**Issue by ahmetkocadogan** [dotnetcore/BootstrapBlazor#161]
I created a project using the Bootstrap Blazor template.

In app.razor file, we have this root `<BootstrapBlazorRoot >`

How can i use `<CascadingAuthenticationState>` to add identity ? When i make it the top element, or inside  `<BootstrapBlazorRoot >` , router does not seem to work.

**Comment by ArgoZhang** [comment]
```
<BootstrapBlazorRoot>
    <CascadingAuthenticationState>
        <Router AppAssembly="@typeof(Program).Assembly">
            <Found Context="routeData">
                <PageTitle>@Title</PageTitle>
                <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                </AuthorizeRouteView>
            </Found>
            <NotFound>
                <LayoutView Layout="@typeof(MainLayout)">
                    <p>Sorry, there's nothing at this address.</p>
                </LayoutView>
            </NotFound>
        </Router>
    </CascadingAuthenticationState>
</BootstrapBlazorRoot>
```

or

```<CascadingAuthenticationState>
    <BootstrapBlazorRoot>
        <Router AppAssembly="@typeof(Program).Assembly">
            <Found Context="routeData">
                <PageTitle>@Title</PageTitle>
                <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                </AuthorizeRouteView>
            </Found>
            <NotFound>
                <LayoutView Layout="@typeof(MainLayout)">
                    <p>Sorry, there's nothing at this address.</p>
                </LayoutView>
            </NotFound>
        </Router>
    </BootstrapBlazorRoot>
</CascadingAuthenticationState>
```

**Comment by ahmetkocadogan** [comment]
@ArgoZhang  i tried both, but router didn't work and i couldn't navigate between pages after adding CascadingAuthenticationState. I'll check again if there is something else wrong. Thank you.

**Comment by ahmetkocadogan** [comment]
@ArgoZhang sorry to bother you again, i'm also learning blazor and couldn't make it work with identity properly.

I added required nuget packages for identity to shared project, and scafolded UI into server project. Is that wrong ?

Is there any possibility for you to create a sample project on top of the project that gets created with visual studio template and add identity to it?

**Comment by ArgoZhang** [comment]
@ahmetkocadogan sure. let me create a sample project and shared it with you later

**Comment by ArgoZhang** [comment]
@ahmetkocadogan hi bro. you can get the sample project from the following repo.

https://github.com/ArgoZhang/IdentitySample

**Comment by ahmetkocadogan** [comment]
@ArgoZhang I can't thank you enough. This is really what i want. Thank you.

**Comment by ArgoZhang** [comment]
@ahmetkocadogan you are welcome
