### ISSUE TITLE
bug: Select Component Not Clearing Value when IsClearing is true 

### ISSUE THREAD

**Issue by VTeamDeveloper1** [dotnetcore/BootstrapBlazor#1618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

im added to default record(Value is 0)  to Items but not working

**Comment by ArgoZhang** [comment]
@VTeamDeveloper1 

`IsClearable` mean's value will be reset when the currently selected item is not the default value.

you can try adding an empty item in the `Items`. it should match your requirement.

```
<div style="width: 120px;">
    <Select Color="Color.Primary" IsClearable="true" Items="Items" Value="Model.Name"></Select>
</div>

@code {
    private Foo Model { get; set; } = new Foo();

    private IEnumerable<SelectedItem> Items { get; set; } = new[]
    {
        new SelectedItem ("Beijing", "Beijing"),
        new SelectedItem ("Shanghai", "Shanghai")
    };
}
```

**Comment by VTeamDeveloper1** [comment]
thank you very much for your reply
