### ISSUE TITLE
Dark theme support.

### ISSUE THREAD

**Issue by OrionRiftStudios** [dotnetcore/BootstrapBlazor#162]
Hello.
First of all thank you for your amazing work!

I am trying to use some components of this library but I am using MudBlazor with dark theme but looks like this library is not supporting Dark theme.
It would be nice if we could have this feature or if this a way to change the theme to dark I cannot find it in the docs.

Thank you

**Comment by ArgoZhang** [comment]
@OrionRiftStudios thank you for contacting us. The dark theme needs a very professional design. i am not good at this. so I can't do this job. need somebody to submit a PR for this.
