### ISSUE TITLE
chore: The Web Assembly pattern loads a large number of non compiled JS

### ISSUE THREAD

**Issue by xsoutline** [dotnetcore/BootstrapBlazor#1648]
### Which class is this unit test associated with?

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/31274694/1d328016-8cf2-443a-863c-98cc75bc3d37)
I need to load only one JavaScript file, how to solve it?

**Comment by Vision-Zhang** [comment]
@xsoutline blazor's js isolation mode is such that using that component loads that component's js, and there is no way to merge it into one file
