### ISSUE TITLE
How to pass extra parameters to IDataService or OnQueryAsync

### ISSUE THREAD

**Issue by oruchreis** [dotnetcore/BootstrapBlazor#165]
Hi,
I'm trying to implement `IDataService` or `OnQueryAsync` for `Table` component. But I couldn't find how to pass extra parameter to `QueryAsync` method. For instance I must pass parent table item id to sub table's query method. Or if I've implemented IDataService, I must access the parameters(`Parameter` attribute or `QueryString` etc..) of the current page or component that includes the `Table` component. So I need to pass extra parameters to query methods. I've tried something like this:
```razor
<Table TItem="MenuItem" Context="item" IsPagination="true" PageItemsSource="new int[] { 10, 25, 50 }"
       IsStriped="true" IsBordered="true"
       ShowToolbar="true" ShowDefaultButtons="false"
       OnQueryAsync="@OnQueryAsync">
....
....
<DetailRowTemplate>
   <Tab>
      <TabItem Text="Localization">
         <Table TItem="MenuItemLocalContent" Context="localContent" IsBordered="true" ShowToolbar="false"
                         OnQueryAsync="@(async options => await OnLocalContentQuery(options, item.Id))">
```
But this time it gives this error which I think query's context is different from parent asynclocal context. 
```
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext
```
Also if I implement IDataService I didn't figure out any way to pass this parent table item id to this sub table's `IDataService`. Also I need to pass pages parameters to parent table's `QueryAsync` method.

**Comment by ArgoZhang** [comment]
@oruchreis hi, I'm sorry for the delay response. 

https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-6.0

you can try use `DbContextFactory`

```
builder.Services.AddDbContextFactory<ContactContext>(opt =>
    opt.UseSqlite($"Data Source={nameof(ContactContext.ContactsDb)}.db"));
```

**Comment by oruchreis** [comment]
Thanks, I solved that issue with owningcompoentbase, but still i didnt figıre out how to get extra parameters to the IDataService like master table's id. i did lastly created another component for the detail tables without using IDataService.

**Comment by ArgoZhang** [comment]
@oruchreis can you create a demo repo? i will submit pr show you
