### ISSUE TITLE
Support razor syntax for Menu component.

### ISSUE THREAD

**Issue by oruchreis** [dotnetcore/BootstrapBlazor#166]
### Is your feature request related to a problem? Please describe.
The `Menu` component has `Items` property typed `MenuItem` to display menu items and this `MenuItem` is not a RenderFragment. We should use razor syntax to implement menu items rather than setting list of objects like `MenuItem`.

### Describe the solution you'd like
Please consider menu component implementations on other Blazor component libraries like blazorise, mudBlazor, etc.. They supports razor syntax like this:
```razor
<Menu>
    <MenuItem></MenuItem>
    <MenuItem></MenuItem>
    <Menu>@*for sub menus, dropdown*@
            <MenuItem></MenuItem>@*sub menu item*@
    </Menu>
    <MenuItem></MenuItem>
    <MenuItem></MenuItem>
</Menu>
```

**Comment by ArgoZhang** [comment]
@oruchreis good idea.

**Comment by ArgoZhang** [comment]
@oruchreis  hi. I really want to realize this function, but due to the problem of this component design, it is difficult to realize this function at present. there are `TopMenu` `SideMenu` in menu component.
