### ISSUE TITLE
bug: ImageViewer 在 OnParametersSetAsync 设置不存在的图片路径后报错

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#1663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ImageViewer 组件在 OnParametersSetAsync 后设置不存在的路径会直接报错卡住

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/acac0157-9693-4af8-8549-bf1726db9afe)

ImageViewer测试
选择ID1记录，正常。
选择ID2记录，因为真实的文件不存在，所以会报“加载失败”，在切换别的产品时，只显示“加载失败”，不显示图片 。
选择ID3记录，在数据库中有2个文件，第2个文件不存在，不受影响；
选择ID4记录，在数据库中有2个文件，第1个文件不存在，受影响，在切换别的产品时，只显示“加载失败”，不显示图片；
选择ID5记录，没有符合相等条件的路径，处理为空，显示正常。

### Steps To Reproduce

[BlazorImageViewer.zip](https://github.com/dotnetcore/BootstrapBlazor/files/12162061/BlazorImageViewer.zip)

### .NET Version

7

**Comment by ArgoZhang** [comment]
@densen2014 

1. 正常
2. 已修复
3. 正常
4. 第一个文件不存在，又设置了模板，模板内不可点击，无法弹出预览框（有没有新思路，应该如何处理才比较合理？）
5. 正常

未解决问题第四个，有什么思路？

**Comment by densen2014** [comment]
> @densen2014 
> 
> 
> 
> 1. 正常
> 
> 2. 已修复
> 
> 3. 正常
> 
> 4. 第一个文件不存在，又设置了模板，模板内不可点击，无法弹出预览框（有没有新思路，应该如何处理才比较合理？）
> 
> 5. 正常
> 
> 
> 
> 未解决问题第四个，有什么思路？

第四个，image用懒加载，设置error后加载错误图片可行吗？
