### ISSUE TITLE
Collapse Bar Tooltip does not go away on mobile browsers

### ISSUE THREAD

**Issue by ahmetkocadogan** [dotnetcore/BootstrapBlazor#171]
I created the project with template.

![image](https://user-images.githubusercontent.com/7287309/161003753-0c4fedb9-1aae-4837-8f71-dcdb04d599e1.png)

This Click to expand/collapsde sidebar tooltip goes away on desktop browsers after mouse leaves the are of icon.

But on mobile browsers, i tested with safari and edge, after expand or collapse sidebar, tooltip stays there  till i press another area in the website.

Is there a parameter to hide the tooltip, like a parameter to never show the tooltip?

**Comment by ArgoZhang** [comment]
@ahmetkocadogan hi, sorry for the delay response. there is a parameter on Layout named `TooltipText`. can you have a try set the value is `string.Empty`?
