### ISSUE TITLE
Deub模式调试：仅我的代码警告

### ISSUE THREAD

**Issue by bicijinlian** [dotnetcore/BootstrapBlazor#1723]
### Which class is this unit test associated with?

Deub模式调试时，出现“仅我的代码警告”
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/10394955/fa0cc7fb-1c7b-4832-9133-f7af213a5bdc)

**Comment by Vision-Zhang** [comment]
@bicijinlian 这是你自己 vs 的设置

**Comment by bicijinlian** [comment]
这个是引用的类库导致的吧



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月28日 09:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [dotnetcore/BootstrapBlazor] Deub模式调试：仅我的代码警告 (Issue #1723) |

@bicijinlian 这是你自己 vs 的设置

**Comment by ArgoZhang** [comment]
@bicijinlian 跟我们的类库无关的。你可以新建一个项目，然后调试
