### ISSUE TITLE
非开发模式运行时，主程序错误

### ISSUE THREAD

**Issue by bicijinlian** [dotnetcore/BootstrapBlazor#1724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

非开发模式运行后，主程序崩溃！
其实是想看看，非开发模式下，示例中源代码显示(Pre组件)的逻辑 (好像是从gitee那里获取文件，这个也很不解：依赖外网及特定的第三方网址)
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/10394955/21e154b9-5fa0-407b-bffe-505679b28247)
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/10394955/ae49666e-bacd-4fa5-aa9c-0fb6a331466c)
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/10394955/3c4b27e7-f94e-4bb7-8d3c-beda9b449d19)
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/10394955/5aff12a9-b893-4fc7-9738-a7feaf730332)

### .NET Version

7.0.9

**Comment by Vision-Zhang** [comment]
@bicijinlian 文档正在改版 移除以这个依赖

**Comment by ArgoZhang** [comment]
我猜你是 Release 模式了，未发布直接运行的
