### ISSUE TITLE
Table: Overlapping issue with Select based filters.

### ISSUE THREAD

**Issue by wettstein-guebau** [dotnetcore/BootstrapBlazor#176]
### Describe the bug
The overlap doesn't work properly for the Select based filters like BoolFilter, EnumFilter...

### To Reproduce

- Open the table filtering sample page.
- Filtering the ShowFilterHeader demo to one line.
- Open Complete filter

![image](https://user-images.githubusercontent.com/99962971/163442201-0e9c182d-d330-4752-835d-e34582ddc244.png)

### Further technical details
- BootstrapBlazor 6.5.2

**Thank you for the great BootstrapBlazor project!**

**Comment by ArgoZhang** [comment]
@wettstein-guebau hi, This is a known problem due to the dropdown component of the `bootstrap`

**Comment by wettstein-guebau** [comment]
hi, then I will live with it and hope bootstrap will fix it in the next version.

**Comment by ArgoZhang** [comment]
@wettstein-guebau hi, you can set min-height  on table
