### ISSUE TITLE
表格组件搜索功能，请求添加特性

### ISSUE THREAD

**Issue by LambertW** [dotnetcore/BootstrapBlazor#177]
很方便的组件，谢谢您的辛苦付出！

提几点优化，

1. 对于枚举类型的列(使用LookUpServiceKey)，并且当Searchable=true时，新增AllowSearchEmpty(默认增加一个请选择下拉框)
2. 对于枚举类型的列(使用LookUpServiceKey)，并且当Searchable=true时，新增SearchAllowMultiSelect，以支持多选组件
3. 对于枚举类型的列(使用LookUpServiceKey)，并且当Searchable=true，SearchAllowMultiSelect=true，新增SearchAllowMultiSelectShowSearch，多选组件支持搜索功能
4. 比较国产化的一项内容，对下拉框，多选，支持拼音首字母查找(结合上述的下拉框)

**Comment by densen2014** [comment]
LookUpServiceKey... 你UK是啥?大不列颠?认真对待一下拼写, 否则一头雾水

**Comment by densen2014** [comment]
大佬入群聊, qq 795206915

**Comment by ArgoZhang** [comment]
track https://gitee.com/LongbowEnterprise/BootstrapBlazor/issues/I5338U
