### ISSUE TITLE
Focus on button

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#179]
Hi, I have a necessity to use focus on Button, for my project I create a provider to do this, but I would like to know if is possible to include this on the component?
Thank you very much

**Comment by ArgoZhang** [comment]
@gmondin sure! welcome to submit PR

**Comment by gmondin** [comment]
For the focus on the button, I used the same way that you are using on input focus, so the code will be like this.
(your code 🙂)
I needed this because for my kind of project, the users has a barcode reader, so they normally use only the fisical keyboard, to be more faster.

ButtonBase.cs

[cid:36cff064-fd8f-4f6a-8614-80af80e17ac2]

[cid:e5c86717-46b1-4e18-8e3b-e1966cae02fb]

Button.razor

[cid:75973bee-070b-48e3-a3f5-6668bf959b67]


Gabriel Mondin


________________________________
De: Argo Zhang ***@***.***>
Enviado: terça-feira, 26 de abril de 2022 13:15
Para: dotnetcore/BootstrapBlazor ***@***.***>
Cc: Gabriel Mondin ***@***.***>; Mention ***@***.***>
Assunto: Re: [dotnetcore/BootstrapBlazor] Focus on button (Issue #179)


@gmondin<https://github.com/gmondin> sure! welcome to submit PR

**Comment by gmondin** [comment]
Can I ask, in cases like this its opened for I change the code and submit on git hub or I need some special access? also for keep the same standard that you do.
Thank you very much


Gabriel Mondin


________________________________
De: Argo Zhang ***@***.***>
Enviado: terça-feira, 26 de abril de 2022 13:15
Para: dotnetcore/BootstrapBlazor ***@***.***>
Cc: Gabriel Mondin ***@***.***>; Mention ***@***.***>
Assunto: Re: [dotnetcore/BootstrapBlazor] Focus on button (Issue #179)


@gmondin<https://github.com/gmondin> sure! welcome to submit PR

**Comment by gmondin** [comment]
Now that I saw that didin't show up the images, so:
(its your code for focus on input)

ButtonBase.cs

protected ElementReference FocusElement { get; set; }
public ValueTask FocusAsync() => FocusElement.FocusAsync();

Button.razor

<button @ref="FocusElement" />

Thank you very much

**Comment by ArgoZhang** [comment]
@gmondin hi, sorry for the delay reply. can you create a new repro let us figure out this issue, or you can submit a PR for this issue

**Comment by gmondin** [comment]
HI, no problem for the delay, I have use the same code for the FocusAsync() that is using for input and works really well.
Thank you very much


Gabriel Mondin


________________________________
De: Argo Zhang ***@***.***>
Enviado: segunda-feira, 2 de maio de 2022 06:47
Para: dotnetcore/BootstrapBlazor ***@***.***>
Cc: Gabriel Mondin ***@***.***>; Mention ***@***.***>
Assunto: Re: [dotnetcore/BootstrapBlazor] Focus on button (Issue #179)


@gmondin<https://github.com/gmondin> hi, sorry for the delay reply. can you create a new repro let us figure out this issue, or you can submit a PR for this issue

**Comment by ArgoZhang** [comment]
@gmondin that's good. i wanna add the following parameter on ButtonBase

```
[Parameter]
public bool IsAutoFocus { get; set; }
```

the default value is false. can this match your requirement?

**Comment by gmondin** [comment]
Hi, I think is better use this one, because for my case is not autofocus, but after some information and I can't put automatic, I need that the user confirm the action.


ButtonBase.cs

protected ElementReference FocusElement { get; set; }
public ValueTask FocusAsync() => FocusElement.FocusAsync();

Button.razor

<button @ref<https://github.com/ref>="FocusElement" />

what do you think?


Gabriel Mondin


________________________________
De: Argo Zhang ***@***.***>
Enviado: segunda-feira, 2 de maio de 2022 10:12
Para: dotnetcore/BootstrapBlazor ***@***.***>
Cc: Gabriel Mondin ***@***.***>; Mention ***@***.***>
Assunto: Re: [dotnetcore/BootstrapBlazor] Focus on button (Issue #179)


@gmondin<https://github.com/gmondin> that's good. i wanna add the following parameter on ButtonBase

[Parameter]
public bool IsAutoFocus { get; set; }


the default value is false. can this match your requirement?

**Comment by ArgoZhang** [comment]
@gmondin i provider a instance method. you can use @@ref keywork and call it directly

```
public void Focus()
{
    FocusElement.FocusAsync();
}
```

**Comment by gmondin** [comment]
Yep, this is the solution that I need, but, sorry, I dont understand, I couldnt found focus on button, also using @ref, are you saying that this alread exist or you gonna provider on the nexts milestones?



Gabriel Mondin


________________________________
De: Argo Zhang ***@***.***>
Enviado: segunda-feira, 2 de maio de 2022 10:34
Para: dotnetcore/BootstrapBlazor ***@***.***>
Cc: Gabriel Mondin ***@***.***>; Mention ***@***.***>
Assunto: Re: [dotnetcore/BootstrapBlazor] Focus on button (Issue #179)


@gmondin<https://github.com/gmondin> i provider a instance method. you can use @@ref<https://github.com/ref> keywork and call it directly

public void Focus()
{
    FocusElement.FocusAsync();
}

**Comment by ArgoZhang** [comment]
@gmondin later, I will let you know

**Comment by gmondin** [comment]
thank you very much


Gabriel Mondin


________________________________
De: Argo Zhang ***@***.***>
Enviado: segunda-feira, 2 de maio de 2022 11:07
Para: dotnetcore/BootstrapBlazor ***@***.***>
Cc: Gabriel Mondin ***@***.***>; Mention ***@***.***>
Assunto: Re: [dotnetcore/BootstrapBlazor] Focus on button (Issue #179)


@gmondin<https://github.com/gmondin> later, I will let you know

**Comment by ArgoZhang** [comment]
@gmondin hi, I had submit 6.5.19 version on Nuget.org. later you can try it.

##### add IsAutoFocus parameter
```
[Paramter]
public bool IsAutoFocus { get; set; }
```

##### add FocusAsync method
```
public ValueTask FocusAsync() => ButtonElement.FocusAsync();
```

you can use it as the following code

```
<Button Text="Test" @ref="FocusButton" />

@code 
{
      private async Task Test()
      {
            await FocusButton.FocusAsync();
      }
}
```

**Comment by gmondin** [comment]
thank you very much :)

**Comment by ArgoZhang** [comment]
@gmondin can you give the repo a star? at the top right of the page

**Comment by gmondin** [comment]
sure :)

**Comment by ArgoZhang** [comment]
@gmondin  thanks
