### ISSUE TITLE
Code documentation in english

### ISSUE THREAD

**Issue by franklupo** [dotnetcore/BootstrapBlazor#181]
Hi,
it is difficult to work with the internal documentation of the code. It should be translated into English.

**Comment by ArgoZhang** [comment]
@franklupo sure. There's too much to translate. I have a lot of work to do alone

**Comment by franklupo** [comment]
but in the code would you like to keep the current language or could it be translated into english?

**Comment by ArgoZhang** [comment]
@franklupo I will use English as my preferred language in the code
