### ISSUE TITLE
Gets all properties of the binding model in EditorForm 

### ISSUE THREAD

**Issue by Huangfusu** [dotnetcore/BootstrapBlazor#184]
首先非常感谢你们的工作， 这套组件真的非常棒。
我在寻找一个 类似在 winform 中 propertygrid 的组件，EditorForm 已经具备了非常好的基础， 不同的地方是 EditorForm针对特定 TModel 的，propertygrid  需要处理任意类型， 这需要在 获取绑定模型所有属性 时做不同的事情。
如果为  将下面语句 （Line 228 in EditorForm.razor.cs）
     // 获取绑定模型所有属性
       var items = InternalTableColumn.GetProperties<TModel>().ToList();
  封装成一个虚方法，让继承类有机会改写 获取绑定模型属性的逻辑。
你觉得如何

**Comment by Huangfusu** [comment]
刚才没注意 EditorForm<TModel>  已经  sealed 了，增加个 Func<object,IEnumerable<ITableColumn>>  或者其它办法都好

**Comment by ArgoZhang** [comment]
@Huangfusu 非常感谢您联系我们，我们主要是在国内码云平台，这了实在是太卡了。https://gitee.com/LongbowEnterprise/BootstrapBlazor

您的这个 `PropertyGrid` 已经有人来提过需求了，我也知道，`winform` 我也可以的。您看看您的具体需求，实际使用中想如何扩展？或者能否提交 PR 直接把功能做到我们的组件上，欢迎与我们讨论

**Comment by Huangfusu** [comment]
@ArgoZhang 回复神速，十分感谢。 回码云继续交流，这个关闭掉。
