### ISSUE TITLE
bug: Starting from version 7.8.7, the custom cell dropdown in the grid cannot open the menu!

### ISSUE THREAD

**Issue by mswang2005** [dotnetcore/BootstrapBlazor#1851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Starting from version 7.8.7, the custom cell dropdown in the grid cannot open the menu!

### .NET Version

.net 7

### Anything else?

VS2022

**Comment by ArgoZhang** [comment]
@mswang2005 any screenshots? please provider a repro demp project thanks

**Comment by ArgoZhang** [comment]
@mswang2005  no response for this issue auto closed
