### ISSUE TITLE
chore(Codecov): test code coverage

### ISSUE THREAD

**Issue by ham187** [dotnetcore/BootstrapBlazor#1857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Hello, I want to be able to add another docview in the same way you can add another tab.

eg.:  TabSet.AddTab

DockViewSet.AddDockComponent

thank you :)

**Comment by ArgoZhang** [comment]
@ham187 not support yet. just a response

**Comment by ArgoZhang** [comment]
@ham187 According to the current design of `DockView`, there will not be any instance methods such as `AddTab` provided, but some extension methods will be added to make it more convenient for users to add `DockComponent`
