### ISSUE TITLE
Visual Studio 2022 使用项目模板创建之后不支持热重置功能

### ISSUE THREAD

**Issue by Gclove2000** [dotnetcore/BootstrapBlazor#1859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

使用BootstrapBalzor的项目模板创建文件之后，在运行后修改文件内容点击热重置不生效。我测试过只有css样式修改可以热重置，但是html元素内容修改热重置不生效。点击网页刷新按钮也不生效。

### .NET Version

6.0

### Anything else?

Viusal Studio 2022
.NET Core 6.0

**Comment by ArgoZhang** [comment]
@Gclove2000 热更新的功能是 `dotnet cli` 提供的，目前我们组件或者工程都无法更改 `hot reload` 的行为，建议去微软 `dotnet` 仓库提交 issue

**Comment by Gclove2000** [comment]
哦，抱歉，我理解错意思了，我以为是去你这里提交。OK，我去微软仓库里面提交。抱歉打扰了
