### ISSUE TITLE
feat: Card get last state of Collapsed by user click

### ISSUE THREAD

**Issue by coddoge** [dotnetcore/BootstrapBlazor#1860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

		<PackageReference Include="BootstrapBlazor" Version="7.8.11" />

I want to save/load UI state in my app, include `Collapsed` of `Card`
But the property `Collapsed` of `Card` is only setter is working , i can not get the lastest user clicked to collapse or expand state of it

### Describe the solution you'd like

I have no idea, if without js glues

### Additional context

forgive my ugly code

```csharp
public class SLCard : Card, IDisposable
{
    [Parameter] public string? SLName { get; set; }
    [Inject] public IEventBus? EventBus { get; set; }
    [Inject] public IJSRuntime? JsRuntime { get; set; }

    private IJSObjectReference? _utility;

    private string SLFullName => SLName + "-Collapse";

    private bool _isAlive;

    protected override void OnInitialized()
    {
        base.OnInitialized();
        EventBus!.Subscript<SaveLoadFlagTellEvent>(HandleSaveLoadFlagTell);
    }

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        _utility = await JsRuntime!.InvokeAsync<IJSObjectReference>("import", "./js/glue.js");
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);
        if (firstRender)
        {
            if (SLName != null) EventBus!.Publish(new SaveLoadFlagAskEvent(SLFullName));

            _isAlive = true;
            _ = CycleOfDetect();
        }
    }

    private async Task CycleOfDetect()
    {
        while (_isAlive)
        {
            await Task.Delay(100);

            //improve: use event instead of polling https://getbootstrap.com/docs/5.3/components/collapse/#events
            var className = await _utility!.InvokeAsync<string>("GetCssClassById", Id);
            var flag = className.Contains("show");

            if (flag == !Collapsed) continue;
            Collapsed = !flag;
            EventBus!.Publish(new SaveLoadFlagTellEvent(SLFullName, Collapsed));
        }
    }

    private void HandleSaveLoadFlagTell(SaveLoadFlagTellEvent obj)
    {
        if (SLName == null) return;
        if (obj.Name != SLFullName) return;
        if (obj.Value == Collapsed) return;

        Collapsed = obj.Value;
        StateHasChanged();
    }

    public void Dispose()
    {
        _isAlive = false;
        EventBus!.UnSubscript<SaveLoadFlagTellEvent>(HandleSaveLoadFlagTell);
    }
}
```

**Comment by ArgoZhang** [comment]
@coddoge hi. can you give this project a star? thanks. you can set a field in your project keep the collapse status

**Comment by coddoge** [comment]
> you give this project a star?

of course!

> you can set a field in your project keep the collapse status

In this project, we use event bus to communication with Save/Load service.

So,

Any plan or consider wrap events to C# from boostrap? It's very useful in this situation :)

Or at least provide a getter wrap ``check show in element.className`` to get last real state?

**Comment by ArgoZhang** [comment]
@coddoge thanks. I will redesign it to fit your requirement in the next release.

**Comment by coddoge** [comment]
@ArgoZhang Thank you verymuch!

**Comment by ArgoZhang** [comment]
@coddoge PR is in processing. you can use the `Collapsed` parameter to get the latest status of the card. later the `v7.9.1-beta01` will be released auto after passing the unit test.

**Comment by coddoge** [comment]
Excellence! 

Now the getter is work expected.

But can I request a Two-way binding for the Property Like  `@bind-Value` ?

Then I can remove the redundancy code `SaveLoad[SLFullName] = _card.Collapsed` before app shutdown

**Comment by ArgoZhang** [comment]
sure! Tomorrow


发自我的 iPhone

在 2023年8月2日，21:36，coding doge ***@***.***> 写道：

﻿

Excellence!

Now the getter is work expected.

But can I request a Two-way binding for the Property Like @bind-Value ?

Then I can remove the redundancy code SaveLoad[SLFullName] = _card.Collapsed before app shutdown
