### ISSUE TITLE
bug: IDataService无法使用TryAddSingleton注入

### ISSUE THREAD

**Issue by j4587698** [dotnetcore/BootstrapBlazor#1863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

使用FreesqlDataService时无效，经检查个人认为是`TryAddSingleton`引起的。

### Expected Behavior

无

### Steps To Reproduce

新建一个BB模板项目，将里面的`AddTableDemoDataService`由`services.AddSingleton(typeof(IDataService<>), typeof(TableDemoDataService<>));`修改为`services.TryAddSingleton(typeof(IDataService<>), typeof(TableDemoDataService<>));`
则不会显示Demo数据。
repo:https://github.com/j4587698/BBTest

### .NET Version

7.0.306

### Anything else?

(base) j4587698@j4587698-PC:~/Desktop$ dotnet --info
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

运行时环境:
 OS Name:     Deepin
 OS Version:  23
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.306/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.306 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by ArgoZhang** [comment]
@j4587698 三个扩展服务工程源码更新包 `v7.9.0` 更新破坏性更新，内部改为 `services.AddScoped(typeof(IDataService<>), typeof(TableDemoDataService<>));` 工程模板升级新版本更新内置代码

**Comment by ArgoZhang** [comment]
@j4587698 我看了一下模板工程，最新模板已经改为 `AddScoped` 啦
