### ISSUE TITLE
feat: Card Collapsing animation missing after update to v7.9.1-beta02 from v7.8.11

### ISSUE THREAD

**Issue by coddoge** [dotnetcore/BootstrapBlazor#1869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I noticed the source in Card.razor its use a `if` statment to switch between show and hide content, it cause missing animation effect during collapsing

### Describe the solution you'd like

If possible, Two-way binding for `Collapsed` property , And collapsing animation, it both available

### Additional context

Is time to wrap event from boostrap to C#?

https://getbootstrap.com/docs/5.3/components/collapse/

 - hide.bs.collapse
 - hidden.bs.collapse
 - show.bs.collapse
 - shown.bs.collapse

Above event can accurate determine last state of Collapse and keep animation effect

**Comment by ArgoZhang** [comment]
@coddoge ok. will be redesigned later. thank you submit issue

**Comment by ArgoZhang** [comment]
@coddoge pls try `v7.9.1-beta03` later

**Comment by coddoge** [comment]
@ArgoZhang I try update to `v7.9.1-beta03` but still missing animate effect during collapsing

Then I create a demo project again for check it, both my computer and another computer can repo the problem

https://anonfiles[.]com/Z3W1d360z2/BlazorApp2_2_7z

**Comment by ArgoZhang** [comment]
@coddoge Hi. could you provide a GitHub repo for this issue? i can't download the project from the URL. sorry

**Comment by coddoge** [comment]
@ArgoZhang Try replace `[.]` to `.`  because block to post reply

I found more problem in card component, let me create a new demo project to check then push to GitHub repo

**Comment by coddoge** [comment]
@ArgoZhang This is repo for repro bug, I found some interesting details

 https://github.com/coddoge/bb-bug-reproduce/blob/main/CardBugs1/Pages/Index.razor

**Comment by ArgoZhang** [comment]
@coddoge hi bro. very embarrassed. please try `v7.9.1-beta04`
