### ISSUE TITLE
Error on DateTimePicker

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#187]
Hi, if my project is multi-language and the date format change if the language, I have an error on DateTimePicker:

Input string was not in a correct format. -    
at System.Globalization.TimeSpanFormat.FormatCustomized(TimeSpan value, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, StringBuilder result)
   at System.Globalization.TimeSpanFormat.Format(TimeSpan value, String format, IFormatProvider formatProvider)
   at System.TimeSpan.ToString(String format)
   at BootstrapBlazor.Components.DatePickerBody.get_TimeValueString()
   at BootstrapBlazor.Components.DatePickerBody.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

Could you check?
Thank you very much

**Comment by ArgoZhang** [comment]
@gmondin sorry for delay reply again. sure I will repro this error. are you find this in English culture?

**Comment by gmondin** [comment]
Hi Argo, thank you for answer me, I found on Italian and Spanish culture, on english works well.

**Comment by ArgoZhang** [comment]
@gmondin hi, I checked it. I think maybe your should set TimeFormat parameter correctly value

**Comment by ArgoZhang** [comment]
@gmondin what's culture code on Italian and Spanish?

**Comment by ArgoZhang** [comment]
@gmondin could you submit a test page for this issue? I didn't repro this issue.

**Comment by gmondin** [comment]
HI @ArgoZhang , I just add the component for make a trial, and I have the error, was like this.

On .razor

<DateTimePicker TValue="DateTime" Value="@DateTime.Today" />

the culture info I'm changing like this, based on a information that I have for every user:

        CultureInfo culture = new(language);
        CultureInfo.DefaultThreadCurrentCulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;
        
Here:         language, can be "it-IT" that I have the error.

**Comment by ArgoZhang** [comment]
@gmondin are you set the localizer resource file? under `it-IT.json` in locales folder

**Comment by gmondin** [comment]
@ArgoZhang yep, I'm setting the localizer on the resource file (but originally the project is using il resource file .resx instead of .json) , the other parts of the project is working really well with this and also if the user use the english language, the datetimepicker works really well.

**Comment by ArgoZhang** [comment]
@gmondin `BootstrapBlazor` component support `resx` format localizer too.

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddBootstrapBlazor(localizationAction: options =>
    {
        // support resx format resource file
        options.ResourceManagerStringLocalizerType = typeof(Program);

        // set json format resource file
        options.AdditionalAssemblies = new[] { typeof(BootstrapBlazor.Shared.App).Assembly };

        // set local json file
        options.AdditionalJsonFiles = new string[]
        {
            @"D:\Argo\src\BootstrapBlazor\src\BootstrapBlazor.Server\Locales\zh-TW.json",
            @"D:\Argo\src\BootstrapBlazor\src\BootstrapBlazor.Server\Locales\zh-CN.json"
        };
    });
}
```

**Comment by gmondin** [comment]
Hi @ArgoZhang I have publish a simple project with the issue in this repo: https://github.com/gmondin/bootstrapBlazorIssues

**Comment by ArgoZhang** [comment]
@gmondin sorry for delay reply. Let me take a look for this issue. maybe i will submit pr into that repo
