### ISSUE TITLE
Error table out of size

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#188]
Hi, after some release, the table component is taking a line after the height and being on top of another component on the page, before was not like this.

Thank you very much

**Comment by ArgoZhang** [comment]
@gmondin could you paste a picture for this issue? I have no idea for this

**Comment by gmondin** [comment]
Hi @ArgoZhang , here I'm using a table with infinity scroll and a fixed height and using tab's or modals with buttons on the footer of the modal or on the bottom after the tab, the last line of the table remain over the buttons, really on the half of the buttons, like this we can click only on the bottom of the buttons, but the problem is not the line, because also if I have only one line, the table is placed over the buttons, I think this was ok (or I didint paid attention) until the version 6.4.0.

**Comment by ArgoZhang** [comment]
@gmondin could you create a repo for this issue?

**Comment by gmondin** [comment]
Hi @ArgoZhang  I tried simulate in a simple project without success, but I looked at my html code and I found that in my project the javascript doesn't put the style, this part: style="height: calc(100% - 46.2031px);", Do you have some idea why?

**Comment by ArgoZhang** [comment]
@gmondin sorry for that. I have no idea. I do not understand what's your exact requirement.

**Comment by ArgoZhang** [comment]
@gmondin sorry. I have no idea for this. can you debugger it?

**Comment by gmondin** [comment]
I have tried but, I couldnt find, so its, ok, I will close this issue.
