### ISSUE TITLE
bootstrap.blazor.chart.bundle.min.js:13 Uncaught RangeError: minimumFractionDigits value is out of range.

### ISSUE THREAD

**Issue by shaochangming** [dotnetcore/BootstrapBlazor#189]
### Describe the bug

bootstrap.blazor.chart.bundle.min.js:13 Uncaught RangeError: minimumFractionDigits value is out of range.
    at new NumberFormat (<anonymous>)
    at bootstrap.blazor.chart.bundle.min.js:13:47741
    at zi (bootstrap.blazor.chart.bundle.min.js:13:47783)
    at zs.numeric (bootstrap.blazor.chart.bundle.min.js:13:48356)
    at Q (bootstrap.blazor.chart.bundle.min.js:13:7902)
    at zs.generateTickLabels (bootstrap.blazor.chart.bundle.min.js:13:55705)
    at zs._convertTicksToLabels (bootstrap.blazor.chart.bundle.min.js:13:58613)
    at zs.update (bootstrap.blazor.chart.bundle.min.js:13:54239)
    at qe (bootstrap.blazor.chart.bundle.min.js:13:25171)
    at Object.update (bootstrap.blazor.chart.bundle.min.js:13:27478)
(anonymous) @ bootstrap.blazor.chart.bundle.min.js:13
zi @ bootstrap.blazor.chart.bundle.min.js:13
numeric @ bootstrap.blazor.chart.bundle.min.js:13
Q @ bootstrap.blazor.chart.bundle.min.js:13
generateTickLabels @ bootstrap.blazor.chart.bundle.min.js:13
_convertTicksToLabels @ bootstrap.blazor.chart.bundle.min.js:13
update @ bootstrap.blazor.chart.bundle.min.js:13
qe @ bootstrap.blazor.chart.bundle.min.js:13
update @ bootstrap.blazor.chart.bundle.min.js:13
_updateLayout @ bootstrap.blazor.chart.bundle.min.js:13
update @ bootstrap.blazor.chart.bundle.min.js:13
(anonymous) @ bootstrap.blazor.chart.bundle.min.js:13
(anonymous) @ bootstrap.blazor.chart.bundle.min.js:7
_resize @ bootstrap.blazor.chart.bundle.min.js:13
resize @ bootstrap.blazor.chart.bundle.min.js:13
s @ bootstrap.blazor.chart.bundle.min.js:13
(anonymous) @ bootstrap.blazor.chart.bundle.min.js:13
(anonymous) @ bootstrap.blazor.chart.bundle.min.js:7
requestAnimationFrame (async)
(anonymous) @ bootstrap.blazor.chart.bundle.min.js:7
(anonymous) @ bootstrap.blazor.chart.bundle.min.js:13
ri @ bootstrap.blazor.chart.bundle.min.js:13

**Comment by shaochangming** [comment]
![image](https://user-images.githubusercontent.com/10721015/170453564-bf6d12b6-0aa1-4327-9c42-9b1a43318134.png)
![image](https://user-images.githubusercontent.com/10721015/170453701-bdd60727-c548-4684-950b-20abcbbf0bfc.png)
正常打开时 首页是有的  属性页面后 首页页面被自动关闭了。需求是不需要关闭首页。刷新只对当前tab页面刷新。

**Comment by shaochangming** [comment]
另外 在警力资源对象页面打开的 弹出框 在第一次打开时 现在到首页页面上 在警力资源对象页面只是显示了遮罩层。

**Comment by ArgoZhang** [comment]
@shaochangming 这些问题都是应用上的问题，感觉与组件无关啊

**Comment by shaochangming** [comment]
是框架逻辑问题。



***@***.***
 
From: Argo Zhang
Date: 2022-05-27 09:20
To: dotnetcore/BootstrapBlazor
CC: shaochangming; Mention
Subject: Re: [dotnetcore/BootstrapBlazor] bootstrap.blazor.chart.bundle.min.js:13 Uncaught RangeError: minimumFractionDigits value is out of range. (Issue #189)
@shaochangming 这些问题都是应用上的问题，感觉与组件无关啊

**Comment by ArgoZhang** [comment]
@shaochangming 是不是我理解错误了啊？我的理解是点击了浏览器的刷新按钮，需求是页面不刷新，需要的是标签页内容刷新，是这样的吗？

**Comment by shaochangming** [comment]
是打开的tab页面都被关闭了 想保留首页不被关闭。

发自我的iPhone

**Comment by ArgoZhang** [comment]
@shaochangming 这个是 blazor 框架设计的问题，目前是 SPA 模式。点击浏览器刷新，一切复原，组件也是无能为力

**Comment by densen2014** [comment]
> 是打开的tab页面都被关闭了 想保留首页不被关闭。
> 
> 
> 
> 发自我的iPhone
> 
> 
> 
> > 在 2022年5月27日，18:50，Argo Zhang ***@***.***> 写道：
> 
> > 
> 
> > ﻿
> 
> > @shaochangming 是不是我理解错误了啊？我的理解是点击了浏览器的刷新按钮，需求是页面不刷新，需要的是标签页内容刷新，是这样的吗？
> 
> > 
> 
> > —
> 
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > You are receiving this because you were mentioned.
> 
> 

Tab 组件开启 ShowClose 后，TabItem 属性 Closable 可对标签页单独设置是否可关闭，默认为 true；本例中 用户管理 标签页不提供关闭功能

[TabItem标签](https://www.blazor.zone/tabs)

**Comment by ArgoZhang** [comment]
@shaochangming 有一个参数 `DefaultUrl` 设置这个即可
