### ISSUE TITLE
Table编辑状态被自动刷新打断

### ISSUE THREAD

**Issue by mswang2005** [dotnetcore/BootstrapBlazor#190]
### Describe the bug
Table编辑状态被自动刷新打断

### To Reproduce
在最新的版本中（server），表格组件如果设置了自动刷新，那么inline编辑时会被打断（还原成未编辑状态），同理，选中状态也会被刷成未远中，以前的版本中未出现这个问题。望请修复！

**Comment by ArgoZhang** [comment]
@mswang2005 大佬方便给个 star 码云那边跟踪这个问题
