### ISSUE TITLE
Popover组件的Content显示信息异常

### ISSUE THREAD

**Issue by HongFei-Ye** [dotnetcore/BootstrapBlazor#1911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

我使用Popover包住BootstrapInputGroup，BootstrapInputGroup包住一个BootstrapInputGroupLabel与Select，然后使用Select的OnSelectedItemChanged事件来触发string Test1的值改变，Popover的Title与Content显示Test1的值，比如说：BuyTimeLength默认值设置为30，Test1的值应该是"30天"，加载或者刷新页面的首次显示正常，但是切换到其他选项后再切换回来，Title里面显示的数据是正常的，Content显示的数据就会是上一个数据，而不是新的数据.

### Expected Behavior

Popover的Title与Content显示Test1的值，Content应该像Title那样显示正确的数据。

### Steps To Reproduce

前端代码：
“

    <div class="row form-inline g-1">
        <div class="col-12 col-sm-6 col-lg-3 ">
            <Popover Placement="Placement.Auto" Title="@Test1" Content="@Test1" IsHtml="true" CustomClass="custom-popover">
                <BootstrapInputGroup>
                    <BootstrapInputGroupLabel DisplayText="购买时长" class="border-warning" />
                    <Select Items="@BuyTimeLengths" @bind-Value="BuyTimeLength" ShowSearch="true" Color="Color.Warning" OnSelectedItemChanged="OnBuyTimeLengthSelectedItemChanged"></Select>
                </BootstrapInputGroup>
            </Popover>
        </div>
    </div>

”

后端代码：

@code{

    private string Test1 { get; set; } = "30天";

    //如果BuyTimeLength默认值设置为30，加载或者刷新页面的首次显示正常，切换到其他选项后再切换回来，默认值的这个数据显示就会是错误的
    public int BuyTimeLength { get; set; } = 30;

    public List<SelectedItem> BuyTimeLengths = new()
        {
            new SelectedItem(){ Value = "1", Text = "1天"},
            new SelectedItem(){ Value = "3", Text = "3天"},
            new SelectedItem(){ Value = "7", Text = "7天"},
            new SelectedItem(){ Value = "30", Text = "30天"},
            new SelectedItem(){ Value = "90", Text = "90天"},
            new SelectedItem(){ Value = "180", Text = "180天"},
            new SelectedItem(){ Value = "360", Text = "360天"},
        };

    private Task OnBuyTimeLengthSelectedItemChanged(SelectedItem val)
    {
        Test1 = val.Text;

        return Task.CompletedTask;
    }

}

### .NET Version

7.0

### Anything else?

![bug](https://github.com/dotnetcore/BootstrapBlazor/assets/131856535/ec8f16e9-fda2-4a7d-8b86-173c999ca015)
[复现项目.zip](https://github.com/dotnetcore/BootstrapBlazor/files/12268718/default.zip)

**Comment by ArgoZhang** [comment]
@HongFei-Ye 感谢提交 Issue ，请提供一下复现示例仓库地址，方便我复现问题，谢谢啦

**Comment by HongFei-Ye** [comment]
张佬，我的这里面有一个：复现项目.zip，你下载解压出来就能看到了，运行后，你先把select切换到90天，然后再切换回30天，你就能看到Content的错误显示了。

**Comment by ArgoZhang** [comment]
@HongFei-Ye 感谢，看到 zip 包啦。我复现一下就修复

**Comment by HongFei-Ye** [comment]
我虽然用了一个曲线救国的方式来实现了我想要的功能，由于我是菜鸡，不知道是不是我的写法或者用法有问题，这几天你的QQ又用不了，所以还请你观摩一下，如果是bug的话，能修复就修复一下，不然以后其他人应该也会遇到。

**Comment by ArgoZhang** [comment]
@HongFei-Ye 收到收到。感谢啦

**Comment by ArgoZhang** [comment]
@HongFei-Ye 

```
private Task OnBuyTimeLengthSelectedItemChanged(SelectedItem val)
{
    Test1 = val.Text;

    // 请增加这句话试试看
    StateHasChanged();

    return Task.CompletedTask;
}
```

**Comment by HongFei-Ye** [comment]
添加StateHasChanged();我昨天就尝试过了，刚刚又试了一下，Content显示的数据依旧是错误的.

**Comment by ArgoZhang** [comment]
我看了源码，`popover` Title 更新有点问题 但是这个 `StateHasChanged` 是必须要加的

**Comment by HongFei-Ye** [comment]
注意：要先把select切换到90天，然后再切换回30天，这样Content显示的数据才会异常。

不应该是popover 的Content显示有点问题吗？Title 显示的是正确的数据呀。

**Comment by ArgoZhang** [comment]
@HongFei-Ye 我录个屏

![iShot_2023-08-06_13 29 35](https://github.com/dotnetcore/BootstrapBlazor/assets/22001478/2129cc3d-b0c0-48ef-bfc1-0976ec5e2790)

**Comment by HongFei-Ye** [comment]
我添加了 StateHasChanged();后显示还是错误：
请看录屏：

https://github.com/dotnetcore/BootstrapBlazor/assets/131856535/e314ab6c-e1ef-4280-832e-0ef31ed5dc23

**Comment by ArgoZhang** [comment]
@HongFei-Ye 

是 `Bug` 稍等我发布 `7.9.1-beta05`

**Comment by HongFei-Ye** [comment]
我把想要动态显示的数据放在Title 里面，然后Content里面放了静态数据，这样我就规避了Content的显示错误问题，所以不急的，方法总比困难多，哈哈哈......

**Comment by ArgoZhang** [comment]
@HongFei-Ye 已发布 `7.9.1-beta05`
