### ISSUE TITLE
Table列功能里面的Visible在某些情况下不生效。

### ISSUE THREAD

**Issue by HongFei-Ye** [dotnetcore/BootstrapBlazor#1919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

我的Table的TItem="MemberStaticNode"，MemberStaticNode里面有一个StaticNode（一对一关系），StaticNode里面有一个NodeCountry，NodeProvince，NodeCity（一对一关系），Table列功能里面的Visible不知道是不是与绑定字段是关联在一起的，我的这种情况下MemberStaticNode的StaticNode字段里面有多个信息（国家，省份，城市），国家与省份我想要不显示，在需要的时候再在列下拉框里面选中进行显示，城市和其他信息保持显示。

### Describe the solution you'd like

能够准确的控制每一列是否显示，即使他们绑定的字段相同，或者添加一个模板之类的方法来进行自定义。

### Additional context

![11](https://github.com/dotnetcore/BootstrapBlazor/assets/131856535/bd7b2b2a-9b6f-4e16-b4e1-1fbfc3679514)
![22](https://github.com/dotnetcore/BootstrapBlazor/assets/131856535/7bf06177-bf73-43b2-9c44-cc81832b2558)
[Table的Visible没有生效.zip](https://github.com/dotnetcore/BootstrapBlazor/files/12279091/Table.Visible.zip)

图片1里面我已经把国家与省份的Visible="false"，但是他们依旧显示在了Table里面（图片2）。
最后的zip文件是复现工程。

**Comment by ArgoZhang** [comment]
你所有列绑定的是模型中的同一个属性，然后又有的显示有的不显示，不支持这种用法，建议走正常的路子，你弄个正常的模型。不同列绑定不同的属性，不香吗？不要走这种奇葩的路线

**Comment by HongFei-Ye** [comment]
我的数据库设计的时候是这样的一个结构，如果单独再去创建一个class来实现不同列绑定不同的属性，这样很多功能又会失效，看来我只有在外面包一个IF来进行控制了。
