### ISSUE TITLE
colors should also be variables for customization

### ISSUE THREAD

**Issue by cairabbit** [dotnetcore/BootstrapBlazor#192]
### Is your feature request related to a problem? Please describe.
I am trying to customize the layout, components by colors (backgound color, text color, border color etc).  
for example, I want to change the background color of `.layout-header` to my color white.

### Describe the solution you'd like
Currently, the color is hard coded in the css file:
```
.layout.is-page .layout-header {
    background-color: #17a2b8;
}
```
so, I have to write another similar css style to override this background-color. 
A better solution is to use css variables in the colors styles, just like those height variables. Then these colors can be easily changed by overriding the variables.
```
:root {
    --bb-layout-header-backgound: #17a2b8;
}
.layout.is-page .layout-header {
    background-color: var(--bb-layout-header-backgound, #17a2b8);
}
```
In my opinion, all colors, heights, or event font-sizes, gaps should be css variables. This is an awesome blazor components library, however, it should be easy to customize. Also, there is no documentation for creating a new theme. Basicaly, just like original bootstrap, user can easily create his/her own theme/skin by just changing the variables. 
Thanks.

**Comment by ArgoZhang** [comment]
@cairabbit sure. will update next release. thank you

**Comment by ArgoZhang** [comment]
@cairabbit hi. released `6.7.4` add some variants for layout component 

```
:root {
    --bb-layout-header-height: 50px;
    --bb-layout-header-backgound: #17a2b8;
    --bb-layout-headerbar-backgound: #1ab394;
    --bb-layout-headerbar-border-color: #1ab394;
    --bb-layout-footer-backgound: #5b6e84;
    --bb-layout-footer-height: 40px;
    --bb-layout-user-height: 65px;
    --bb-layout-sidebar-width: 214px;
    --bb-layout-sidebar-collapse-width: 70px;
    --bb-layout-sidebar-banner-background: #367fa9;
    --bb-layout-sidebar-scrollbar-background: #c1c1c1;
    --bb-layout-sidebar-backgound: #343a40;
    --bb-layout-sidebar-color: #c2c7d0;
    --bb-layout-title-color: #e9ecef;
}
```

please submit a PR for this if i missing any variable.

**Comment by ArgoZhang** [comment]
@cairabbit use variable is great idea. The project is gradually changing

**Comment by cairabbit** [comment]
@ArgoZhang  awesome, thank you very much.
