### ISSUE TITLE
bug: Table LineNo no work expected after scroll with virtual scroll

### ISSUE THREAD

**Issue by coddoge** [dotnetcore/BootstrapBlazor#1945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

See reproduce project, set 100 items then scroll to bottom, last row  LineNo show 35, expected 100

### Steps To Reproduce

https://github.com/coddoge/bb-bug-reproduce/blob/main/TableBugs1/Pages/Index.razor

### .NET Version

7.0.400-preview.23330.10

**Comment by ArgoZhang** [comment]
@coddoge on the way

**Comment by ArgoZhang** [comment]
@coddoge fixed. please try  `7.9.2-beta04` later
