### ISSUE TITLE
bug: Table, Virtual Scroll + Filterable = BOOM?

### ISSUE THREAD

**Issue by coddoge** [dotnetcore/BootstrapBlazor#1953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After set filter by click column header, filtered result working not as expected. truncated? or "paging" wrong?

If it's my mistake, please add `Virtual Scroll + Filterable` into samples, i can not find in https://www.blazor.zone/table/virtualization

### Steps To Reproduce

https://github.com/coddoge/bb-bug-reproduce/blob/main/TableBugs2/Pages/Index.razor

**Comment by ArgoZhang** [comment]
@coddoge Hi. on my travels, this issue will be fixed late. this is just a response.

**Comment by coddoge** [comment]
@ArgoZhang  Have fun travelling!

I'll find some workaround until this problem solve.

Unfortunately `Paging+Filterable=BOOM` 

I consider trun off paging and virtual-scrolling for filting, but it may cause OOM if too many rows

**Comment by ArgoZhang** [comment]
@coddoge 

1. update the `Table` component usage
```
<div style="height: 500px">
    <Table TItem="DataItem" OnQueryAsync="DoQuery" ShowLineNo LineNoText="#" IsBordered IsFixedHeader ScrollMode="ScrollMode.Virtual">
             <TableColumns>
                 <TableColumn Text="Text" @bind-Field="@context.Text" Filterable></TableColumn>
         </TableColumns>
     </Table>
 </div>
```

the point is to set the `Table` component `TItem="DataItem"` to remove the `TItem="DataItem" TType="string"`

2. apply Filters condition

```
private async Task<QueryData<DataItem>> DoQuery(QueryPageOptions options)
{
    return new QueryData<DataItem>
    {
        Items = _items.Where(options.Filters.GetFilterFunc<DataItem>()).Skip(options.StartIndex).Take(options.PageItems).ToList(),
        TotalCount = _items.Count
    };
}
```

the key point add the `Where(options.Filters.GetFilterFunc<DataItem>()` linq for filter the data

**Comment by ArgoZhang** [comment]
@coddoge sorry for that. the clear function is incorrect. later will fixed it.

**Comment by ArgoZhang** [comment]
@coddoge please try `v7.9.2-beta06`

**Comment by coddoge** [comment]
@ArgoZhang Thank you for point out.

But after update useage, the filter result still no working as expected, reproduce repo was updated. 

https://github.com/coddoge/bb-bug-reproduce/blob/main/TableBugs2/Pages/Index.razor

Filter result still aways truncated in 35 rows.

If any my mistake, please point out.

**Comment by ArgoZhang** [comment]
@coddoge Hi. I submitted a PR for this. please take a review

1. please remove async before the Task keyword. use Task.FromResult
```
private Task<QueryData<DataItem>> DoQuery(QueryPageOptions options)
{
    var items = _items!.Where(options.Filters.GetFilterFunc<DataItem>());
    var data = items.Skip(options.StartIndex).Take(options.PageItems);
    var ret = new QueryData<DataItem>
    {
        Items = data,
        TotalCount = items.Count(),
        IsFiltered = options.Filters.Any()
    };
    return Task.FromResult(ret);
}
```

2. add `IsFiltered="true"`

**Comment by coddoge** [comment]
Thank you verymuch!

Finally, table filtering is work as expected.
