### ISSUE TITLE
Order on table columns

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#1959]
### Which class is this unit test associated with?

I'm creating dynamic tables based on generic class, and using custom attributes to show, change text, width, etc, everything is ok and works good, but for now the order is the same order of the properties on the class, so I would like to have a custom order, I searched on the component and found the property Order on columns, but when I'm using this is not working.
My code is something like this, everything works, except order.

  private Task OnColumnCreating(List<ITableColumn> columns)
  {
    foreach (var item in columns)
    {
      int width = GetWidth(item);
      if (width > 0) item.Width = width;

      item.Text = GetText(item);
      int order = GetOrder(item);
      if (order > 0) item.Order = order;
     item.Visible = GetVisibility(item);;
    }
    return Task.CompletedTask;
  }
  
  am I doing wrong? theres other way to do? or this is not working?
  
  thank you very much

**Comment by ArgoZhang** [comment]
@gmondin hi. could you provide a mini-sample project? I will repro this and PR into your repo if resolve it.

**Comment by gmondin** [comment]
Hi @ArgoZhang the code is something like this, its a simple table, the only thing is that is generated by T = class dynamically in other parts of the project. The table is created normally and works, I only try to add the order (I put an example, because in my code I take from Property Attribute, but doesnt show in the order that I'm putting on)

 <Table TItem="T"
        Items="@_List"
        SelectedRows="@_SelectedRows"
        ScrollingDialogContent="true"
        ScrollMode="ScrollMode.Virtual"
        ShowDefaultButtons="false"
        IsMultipleSelect="false"
        IsFixedHeader="true"
        Height="200"
        ClickToSelect="true"
        ShowLoading="true"
        AutoGenerateColumns="true"      
        RenderModeResponsiveWidth="BreakPoint.ExtraSmall"
        OnColumnCreating="@OnColumnCreating"
        UnsetText="" />

private Task OnColumnCreating(List columns)
{
int order = columns.count();
foreach (var item in columns)
{
  item.Order = order;
 order --;
}
return Task.CompletedTask;
}

**Comment by ArgoZhang** [comment]
@gmondin sorry, I can't provide any help if there is no mini-repro project.
