### ISSUE TITLE
Use bootstrap css variables as much as possible

### ISSUE THREAD

**Issue by cairabbit** [dotnetcore/BootstrapBlazor#202]
### Is your feature request related to a problem? Please describe.
The components are great. However, it's not easy to customize the look and feel. Bootstrap itself has many css varaibles, including gaps, colors, z-indexes etc. The more varaibles used the better support in customization. Ideally, all colors (background, border, text, link, hover, box-shadow etc), paddings, margins, sizes, opacity etc should use variables. Because different theme have different values.

### Describe the solution you'd like
Use as much bootstrap css variables as possible would be wonderful. In case there is no suitable bootstrap variables to use, then add new variable. Too many varaibles could also be a problem, so a good design on the variables is important, meaning the variables can be re-used in many components. 

### Additional context
N/A

This is a heavy and time consuming work but I think it's worthy. After all, tons of thanks for your exellent work.

**Comment by ArgoZhang** [comment]
@cairabbit Yes! I'm working on it.
