### ISSUE TITLE
Table colunm visible doesn't work after first render

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#203]
I'm trying to hide a column from a table using Visible, but only works on first render, if I have a button where I can change the status for false and use StateHasChanged, the column still visible.

**Comment by ArgoZhang** [comment]
yes. it's by design. please take a look for this https://www.blazor.zone/tables/column#Visible

**Comment by gmondin** [comment]
I saw, thanks, but it's possibile change this by code using, example a variable bool on Visible in the colunm? it's because I have one colunm that's show for some user and for other no, but in the method OnParametersSetAsync(), but at the time that goes to check some details, the colunm is already visible, and I can't change, I have tried on your source code and I have made a few changes with the same idea of this two options and it's works. it's possible have this possibility? like change the visibile in any point by code.

**Comment by ArgoZhang** [comment]
@gmondin sound good! could you submit a PR for this issue?
