### ISSUE TITLE
Table OnSort does not work as expected

### ISSUE THREAD

**Issue by hsin19** [dotnetcore/BootstrapBlazor#205]
### Describe the bug

The Table is not sorted by the `OnSort` setting when `OnQueryAsync` not sorting.

<img width="960" alt="螢幕擷取畫面 2022-07-01 233226" src="https://user-images.githubusercontent.com/80679430/176925563-662f585f-c34e-432b-8be5-de41e042f0e9.png">

`OnSort` successfully change `SortString` and then generate correct `SortList`. However, it will not be used because the condition is true on line 547.

https://github.com/dotnetcore/BootstrapBlazor/blob/72a77dd9f6753e7d601dbf0df358e6305aae0ee9/src/BootstrapBlazor/Components/Table/Table.razor.Edit.cs#L545-L557

This is why I pull #204.

### To Reproduce

[sample](https://github.com/hsin19/BootstrapBlazor/tree/sample-table-onsort/src/BootstrapBlazor.Shared/_test)

### Exceptions (if any)

N/A

### Further technical details

- BootstrapBlazor version: latest
- .NET 6
- VS2022

**Comment by ArgoZhang** [comment]
@hsin19  fixed. thanks
