### ISSUE TITLE
文档ImageView部分 404

### ISSUE THREAD

**Issue by tpnest** [dotnetcore/BootstrapBlazor#207]
![image](https://user-images.githubusercontent.com/57797158/177096777-92c86495-3089-43ac-96aa-c5066276e7eb.png)

**Comment by ArgoZhang** [comment]
@tpnest 我这里是好的，无 404

**Comment by tpnest** [comment]
我在多台设备包括手机上都看不见ImageViewer组件的示例代码提示404，但是其他组件是正常的，不知道什么原因。 @ArgoZhang
