### ISSUE TITLE
6.7.29  版本在多國語系有問題

### ISSUE THREAD

**Issue by Louis12178** [dotnetcore/BootstrapBlazor#208]
我使用 DateTimePicker 時，顯示文字都變成英文。
比對程式碼，好像是程式碼前頭都少宣告 using Microsoft.AspNetCore.Components; 引起的。

**Comment by ArgoZhang** [comment]
@Louis12178 能否提供截图等信息，我这里无法复现

**Comment by ArgoZhang** [comment]
using Microsoft.AspNetCore.Components 这个引用是使用的全局引用
