### ISSUE TITLE
feat(ListView): api to order by collapse

### ISSUE THREAD

**Issue by 848555155** [dotnetcore/BootstrapBlazor#2081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

listview组件的group功能的排序写死了，希望能用一组API暴露排序方法。
https://github.com/dotnetcore/BootstrapBlazor/blob/28fbfd10bdbe53da97699a890bddd065939d1394/src/BootstrapBlazor/Components/ListView/ListView.razor#L30

### Describe the solution you'd like

希望添加一个类似的Parameter
[Parameter] public Func<IGrouping<object?, TItem>, string> GroupOrder { get; set; } = (k) => k.Key;

**Comment by ArgoZhang** [comment]
@848555155 release `7.10.4-beta03`
