### ISSUE TITLE
missingmanifestresourceexception

### ISSUE THREAD

**Issue by nmezhangxi** [dotnetcore/BootstrapBlazor#209]
### To Reproduce
Create a new project by the template. Running in Visual Studio, from the output , many missingmanifestresourceexception occurs.

### Exceptions (if any)
引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.InvalidOperationException”(位于 Microsoft.AspNetCore.Components.dll 中)
引发的异常:“System.InvalidOperationException”(位于 Microsoft.AspNetCore.Components.dll 中)
“BootstrapBlazorApp1.Server.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.6\System.Net.WebSockets.dll”。包含/排除设置已禁用符号加载。
引发的异常:“System.InvalidOperationException”(位于 Microsoft.AspNetCore.Components.Server.dll 中)
引发的异常:“System.InvalidOperationException”(位于 Microsoft.JSInterop.dll 中)
引发的异常:“System.InvalidOperationException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.InvalidOperationException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.InvalidOperationException”(位于 Microsoft.AspNetCore.Components.Server.dll 中)
引发的异常:“System.InvalidOperationException”(位于 Microsoft.JSInterop.dll 中)
引发的异常:“System.InvalidOperationException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.InvalidOperationException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.InvalidOperationException”(位于 Microsoft.AspNetCore.Components.dll 中)
引发的异常:“System.InvalidOperationException”(位于 Microsoft.AspNetCore.Components.dll 中)
引发的异常:“System.InvalidOperationException”(位于 Microsoft.AspNetCore.Components.dll 中)
引发的异常:“System.InvalidOperationException”(位于 Microsoft.AspNetCore.Components.dll 中)
引发的异常:“System.InvalidOperationException”(位于 Microsoft.AspNetCore.Components.dll 中)
引发的异常:“System.InvalidOperationException”(位于 Microsoft.AspNetCore.Components.dll 中)

### Further technical details
- BootstrapBlazor version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by ArgoZhang** [comment]
@nmezhangxi not repro
