### ISSUE TITLE
Question: PDF Viewer and Reports

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#210]
I have a question, do you have plans to pdf viewer or reports?
I'm asking because I'm using from others now and if you have some plans, I would like to use yours.

**Comment by ArgoZhang** [comment]
@gmondin I haven't found a solution for PDF. Do you have any good solution recommendations?

**Comment by Ponderfly** [comment]
> 

https://github.com/QuestPDF/QuestPDF/ 这个不错

**Comment by gmondin** [comment]
thnak you very much
