### ISSUE TITLE
doc: abpvnext中使用table文档

### ISSUE THREAD

**Issue by He-Wu** [dotnetcore/BootstrapBlazor#2108]
### Document describing which component

table组件在abp中，dto在Contracts层中，如何规范的设置TItem=dto得到table的列，特性AutoGenerateColumn只引用在abp的blazor在dto中无法使用，是否有这方面的文档或者abp和bootstrapBlazor结合使用的一些文档可以提供

**Comment by ArgoZhang** [comment]
@ArgoZhang 没用过 abp 这个无法回答，也没有资料提供

**Comment by He-Wu** [comment]
好吧
