### ISSUE TITLE
doc: 我想在bootstrapBlazor上封装一个AdminTable，但是遇到了问题

### ISSUE THREAD

**Issue by He-Wu** [dotnetcore/BootstrapBlazor#2116]
### Document describing which component

Add sample code for {Component}
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/56440130/adf520de-2f6c-4f86-9f0b-8b40557f34af)

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/56440130/f807e69d-8d61-4219-9206-441754f61422)
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/56440130/48cdb43a-5827-42ad-97a9-1ab2e0e2789d)
我只不过将TItem改成了TDto就会无法推断具体类型，如果我需要加入更多的泛型参数比如
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/56440130/90ce2c2a-349f-4776-b628-ce3b68ef7c87)
这种又该如何去改呢？

**Comment by He-Wu** [comment]
这个泛型规定了一定是TItem吗，实际中肯定不是就一个TItem就能搞定的，我该如何去封装改呢？

**Comment by ArgoZhang** [comment]
@He-Wu 大佬能否帮忙点个 star 啊

**Comment by He-Wu** [comment]
> 

大佬点了start了

**Comment by ArgoZhang** [comment]
@He-Wu 问问题提供例子啊。你换位思考你一下。你的问题是一句话能回答的嘛？你不提供例子，真的很难帮你解决问题。而且这个不是我们组件的问题，是你二开的问题。

**Comment by He-Wu** [comment]
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/56440130/1efeda36-db0c-48e5-8efd-08c182cdfcf1)
我改成TItem了都不行
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/56440130/6f023822-fd09-4c01-a3e1-2066be07cf5d)
这是为什么？

**Comment by Vision-Zhang** [comment]
TItem 是 table 要的泛型不能改，至于你的 dto 是你要考虑怎么根据业务包装到 table
