### ISSUE TITLE
table autorefresh issue

### ISSUE THREAD

**Issue by a0926019412** [dotnetcore/BootstrapBlazor#212]
I use table component, set IsAutoRefresh as true and set AutoRefreshInterval as 2000
(reference here [ https://www.blazor.zone/tables/autorefresh ](url))

but OnQueryAsync method only fire one time,
can give me some key point ?

thanks

**Comment by ArgoZhang** [comment]
@a0926019412 thank you for submitting the issue. this issue has been fixed. later will release a new version `6.8.19`
