### ISSUE TITLE
bug(ModalDialog): missing the return value check

### ISSUE THREAD

**Issue by yuanan** [dotnetcore/BootstrapBlazor#2125]
https://github.com/dotnetcore/BootstrapBlazor/blob/b2adaf2d53ab056d07188a75c2aaecb5abe77329/src/BootstrapBlazor/Components/Modal/ModalDialog.razor.cs#L288

The return value of OnClickSave was not assigned to the ret variable, causing OnClickSave to have no internal control over whether to close the window.

**Comment by ArgoZhang** [comment]
@yuanan Hi. can you give the project a star? thanks
