### ISSUE TITLE
feat(Tab): support drag/drop function

### ISSUE THREAD

**Issue by boc2010** [dotnetcore/BootstrapBlazor#2146]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the solution you'd like

Currently I am using your Bootstrap Blazor with Admin Template.
Can you add **Scroll** or **pan feature** on these **Tab pages**?
Because when you open many Pages Tab, they will be hidden to the right and covered. (image attached)
Thank you very much for sharing your Bootstrap Blazor !

### Additional context

![Screenshot 2023-09-17 115427](https://github.com/dotnetcore/BootstrapBlazor/assets/49285229/e3b63006-dba6-4399-8986-e0b5594bbfae)

**Comment by ArgoZhang** [comment]
@boc2010 hi. we can provide a drag-and-drop feature on Tab. For the scroll function, you can use CSS

**Comment by ArgoZhang** [comment]
@boc2010 

### add some sass rule for Tab drag/drop you can custom those

```
.tab-drag-over {
    animation: drag-tab-item 1s linear infinite;
}

.tab-dragging th[draggable] * {
    pointer-events: none;
}

.tab-drag {
    background-color: var(--bs-secondary);
}

@keyframes drag-tab-item {
    50% {
        background-color: var(--bs-primary);
    }
}
```

### add **AllowDrop** parameter on Tab component default value is false

```
/// <summary>
/// get/set whether allow drag tab item for reorder default value is false
/// </summary>
[Parameter]
public bool AllowDrag { get; set; }
```
