### ISSUE TITLE
bug: Table组件的编辑弹窗中，使用代码修改了字段的值后，不会立即刷新

### ISSUE THREAD

**Issue by cqths** [dotnetcore/BootstrapBlazor#2152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

在Foo.cs中定义3个测试字段：
![1](https://github.com/dotnetcore/BootstrapBlazor/assets/145242365/88cb00f5-6898-44c2-8937-951ba9d8bd61)
在TableDemo.razor中定义2种方式修改字段的值
![2](https://github.com/dotnetcore/BootstrapBlazor/assets/145242365/71aa86e7-be70-4e81-af5a-e777f5537346)
TableDemo.razor.cs中的代码如下
![3](https://github.com/dotnetcore/BootstrapBlazor/assets/145242365/1c0e8379-c3da-4c1a-8c96-da78eb190d27)
程序运行后，在编辑弹窗中，单击 CountDecimal++ 按钮，此时 CountDecimal 的值已经改变，但界面中CountDecimal输入框中的显示值无变化。
![4](https://github.com/dotnetcore/BootstrapBlazor/assets/145242365/0a445bab-9704-4ffd-8eba-7fa9874b1a47)
在CountDouble输入框中输入内容后，鼠标离开输入框，此时都会刷新 CountDecimal 输入框中的值。
![5](https://github.com/dotnetcore/BootstrapBlazor/assets/145242365/10c7a969-adfa-456f-9713-bb98b0eafd3b)

### Expected Behavior

预期应该是：当 CountDecimal++ 按钮单击时，CountDecimal 输入框中的内容，立即刷新。

**Comment by ArgoZhang** [comment]
@cqths 

Table 编辑时各列刷新问题参考视频

https://www.bilibili.com/video/BV17f4y1c7N1/?spm_id_from=333.999.0.0
