### ISSUE TITLE
DataTimeRange issue

### ISSUE THREAD

**Issue by a0926019412** [dotnetcore/BootstrapBlazor#216]
Dears

I use DataTimeRange component and use two-way binding reference here [https://www.blazor.zone/datetimeranges](url)

the binding variable not set correct value when I change the value first time, but after that work fine
(Ex: set startdate: 2022/08/01 enddate: 2022/08/02,  in the OnValueChanged event the parameter item's value is correct, but binding 
   variable set other datetime like startdate: 2022/08/01 enddate: 2022/08/31 after OnValueChanged event  ending)

**Comment by qubit-tech** [comment]
在 EditorForm -> EditorItem -> EditTemplate 里，设置@bind-value时，会出现第一次没法正确设置时间问题，DataTimeRange独立使用时没问题。

**Comment by wapco** [comment]
DataTimeRange 目前只支持日期，能否能支持精确到时间？

**Comment by ArgoZhang** [comment]
我要复现一下这个问题

**Comment by a0926019412** [comment]
@qubit-tech Yes,The same problem can be reproduced with ValitateForm contains  DateTimeRange

**Comment by ArgoZhang** [comment]
@a0926019412 @qubit-tech 正在修复 fixing

**Comment by ArgoZhang** [comment]
@a0926019412 @qubit-tech fixed

**Comment by ArgoZhang** [comment]
> DataTimeRange 目前只支持日期，能否能支持精确到时间？

下个里程碑支持

**Comment by a0926019412** [comment]
@ArgoZhang Thanks for your reply.
