### ISSUE TITLE
bug: 使用BootstrapBlazorProjectTemplate创建的项目运行时存在找不到资源异常

### ISSUE THREAD

**Issue by haoyond** [dotnetcore/BootstrapBlazor#2162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. 使用BootstrapBlazorProjectTemplate创建的项目（Server Side）.
2. 启动项目
3. 在输出窗口有如下提示：
`引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)`
4. 打开visual studio 诊断工具，查看事件中的异常，如下

> System.Resources.MissingManifestResourceException (Could not fid the resource 'BootstrapBlazor.Components.ErrorLogger.resource' among the resource 'BootstrapBlazor.Locales.en.json''BootstrapBlazor.Locales.en.json','BootstrapBlazor.Locales.zh.json'

### Expected Behavior

消除此bug

### Steps To Reproduce

1. 使用BootstrapBlazorProjectTemplate创建的项目（Server Side）.
2. 启动项目
3. 在输出窗口有如下提示：
`引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)`
4. 打开visual studio 诊断工具，查看事件中的异常，如下

> System.Resources.MissingManifestResourceException (Could not fid the resource 'BootstrapBlazor.Components.ErrorLogger.resource' among the resource 'BootstrapBlazor.Locales.en.json''BootstrapBlazor.Locales.en.json','BootstrapBlazor.Locales.zh.json'

### .NET Version

.net core 7.0

**Comment by Vision-Zhang** [comment]
![4UT3R`9N_Q_Z5O3 70_P17B_tmb](https://github.com/dotnetcore/BootstrapBlazor/assets/49146231/18f5d469-92af-4e4c-86d7-2a36eba4312d)
