### ISSUE TITLE
feat: 建议增加查找资源配置

### ISSUE THREAD

**Issue by haoyond** [dotnetcore/BootstrapBlazor#2163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

    JsonStringLocalizer 的实现类  internal class JsonStringLocalizer : ResourceManagerStringLocalizer 的GetStringSafely方法，查找本地化资源的策略是，

1. 先找  执行GetStringFromService(name)
2. 如果找不到，执行 GetStringSafely(name, null)
3. 还找不到，执行 GetStringSafelyFromJson(name)

第2 步的问题是，如果查找不到，会产生大量的
`引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)`
`引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)`
`引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)`
`引发的异常:“System.Resources.MissingManifestResourceException”(位于 System.Private.CoreLib.dll 中)`

使得程序响应速度变慢。

### Describe the solution you'd like

 建议增加一个配置选项，用于设置是否从资源文件中查找。同时还可提高程序响应速度。

**Comment by ArgoZhang** [comment]
@haoyond duplicate #2162

**Comment by william19941994** [comment]
运行变慢的主要原因是和Debugger通讯导致的。异常的开销有一些，但是调试模式下非常大。
设计模式里面有用Exception的，如果不习惯可以让微软把这个逻辑额外加个参数，比如叫success。指示是配置文件里面存的null，还是配置文件里面没有这个设置，逐级返回。供很多层调用的上层代码来决定回退到下一个配置文件。
对于群众建议的仅我的代码模式，也可以参考一下。
