### ISSUE TITLE
feat(MultiSelect): prevent height resizing

### ISSUE THREAD

**Issue by RemiCELLARD** [dotnetcore/BootstrapBlazor#2164]
### Which class is this unit test associated with?

Hi,

It is possible to prevent the MultiSelect height resizing with new parameter on the component (or fix it?) (see images) ?
Thanks

Before :
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/25703106/8d4e3e12-fe98-457c-ba01-4a99468cb7a3)

After :
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/25703106/29a3a8ab-d372-4325-9000-261649b090bc)

**Comment by ArgoZhang** [comment]
@RemiCELLARD Can I add an `IsFixedHeight` parameter to meet your requirements?

**Comment by RemiCELLARD** [comment]
> @RemiCELLARD Can I add an `IsFixedHeight` parameter to meet your requirements?

Hi, yes if it's possible ?

**Comment by ArgoZhang** [comment]
@RemiCELLARD let me try.

**Comment by ArgoZhang** [comment]
@RemiCELLARD please try `7.10.8-beta07` later
