### ISSUE TITLE
图表类标签在点击的时候其余隐藏突出选择的标签为宜，实现：看哪个点哪个，而不是反过来。

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#2166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

目前是：选中某个标签，是该标签的图隐藏。（图表类，柱状图折线图，均是如此）
其实这个有点反人性，在多标签的时候更是难受。
建议：选中某标签，该标签仍然显示，其余标签隐藏。

其实想要的效果就是：看哪个点哪个，而不是反过来。

**Comment by ArgoZhang** [comment]
@bigsinger 这个组件是包装的 `chart.js` 这个功能原生的就是这样。我们没能力改，可否去 chart.js 提交 Issue 啊

**Comment by bigsinger** [comment]
今天想到一个替代的方案，默认只让第一个标签处于选择状态，其他标签处于非选择状态，这样就可以实现这种效果了。
举个例子，想要分析各个销售人员的业绩，有一两百个销售人员，太多了，第一个标签为总营业额可以处于选择状态。其他销售人员的，就全部默认非选择状态，想要看哪个销售的业绩，就点击开启就可以看了。

 看看能不能实现？ @ArgoZhang

**Comment by ArgoZhang** [comment]
这个组件是我们包装 chart.js 不要自己想啊。这个太难了。你需要去看看 chart.js 官网的例子，它有这个功能，我们就可以做啦。如果没有，我们是无法实现的

**Comment by bigsinger** [comment]
> 这个组件是我们包装 chart.js 不要自己想啊。这个太难了。你需要去看看 chart.js 官网的例子，它有这个功能，我们就可以做啦。如果没有，我们是无法实现的

有替代的实现方式，我给chat.js提了，回复见：https://github.com/chartjs/Chart.js/issues/11559#issuecomment-1784588715
并且给出了overflow上的参考方案。只不过都是JavaScript的实现，@ArgoZhang 请帮忙看下是否可以封装到c#代码里？感谢。

**Comment by bigsinger** [comment]
@ArgoZhang  图表是否可以不使用chart.js，减少对js的使用，推荐一个开源库：https://github.com/beto-rodriguez/LiveCharts2

**Comment by ArgoZhang** [comment]
@bigsinger 我们组件库就是封装 Chart.js 的组件库，不可以随便更换的，老用户或者已经上线的项目怎么办？

如果你自己的项目还没有上线，直接使用 `LiveCharts2` 即可，不需要非要使用我们的图表库，这个是可以一起使用的不冲突

既然是 web 项目，`js` 是最优解，没有之一，再加上如果是 `ssr` 模式考虑到服务器的 `CPU` `内存` 开销更应该倾向与 `chart.js` 这种 js 架构的库
