### ISSUE TITLE
bug: Render on Table with row virtualization and Tree

### ISSUE THREAD

**Issue by RemiCELLARD** [dotnetcore/BootstrapBlazor#2167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you use table with row virtualization and Table-Tree, expand/collapsed action on tree seems to be not working well ...

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/25703106/5a4a6c8c-c291-4e31-a1df-e49186cdcb7d)
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/25703106/fbccacad-d346-4387-9f23-dfb939a6201b)

### Expected Behavior

Expand/collapsed the tree correctly

### .NET Version

7.0.401

### Anything else?

BootstrapBlazor v6.12.0

Razor component call :
```razor
<Table HeaderStyle="TableHeaderStyle.Light"
       Items="ClientsList"
       IsTree="true"
       IsMultipleSelect="true"
       AllowResizing="true"
       AllowDragColumn="true"
       
       TreeNodeConverter="TreeNodeConverter"
       RenderMode="TableRenderMode.Table"

       ScrollMode="ScrollMode.Virtual"
       Height="400"

       ShowToolbar="true"
       ShowDefaultButtons="false"
       ShowSearch="false"
       ShowRefresh="false">
```

**Comment by ArgoZhang** [comment]
@RemiCELLARD hi. sorry for the delayed reply. for now not support `virtualization` on `IsTree` mode
