### ISSUE TITLE
修正ImagePreviewer拖动图片不跟手的bug

### ISSUE THREAD

**Issue by cqths** [dotnetcore/BootstrapBlazor#2168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

修正src/BootstrapBlazor/wwwroot/modules/viewer.js拖动图片不跟手的bug。
原行为：鼠标（或者触摸）从左上拖动到右下，图片只移动一半距离。
Bug原因：使用Margin移动图片需要左右、上下同时设置，例如：margin-left:100px;margin-right:-100px才能
向右移动100px，只设置一个则只移动50px。

### Expected Behavior

修订后：同时设置左上、右下。

**Comment by ArgoZhang** [comment]
duplicate #2172
