### ISSUE TITLE
Table组件中，如果有计算列，可以正常显示，但使用 导出 功能导出为 Excel 表格后，计算列是空白的。

### ISSUE THREAD

**Issue by cqths** [dotnetcore/BootstrapBlazor#2175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

计算列的定义示例：
public double 月租金 => 标的面积 * 单价;
在Table组件中显示正常，导出为Excel文件是空白列。

### Expected Behavior

应该导出显示的计算值。

**Comment by densen2014** [comment]
这跟组件无关的，业务要自己考虑实现。你自己建个属性计算，导出自然就有了。

**Comment by ArgoZhang** [comment]
@cqths 不是 `bug` ，导出是通用的，是跟数据模型相关，模型中没有这个计算列属性，默认导出就没有数据，你可以自定义导出，这就是老周说的业务了
