### ISSUE TITLE
Carousel component, set interval / no interval

### ISSUE THREAD

**Issue by pomeara** [dotnetcore/BootstrapBlazor#219]
Hi @ArgoZhang ,

I am using the Carousel and ImageViewer components and would like the following features to extend the Carousel component.

1. A flag to stop the 'automatic interval' so the user has to select the image next/previous

Can the ImageViewer component be made 'like' the Caroursel component so that you can cycle through images, I like that the image viewer can 'zoom' into an array of images, it would be a really nice extension to allow it to act like a Carousel component and cycle through the images used for the zoom

Many thanks
Patrick

**Comment by ArgoZhang** [comment]
@pomeara sure. I plan to achieve this function in the next milestone

**Comment by ArgoZhang** [comment]
@pomeara the bootstrap carousel update some new feature in `v5.2.0`. I will integrade them. include the `Stop` `Pause` etc feature
