### ISSUE TITLE
bug: 在Table的EditTemplate 使用Select 组件有绑定值的情况下只显示value

### ISSUE THREAD

**Issue by NingLiu1998** [dotnetcore/BootstrapBlazor#2190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 在Table的EditTemplate 使用Select 组件有绑定值的情况下只显示value

## razor页面

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/109678937/b44685e2-ce07-4265-a24b-f58e49f600c8)

## OnQueryAsync 方法

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/109678937/428a505b-f3f3-4ffa-88b5-168f642d90dc)

## 界面效果

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/109678937/cffc9ba2-3a7a-4838-b896-faf9c91b1a6a)

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/109678937/90c3d010-7fc1-44b1-bbfc-fe2264d258e1)

## 源码地址

[raozor页面代码](https://github.com/MineCosmos/Bot/blob/main/MineCosmos.Bot.BlazorApp/MineCosmos.Bot.BlazorApp.Shared/Pages/Users.razor)

[OnQueryAsync 方法代码](https://github.com/MineCosmos/Bot/blob/main/MineCosmos.Bot.BlazorApp/MineCosmos.Bot.BlazorApp.Shared/Base/BotComponentBase.cs)
> 方法名是：ServerDrawDropOnQueryAsync

### Expected Behavior

预期显示所绑定的text，而不是value

### Steps To Reproduce

项目代码是用的 **Bootstrap Blazor App Extension** 扩展插件 的 **Bootstrap Blazor Project Template** 项目模板

[raozor页面代码](https://github.com/MineCosmos/Bot/blob/main/MineCosmos.Bot.BlazorApp/MineCosmos.Bot.BlazorApp.Shared/Pages/Users.razor)

[OnQueryAsync 方法代码](https://github.com/MineCosmos/Bot/blob/main/MineCosmos.Bot.BlazorApp/MineCosmos.Bot.BlazorApp.Shared/Base/BotComponentBase.cs)
> 方法名是：ServerDrawDropOnQueryAsync

### Exceptions (if any)

选择保存以及绑定都是对的，只是显示问题

### .NET Version

7.0

**Comment by NingLiu1998** [comment]
[效果演示地址](https://www.bilibili.com/video/BV1TV411w7w8/)

**Comment by ArgoZhang** [comment]
@NingLiu1998 复现工程呢

**Comment by NingLiu1998** [comment]
https://cowtransfer.com/s/31aca8f1d07346 点击链接查看 [ BootstrapBlazorApp1.zip ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 h3hnb9 查看；

**Comment by NingLiu1998** [comment]
> @NingLiu1998 复现工程呢

上传了 [奶牛快穿](https://cowtransfer.com/s/31aca8f1d07346)  顺便把图片上传疑惑也放了

**Comment by NingLiu1998** [comment]
[BootstrapBlazorApp1.zip](https://github.com/dotnetcore/BootstrapBlazor/files/12746653/BootstrapBlazorApp1.zip)

**Comment by ArgoZhang** [comment]
少设置了一个参数

```
<Select IsVirtualize="true"
        ShowLabel="true"
        @bind-Value="@context.SelectId"
        DisplayText="Minecraft服务器"
        DefaultVirtualizeItemText = "Test"
        OnQueryAsync="ServerDrawDropOnQueryAsync"></Select>
```
