### ISSUE TITLE
contextMenu

### ISSUE THREAD

**Issue by zcwgd163** [dotnetcore/BootstrapBlazor#220]
### 缺少右键菜单
作者你好:
我用这套组件结合electron做了个桌面程序，发现没有右键菜单可用。

我想在组件上使用右键菜单，但没有找到可用的组件。因为我是用electron做桌面程序，所以有右键菜单需求。
请问可以在组件上加上右键菜单功能吗？或者怎么做？

**Comment by ArgoZhang** [comment]
@zcwgd163 准备改造 Menu 组件，到时候支持一下右键菜单可以吗？

**Comment by zcwgd163** [comment]
> @zcwgd163 准备改造 Menu 组件，到时候支持一下右键菜单可以吗？

好的，谢谢。
