### ISSUE TITLE
chore: How to properly display a ticket's title when opened from a Link another Form Tabs?

### ISSUE THREAD

**Issue by boc2010** [dotnetcore/BootstrapBlazor#2202]
### Which class is this unit test associated with?

Hi @ArgoZhang,

How to properly display a ticket's title when opened from a Link another Form Tabs?
Currently, I have opened the ticket link to another Tabs. However, the title of the opened ticket does not match the name of that ticket (image attack)
[
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/49285229/4e1bd904-0948-474e-bed1-5d818d0227e2)
](url)

**Comment by ArgoZhang** [comment]
@boc2010 hi. please provide some code. which way to open a new tab item

1. `TabItemOptionAttribute`
2. `TabItemMenuBinder`
3. from `MenuItem`
4. `NavigationManager` extension method `NavigateTo`

**Comment by ArgoZhang** [comment]
@boc2010 

1. using BootstrapBlazor.Component
2. add `IServiceProvider` services
```
[Inject]
[NotNull]
private IServiceProvider? ServiceProvider { get; set; }
```
3. using the extension method
```
Navigation.NavigateTo(ServiceProvider, $"impexp/impexe{strDatType}/{strIdVouchers}", text, icon, closable)
```

**text**:  the title of `TabItem`
**icon**: the icon of `TabItem`
**closable**: whether can close the `TabItem`

**Comment by ArgoZhang** [comment]
@boc2010 Hi it works? can I close this issue? if you have any questions let us know.
