### ISSUE TITLE
Localization in Webassambly

### ISSUE THREAD

**Issue by a0926019412** [dotnetcore/BootstrapBlazor#2203]
請問, 元件多語系切換的方式, 是否有提供類似i18n方式, 不需要做 navigateTo reload, 
直接在clientside 切換的方式呢?

**Comment by densen2014** [comment]
没有。 你要的只能走i18n blazor那个库了

**Comment by ArgoZhang** [comment]
@densen2014 i18n 不 reload 怎么切换语言？

**Comment by densen2014** [comment]
> @densen2014 i18n 不 reload 怎么切换语言？

https://www.cnblogs.com/densen2014/p/16105174.html

**Comment by a0926019412** [comment]
@densen2014 目前是先混著用, 看之後有沒有機會提供類似的方式去更新, 方便讓我們做統一

@ArgoZhang 另外想問, 關於table的刷新, 我們這邊有些應用要做動態欄位名稱(column header text)
當欄位名稱用雙向綁定後更新時, 呼叫this.statehaschanged 似乎不會立即產生作用, 要另外呼叫queryasync method才會生效 
請問是否有機會結合兩個事件呢? (有時也會有父元件更新子元件的應用)

**Comment by ArgoZhang** [comment]
try https://www.blazor.zone/table/dynamic-object
