### ISSUE TITLE
New Feature Card carousel  

### ISSUE THREAD

**Issue by Vikas8881** [dotnetcore/BootstrapBlazor#221]
Hey Guys. Please look in this URL section Ecommerce
can we get something like this 
https://www.htmlelements.com/blazor/blazor-ui/demos/e-commerce-details

on this page
**Related products**
because as I can see there is no component for this kind of operations

![screenshot-www htmlelements com-2022 08 17-01_42_39](https://user-images.githubusercontent.com/48914844/184976393-699a6114-2198-45ed-8804-191289bebfa9.png)

**Comment by ArgoZhang** [comment]
@Vikas8881 thank you for submitting the issue. yes no this kind of component yet. can you submit a PR for this?

**Comment by pomeara** [comment]
Hi @ArgoZhang  I think this javascript will solve this (and would be a nice addition)

[OwlCarousel](https://owlcarousel2.github.io/OwlCarousel2/)

**Comment by ArgoZhang** [comment]
@pomeara @Vikas8881 Sorry for the late reply. I'll take a look at this when I'm free. Maybe I can implement it at the next milestone

**Comment by Vikas8881** [comment]
@ArgoZhang thanks for your reply.
I know you can do this 😁😁😁

**Comment by ArgoZhang** [comment]
@Vikas8881 there is a smple match this requirement 

http://localhost:50853/carousels#ChildContent
