### ISSUE TITLE
feat(Table): 编辑弹窗按 Order 值排列

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#2213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

![F3}68M9G_2PI}7ZGZY)@(BW](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/6e1787cb-4e54-4cb5-8518-9bde55aacb7e)

Table组件中，Order 值在列表中，按 正、0、负 的顺序显示。
在新建编辑弹窗中，按 负、0、正 的顺序显示。
这2个地方，显示顺序能不能搞成一致的啊

**Comment by densen2014** [comment]
我来安排

**Comment by ArgoZhang** [comment]
@densen2014 感觉应该 倒序排序即可目前是一个奇怪的逻辑

```
return cols.Where(a => a.Order > 0).OrderBy(a => a.Order)
  .Concat(cols.Where(a => a.Order == 0))
  .Concat(cols.Where(a => a.Order < 0).OrderBy(a => a.Order));
```

https://github.com/dotnetcore/BootstrapBlazor/blob/8661e48a12484a111dddf25192d286a3f98a42a0/src/BootstrapBlazor/Utils/Utility.cs#L323

**Comment by densen2014** [comment]
> @densen2014 感觉应该 倒序排序即可目前是一个奇怪的逻辑
> 
> 
> 
> https://github.com/dotnetcore/BootstrapBlazor/blob/8661e48a12484a111dddf25192d286a3f98a42a0/src/BootstrapBlazor/Utils/Utility.cs#L323-L325
> 
> 

之前是我提交的，逻辑没毛病的。

**Comment by densen2014** [comment]
负数越大越在后面，是分开排序的

**Comment by ArgoZhang** [comment]
懂了 `3, 2, 1, 0, -1, -2, -3` 排序规则，真变态
