### ISSUE TITLE
设置Color.None时候Button会有Outline

### ISSUE THREAD

**Issue by Tendx** [dotnetcore/BootstrapBlazor#223]
大佬们，我从6.8.17升级到最新版，发现设置Button的Color=Color.None的时候，鼠标悬停时Button会出现Outline，旧版本默认样式不会有Outline。
这个还会改回去么，还是以后就保持这样了？

**Comment by ArgoZhang** [comment]
@Tendx 感谢提交 Issue 我马上改回去，6.8.17 `bootstrap` 更新到 `5.2.0` 很多细节发生了变化，发现可以随时联系我。我更新样式尽量保持原状。这个自己项目中也可以写一个样式进行消除。请留意新版本，我最迟明天发包 6.9.4

**Comment by ArgoZhang** [comment]
@Tendx 已修复 `6.9.4`

**Comment by Tendx** [comment]
大佬，点击的时候outline还在。。。

**Comment by ArgoZhang** [comment]
@Tendx 非常抱歉，由于我的测试不充分给您带来了不必要的麻烦，已经修复，稍等我再发一个包

```
.btn-none {
    --bs-btn-active-border-color: transparent;
}
```

临时解决可在您自己项目中的样式表文件中增加上面的 样式即可

**Comment by ArgoZhang** [comment]
@Tendx `6.9.5` 已发布
