### ISSUE TITLE
feat(JSRuntime): Add JSRuntime extension method support

### ISSUE THREAD

**Issue by azlis** [dotnetcore/BootstrapBlazor#2231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Added JSRuntime extension method support

**Comment by ArgoZhang** [comment]
@azlis 我看了一下设计，我感觉如果做如下更改，感觉会更好

1. 移除 `IBootstrapBlazorJSHelper` 接口以及实现
这个功能其实是对 `JSInvoke` 能力的一种扩展，微软已经封装了很多互操作类集中到 `IJSRuntime` 接口中，我建议我们只需要做扩展方法即可，减少用户学习成本，自然而然的就用了

2. 对 `IJSRuntime` 实例进行方法扩展
```
public static ValueTask AddLink(string link, string? rel = null) => InvokeVoidAsync("doAddLinkWithRel", link, rel);
```
