### ISSUE TITLE
文档/对话框页发现的一个问题

### ISSUE THREAD

**Issue by staoran** [dotnetcore/BootstrapBlazor#224]
### Describe the bug
在[文档的对话框页](https://www.blazor.zone/dialogs)，某些操作会使弹窗按钮失效，此问题不知是否是 BUG

### To Reproduce
1. 打开 https://www.blazor.zone/dialogs 
2. 点击任意支持 ESC 关闭的对话框按钮
3. 弹出后 随意点按键盘（abcd 空格 之类的）
4. 通过 ESC 关闭对话框
5. 全页对话框按钮失效

3-4 是触发问题的关键。如果在第三步之后使用对话框右上角 X 或关闭按钮关闭对话框则不会出问题。

### Exceptions
控制台中未见异常

### Further technical details
Windows 10 专业版 22H2 19045.1889

以下浏览器均重现问题
Microsoft Edge 版本 104.0.1293.54 (正式版本) (64 位)
Firefox 103.0.2 (64 位)

**Comment by ArgoZhang** [comment]
@staoran 感谢提交 Issue 已复现 正在修复

**Comment by ArgoZhang** [comment]
@staoran 已修复 `6.9.4`
