### ISSUE TITLE
能给一个SliderCaptcha后端验证的逻辑吗

### ISSUE THREAD

**Issue by yinjisong** [dotnetcore/BootstrapBlazor#2246]
### Document describing which component

我照着你的java方法用PHP实现了一下但是有问题

**Comment by ArgoZhang** [comment]
@yinjisong 没懂，这是 blazor 你怎么用 PHP 实现的？

**Comment by densen2014** [comment]
神奇，咋们项目怎么有java来的，为什么又要做成php

**Comment by ArgoZhang** [comment]
@densen2014 应该是那个 js 库，issue 建错库了
