### ISSUE TITLE
Update to FontAwesome 6

### ISSUE THREAD

**Issue by DominicSaladin** [dotnetcore/BootstrapBlazor#225]
### Is your feature request related to a problem? Please describe.
I found this project about 2 months ago and I really like it. Problem is, I'm using the latest FontAwesome version, which is version 6.
But it seems like this project is still using FontAwesome 4.

### Describe the solution you'd like
Update the css to FontAwesome 6 and check / update all css class references

**Comment by ArgoZhang** [comment]
@DominicSaladin Is FontAwesome 6 free?

**Comment by DominicSaladin** [comment]
@ArgoZhang Yes, there is a free and a pro version. With the free version you get like 1600 icons, instead of 600 you got with FontAwesome 4

**Comment by ArgoZhang** [comment]
@DominicSaladin it's worth update to V6. I create a branch name of `feat-fa-v6`. you can tracking the progress or submit commit for this. we can work together

**Comment by pomeara** [comment]
I would love an update to v6 also great idea @DominicSaladin and great work @ArgoZhang

**Comment by DominicSaladin** [comment]
> @DominicSaladin it's worth update to V6. I create a branch name of `feat-fa-v6`. you can tracking the progress or submit commit for this. we can work together

Yeah sure I'll help. I'm currently mapping all the old icons to the new one in an excel file and hope that a find and replace will do the job afterwards :)

**Comment by DominicSaladin** [comment]
I started updating all icons. 180 so far :D
https://github.com/DominicSaladin/BootstrapBlazor/tree/feat-fa-v6

**Comment by ArgoZhang** [comment]
@DominicSaladin I also submitted some updates.

**Comment by DominicSaladin** [comment]
Sooo, everything should be updated now :D

**Comment by ArgoZhang** [comment]
@DominicSaladin  thanks. great work

**Comment by ArgoZhang** [comment]
@DominicSaladin hi. Can you submit a PR from `feat-fa-v6` to `main`. Thank you for your contribution.

**Comment by ArgoZhang** [comment]
@DominicSaladin I have released version `6.9.6`. You can submit PR at any time if you find any missing or incorrect icons. thank you
