### ISSUE TITLE
Blazor Hybrid use ProtectedSessionStorage error.

### ISSUE THREAD

**Issue by moll33er** [dotnetcore/BootstrapBlazor#226]
Blazor Hybrid WPF Blazor app

Error information:
System.Reflection.TargetInvocationException:“Exception has been thrown by the target of an invocation.”
InvalidOperationException: Cannot provide a value for property 'ProtectedSessionStore' on type '....'. There is no registered service of type 'Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedSessionStorage'.

Solution:

MainWindow.xaml.cs add code
```
            serviceCollection.AddDataProtection();
            serviceCollection.AddScoped<ProtectedSessionStorage>();
```
.NET 6.0 must used AddScoped not AddSingleton.

**Comment by ArgoZhang** [comment]
@moll33er Thanks. could you give this project a star?
