### ISSUE TITLE
The localization can be overriden

### ISSUE THREAD

**Issue by cairabbit** [dotnetcore/BootstrapBlazor#2265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When using third party components that based on bootstrapBlazor, if some localization string were missing in that component, I'd like to add those localization in my project to show correct localized string. 
for example:
I'm getting these errors:
[17:11:29 DBG] ResourceManagerStringLocalizer searched for 'ToastTitle' in 'BootstrapBlazor.Resources.Components.ErrorLogger' with culture 'zh-CN'.
[17:11:29 DBG] ResourceManagerStringLocalizer searched for 'TooltipText' in 'BootstrapBlazor.Resources.Components.Layout' with culture 'zh-CN'.

### Describe the solution you'd like

for the above problem,  I want to add translations for 'ToastTitle' in 'BootstrapBlazor.Resources.Components.ErrorLogger' and 'TooltipText' in 'BootstrapBlazor.Resources.Components.Layout' in my project this way:

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/1597596/26b7ac17-396b-408c-b57d-775928b93ddc)

Now my localized strings should work with 3rd party components.

### Additional context

There is another way is to use `ILocalizationResolve` to solve this problem. However, in my opinion, these two features are targeting different goals. By using `ILocalizationResolve`, I'm more likely to use some external service to do translations (i.e. Google Translation service), but by this overridden feature, I'd like to solve or override the translations myself. Thanks.

**Comment by ArgoZhang** [comment]
@cairabbit thank you for contracting us. so did you wanna add a way `ILocalizationResolve` on `BootstrapBlazor`?
