### ISSUE TITLE
DateTimePicker with time interval

### ISSUE THREAD

**Issue by rehali** [dotnetcore/BootstrapBlazor#227]
First of all, I'm very impressed with the complete BootstrapBlazor component library, so thanks for such great work.

It would be nice to restrict the **timepicker** so that you could have intervals of say 5min, 10min, 15min, rather than having just an increment by minute.

It would be nice to be able to turn off the seconds incrementer, I'm sure a lot of users don't require timing down to the second.

Also I can see how to set the **SideBarItems** for the **DateTimeRange** component, but I can't see how to set the **SidebarItems** for the **DateTimePicker** - I've created a collection of **DatePickerCells** but don't see how to use them.

Finally, the documentation shows an option for **TimeFormat** which doesn't seem to be available, although using the **Format** property does allow you to set both date and time formats.

**Comment by ArgoZhang** [comment]
@rehali hi, sorry for the late reply. thanks for your issue. 

1. remove the TimeFormat from doc
2. redesign TimePicker in next milestone
