### ISSUE TITLE
bug: 虚拟滚动模式 Tips 定位漂移

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#2295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
    [DisplayName("客户")]
    [AutoGenerateColumn(ShowTips = true, TextEllipsis = true, Width = 150, Order = 4)]
    public string CustomerName { get; set; }
```
## 名称很长的情况下定位漂移

![H1 6WM SFDZDA9Z5HD5266](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/1280d57d-fb8e-4441-9ee3-8165e5e2a727)

## 客户名称长度短的tips没问题

![)HADDIH2YH@LGMICP3_H`ZO](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/1fcc75a3-7deb-4d96-b853-f75819db293e)

## 拉长列宽后定位就正确了

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/3834921c-316d-4ebe-8d43-97fccbbeec13)

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/c062e259-c653-4864-ad92-9b009e05f1f6)

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/7bf8f28f-10dd-4916-8c73-9f5574715577)

### .NET Version

7

**Comment by ArgoZhang** [comment]
@densen2014 这个 bug `bootstrap` 那边一直没有解决，这个代码我们几乎一行都没有
