### ISSUE TITLE
bug: 使用Popconfirm 气泡确认框无法清空Table组件的界面显示数据

### ISSUE THREAD

**Issue by wangfei9999** [dotnetcore/BootstrapBlazor#2296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

使用Popconfirm 气泡确认框无法清空Table组件的界面显示数据

**Comment by wangfei9999** [comment]
`
@page "/"

<h1>Hello, world!</h1>

<Button Icon="fa-solid fa-arrows-rotate" Text="Button组件-清空Table" OnClick="OnTableClear" class="my-2" />

<PopConfirmButton Placement="Placement.Top"
                  Color="Color.Danger"
                  ConfirmIcon="fa-solid fa-triangle-exclamation text-danger"
                  ConfirmButtonColor="Color.Danger"
                  Text="PopConfirmButton组件-清空Table"
                  Content="确定删除数据吗？"
                  IsAsync="true"
                  OnConfirm="@OnTableClearAsync" />

<Table TItem="Foo" Items="@Items">
    <TableColumns>
        <TableColumn @bind-Field="@context.Id" Width="180" />
        <TableColumn @bind-Field="@context.Name" />
    </TableColumns>
</Table>


@code{
    public class Foo
    {
        public int Id { get; set; }

        public string? Name { get; set; }
    }

    private List<Foo>? Items { get; set; }

    protected override Task OnInitializedAsync()
    {
        Items = Enumerable.Range(1, 10).Select(i => new Foo() { Id = i, Name = $"名称_{i}" }).ToList();

        return base.OnInitializedAsync();
    }


    private void OnTableClear()
    {
        Items = null;
    }

    private Task OnTableClearAsync()
    {
        Items = null;
        return Task.CompletedTask;
    }
}
`

**Comment by wangfei9999** [comment]
```
@page "/"

<h1>Hello, world!</h1>

<Button Icon="fa-solid fa-arrows-rotate" Text="Button组件-清空Table" OnClick="OnTableClear" class="my-2" />

<PopConfirmButton Placement="Placement.Top"
                  Color="Color.Danger"
                  ConfirmIcon="fa-solid fa-triangle-exclamation text-danger"
                  ConfirmButtonColor="Color.Danger"
                  Text="PopConfirmButton组件-清空Table"
                  Content="确定删除数据吗？"
                  IsAsync="true"
                  OnConfirm="@OnTableClearAsync" />

<Table TItem="Foo" Items="@Items">
    <TableColumns>
        <TableColumn @bind-Field="@context.Id" Width="180" />
        <TableColumn @bind-Field="@context.Name" />
    </TableColumns>
</Table>


@code{
    public class Foo
    {
        public int Id { get; set; }

        public string? Name { get; set; }
    }

    private List<Foo>? Items { get; set; }

    protected override Task OnInitializedAsync()
    {
        Items = Enumerable.Range(1, 10).Select(i => new Foo() { Id = i, Name = $"名称_{i}" }).ToList();

        return base.OnInitializedAsync();
    }


    private void OnTableClear()
    {
        Items = null;
    }

    private Task OnTableClearAsync()
    {
        Items = null;
        return Task.CompletedTask;
    }
}
```

**Comment by densen2014** [comment]
@ref table

table.load

**Comment by ArgoZhang** [comment]
@wangfei9999 

目测
 
```
private Task OnTableClearAsync()
{
    Items = null;

    // 增加 这一行代码
    StateHasChanged();

    return Task.CompletedTask;
}
```
