### ISSUE TITLE
Carousel upgrade 

### ISSUE THREAD

**Issue by pomeara** [dotnetcore/BootstrapBlazor#230]
Hi @ArgoZhang ,

I really like this Carousel and though a second Carousel could be added to BB to integrate this free java script library

[OwlCarousel](https://owlcarousel2.github.io/OwlCarousel2/)

This would solve Issue 221

**Comment by ArgoZhang** [comment]
@pomeara great idea. I'll refer to it when I'm free

**Comment by ArgoZhang** [comment]
@pomeara sorry to say I don't have enough time to learn this js. The BB component library no longer considers integrating JS lib. 

I strongly suggestion that create a new lib named of BootstrapBlazor.OwlCarousel lib for this js lib
