### ISSUE TITLE
IsSelectAllTextOnFocus is not working

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#2320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After the last update the options IsSelectedAllText is not working on focus by click on the mouse, or mobile or by code, any options.

**Comment by ArgoZhang** [comment]
@gmondin hi. thank you for contact us. let me repro this issue.

**Comment by ArgoZhang** [comment]
@gmondin 

```
<BootstrapInput PlaceHolder="Please input ..."
                        TValue="string"
                        IsAutoFocus="true"
                        IsSelectAllTextOnFocus="true" />
```

it works fine.

please provider repro mini project
