### ISSUE TITLE
bug: <Spinner span not work 旋转组件似乎无效>

### ISSUE THREAD

**Issue by OneEyedOlaf** [dotnetcore/BootstrapBlazor#2333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Added the rotating component to the code but can't see him, according to the browser console the component is already there, just not visible.
Here is my code:<Spinner Color="Color.Danger" SpinnerType="SpinnerType.Grow" Size="Size.Large">loading...</Spinner>

在代码中添加了旋转组件但是看不到他，根据浏览器控制台来看，组件已经存在，只不过看不见。
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/140895631/c9cb726b-ded3-4a39-8dc3-4b2d66a4cbcf)

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/140895631/f7c901de-888c-4dc1-9f83-108d8262faac)

### Expected Behavior

Can be displayed as a normal component

### .NET Version

7

### Anything else?

vs

**Comment by ArgoZhang** [comment]
@OneEyedOlaf Issue 不合格请提供最小复现工程，不然无法继续
