### ISSUE TITLE
Can not find summernote-bs5.min.css

### ISSUE THREAD

**Issue by 1002527441** [dotnetcore/BootstrapBlazor#234]
### Describe the bug
i am trying to only use <Editor> component in my project, and find this error.

@page "/counter"

![image](https://user-images.githubusercontent.com/53967483/187108679-f3aa6406-a9d2-4d74-9dd1-d0ab87f15d8f.png)

![image](https://user-images.githubusercontent.com/53967483/187108829-24e2030b-a46a-4d0e-ad7e-26a6489e5320.png)

![image](https://user-images.githubusercontent.com/53967483/187108871-fba9a179-b1fb-4388-92ab-063950af129f.png)

### To Reproduce

https://github.com/1002527441/Blazor.SummerNote

### Further technical details
- BootstrapBlazor.SummerNote 6.0..2
- 
- Include the output of `dotnet --info`
- 
- .NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS 2022 you're running on, and its version

**Comment by ArgoZhang** [comment]
@1002527441 thanks for your issue. later i will check it and fix

**Comment by ArgoZhang** [comment]
@1002527441 can't fork your repo. Can you send me an email? If you are Chinese, you can join my community QQ group 795206915
