### ISSUE TITLE
Table control allow columns to 'dissapear' based on different col specitications

### ISSUE THREAD

**Issue by pomeara** [dotnetcore/BootstrapBlazor#235]
@ArgoZhang  when I use the <Table> control and I have many columns, I wish to make columns dissapear when the form is sized smaller , currently a 'scroll bar' appears which is good but it would be good to specify a way to 'hide/remove' these columns from the grid when the user is on a mobile device (as a scroll bar is not very easy to use on a phone etc...)

I have lookekd to see if this is implemented but could not see it and this would be a nice upgrade so the Table works better in responsive mode on smaller screens

**Comment by ArgoZhang** [comment]
@pomeara Is this question about the table component? The table component has a parameter `RenderMode`. The default value is `TableRenderMode.Auto`. It will automatically adapt to the small screen.
