### ISSUE TITLE
Toast clickable like push notification

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#238]
Hi, I would like to know if is possible make the toast clickable like a push notification, I have tried use the additional attributes, but its not working.
I have made put a component with a clickable element on toast, but, like this the click is only in that area and the ideal for me is something like push notification, where the click is all the component, its possible do this with additional attributes?
Other question, it's possible make disabled the close X on toast?

**Comment by ArgoZhang** [comment]
@gmondin sure. 

1. add a ShowClose parameter on Toast
2. you can custom the `ChildContent` parameter on `ToastOption` for hook the click event

**Comment by ArgoZhang** [comment]
@gmondin https://github.com/dotnetcore/BootstrapBlazor/commit/254cd7156c0e5a755a542487beb6339f27b18a13

is it ok?

**Comment by gmondin** [comment]
Yes, is it ok, thank you very much

**Comment by ArgoZhang** [comment]
@gmondin ok. will integrate the next release
