### ISSUE TITLE
bug: BootstrapBlazor EditorForm Not Rendering

### ISSUE THREAD

**Issue by franks1** [dotnetcore/BootstrapBlazor#2384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**The Bootstrap Editor form is not rendering. 
There appears  only spinner.
This is seen after upgrading to .NET 8**

### Expected Behavior

The form should render the display model bound to the Editor Form

**Comment by ArgoZhang** [comment]
@franks1 hi. could you provider a mini repo project?

it seem works fine on the website

http://www.blazor.zone/editor-form

**Comment by franks1** [comment]
Sure I will do that

**Comment by franks1** [comment]
Please find a sample project i built to illustrate the issue
[https://github.com/franks1/EditorFormBlazorApp](url)

**Comment by franks1** [comment]
> @franks1 Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnetcore/bootstrapblazor/blob/main/docs/repro.md) that illustrates the problem.

Please find a sample project i build to illustrate the issue

[https://github.com/franks1/EditorFormBlazorApp](url)

**Comment by ArgoZhang** [comment]
@franks1 wrong url. pls update the repro project link

**Comment by ArgoZhang** [comment]
@franks1 can't open the follow url https://github.com/franks1/EditorFormBlazorApp

**Comment by franks1** [comment]
> @franks1 can't open the follow url https://github.com/franks1/EditorFormBlazorApp

I have made it public now please tray again

**Comment by ArgoZhang** [comment]
@franks1 

add the follow code on your Home.razor

```
@rendermode InteractiveServer
```

submit a PR for you

**Comment by franks1** [comment]
> @franks1 
> 
> add the follow code on your Home.razor
> 
> ```
> @rendermode InteractiveServer
> ```
> 
> submit a PR for you

Okay

**Comment by franks1** [comment]
> @franks1
> 
> add the follow code on your Home.razor
> 
> ```
> @rendermode InteractiveServer
> ```
> 
> submit a PR for you

I can confirm that after making the relevant code additions the form is now rendering.

**Comment by franks1** [comment]
Thank you

**Comment by ArgoZhang** [comment]
@franks1 pls give this project a star if you like it. thanks

**Comment by franks1** [comment]
> @franks1 pls give this project a star if you like it. thanks

Sure
