### ISSUE TITLE
VS2022 .NET8 Blazor Server 项目一直提示报错内容 

### ISSUE THREAD

**Issue by wangfei9999** [dotnetcore/BootstrapBlazor#2387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/73685882/65dc4731-6c0c-4733-b9b3-5a4088b864ec)

### .NET Version

8.0

**Comment by wangfei9999** [comment]
q

**Comment by ArgoZhang** [comment]
@wangfei9999 咳咳咳
