### ISSUE TITLE
table增加重置分页页码的功能

### ISSUE THREAD

**Issue by xisimao** [dotnetcore/BootstrapBlazor#239]
我现在遇到了这样一个场景，table显示某个设备的数据，当我切换设备时，会调用  ` await _table.QueryAsync(); ` 这样的代码，此时我希望查询新设备的第一页数据，但是实际上，我在OnQueryAsync回调中的QueryPageOptions参数页码还是旧的,所以希望有一个可以重置或者设置table页码的方法或属性，来避免这样的问题。

**Comment by ArgoZhang** [comment]
@xisimao add pageIndex parameter on QueryAsync method

https://github.com/dotnetcore/BootstrapBlazor/commit/59bf137454704a58c9b2698cad0e96fd537e79aa
