### ISSUE TITLE
关于表格组件中的自定义搜索问题

### ISSUE THREAD

**Issue by SeptSkyTime** [dotnetcore/BootstrapBlazor#2396]
在表格组件的帮助文档中，我正在学习如何使用自定义搜索功能，下图为帮助文档的示例代码：
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/141984875/c9543c09-c605-41b7-9f54-146fc7d72325)
在`<CustomSearchTemplate>`内的`<FooSearch>`标签是如何定义的？不知道在哪里能够找到`<FooSearch>`的定义代码。
我正在尝试使用表格的自定义搜索功能，因为这个标签而不知道如何进行下去了。
另外，在哪里能下载到文档各个组件演示的代码，直接在文档页面内查看代码不够方便。
谢谢！

**Comment by densen2014** [comment]
文档工程就在你发issue这里，所有的源码也都在。

**Comment by ArgoZhang** [comment]
@SeptSkyTime 

###  第一步 
点击右上角 Star 

### 第二步
打开 [https://github.com/dotnetcore/BootstrapBlazor?wt.mc_id=DT-MVP-5004174](https://github.com/dotnetcore/BootstrapBlazor?wt.mc_id=DT-MVP-5004174)

找到 Clone 把项目弄到本地

### 第三步

vs2022 打开工程

### 代码路径

https://github.com/dotnetcore/BootstrapBlazor/tree/main/src/BootstrapBlazor.Server/Components/Samples

**Comment by ArgoZhang** [comment]
### FooSearch

https://github.com/dotnetcore/BootstrapBlazor/blob/main/src/BootstrapBlazor.Server/Components/Components/FooSearch.razor

**Comment by SeptSkyTime** [comment]
> @SeptSkyTime Thank you for reporting. We will give triage later.



> ### FooSearch
> https://github.com/dotnetcore/BootstrapBlazor/blob/main/src/BootstrapBlazor.Server/Components/Components/FooSearch.razor

找到了，知道如何自定义搜索界面了。
非常感谢！

**Comment by ArgoZhang** [comment]
@SeptSkyTime 帮忙点个 star 啊。这是美德

**Comment by SeptSkyTime** [comment]
> @SeptSkyTime 帮忙点个 star 啊。这是美德

已点star

**Comment by SeptSkyTime** [comment]
关于<FooSearch>组件，我将示例代码中的该定义拷贝到我的项目中，然后出现了下面的错误提示，甚至我使用BootStrapBlazor的项目向导创建一个Server端的项目，依然存在这个问题。
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/141984875/8aa1e6ac-3f21-4fd8-9a25-740d248a69f7)
错误提示内容：RZ9991	The attribute names could not be inferred from bind attribute 'bind-Value'. Bind attributes should be of the form 'bind' or 'bind-value' along with their corresponding optional parameters like 'bind-value:event', 'bind:format' etc.
按错误提示搜索也没有找到对症的解决办法，我对Blazor不是很熟悉，所以现在是一筹莫展，请帮忙提示一下解决问题的思路，谢谢！

**Comment by ArgoZhang** [comment]
@SeptSkyTime 你这样弄下去问题会越来越多。建议规划一下学习路径。找些教程看看。这都是最基本的问题

你的信息提供的不全。我猜

1. `Value` 没有定义
2. `razor` 页面内没有 `@using BootstrapBlazor.Components`

**Comment by SeptSkyTime** [comment]
> @SeptSkyTime 你这样弄下去问题会越来越多。建议规划一下学习路径。找些教程看看。这都是最基本的问题
> 
> 你的信息提供的不全。我猜
> 
> 1. `Value` 没有定义
> 2. `razor` 页面内没有 `@using BootstrapBlazor.Components`

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/141984875/1be289b7-dad5-4977-aa97-c522629bf4e3)
<FooSearch>的界面和代码直接从源码的示例程序中拷贝出来的，只是修改了命名空间，我的项目是Net7，源码示例是Net8，按理不应该出现这个问题，我自己再研究研究吧。谢谢！
