### ISSUE TITLE
bug: Examples Site Offline

### ISSUE THREAD

**Issue by zebby-nick** [dotnetcore/BootstrapBlazor#2397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The website https://www.blazor.zone/ is timing out. No Errors just a time out. Has been working for weeks no issues.

**Comment by ArgoZhang** [comment]
@zebby-nick i don't understand what your mean. the website working fine.

**Comment by zebby-nick** [comment]
@ArgoZhang Very strange. works now. Not sure what the problem was, might have just been me but I did test from multple locations. All working now though.

**Comment by ArgoZhang** [comment]
@zebby-nick hi. could you give this project a star if you like it
