### ISSUE TITLE
Upload.js的bb_upload_drag_init方法报错

### ISSUE THREAD

**Issue by wapco** [dotnetcore/BootstrapBlazor#240]
当InputUpload作为父控件继承的时候，bb_upload_drag_init中的element参数为null会报错，应该新增一行判断 if (!element) return;

**Comment by wapco** [comment]
如自定义控件OssInputUpload 继承InputUpload，会触发这个异常
@typeparam TValue
@inherits InputUpload<TValue>

<InputUpload TValue="TValue" UploadDir="@UploadDir" ShowDeleteButton="true" OnChange="@OnFileChange" OnDelete="@OnFileDelete"></InputUpload>

**Comment by ArgoZhang** [comment]
@wapco 感谢提交 issue 已修复，下个版本更新
