### ISSUE TITLE
Camera can not get Image

### ISSUE THREAD

**Issue by Lanticee** [dotnetcore/BootstrapBlazor#241]
I try to Use camera. 
open works. can see camera image.
close works.
but Capture can not return image, only data;

then i try at https://www.blazor.zone/Cameras.

It get same result without any exception.

**Comment by ArgoZhang** [comment]
@Lanticee that's right. you can process the data string in the OnCapture callback

**Comment by Lanticee** [comment]
I did like sample code on OnCapture

but  parameter only get data; ,without images base64 string.

then i try demosite, it get same result.

**Comment by ArgoZhang** [comment]
@Lanticee sorry for my mistake. this bug has been fixed and bump version to `6.10.2`

**Comment by Lanticee** [comment]
thx a lot
