### ISSUE TITLE
bug: BootstrapBlazor Form Post Error

### ISSUE THREAD

**Issue by franks1** [dotnetcore/BootstrapBlazor#2410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Could you help me post a login form with BootstrapBlazor Validate form? The Validation works perfectly fine, however, the form post does not work and throws error : 
**System.InvalidOperationException: Headers are read-only, response has already started.**
I have created a sample project here: [Repo (https://github.com/franks1/BlazorApp1.git) ]

### Expected Behavior

The form post should work like the traditional html form element or Form post in asp mvc without the Header error.

**Comment by franks1** [comment]
> @franks1 Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnetcore/bootstrapblazor/blob/main/docs/repro.md) that illustrates the problem.

Find sample repo here: https://github.com/franks1/BlazorApp1

**Comment by ArgoZhang** [comment]
@franks1 sorry for that this repro-project can't running on my host

```
Error: System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure' to the 'UseSqlServer' call.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "aspnet-BlazorApp1-dbdca2cb-dc03-4a03-a1a9-67f1bbde1ade" requested by the login. The login failed.
Login failed for user 'WIN-67LV50OMMEV\Argo'.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at 
```

BTW: your question seems not issue about `BootstrapBlazor` component

**Comment by franks1** [comment]
> @franks1 sorry for that this repro-project can't running on my host
> 
> ```
> Error: System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure' to the 'UseSqlServer' call.
>  ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "aspnet-BlazorApp1-dbdca2cb-dc03-4a03-a1a9-67f1bbde1ade" requested by the login. The login failed.
> Login failed for user 'WIN-67LV50OMMEV\Argo'.
>    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at 
> ```
> 
> BTW: your question seems not issue about `BootstrapBlazor` component 

I will make changes to the connection string and get back to you.

**Comment by franks1** [comment]
> @franks1 sorry for that this repro-project can't running on my host
> 
> ```
> Error: System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure' to the 'UseSqlServer' call.
>  ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "aspnet-BlazorApp1-dbdca2cb-dc03-4a03-a1a9-67f1bbde1ade" requested by the login. The login failed.
> Login failed for user 'WIN-67LV50OMMEV\Argo'.
>    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at 
> ```
> 
> BTW: your question seems not issue about `BootstrapBlazor` component

I have updated the repo with sqllite database as primary database . Kindly try again . Please if possible kindly assist me to find out why form post using BootstrapBlazor Form is behaving this way, while just static rendered form does not give the exception.

**Comment by ArgoZhang** [comment]
@franks1 hi. No errors occurred on my console. what's the error in your environment?

**Comment by franks1** [comment]
> @franks1 hi. No errors occurred on my console. what's the error in your environment?
Ok. The application environment is development.
Sorry for the update. I managed to resolve the problem last night. The issue involved setting the cookie in the browser for authentication. I found a way to do this in Blazor without using SignInManager to handle the Sign in process. Thanks for the assistance. I am grateful

**Comment by ArgoZhang** [comment]
@franks1 you are welcome
