### ISSUE TITLE
bug: Select "OnSelectedItemChanged" inside Table EditTemplate won't change cascading Select.

### ISSUE THREAD

**Issue by Morteza8181** [dotnetcore/BootstrapBlazor#2419]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

I have a Table with Form Editing Mode. and two cascading Select. while my cascading Select work outside of Table EditTemplate it stop working when i move it inside EditTemplate.

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/151643359/f21a272e-6d8e-4e08-a366-564e9b799ea4)

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/151643359/c3acc0a6-d5db-4403-b6d5-661c66216ec4)

### .NET Version

7.0

**Comment by ArgoZhang** [comment]
@Morteza8181 

```
<EditTemplate>
    <YourComponent />
</EditTemplate>
```

```
<Select ... />
<Select ... />
```
