### ISSUE TITLE
High  Extend features for controls BootstrapInput,BootstrapInputNumber,...

### ISSUE THREAD

**Issue by Himaa-m0unir** [dotnetcore/BootstrapBlazor#242]
when using BootstrapInputs it doesn't have following which is a must on any controls 
_Control [Got focused event]
_Control [lost focus event]
_Control [On Key Press / Key Up event]

**Comment by ArgoZhang** [comment]
These element have too many events. we can use native methods

```
<BootstrapInput @onkeyup="" />
```

```
@code {

    private void OnKeyDown(KeyboardEventArgs args)
    {

    }
}
```
