### ISSUE TITLE
DockView

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#2430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

On DockView, could you include a pin to fix or hide the dock? 

### Describe the solution you'd like

Like this when you hide, this can go to a "tab" on top/right/left/down (with this options), also has a option to initialize hide or visible.
Thank you

**Comment by ArgoZhang** [comment]
@gmondin sorry for the delayed reply because of illness. the `DockView` is the wrapper of [GlodenLayout](https://golden-layout.com/).

please find the feature on `GlodenLayout` first. then we can move it into our component lib
