### ISSUE TITLE
Collapse is not working 

### ISSUE THREAD

**Issue by Himaa-m0unir** [dotnetcore/BootstrapBlazor#244]
![image](https://user-images.githubusercontent.com/11277707/189548935-1e793b94-eb81-48f8-b9d8-dabfa67289d1.png)

![image](https://user-images.githubusercontent.com/11277707/189548953-c7834ef3-3b42-417e-9ddb-3dc9f4abf82c.png)

**Comment by ArgoZhang** [comment]
@Himaa-m0unir thanks for contracting us. fixing

**Comment by ArgoZhang** [comment]
@Himaa-m0unir fixed. thanks
