### ISSUE TITLE
6.9.10后的版本AuthorizeRouteView控件失效

### ISSUE THREAD

**Issue by wapco** [dotnetcore/BootstrapBlazor#245]
6.9.10之后的版本AuthorizeRouteView控件失效，导致未登录用户不会跳转到登录页，页面layout消失，只显示main区域。
6.9.10之前包含6.9.10都是正常的。如下代码：
`<OidcRedirectToLogin/>`没有触发

> 
`<BootstrapBlazorRoot>
    <CascadingAuthenticationState>
        <Router AppAssembly="@typeof(App).Assembly" AdditionalAssemblies="AppSetting.AdditionalAssemblies">
            <Found Context="routeData">
                <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                    <NotAuthorized>
                        @if (context.User.Identity?.IsAuthenticated != true)
                        {
                            <OidcRedirectToLogin/>
                        }
                        else
                        {
                            <p role="alert">You are not authorized to access this resource.</p>
                        }
                    </NotAuthorized>
                </AuthorizeRouteView>
                <FocusOnNavigate RouteData="@routeData" Selector="h1"/>
            </Found>
            <NotFound>
                <PageTitle>Page Not found</PageTitle>
                <LayoutView Layout="@typeof(MainLayout)">
                    <p role="alert">Sorry, there's nothing at this address.</p>
                </LayoutView>
            </NotFound>
        </Router>
    </CascadingAuthenticationState>
</BootstrapBlazorRoot>`

**Comment by wapco** [comment]
用的oidc组件是ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect

**Comment by j4587698** [comment]
@wapco 大佬能提供一下更详细的信息嘛？如果能有一个最小复现项目。
是只有ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect这个会出现问题嘛？
我使用cookie的方式做了一下测试，是没有问题的。

**Comment by wapco** [comment]
> @wapco 大佬能提供一下更详细的信息嘛？如果能有一个最小复现项目。 是只有ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect这个会出现问题嘛？ 我使用cookie的方式做了一下测试，是没有问题的。

麻烦加一下微信吧，我把项目发给你：px2757

**Comment by j4587698** [comment]
@wapco 如果没有保密要求，可以直接上传到这里，如果有可以加群处理。

**Comment by wapco** [comment]
已加群

**Comment by ArgoZhang** [comment]
@wapco 复现代码呢？国人尽量采用 gitee 我很难登录 github

**Comment by ArgoZhang** [comment]
@wapco 有人再次提出这个问题。待解决

**Comment by ArgoZhang** [comment]
@wapco 已转移到 https://gitee.com/LongbowEnterprise/BootstrapBlazor/issues/I5RED9

**Comment by Vision-Zhang** [comment]
@wapco  需要在 Layout 标签内加入 NotAuthorized 标签
