### ISSUE TITLE
Active Menu

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#2457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, on the Menu component when I have child and I click on the parent, doesn't mark the parent as active or call the OnClick, like this remain active the menu that the user clicked before.
In that case when I have mora than one submenu it not easy for the users (on the mobile) know where they are.
Thank you very much

**Comment by gmondin** [comment]
For a simple solution, maybe, a suggestion, you need just change the code on SideMenu.razor for:

<ul @attributes="@AdditionalAttributes" id="@Id" class="@GetMenuClassString">
    @foreach (var item in Items)
    {
        if (item.Items.Any())
        {
            <li @onclick:stopPropagation @onclick="() => OnClickItem(item)">
                <MenuLink Item="@item" ArrowIcon="@ArrowIcon" data-bs-toggle="collapse" data-bs-target="@GetTargetIdString(item)" />
                @if (!item.IsDisabled)
                {
                    <CascadingValue Value="item" IsFixed="true">
                        <SideMenu Items="@item.Items" OnClick="@OnClickItem" Id="@GetTargetId(item)" DropdownIcon="@DropdownIcon" class="collapse" data-bs-parent="@ParentIdString" />
                    </CascadingValue>
                }
            </li>
        }
        else
        {
            <li @onclick:stopPropagation @onclick="() => OnClickItem(item)">
                <MenuLink Item="@item" ArrowIcon="@ArrowIcon" />
            </li>
        }
    }
</ul>

**Comment by ArgoZhang** [comment]
@gmondin hi, I don't quite understand what you mean. do you wanna add `active` on parent menu when the child menu item is active?

**Comment by wapco** [comment]
我也遇到了，升级到最新版本后，所有的父级菜单都变选中状态了，我又还原回去了。

**Comment by wapco** [comment]
确实，之前8.0.3出现这个问题，现在8.0.4已经修复了，不过样式--bb-layout-title-color怎么变成黑色了，导致header现在样式有点问题。

**Comment by ArgoZhang** [comment]
@wapco 群友建议组件不要设置颜色，移除了默认颜色，采用 bs 的变量。可自行给那个变量赋值即可
