### ISSUE TITLE
question: 元件繼承問題

### ISSUE THREAD

**Issue by a0926019412** [dotnetcore/BootstrapBlazor#2464]
您好 想請教元件繼承問題
因為想要在部分元件在使用時直接給預設值 , 想繼承select元件並給予一些預設值 (比如ShowSearch) 
下圖為razor程式碼

![inherit](https://github.com/dotnetcore/BootstrapBlazor/assets/4286244/e37004fd-fcb0-4d47-9082-2ef8640eab61)

但使用後會報以下錯誤
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/4286244/7306858b-413a-49d2-8a37-d4392973afca)

請問是我用法錯誤嗎?

**Comment by ArgoZhang** [comment]
@a0926019412 组件是需要 js 工作的。你需要设置脚本路径

@attribute [JSModuleAutoLoader("./_content/xxxxx/Select.razor.js", JSObjectReference = true)]
