### ISSUE TITLE
Question: Has an option to get the event of scroll up or down on the table?

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#248]
I would like to know if has a option to get when the scroll on table get down and on up, example I would like to get some result, but if the user get on bottom of the scroll or on top I would like to get more result, based on my parameters, like I will get information based on a range of date, but if the user scroll up I will get more information before this range of date.
Other question, its possible move the scroll up or down by code? example, I got the information and I would like to move down for the last line based last date, or move up, etc.
Thank you very much

**Comment by ArgoZhang** [comment]
@gmondin hi, first sorry for the delayed reply. for now, there is no way to control the table scroll from C#. I suggestion that use javascript control the table scroll

**Comment by gmondin** [comment]
@ArgoZhang thank you very much
