### ISSUE TITLE
Font awesome not found 404 & Carousel

### ISSUE THREAD

**Issue by Vikas8881** [dotnetcore/BootstrapBlazor#249]
I try today latest version in web Assembly and there is show a 404 for font awesome file from the content.

2nd. Carousel have only width using only fixed number not support 100% or auto
3rd. The carousel does not support the Height

**Comment by Vision-Zhang** [comment]
Hi, @Vikas8881  Could you give a webAssembly demo to me for me or tell the steps to reproduce to me

**Comment by ArgoZhang** [comment]
@Vikas8881 sorry for the delayed reply. will update in the next release

**Comment by ArgoZhang** [comment]
@Vikas8881 hi, I quick look that it will use `100%`  if do not set the width value

**Comment by ArgoZhang** [comment]
@Vikas8881 update the `Width` parameter to string data type support `auto` `percentage`

link commit cfc805cf6bc5e820b5bca43e0eb83f6e8923d81d

**Comment by bigsinger** [comment]
参考： #1235  安装：BootstrapBlazor.FontAwesome
