### ISSUE TITLE
6.10.2版本menu样式bug

### ISSUE THREAD

**Issue by Tendx** [dotnetcore/BootstrapBlazor#250]
大佬们好~
我最近从6.9.x升级到最新的版本，发现Layout Side的menu样式有点小问题：
Side菜单项在网页全屏的时候（窗体达到一定宽度触发），鼠标hover menu的时候，宽度会增加。调整了下版本，发现问题从6.10.2版本开始出现。
![图片](https://user-images.githubusercontent.com/11781461/191719665-4ac16e17-dad6-4ed7-8dfb-0cbe4d33d555.png)
![图片](https://user-images.githubusercontent.com/11781461/191718879-e839aa29-eb75-4f9f-845c-5af6cf178b7e.png)

为了说明问题，我创建了一个默认的blazor server项目，按文档做了设置，只修改了MainLayout.razor为如下内容：

```
@inherits LayoutComponentBase

<PageTitle>BATest</PageTitle>

<div class="page">
    <Layout IsFullSide=true Menus=@MenuItems>
        <Side/>
        <Main>
            <div class="p-5">
                @Body
            </div>
        </Main>
    </Layout>
</div>


@code {
    private IEnumerable<MenuItem>? MenuItems { get; set; }

    protected override Task OnInitializedAsync()
    {
        MenuItems = new List<MenuItem>()
        {
            new ("设置", null, "fa-solid fa-gears")
            {
                Items  = new List<MenuItem>()
                {
                    new ("用户", "/Setting/User"),
                    new ("结点", "/Setting/Node"),
                }
            },
            new ("控制台", "Control", "fa-solid fa-terminal"),
        };
        return Task.CompletedTask;
    }
}
```
附件是项目打包：
[BATest.zip](https://github.com/dotnetcore/BootstrapBlazor/files/9624608/BATest.zip)

**Comment by ArgoZhang** [comment]
@Tendx 感谢提交 Issue 这个问题已经修复啦，更新到最新版本即可
