### ISSUE TITLE
feat(Slider): support Range attribute 

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#2541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

比如定义
```
    /// <summary>
    /// 单个条形的宽度,默认值：2 / Width,default: 2
    /// </summary>
    [DisplayName("宽度")]
    [Range(1, 6)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public int Width { get; set; } = 2;
```

`<Slider @bind-Value="Width"  />`

直接生成 

`<input type="range" id="bb_48299002_44428919_Width" class="form-range" min="1" max="6">`

而不需要写

`<Slider @bind-Value="Width" Min="1" Max="6" />`

**Comment by ArgoZhang** [comment]
@densen2014 安排
