### ISSUE TITLE
Camera component not work with Iphone/Ipad

### ISSUE THREAD

**Issue by Intekai** [dotnetcore/BootstrapBlazor#257]
Camera component not work with Iphone/Ipad

The screen is black i active camera and accept allow camera bit box is black

### Further technical details
- BootstrapBlazor version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by Intekai** [comment]
![image](https://user-images.githubusercontent.com/68114285/194338481-fa6939ad-6468-4e8d-84fc-3bb215b5772b.png)
i have tested it with iphone 7 and 13 screen black

**Comment by ArgoZhang** [comment]
@Intekai please have a try and choose the `Back` option. is it work?

**Comment by Intekai** [comment]
Yes I have test it but not workAntonio Tedesco -------- Messaggio originale --------Da: Argo Zhang ***@***.***>Data: gio 6 ott 2022, 16:27A: dotnetcore/BootstrapBlazor ***@***.***>Cc: Intekai ***@***.***>, Mention ***@***.***>Oggetto: Re: [dotnetcore/BootstrapBlazor] Camera component not work with Iphone/Ipad (Issue #257)
@Intekai please have a try and choose the Back option. is it work?

**Comment by Intekai** [comment]
i try it here: https://www.blazor.zone/Cameras  but not work with iphone, black screen

**Comment by ArgoZhang** [comment]
@Intekai  sorry that I am not reproing this issue. so I can't fix it.
