### ISSUE TITLE
After upgrading to version 8.* or above, the project cannot be opened with browsers such as Google dual-core

### ISSUE THREAD

**Issue by Dragon199308** [dotnetcore/BootstrapBlazor#2575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading to version 8.* or above, the project cannot be opened with browsers such as Google dual-core，Right now I'm stuck with Google and edge, but it's not always possible for people to use both

### Expected Behavior

The page failed to enter. Error: Assert failed: This browser/engine doesn't support WASM SIMD. Please use a modern version. See also https://aka.ms/dotnet-wasm-features

### .NET Version

8.*

**Comment by ArgoZhang** [comment]
@Dragon199308 hi, how to repro this issue?

**Comment by Dragon199308** [comment]
This error is a browser compatibility issue, the user can just change the browser, but this user experience is very poor. In order to open your web page users need to download a dedicated browser, which is not good.[ Google dual-core browser, kernel version: Chromium 86.0.4240.198 + IE (Trident 7~11)]

**Comment by ArgoZhang** [comment]
@Dragon199308 So what is the relationship with our `BootstrapBlazor` library

**Comment by Dragon199308** [comment]
The specific description is this
![1702542926147_A374906C-7FD1-4605-AE67-6B173B1F5959](https://github.com/dotnetcore/BootstrapBlazor/assets/33534706/69f73c2e-6780-44c0-818d-2355d75e1a29)

**Comment by ArgoZhang** [comment]
so where is our lib `BootstrapBlazor`?  I think you should go to the `dotnet` repo submit an issue
