### ISSUE TITLE
bug(Switch): Switch InvokeAsync to parent component with EventCallback blocks

### ISSUE THREAD

**Issue by rasmuschristensen** [dotnetcore/BootstrapBlazor#2595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

From the switch components OnValueChanged I try to call InvokeAsync on an EventCallback set from its parent. When ever I call InvokeAzync, the switch component stops updating its ui and its value does not change.

### Expected Behavior

I would expect I could trikker an eventcallback to communicate out from the component hosting the switch component

### .NET Version

net7.0

**Comment by rasmuschristensen** [comment]
Here is a component to test 
`<tr>
    <td class="p-0 row-select "></td>
    <td>
        @Name<br/>
        <span class="text-muted">
            <small>@Description</small>
        </span>
    </td>
    <td class="align-middle">
        <Switch OnColor="Color.Success" Value="@match" ValueChanged="Callback" OnValueChanged="OnValueChanged" ></Switch>
    </td>
    <td></td>
</tr>

@code {

    [Parameter]
    public string Name { get; set; }

    [Parameter]
    public string Description { get; set; }

    [Parameter]
    public AccessItemTypes AccessItemType { get; set; }

    [Parameter] public EventCallback<bool> OnConfirm { get; set; }

    [Parameter]
    public bool ItemValue { get; set; }
    
    private bool match { get; set; } = false;
    
    public override Task SetParametersAsync(ParameterView parameters)
    {
        match = parameters.GetValueOrDefault<bool>(nameof(ItemValue), false);
        return base.SetParametersAsync(parameters);
    }
    
    private Task OnValueChanged(bool arg)
    {
        System.Console.WriteLine($"OnValueChanged {arg}");
        return Task.FromResult(true);
        OnConfirm.InvokeAsync();
    }
    
    private void Callback(bool obj)
    {
        System.Console.WriteLine($"callback " + obj);
        match = obj;
    }
}`

**Comment by ArgoZhang** [comment]
@rasmuschristensen please provider mini repro project.

**Comment by ArgoZhang** [comment]
@rasmuschristensen no feedback. auto close this issue
