### ISSUE TITLE
在动态表格中，当我需要显示新的数据模型的数据表格时，如何清除原数据模型所定义的列？

### ISSUE THREAD

**Issue by SeptSkyTime** [dotnetcore/BootstrapBlazor#2626]
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/141984875/a96141fe-7431-49ec-9e20-a40c02822bcb)
如截图中所示，我尝试使用代码
tableRef.Columns.Clear();
实现清除功能，然而会导致任何动态列无法显示；
如果不添加上述代码，将会导致tableRef.Columns.Count不断增加，而且如果新的数据模型列数（假设有6列）少于老的数据模型列数（假设有10列）时，多出的4列定义仍然显示在新的表格页面中，请问这种问题如何解决？
问题截图如下所示：
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/141984875/4944af71-f582-48fa-ae5d-c102184dedc9)
谢谢！

**Comment by ArgoZhang** [comment]
@SeptSkyTime 你这个需求应该是动态列，动态对象的解决方案

参考示例 

https://www.blazor.zone/table/dynamic

https://www.blazor.zone/table/dynamic-object

**Comment by SeptSkyTime** [comment]
> @SeptSkyTime 你这个需求应该是动态列，动态对象的解决方案
> 
> 参考示例
> 
> https://www.blazor.zone/table/dynamic
> 
> https://www.blazor.zone/table/dynamic-object

感谢提示！
