### ISSUE TITLE
Keyboard navigation and selection to Select component

### ISSUE THREAD

**Issue by kaupov** [dotnetcore/BootstrapBlazor#263]
I'm trying to navigate through input elements with 'tab' key on keyboard, but it gets stuck on Select component. The focus won't move further from Select component.

Also keyboard selection from options is not working on Select component. E.g. I'm trying to select an option with arrow up/down on keyboard, but the selection does not change. Basically, missing the `<select>` tag behavior.

Maybe other form components are also missing this behavior but Select is the one we are currently dealing with.

**Comment by ArgoZhang** [comment]
@kaupov thanks for contacting us. do you want to auto-expand the dropdown menu when the `Select` component is focused?

**Comment by kaupov** [comment]
@ArgoZhang this is not default behavior of a `<select>` element but we actually could use that feature. If it would be configurable, then it would be perfect.

**Comment by ArgoZhang** [comment]
@kaupov sure! let me figure out it.

**Comment by ArgoZhang** [comment]
@kaupov I have some investigation for this. all of which are solutions for adding tab index. do you have any idea about this?
