### ISSUE TITLE
发现两个小bug

### ISSUE THREAD

**Issue by wapco** [dotnetcore/BootstrapBlazor#265]
问题一：
![QQ截图20221024110737](https://user-images.githubusercontent.com/29369553/197440952-380efe19-fd28-4ea4-bdfe-177c8d6f0ba3.png)
触发验证不通过事件后关闭窗口，控制台会报错

问题二：
![QQ截图20221024110853](https://user-images.githubusercontent.com/29369553/197441093-f0dcf8ae-4662-461c-9520-2ccd729a8e74.png)
下拉搜索功能不能用，输入字母或者删除的时候没反应。

另外下拉框如果内容很长，没办法自动设置宽度，导致下拉组件文字被覆盖
![5FEB7F96-C91A-4bcf-B2B7-149736642D51](https://user-images.githubusercontent.com/29369553/197441754-993cb5b9-dfbe-4f78-950f-d3629d1a9885.png)

bb版本：6.11.21

**Comment by ArgoZhang** [comment]
@wapco 已发布 `v6.11.22`
