### ISSUE TITLE
component DataProvider is never called

### ISSUE THREAD

**Issue by ntmessagebox** [dotnetcore/BootstrapBlazor#2653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Project created using Visual Studio 2022 Preview.

.NET ASPIRE SOLUTION
-> .NET 8 Blazor Web App (Auto mode) with sample components

<Sidebar @ref="sidebar"
         IconName="IconName.BootstrapFill"
         Title="Blazor Bootstrap"
         DataProvider="SidebarDataProvider" />

```
@code {
    Sidebar sidebar;
    IEnumerable<NavItem> navItems;

    private async Task<SidebarDataProviderResult> SidebarDataProvider(SidebarDataProviderRequest request)
    {
        if (navItems is null)
            navItems = GetNavItems();

        return await Task.FromResult(request.ApplyTo(navItems));
    }

    private IEnumerable<NavItem> GetNavItems()
    {
        navItems = new List<NavItem>
        {
            new NavItem { Href = "/getting-started", IconName = IconName.HouseDoorFill, Text = "Getting Started"},
            new NavItem { Href = "/alerts", IconName = IconName.CheckCircleFill, Text = "Alerts"},
            new NavItem { Href = "/autocomplete", IconName = IconName.InputCursorText, Text = "Auto Complete"},
            new NavItem { Href = "/breadcrumb", IconName = IconName.SegmentedNav, Text = "Breadcrumb"},
            new NavItem { Href = "/sidebar", IconName = IconName.LayoutSidebarInset, Text = "Sidebar"},
        };
        return navItems;
    }
}
```

This code produce this result : 

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/126427518/799c351e-0790-4dd0-a66e-24a0d126868e)

### .NET Version

.NET 8

**Comment by ntmessagebox** [comment]
Minimalistic repo project : https://github.com/ntmessagebox/BootstrapAspire

(It's not using Render mode auto but it's not also not working)

**Comment by ArgoZhang** [comment]
@ntmessagebox Hi. We not provider any component named of `Sidebar`. I think you created an Issue in the wrong repo
