### ISSUE TITLE
In select componen, can't enter text in search text 

### ISSUE THREAD

**Issue by Irajjj** [dotnetcore/BootstrapBlazor#266]
### Describe the bug
The 6.6.8 version worked fine for me, but since I update to 6.11.21, I can't enter text in search text  in select component.
Also, in www.blazor.zone/selects I don't see "OnSearchTextChanged" in the list of events, anymore.
I'm using multiselect component and it works fine for typing text. (the only problem with this component is that when I select a check box, the whole line becomes colored and the color of check boy is equal to the color of the whole line)

### To Reproduce

```
<Select TValue="string"
Items="serialParametersNew"
PlaceHolder="Not selected"
OnSelectedItemChanged="ParameterSelectedChange1"
@bind-Value="@ParameterSelected1"
ShowSearch="true"
OnSearchTextChanged="@OnSearch"></Select>

```

### Exceptions (if any)
I wish I can simply type and search for items.

### Further technical details
- BootstrapBlazor version 6.11.21
- .Net 6.0
- The IDE: VS 2022, 17.3.4

**Comment by ArgoZhang** [comment]
@Irajjj thanks for contacting us. please try the latest version `v6.11.22`
