### ISSUE TITLE
Grid component Single/DoubleClick

### ISSUE THREAD

**Issue by sezikpepa** [dotnetcore/BootstrapBlazor#2676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I use Grid component and have action for single click and different action for double click. When I double click the row, action for single click is triggered twice and then action for double click is triggered. (Properties OnRowDoubleClick and OnRowClick)

### Expected Behavior

I think the proper behaviour should be that only double click action si triggered on doubleclick.

### Steps To Reproduce

Create new Grid component, assign properties OnRowClick and OnRowDoubleClick. Double click on a line.

### .NET Version

8.0

**Comment by ArgoZhang** [comment]
@sezikpepa Thank you for contacting us. please provider a mini project
