### ISSUE TITLE
TabItem Key has removed 

### ISSUE THREAD

**Issue by Himaa-m0unir** [dotnetcore/BootstrapBlazor#270]
TabItem **Key attribute** has removed in updated version

**Comment by ArgoZhang** [comment]
@Himaa-m0unir hi sorry for the delayed reply. 

yes. the `key` parameter should not belong to the `TabItem`

**Comment by Himaa-m0unir** [comment]
How can identify the tabitem i use it and it was helpful

**Comment by ArgoZhang** [comment]
@Himaa-m0unir I will update a sample for this :)

**Comment by Himaa-m0unir** [comment]
Thank you for you usual support and rfforts

**Comment by ArgoZhang** [comment]
@Himaa-m0unir you are welcome. could you show me some code for this issue?

**Comment by Himaa-m0unir** [comment]
Here is sample and the key property is very usefulWhen user click/switch the tab I want to know which key is clicked (as ENUM) instead of textI think it is better also so please keep it in next release  Sent from Mail for Windows From: Argo ZhangSent: Saturday, November 5, 2022 7:48 PMTo: dotnetcore/BootstrapBlazorCc: The Unknown Master; MentionSubject: Re: [dotnetcore/BootstrapBlazor] TabItem Key has removed (Issue ***@***.*** you are welcome. could you show me some code for this issue?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ArgoZhang** [comment]
@Himaa-m0unir can't read it

**Comment by Himaa-m0unir** [comment]
This is an example of usage what you cant read ?

**Comment by ArgoZhang** [comment]
@Himaa-m0unir what's mean for 

```
<!--
/* Font Definitions */
[@font-face](https://github.com/font-face)
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
[@font-face](https://github.com/font-face)
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
[@page](https://github.com/page) WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.25in 1.0in 1.25in;}
div.WordSection1
	{page:WordSection1;}
-->
```

I really don't understand this.
