### ISSUE TITLE
can't localize BootstrapBlazor.Components.TableFilter

### ISSUE THREAD

**Issue by Dimasikkk1** [dotnetcore/BootstrapBlazor#2707]
### Which class is this unit test associated with?

For some reason, IStringLocalizer<BootstrapBlazor.Components.TableFilter> does not find and localize my lines in ru.json.

> {
  "BootstrapBlazor.Components.TableFilter": {
    "ClearButtonText": "Сброс",
    "FilterButtonText": "Фильтр",
    "BoolFilter.AllText": "Все",
    "BoolFilter.TrueText": "True",
    "BoolFilter.FalseText": "False",
    "GreaterThanOrEqual": "GreaterThanOrEqual",
    "LessThanOrEqual": "LessThanOrEqual",
    "GreaterThan": "GreaterThan",
    "LessThan": "LessThan",
    "Equal": "Equal",
    "NotEqual": "NotEqual",
    "Contains": "Contains",
    "NotContains": "NotContains",
    "EnumFilter.AllText": "All",
    "NotSupportedMessage": "Unsupported filter type, Please customize the filter use FilterTemplate"
  }
}

My test repo: [https://github.com/Dimasikkk1/MP1TestRepo](https://github.com/Dimasikkk1/MP1TestRepo)
I use BootstrapBlazor 8.0.7-beta03

**Comment by ArgoZhang** [comment]
@Dimasikkk1 could you provider a mini-project for repro this issue?

**Comment by ArgoZhang** [comment]
@Dimasikkk1 

```

builder.Services.AddBootstrapBlazor(localizationConfigure: options =>
{
    options.AdditionalJsonAssemblies = [typeof(App).Assembly];
});
```

**Comment by ArgoZhang** [comment]
@Dimasikkk1 

The next version will not need to add this. `v8.0.7`

**Comment by ArgoZhang** [comment]
@Dimasikkk1 you can upgrade the package to v8.1.0
