### ISSUE TITLE
datetimepicker cannot select another month after binded value

### ISSUE THREAD

**Issue by dsdruby** [dotnetcore/BootstrapBlazor#271]
### Describe the bug
datetimepicker cannot select another month after binded value

<DateTimePicker TValue="DateTime?" Format="yyyy-MM-dd" @bind-Value="@dt" />

**Comment by ArgoZhang** [comment]
@dsdruby hi. sorry for the delayed reply. I will repro this issue.

**Comment by ArgoZhang** [comment]
@dsdruby sorry for the delayed reply. please provide a repro sample code. there is no repro in my code.

**Comment by dsdruby** [comment]
i provided the source code already. 

 <DateTimePicker TValue="DateTime?" Format="yyyy-MM-dd" @bind-Value="@dt" />

You can paste it in a razor page and run it. You try to click the datetimepicker control and the calendar will be prompted out. 
By default, the calendar will show the month of @dt. At that time, you try to click "<" or ">" to select another month. you will see it is unable to do so. The calendar will stay at the month of @dt and will not switch to another month.

**Comment by ArgoZhang** [comment]
@dsdruby not repro

```
<DateTimePicker TValue="DateTime?" Format="yyyy-MM-dd" @bind-Value="@dt" />

@code {
    private DateTime? dt { get; set; }
}
```

it works fine in my code. so I think maybe something is wrong with your project. I want to help you if you can provide a complete project.

**Comment by dsdruby** [comment]
protected override async Task OnAfterRenderAsync(bool firstRender)
 {
 StateHasChanged();
}

after invoked StateHasChanged();, this issue will occur
