### ISSUE TITLE
When opening a Model or ImageViewer to view a larger image. When the browser rolls back to the previous page, these layers do not close.

### ISSUE THREAD

**Issue by tpnest** [dotnetcore/BootstrapBlazor#272]
### Describe the bug
When opening a Modal or ImageViewer to view a larger image. When the browser rolls back to the previous page, these layers do not close.

### To Reproduce

![image](https://user-images.githubusercontent.com/57797158/199906290-89d5ff2b-7e1f-4502-9971-3fd0094a1fb9.png)

How can this problem be solved 
请问如果想在返回时关闭这个弹层应该怎么做呢？英语不好请见谅
### Further technical details
- BootstrapBlazor version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by densen2014** [comment]
都是华人可以用的汉语的 ：）

**Comment by ArgoZhang** [comment]
@tpnest 已修复晚点发布新版本

**Comment by ArgoZhang** [comment]
@tpnest 已修复 v7.0.0
