### ISSUE TITLE
Table 的明细行如何通过点击当前行展开或关闭，而不是点击展开关闭图标。

### ISSUE THREAD

**Issue by wangfei9999** [dotnetcore/BootstrapBlazor#2749]

**Comment by wangfei9999** [comment]
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/73685882/e9c988b9-3b00-4995-819c-0587b2b38f0e)

**Comment by ArgoZhang** [comment]
这个需要自己写个 JS 来完成，目前组件展开都是用图标来实现的

**Comment by ArgoZhang** [comment]
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/22001478/68917bde-97ed-43a4-8a67-16c9cbcb6dcb)
