### ISSUE TITLE
datetimepicker cannot select another month after binded value

### ISSUE THREAD

**Issue by dsdruby** [dotnetcore/BootstrapBlazor#276]
protected override async Task OnAfterRenderAsync(bool firstRender)
 {
 StateHasChanged();
}

after invoked StateHasChanged();, this issue will occur

_Originally posted by @dsdruby in https://github.com/dotnetcore/BootstrapBlazor/issues/271#issuecomment-1319723934_

**Comment by densen2014** [comment]
Todo bien, no hay error

1. dotnet new install Bootstrap.Blazor.Templates::*
2. dotnet new bbapp
3. cd BootstrapBlazorApp.Server and modify code with this 

file `BootstrapBlazorApp.Shared\Pages\Index.razor'
```
@page "/"
@attribute [TabItemOption(Text = "Index", Closable = false)]
<PageTitle>Index</PageTitle>

<h1>Hello, blazor! @flag</h1>

<div class="row">
    <div class="col-sm-4">
        <DateTimePicker TValue="DateTime" Value="@DateTime.Today" />
    </div>
</div>

@code{
    string flag="step 0";
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        flag="step 1";
        StateHasChanged();
    }
}
```

4. dotnet watch
5. my codes is here [demo.zip](https://github.com/dotnetcore/BootstrapBlazor/files/10040754/demo.zip)

i think totally ok.
