### ISSUE TITLE
feat(input): input公开Type属性和加个正则

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#2769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

比如 inputnumber 有时候要全数字键盘, 有时候只要电话键盘, 有时候要有小数点的键盘, type 就要暴露出来设置键盘属性才行, 然后电话号码之类输入可以正则限制一下

**Comment by ArgoZhang** [comment]
@densen2014 已内置支持

```
<BootstrapInput type="phone" pattern=".+?" />
```
