### ISSUE TITLE
文件上传组件如何在上传成功处理回调函数，把进度条删除掉

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#278]
目前是上传成功后，会一直在下面追加列表，不太美观，想设置上传成功后自动隐藏掉进度条，上传过程中还是要看下进度条的。

**Comment by ArgoZhang** [comment]
@bigsinger 可参考模板完善 Issue 目前描述过于简单，无法理解并且提供功能，或者提交 PR 更好
