### ISSUE TITLE
BootstrapInputNumber： After verifying the type, the numerical value was modified, but the error status was not changed.

### ISSUE THREAD

**Issue by Dragon199308** [dotnetcore/BootstrapBlazor#2783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/33534706/5d6e1a5b-deb5-43da-acad-9dc1bb9c8c50)

then...

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/33534706/9e5832e6-013d-425e-9eec-71b695f76f92)

### Expected Behavior

When I set the data type to int and input a decimal point, the data is converted to an integer, but the error message still appears. The model authentication error persists, and when I click save, the error message "number type error" still appears.

### Exceptions (if any)

 >>>>>> Here's my code:

<ValidateForm Model="@Model" OnValidSubmit="OnSaveAsync">
    <div>
        <div class="col-12 col-sm-12">
            <Select ShowLabel="true" TValue="int" @bind-Value="@Model.CategoryId" Items="CategoryItems" />
        </div>
        <div class="col-12 col-sm-12">
            <BootstrapInput ShowLabel="true" @bind-Value="@Model.Title" maxlength="500" />
        </div>
        <div class="col-12 col-sm-12"> 
            <Editor @bind-Value="@(Model.Content)" IsEditor="true"  PlaceHolder="" Height="300"></Editor>  
        </div>
        <div class="col-12 col-sm-12">   
            <Upload ShowProgress="true" IsMultiple="false" IsSingle="true" ShowLabel="false"
                           MaxFileSize="10MB" MaxImageSize="10MB" Accept=".xlsx;*.xls;*.doc;*.docx;*.pdf" @bind-Value="@Model.FilePath" />
        </div>
        <BootstarpFormText ClassName="text-danger" Text="AttatchmentFileTip"></BootstarpFormText>
        <div class="col-12 col-sm-12">  
            <BootstrapInput ShowLabel="true" TValue="int" @bind-Value="@Model.OrderId" maxlength="6" />
           <BootstrapInputNumberShowLabel="true"  @bind-Value="@Model.OrderId"  /> 
        </div>
    </div>
   
    <div class="form-footer">
        <DialogCloseButton IsAsync="true" />
        <DialogSaveButton />
    </div> 
</ValidateForm> 

@code {

    [Parameter]
    [NotNull]
    public HelpSubjectSummaryDTO Model { get; set; } = new HelpSubjectSummaryDTO();

    [Parameter]
    [NotNull]
    public List<SelectedItem> CategoryItems { get; set; } 

    [Inject]
    [NotNull]
    private ISmartlifeApi? SmartlifeApi { get; set; }

    [Inject]
    [NotNull]
    private TipsMessage? TipsMessage { get; set; }

    [Parameter]
    public Func<Task>? OnSaveButtonClick { get; set; }

    [CascadingParameter]
    private Func<Task>? OnCloseAsync { get; set; }

    private bool IsAdd { get; set; } = true;
     
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        
    }

    private bool CheckFilePath(string filePath)
    {
        if (filePath.IsNullOrEmpty()) return true;
 
        return false; 
    }

    private async Task OnSaveAsync(EditContext context)
    {
        var success = true;
       
    }
     
}

### .NET Version

8.*

**Comment by densen2014** [comment]
hi，show your codes please

**Comment by Dragon199308** [comment]
> hi，show your codes please
ok


<ValidateForm Model="@Model" OnValidSubmit="OnSaveAsync">
    <div class="@StyleUtils.CultureFormClassString">
        <div class="col-12 col-sm-12">
            <Select ShowLabel="true" TValue="int" @bind-Value="@Model.CategoryId" Items="CategoryItems" />
        </div>
        <div class="col-12 col-sm-12">
            <BootstrapInput ShowLabel="true" @bind-Value="@Model.Title" maxlength="500" />
        </div>
        <div class="col-12 col-sm-12"> 
            <Editor @bind-Value="@(Model.Content)" IsEditor="true"  PlaceHolder="" Height="300"></Editor>  
        </div>
        <div class="col-12 col-sm-12">   
            <Upload ShowProgress="true" IsMultiple="false" IsSingle="true" ShowLabel="false"
                           MaxFileSize="10MB" MaxImageSize="10MB" Accept=".xlsx;*.xls;*.doc;*.docx;*.pdf" @bind-Value="@Model.FilePath" />
        </div>
        <BootstarpFormText ClassName="text-danger" Text="AttatchmentFileTip"></BootstarpFormText>
        <div class="col-12 col-sm-12">  
            <BootstrapInput ShowLabel="true" TValue="int" @bind-Value="@Model.OrderId" maxlength="6" />
     OR
          <BootstrapInputNumberShowLabel="true"  @bind-Value="@Model.OrderId"  />
 
        </div>
    </div>
   
    <div class="form-footer">
        <DialogCloseButton IsAsync="true" />
        <DialogSaveButton />
    </div> 
</ValidateForm>

**Comment by Dragon199308** [comment]
> hi，show your codes please

ok

<ValidateForm Model="@Model" OnValidSubmit="OnSaveAsync">
    <div>
        <div class="col-12 col-sm-12">
            <Select ShowLabel="true" TValue="int" @bind-Value="@Model.CategoryId" Items="CategoryItems" />
        </div>
        <div class="col-12 col-sm-12">
            <BootstrapInput ShowLabel="true" @bind-Value="@Model.Title" maxlength="500" />
        </div>
        <div class="col-12 col-sm-12"> 
            <Editor @bind-Value="@(Model.Content)" IsEditor="true"  PlaceHolder="" Height="300"></Editor>  
        </div>
        <div class="col-12 col-sm-12">   
            <Upload ShowProgress="true" IsMultiple="false" IsSingle="true" ShowLabel="false"
                           MaxFileSize="10MB" MaxImageSize="10MB" Accept=".xlsx;*.xls;*.doc;*.docx;*.pdf" @bind-Value="@Model.FilePath" />
        </div>
        <BootstarpFormText ClassName="text-danger" Text="AttatchmentFileTip"></BootstarpFormText>
        <div class="col-12 col-sm-12">  
            <BootstrapInput ShowLabel="true" TValue="int" @bind-Value="@Model.OrderId" maxlength="6" />
     OR
          <BootstrapInputNumberShowLabel="true"  @bind-Value="@Model.OrderId"  />
 
        </div>
    </div>
   
    <div class="form-footer">
        <DialogCloseButton IsAsync="true" />
        <DialogSaveButton />
    </div> 
</ValidateForm> 


@code {

    [Parameter]
    [NotNull]
    public HelpSubjectSummaryDTO Model { get; set; } = new HelpSubjectSummaryDTO();

    [Parameter]
    [NotNull]
    public List<SelectedItem> CategoryItems { get; set; } 

    [Inject]
    [NotNull]
    private ISmartlifeApi? SmartlifeApi { get; set; }

    [Inject]
    [NotNull]
    private TipsMessage? TipsMessage { get; set; }

    [Parameter]
    public Func<Task>? OnSaveButtonClick { get; set; }

    [CascadingParameter]
    private Func<Task>? OnCloseAsync { get; set; }

    private bool IsAdd { get; set; } = true;
     
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        
    }

    private bool CheckFilePath(string filePath)
    {
        if (filePath.IsNullOrEmpty()) return true;
 
        return false; 
    }

    private async Task OnSaveAsync(EditContext context)
    {
        var success = true;
       
    }
     
}

**Comment by Dragon199308** [comment]
> hi，show your codes please
Here's my code

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/33534706/59e7c527-cfcc-444b-9b48-0666435c917b)

**Comment by Dragon199308** [comment]
> hi，show your codes please

**<BootstrapInputNumberShowLabel="true"  @bind-Value="@Model.OrderId"  />** 

The same is true with this component

**Comment by ArgoZhang** [comment]
@Dragon199308 please upload repro demo mini-project

**Comment by ArgoZhang** [comment]
无反馈，自动关闭
