### ISSUE TITLE
recommended to add fluent validation to the ValidateForm component

### ISSUE THREAD

**Issue by dsdruby** [dotnetcore/BootstrapBlazor#279]
**recommended to add fluent validation to the framework**

sometimes, the default data annotation validator provided by .net core is not powerful enough to validate the complex model with collections and dynamic model. I tried to adopt the [Blazored.FluentValidation](https://github.com/Blazored/FluentValidation) to my application. 
Since ValidateForm has already included the data annotation validator, there is no way to disable it. 

and I tried to use back the original EditForm component. It works fine with all .net blazor compoents but not for the input components provided by your blazor framework. The validated items such as datetimepicker, checkbox are not able to display properly with valid or invalid css class. it would be great if you can include it. Thanks!

**Comment by ArgoZhang** [comment]
@dsdruby hi. thanks for the suggestion. could you provide a sample code?
