### ISSUE TITLE
Table - Selection 顯示問題

### ISSUE THREAD

**Issue by a0926019412** [dotnetcore/BootstrapBlazor#2805]
### Which class is this unit test associated with?

想請問 我想要從別的事件引發tablerow的勾選
我試了在button click事件中嘗試了以下code
table.SelectedRows.AddRange(table.Items);

我看物件裡面是有的, 但是畫面上沒有顯示勾選 (當然 有設定multiselect="true")
我試過呼叫table.QueryAsync 以及StateHasChange , 但畫面上沒有更新

請問目前元件有提供這樣的應用嗎?

**Comment by densen2014** [comment]
有例子的。

**Comment by a0926019412** [comment]
@densen2014 範例上的例子都是可以work的, 如果是放在initialize預設勾選 , 或button event 下clear 都顯示正常
但button event下加入勾選的項目就沒作用
有試過@bind-SelectedRows="SelectedItems",  對SelectedItems 新增資料 , 也試過@ref="table", table.SelectedItems 新增資料 
畫面上並沒有顯示勾選

如果需要更詳細的資料, 在跟我說一下 , 我再貼原始碼&畫面

**Comment by ArgoZhang** [comment]
不能使用 `table.SelectedItems` 用双绑才可以

**Comment by a0926019412** [comment]
您好 不好意思 是我自己程式的bug
剛試過是可以正常運行的, 感謝你們回應
