### ISSUE TITLE
Move the field attribute to a seperate metadata type

### ISSUE THREAD

**Issue by cairabbit** [dotnetcore/BootstrapBlazor#2868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently, when using `AutoGenerateColumn` attribute to auto generate the columns in table, this attribute needs to be put in the Model class. However, ususally, the model/dto classes are at other shared library which could be used in both api side and client side. Or we use a 3rd party model classes. In this case, it's better to allow user add metadata type on the fly and then register(bind) it to a model type. This way, user can separate the model type with UI definition metadata type.

### Describe the solution you'd like

the existing model class may look like:

```
public class Foo
{
    // 列头信息支持 Display DisplayName 两种标签

    /// <summary>
    /// 主键
    /// </summary>
    [Key]
    [Display(Name = "主键")]
    [AutoGenerateColumn(Ignore = true)]
    public int Id { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    [Required(ErrorMessage = "{0}不能为空")]
    [AutoGenerateColumn(Order = 10, Filterable = true, Searchable = true)]
    [Display(Name = "姓名")]
    public string? Name { get; set; }
    
    ...
}
```

The solution could be:
```
// Foo class is in Common library, which is used in Biz layer, Api web project and UI web project
public class Foo
{
    /// <summary>
    /// 主键
    /// </summary>
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    [Required(ErrorMessage = "{0}不能为空")]
    public string? Name { get; set; }
    
    ...
}

[UIMetadataFor(typeof(Foo))] // this can be either a class attribute, or somewhere we can bind it to the model class
public class FooMetadata
{
    [Display(Name = "主键")]
    [AutoGenerateColumn(Ignore = true)]
    public int Id { get; set; }

    [AutoGenerateColumn(Order = 10, Filterable = true, Searchable = true)]
    [Display(Name = "姓名")]
    public string? Name { get; set; }
}
```

**Comment by ArgoZhang** [comment]
@cairabbit Thank you for contacting us. This is a good idea. Can you submit a PR to implement this feature?

**Comment by cairabbit** [comment]
Hi, Has this under development? Otherwise, I'm happy to do this. For now, I haven't done anything yet but if I'm happy to do this. Hope I can make it before the milestone v8.2.0. Let me know if you still need a hand. Thanks.

**Comment by densen2014** [comment]
hi，Just reference the component library in your project,UI component file size just a little. There are currently no plans to extract features into a standalone shared library.

**Comment by ArgoZhang** [comment]
@cairabbit Thank you very much for your reply. I am very proud that you have participated in our project. This month is the Spring Festival in China, so I am very busy. I am looking forward to your help with this feature

**Comment by cairabbit** [comment]
@ArgoZhang Happy Chinese New Year. I'm also a Chinese. :) .Thanks for your invitation. I'll start working on this feature. I'll keep you update.

**Comment by densen2014** [comment]
可以考虑这几个特性 (AutoGenerateClass, AutoGenerateColumn..) 抽成 abstract,单独一个包 BootstrapBlazor.Abtracts.dll
