### ISSUE TITLE
feat(Toast): add PreventDuplicates option to Toast options

### ISSUE THREAD

**Issue by HarpunDK** [dotnetcore/BootstrapBlazor#2869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Hi, I would love to see an option to the Toast configuration, with the possibility to add PreventDuplicates.

When showing multiple toastr, the possibility with PreventDuplicates is ON, is for the software to check if an existing Toast with title already are being displayed, then block for duplicate toastr to be visible.

Case: Client pushes button and button is blocked in the backend, displaying "access denied" as a toast with 5 seconds time of visibility, then user keep pushing the button - which will result in multiple toastr being displayed and flooding the view. 

Let me know if you need further information. I know several other implementation of toast's have this option.

**Comment by ArgoZhang** [comment]
@HarpunDK I personally think using Swal is more suitable for this scenario

**Comment by HarpunDK** [comment]
Hi, thank you for your quick response. I am aware of sweet-alart. In my case, to be more specific, it happens when a user refreshes a collection of items. The update event, which triggers and "long-running" toast, then the user refreshes again and a new "duplicate" is shown. 
It is okay if you Swal more suitable. But Toast are a good non-blocking functionality, like pushing updates or confirmations.

**Comment by ArgoZhang** [comment]
@HarpunDK ok. add a parameter `PreventDuplicates` on `Toast` component. the default value is `false`.

**Comment by ArgoZhang** [comment]
@HarpunDK hi. I have made some updates to meet your requirements. 

```
private async Task Show(ToastOption option)
{
    if (option.PreventDuplicates)
    {
        var lastOption = Toasts.LastOrDefault();
        if (lastOption == null || CompareOption(option, lastOption))
        {
            return;
        }
    }
    Toasts.Add(option);
    await InvokeAsync(StateHasChanged);
    return;

    bool CompareOption(ToastOption source, ToastOption target) => source.Title == target.Title && source.Content == target.Content;
}
```

if you use the `ChildContent` template. the parameter `PreventDuplicates`  will not work

**Comment by ArgoZhang** [comment]
@HarpunDK 

please double check http://www.blazor.zone/toast#PreventDuplicates

**Comment by HarpunDK** [comment]
Hi @ArgoZhang, I've installed the preview and found the PreventDuplicates option. I've tested and it solved my _issue_. TY for you quick reaction!

**Comment by ArgoZhang** [comment]
@HarpunDK thank you for your reply. could you give this project a star?
