### ISSUE TITLE
bug(): Modal 组件使用Ctl+F5刷新后 出现错误

### ISSUE THREAD

**Issue by mk7710** [dotnetcore/BootstrapBlazor#2884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

当我在页面中添加<Modal>
    <ModalDialog>

    </ModalDialog>
</Modal>组件，![EBFNOQMSD3ZBBAJ7_WF%KGI](https://github.com/dotnetcore/BootstrapBlazor/assets/58585504/7e7ba00a-71b0-4c1b-b502-aaa5cf8eca07)
![EBFNOQMSD3ZBBAJ7_WF%KGI](https://github.com/dotnetcore/BootstrapBlazor/assets/58585504/318ae033-2d3d-4fa9-ba81-49bed5202b93)

**Comment by ArgoZhang** [comment]
@mk7710 更新到最新试一下可以吗？

**Comment by ArgoZhang** [comment]
@mk7710 无反馈自动关闭
