### ISSUE TITLE
Modal not clearing/setting correct state after close combined with NavigationManager.NavigateTo

### ISSUE THREAD

**Issue by HarpunDK** [dotnetcore/BootstrapBlazor#2941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using Modal and using Show and Close methods. After close, with 'await', then using: NavigationManager.NavigateTo("/Counter");

The scollbar is locked on the next page. Scrollbar keeps state: overflow: hidden and body keeps: class="modal-open"

![2024-02-13_11-05-40](https://github.com/dotnetcore/BootstrapBlazor/assets/8235893/587113fa-1995-4d1c-9304-0699a9a54f42)

### Expected Behavior

After call .Close() on Modal, I would expect body-section to be "released" from Modal-state.
I could be using it all wrong. Would very much like to hear your opinion.

### Steps To Reproduce

[BlazorApp2.zip](https://github.com/dotnetcore/BootstrapBlazor/files/14259472/BlazorApp2.zip)

Start the application.
Navigate to: /   (Home)
Scroll to bottom and Click the button; "Show dialog..."
- Dialog will then show for 3 seconds.
- Page will then redirect to "/Counter"

You will notice, that scrollbar is locked and if you inspect the page, you will find body have attributes like: 
![2024-02-13_11-05-40](https://github.com/dotnetcore/BootstrapBlazor/assets/8235893/587113fa-1995-4d1c-9304-0699a9a54f42)

Hope this makes sense, let me know if you need further information.

### .NET Version

8

**Comment by ArgoZhang** [comment]
@HarpunDK Hi

```
private async Task ShowDialog()
{
    await modalRef.Show();
    await Task.Delay(3_000);
    await modalRef.Close();
    
    await Task.Delay(300);
    NavigationManager.NavigateTo("/Counter");
}
```

you can add `await Task.Delay(300)` before navigation.

i will move the delay into `Close` method in the next release.

**Comment by HarpunDK** [comment]
Thank you, I will try it out right now!

**Comment by HarpunDK** [comment]
Sorry for the inconvenience. That did the trick.

**Comment by ArgoZhang** [comment]
@HarpunDK hi. i had release `8.2.4-beta01`

```
<Modal @ref="modalRef" OnCloseAsync="OnCloseAsync">
    <ModalDialog IsCentered="true" IsDraggable="false" IsScrolling="true" ShowCloseButton="false" ShowFooter="false" ShowHeaderCloseButton="false" ShowHeader="false" Size="Size.Large">
        <BodyTemplate>
            GRRRRRR <br />
            GRRRRRR <br />
            GRRRRRR <br />
            GRRRRRR <br />
            Some content here - we will wait 3 seconds.
        </BodyTemplate>
    </ModalDialog>
</Modal>
```

```
@code
{
    private Modal modalRef = default!;

    private async Task ShowDialog()
    {
        await modalRef.Show();
        await Task.Delay(3_000);
        await modalRef.Close();
    }

    private Task OnCloseAsync()
    {
        NavigationManager.NavigateTo("/Counter");
        return Task.CompletedTask;
    }
}
```

recommendation use `OnCloseAsync` callback on `Modal`.

Because the `Close` method will trigger the client **javascript Close** method, which has a transition animation delay of approximately 150 milliseconds and triggers the OnCloseAsync callback after the animation ends.
