### ISSUE TITLE
Table: 新建选项卡里面控件无法根据代码重绘

### ISSUE THREAD

**Issue by xunmeng2002** [dotnetcore/BootstrapBlazor#2982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

我这里通过Select来控制两个div 的显示，这两个div中分别有一个 CheckboxList，
当改变Select选项为ShowNone时，两个CheckboxList均不显示，
当改变Select选项为ShowNumber时，显示数字的 CheckboxList，
当改变Select选项为ShowZodiac时，显示汉字的CheckboxList。
在页面中直接放置这几个控件，这一机制成功；
在Table组件的 EditTemplate 中放置这几个控件，单击新建按钮，然后改变选弹出页面中的Select选择值，发现弹出的新建窗口不会随着选项的改变而重新绘制。

### Expected Behavior

希望Table组件的新建页面中控件元素能够根据代码即时响应

### Steps To Reproduce

[TestBootstrapBlazor.zip](https://github.com/dotnetcore/BootstrapBlazor/files/14371235/TestBootstrapBlazor.zip)

### .NET Version

net8.0

### Anything else?

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/7625156/ddbdb35f-0d5e-4dc4-ba24-fe8183d4f1af)
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/7625156/56f4c42d-5f22-4e01-9dec-e5340fea9c83)

**Comment by densen2014** [comment]
加群 795206915。 封装成组件就能自己刷了，因为那个是模板，所以无法刷状态Densen informatica在 2024年2月22日，09:52，bb-auto[bot] ***@***.***> 写道：﻿
@xunmeng2002 Thank you for reporting. We will give triage later.

**Comment by xunmeng2002** [comment]
谢谢，我去试试

**Comment by xunmeng2002** [comment]
封装组件后确实可以刷新，感谢大佬
