### ISSUE TITLE
Table 放在 Dialog中时，过滤功能无法输入

### ISSUE THREAD

**Issue by mswang2005** [dotnetcore/BootstrapBlazor#303]
Table 放在 Dialog中时，过滤功能无法输入
![新建位图图像](https://user-images.githubusercontent.com/23739744/206452167-698f1482-0687-4608-b585-230bc2805bad.jpg)

**Comment by ArgoZhang** [comment]
@mswang2005 正在修复中 ...

**Comment by ArgoZhang** [comment]
@mswang2005 已修复，发布 `v7.1.5`
