### ISSUE TITLE
在Table的CustomerSearchTemplate内使用DateTimePicker组件，无法清空所选日期

### ISSUE THREAD

**Issue by hejinda** [dotnetcore/BootstrapBlazor#304]
在Table的CustomerSearchTemplate内使用DateTimePicker组件，无法清空所选日期
代码如下：
&lt;CustomerSearchTemplate>
                    <DateTimePicker TValue="DateTime?" @bind-Value="@CustomerSearchModel.Time"  />
&lt;/CustomerSearchTemplate>

**Comment by ArgoZhang** [comment]
@hejinda  提供复现工程

**Comment by hejinda** [comment]
[Test.zip](https://github.com/dotnetcore/BootstrapBlazor/files/10305502/Test.zip)

复现工程见压缩包，导航到/test，进入高级搜索，里面的日期组件，无法清空。

**Comment by ArgoZhang** [comment]
@hejinda 可以清空，点击 reset

**Comment by ArgoZhang** [comment]
@hejinda 模板中包裹到一个新的组件内，组件内刷新即可解决问题
