### ISSUE TITLE
table search case sensitive

### ISSUE THREAD

**Issue by mozahr** [dotnetcore/BootstrapBlazor#3041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Search in the Table is case sensitive, tried to use LookupStringComparison with OrdinalIgnoreCase but did not work.
Any idea how to use search without case sensitive?

**Comment by ArgoZhang** [comment]
@mozahr please provide a mini-project for repro this issue.

**Comment by ArgoZhang** [comment]
duplicate #2483
