### ISSUE TITLE
overflow-hidden on the body of the page

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#305]
Hi, since that I updated for 7.1.0 version, I saw that I started have problems with the overflow, when I look at the code, I saw that the problem is because this version is putting a class overflow-hidden on the tag body of the page.
Theres some reason for do this?
Thank you very much

**Comment by gmondin** [comment]
hi @ArgoZhang , Is it on drawer component, is keeping the overflow-hidden if inside of the drawer I'm redirect to other page.
If I only close the the drawer is working really well.

**Comment by gmondin** [comment]
hi @ArgoZhang looking in your project, I think that is something in the class drawer.js that

**Comment by gmondin** [comment]
Hi, @ArgoZhang For you know, I just create a function that take out the overflow-hidden class from body when I close the drawer and its work normally now.

**Comment by ArgoZhang** [comment]
> hi @ArgoZhang , Is it on drawer component, is keeping the overflow-hidden if inside of the drawer I'm redirect to other page. If I only close the the drawer is working really well.

yes. this is an issue.

**Comment by ArgoZhang** [comment]
> Hi, @ArgoZhang For you know, I just create a function that take out the overflow-hidden class from body when I close the drawer and its work normally now.

yes. you have to call the `Close` before navigating to the other pages

**Comment by ArgoZhang** [comment]
@gmondin hi. I have released `v7.1.8-beta01` can you have a try? I think this issue has been fixed.

**Comment by gmondin** [comment]
> @gmondin hi. I have released `v7.1.8-beta01` can you have a try? I think this issue has been fixed.

Hi @ArgoZhang its working now, thank you very much
