### ISSUE TITLE
demo 网站上用平板浏览时的问题

### ISSUE THREAD

**Issue by Jason190** [dotnetcore/BootstrapBlazor#309]
https://www.blazor.zone/
使用小米平板电脑Android12浏览
点击演示内容后，比如说select中的下拉文本框，左侧的导航栏不能滚动，怎么搞都是滚动右边的内容栏，再次点击左侧菜单可以恢复滚动
怀疑是失去焦点，导致菜单栏不能正常滚动
不确定是Demo网站的问题还是组件库问题

**Comment by ArgoZhang** [comment]
@Jason190 无截图，无示例代码，不太好回答
