### ISSUE TITLE
feat(Gantt): support localization

### ISSUE THREAD

**Issue by cetinbas** [dotnetcore/BootstrapBlazor#3114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am seeing month names in Chinese in Gantt, while using en-US culture.
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/5260245/92c2260f-1783-4fd0-b3d1-7d9059efbbe8)

### Expected Behavior

Month names should appear in English

### Steps To Reproduce

- Visit the Gantt example URL: https://www.blazor.zone/gantt
- Language of the example is set to English.
- My OS culture is en-US.
- I see the same result both on the URL above and in my local build.

### .NET Version

8.0.202

**Comment by ArgoZhang** [comment]
link discussion #3111
