### ISSUE TITLE
Warning when installing or updating template

### ISSUE THREAD

**Issue by NullDict** [dotnetcore/BootstrapBlazor#3136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When installing or updating Bootstrap.Blazor.Templates, dotnet warns that "The following templates use the same identity 'BootstrapBlazorWebApp'."  and said there is a conflict. 
Although this has not caused any usability trouble, I think this may not be an expected behavior of the package.

here is the log:
 dotnet new install Bootstrap.Blazor.Templates::*
The following template packages will be installed:
   Bootstrap.Blazor.Templates::*

Warning:
The following templates use the same identity 'BootstrapBlazorWebApp':
  ? 'Bootstrap Blazor Web App Auto(Global)' from 'Bootstrap.Blazor.Templates::8.1.4'
  ? 'Bootstrap Blazor Web App Auto(Per page/component)' from 'Bootstrap.Blazor.Templates::8.1.4'
The template from 'Bootstrap Blazor Web App Auto(Per page/component)' will be used. To resolve this conflict, uninstall the conflicting template packages.
Success: Bootstrap.Blazor.Templates::8.1.4 installed the following templates

### Expected Behavior

No conflict warn,  I guess.

### Steps To Reproduce

Just run dotnet new install Bootstrap.Blazor.Templates::* in the dotnet 8 environment where the template is not installed.

### .NET Version

8.0.201

### Anything else?

 dotnet --info
.NET SDK:
 Version:           8.0.201
 Commit:            4c2d78f037
 Workload version:  8.0.200-manifests.5638171e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.201\

.NET workloads installed:
 [wasm-tools]
   Installation Source: SDK 8.0.200
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.2\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.101 [C:\Program Files\dotnet\sdk]
  8.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by ArgoZhang** [comment]
@NullDict release `v8.1.5`
