### ISSUE TITLE
datatable类型数据导出excel服务数值型默认是文本方式保存,字段标题重复会报错

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#3243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. 数值型默认是文本方式
2. 导出提示列名已存在

![DA{}SN{VFV)`8VO`IRDRWCO](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/1aa26417-d612-4cda-a297-e74d081e6b38)

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/e2dc4459-7412-4add-bffb-0ff507423c35)

直接使用miniexcel导出没这两个问题, 所以应该是数据转换部分需要特殊处理一下
`MiniExcelLibs.MiniExcel.SaveAs("分店类别销售.xlsx", dt,overwriteFile:true);`

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/39d8830d-a114-4fc8-9ab2-486246482f27)

**Comment by densen2014** [comment]
测试元组miniexcel不支持, 
而 FormatValue(pi, Utility.GetPropertyValue(item, pi.GetFieldName()));会导出为文本
@ArgoZhang 看来是得自己业务实现?或者配置datatable就不走内部逻辑?

```
        var value = new List<(string, object?)>();
        cols ??= Utility.GetTableColumns<TModel>();
        foreach (var item in items)
        {
            if (item != null)
            {
                var row = new List<(string, object?)>();
                foreach (var pi in cols)
                {
                    var val = await FormatValue(pi, Utility.GetPropertyValue(item, pi.GetFieldName()));
                    row.Add((pi.GetDisplayName(), val));
                }
                value.AddRange(row);
            }
        }
       ...
```

**Comment by ArgoZhang** [comment]
### 键值不可重复问题

内部逻辑不用 `Dictionary` 即可解决

### FormatValue 问题

这个是很多人要的功能，目前没办法直接去掉，正确的思路应该是如何把 C# 中的格式化字符串给 `MiniExcel` 但是有一些是 `FormatCallback` `MiniExcel` 肯定是无法处理的。只能再寻找其他解决方案

**Comment by densen2014** [comment]
格式化数值没法处理了. 自己业务只能自己写一下吧

**Comment by ArgoZhang** [comment]
对啊。格式化的问题，目前就需要自己写了。内置的肯定变成 `string`
