### ISSUE TITLE
bug(TreeView):  AutoCheckChildren not work use OnExpandNodeAsync load children

### ISSUE THREAD

**Issue by XiaoChenDan** [dotnetcore/BootstrapBlazor#3312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

当TreeView组件的ClickToggleCheck设置为false时，并使用OnExpandNodeAsync异步加载子节点，展开的子节点的选中状态CheckedState始终按父节点的选中状态来控制，此时AutoCheckChildren不起作用。当我想通过手动设置子节点的选中状态CheckedState时，是无效的。

### Expected Behavior

当AutoCheckChildren=false时，使用OnExpandNodeAsync异步加载子节点，子节点的选中状态可以通过设置CheckedState参数进行控制。

### Steps To Reproduce

[测试案例](https://github.com/XiaoChenDan/BootstrapBlazor.OnlyServer)

### .NET Version

Net8.0

**Comment by ArgoZhang** [comment]
@XiaoChenDan 帮忙点一下 star 稍等有空我看一下复现工程

**Comment by XiaoChenDan** [comment]
要得

**Comment by ArgoZhang** [comment]
PR 那边有 CLA 需要你去点一下

**Comment by XiaoChenDan** [comment]
因为“移除 ExpandableNodeCache.ToggleNodeAsync() 中展开节点始终对子节点 CheckedState的赋值”，导致原单元测试 TreeNodeCacheTest.ToggleNodeAsync_Ok(CheckboxState state) 不通过了，需不需要我来删除，并对应在 TreeViewTest 再加对应的单元测试？

**Comment by ArgoZhang** [comment]
需要的，单元测试覆盖率是有要求的
