### ISSUE TITLE
doc(Localization): The document seems to have a problem with display.

### ISSUE THREAD

**Issue by twizardp** [dotnetcore/BootstrapBlazor#3316]
### Document describing which component

Getting Started -> Localization
![2024-04-19 134636](https://github.com/dotnetcore/BootstrapBlazor/assets/57797158/6c618fdf-4d0e-4948-9efd-93114da1d802)

**Comment by ArgoZhang** [comment]
@twizardp 感谢，我马上修复一下，帮忙项目点个 star
