### ISSUE TITLE
Editor 在Table组件TableColumn绑定字段EditTemplate，新增正常，再次编辑提示错误

### ISSUE THREAD

**Issue by sxbjxyy** [dotnetcore/BootstrapBlazor#3337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

在Table组件TableColumn绑定字段EditTemplate中 通过 Editor 绑定string类型字段，表格新增时正常，可以将值写入数据库，但再次表格编辑刚写入的该条，提示错误
One or more errors occurred. (Value cannot be null. (Parameter 'jsObjectReference'))

### Expected Behavior

修复bug

### Steps To Reproduce

https://github.com/sxbjxyy/BB/tree/main/Issue_Editor
以上是最小工程再现

### .NET Version

.Net 8

### Anything else?

BootstrapBlazor 8.4.7

**Comment by ArgoZhang** [comment]
@sxbjxyy 项目右上角帮忙点一下 star 谢谢啦

**Comment by ArgoZhang** [comment]
@sxbjxyy 已修复，稍后发个新包，更新即可
