### ISSUE TITLE
feat(MultiSelect): make Clear/SelectAll/InvertSelect methods to public

### ISSUE THREAD

**Issue by eramosr16** [dotnetcore/BootstrapBlazor#3398]
We need the following methods to be available:

- Clear
- SelectAll
- InvertSelect

https://github.com/dotnetcore/BootstrapBlazor/blob/13c607e69a2a2f5872cb230c451af5ea2de6810c/src/BootstrapBlazor/Components/Select/MultiSelect.razor.cs#L308

This methods would help when user wants to customize the buttons on the toolbar, otherwise we cannot reproduce the same actions outside.

**Comment by ArgoZhang** [comment]
@eramosr16 could you give a star for this project? thanks

**Comment by eramosr16** [comment]
Done and thanks for all the hard work.
