### ISSUE TITLE
feat(Table): add OnAutoFitContentAsync parameter

### ISSUE THREAD

**Issue by ArgoZhang** [dotnetcore/BootstrapBlazor#3448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

add OnAutoFitContentAsync parameter

**Comment by gourav2110** [comment]
@ArgoZhang 
It would be great if we can have this enhancement by this release.

**Comment by ArgoZhang** [comment]
@gourav2110 There is a problem that needs to be solved. Since click events and drag events have been used, double-click events cannot be obtained.

Do you have any solution or idea?
