### ISSUE TITLE
bug(SelectTable): 下拉框表格宽度没有充满元素

### ISSUE THREAD

**Issue by guozhang164** [dotnetcore/BootstrapBlazor#3461]
### Which class is this unit test associated with?
版本: .NET 7.0 Blazor Server
最小复现工程，请见附件。
如图所示，下拉弹出来的表格宽度没有充满整个元素。
![3832051982](https://github.com/dotnetcore/BootstrapBlazor/assets/4440534/d35cb29b-8ff5-4902-b55f-1dae238dac5e)

**Comment by guozhang164** [comment]
不好意思，附件刚刚直接拖进去的好像没有上传成功，请查收附件最小Demo工程，谢谢
[Uploading Demo-TableSelect.zip…]()

**Comment by guozhang164** [comment]
通过官网代码测试，V8.5.0版本表格选择器，下拉框表格宽度充满元素。
V8.5.5版本出现宽度不够充满元素

**Comment by ArgoZhang** [comment]
@guozhang164 右上角帮忙点一下 star 谢谢啦。我稍后下载 zip 包看一下

**Comment by guozhang164** [comment]
[Demo-TableSelect.zip](https://github.com/dotnetcore/BootstrapBlazor/files/15269459/Demo-TableSelect.zip)
好的，重新上传了一下
