### ISSUE TITLE
feat(Uplaod): 点击图片就放大查看图片

### ISSUE THREAD

**Issue by movieliang** [dotnetcore/BootstrapBlazor#3472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

**大佬好，提个小建议，上传组件Uplaod 当为预览卡片式CardUpload时，希望点击图片就放大，相当于点下面的放大按钮。每次都点那个小按钮感觉不方便,谢谢！**

![7~{2T2@ R`U)N`$G$_35}UR](https://github.com/dotnetcore/BootstrapBlazor/assets/16262928/48ed4fbd-0100-4e38-a25b-d3a9a4e0e815)

**Comment by ArgoZhang** [comment]
@movieliang 请试试看 `8.5.8-beta02`

**Comment by movieliang** [comment]
可以了，谢谢大佬！
