### ISSUE TITLE
Does BootstrapBlazor work on a MAUI  hybrid application?

### ISSUE THREAD

**Issue by MilvioLua** [dotnetcore/BootstrapBlazor#3527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Im plan to use the shared project on my MAUI hybrid wich I think will work well as long i run on windows.

### Describe the solution you'd like

Can every component work on Android or Ios?

**Comment by ArgoZhang** [comment]
@MilvioLua hi. take a look https://github.com/dotnetcore/BootstrapBlazor/tree/main/src/maui/BootstrapBlazor.Maui

**Comment by MilvioLua** [comment]
thanks.
