### ISSUE TITLE
feat(MultiSelect): add right icon like select

### ISSUE THREAD

**Issue by eramosr16** [dotnetcore/BootstrapBlazor#3556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Multiselect is missing the right arrow icon similar to select: 

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/17813469/7125640a-e04d-45c9-b722-78e36714d622)

### Expected Behavior

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/17813469/e02c9a11-ed50-42e9-9661-1fd7f52a4a86)

### Steps To Reproduce

Multiselect: https://www.blazor.zone/multi-select
Select: https://www.blazor.zone/select

**Comment by ArgoZhang** [comment]
@eramosr16 hi. this is not a bug it's by design.

**Comment by eramosr16** [comment]
Sorry perhaps the word "bug" is misleading, I'll try to make it work on my side, thanks for adding my as contributor, sometimes I missed some tests in my pr due to time constraints, I hope you understand.  
From the user perspective visually MultiSelect is like a Select, so we need to signalize to the user that he had to click and select things similar to what we had on the Select component and also to be consistent on the UI.

I'll create a PR to address this. Thanks
