### ISSUE TITLE
feat(Table): Add OnRenderedAsync Callback for Post-Render Operations

### ISSUE THREAD

**Issue by azlis** [dotnetcore/BootstrapBlazor#3558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

This issue proposes the introduction of a new `OnRenderedAsync` callback method to the `Table<TItem>` component. The purpose of this callback is to provide developers with a hook that is invoked after the table has completed rendering its data.

The `OnRenderedAsync` method would be of the type `Func<Task, Task<Table<TItem>>>?`, allowing for asynchronous operations to be performed post-render. This could be useful in scenarios where developers need to execute additional logic once the table is displayed, such as triggering animations, initiating API calls for more data, or applying dynamic styling.

Additionally, the method would be decorated with the `[Parameter]` attribute, making it a parameter that can be passed to the `Table<TItem>` component within Razor components. This aligns with the Blazor framework's component parameter design and ensures consistency with other callback mechanisms within the component.

By implementing this feature, we enhance the `Table<TItem>` component's flexibility and utility in complex applications where post-render actions are necessary.

### Expected Benefits:
- Provides a clear and explicit way to perform actions after the table has been rendered.
- Aligns with the existing component design patterns in Blazor for handling events and lifecycle methods.
- Increases the component's versatility in real-world applications.

I believe this enhancement will be a valuable addition to the `Table<TItem>` component and look forward to any further suggestions or discussions on its implementation.

**Comment by ArgoZhang** [comment]
@azlis `OnAfterRenderCallback` parameter
