### ISSUE TITLE
DrawerMode seems still not in place, is there any plan?

### ISSUE THREAD

**Issue by cairabbit** [dotnetcore/BootstrapBlazor#3578]
@cairabbit Thank you very much for your suggestion.

### AddTemplate
We can add a new template `AddTemplate`

### SearchMode
https://www.blazor.zone/table/search#CustomerSearchModel

```
<Table TItem="Foo" CustomerSearchModel="@CustomerSearchModel" ShowSearch="true">
    <TableColumns>
        <TableColumn @bind-Field="@context.DateTime" Width="180" />
    </TableColumns>
    <CustomerSearchTemplate>
        @if (context is FooSearchModel model)
        {
            <FooSearch @bind-Value="@model" />
        }
    </CustomerSearchTemplate>
</Table>
```

### Separate table
This component library has been around for over four years now, and it is very difficult to separate tables. Many old users find it difficult to accept this change

### Drawer Mode
This is a good idea. We should implement this model

```
public enum EditMode
{
    /// <summary>
    /// 弹窗式编辑模式
    /// </summary>
    Popup,

    /// <summary>
    /// 行内编辑模式
    /// </summary>
    EditForm,

    /// <summary>
    /// 单元格内编辑模式
    /// </summary>
    InCell,

    /// <summary>
    /// 抽屉编辑模式
    /// </summary>
    Drawer
}
```

_Originally posted by @ArgoZhang in https://github.com/dotnetcore/BootstrapBlazor/issues/2867#issuecomment-1914479421_

**Comment by ArgoZhang** [comment]
@cairabbit I've been a little busy recently and haven't had time to display this function. It would be great if you could implement this function.

**Comment by ArgoZhang** [comment]
link discuss #2874

**Comment by ArgoZhang** [comment]
@cairabbit I took a look at the code. I think that the drawer component must be changed to service mode first. Currently, inline mode is not suitable for use as a table editing window.

**Comment by cairabbit** [comment]
awesome, thanks.
