### ISSUE TITLE
bug(DateTimeRange): ViewMode="DatePickerViewMode.Month"时无法选择

### ISSUE THREAD

**Issue by huangyy21** [dotnetcore/BootstrapBlazor#3587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

当设置ViewMode="DatePickerViewMode.Month"，组件显示正常，但是无法选择月份。
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/44044646/0f21fca4-7b40-4080-a78e-0575fb4a19f6)

**Comment by ArgoZhang** [comment]
@huangyy21 项目右上角帮忙点一下 star 谢谢啦。稍后我有时间修复一下，目前不支持选择年或者月
