### ISSUE TITLE
CheckboxList当IsButton=true时有bug

### ISSUE THREAD

**Issue by wapco** [dotnetcore/BootstrapBlazor#3680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

private string? GetButtonItemClassString(SelectedItem item) => CssBuilder.Default("btn")
        .AddClass($"active bg-{Color.ToDescriptionString()}", CurrentValueAsString.Contains(item.Value))
        .Build();

这段代码中 CurrentValueAsString.Contains(item.Value) 有bug，假设Items的value分别为qr,metterqr，只要选中了metterqr，qr的选项也会被选中

**Comment by ArgoZhang** [comment]
@wapco 发布 `v8.6.3-beta01`
