### ISSUE TITLE
bug(Table): 虚拟滚动模式下点击行导致滚动到顶端

### ISSUE THREAD

**Issue by RRQM** [dotnetcore/BootstrapBlazor#3779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Table组件在设置虚拟滚动时，单机选中项目后，会导致滚动条意外复位到0位置。Table设置如下：
```
<Table IsBordered="true" ScrollMode="ScrollMode.Virtual" Height="500" ShowSearch="true" ClickToSelect="true" IsMultipleSelect="false" >
    <TableColumns>
      ...
    </TableColumns>
</Table>
```

### Steps To Reproduce

https://gitee.com/RRQM_Home/publicworkbook/tree/master/Demo015

这是demo，直接运行可复现

### Exceptions (if any)

无异常

### .NET Version

net8.0

**Comment by ArgoZhang** [comment]
@RRQM 项目右上角帮忙点一下 star 感谢感谢，安排复现修复

**Comment by RRQM** [comment]
thanks
