### ISSUE TITLE
doc(Table): 示例 Id 重复导致复选框显示不正确

### ISSUE THREAD

**Issue by WenTao25** [dotnetcore/BootstrapBlazor#3791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Uploading 1720161869922.mp4…

**Comment by densen2014** [comment]
本来就这样设计的。

**Comment by WenTao25** [comment]
开启自动加载，明明只是点击一个勾选框，结果却选中了两个勾选框，原本应该不是想这样设计吧
![Uploading 1720165548729.jpg…]()

**Comment by ArgoZhang** [comment]
@WenTao25 请提供复现步骤或者例子，或者官网那个示例地址

**Comment by ArgoZhang** [comment]
@WenTao25 示例超过 10 以后 ID 总是 10 导致的

**Comment by WenTao25** [comment]
https://www.blazor.zone/table/auto-refresh;
在自动刷新组件中点击变化的数据的勾选框，会造成其他数据的勾选框状态不正确；
