### ISSUE TITLE
feat(Chart): Add support for controlling the range of the Y axis

### ISSUE THREAD

**Issue by grisharav** [dotnetcore/BootstrapBlazor#3888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I need to be able to set the Y-range of a chart, and currently have no ability to do so

### Describe the solution you'd like

For each Y axis, specify the min/max values to use for it. See https://www.chartjs.org/docs/latest/samples/scales/linear-min-max-suggested.html

**Comment by ArgoZhang** [comment]
@grisharav thank you for submitting an issue. need support
```
scales: {
  y: {
    // the data minimum used for determining the ticks is Math.min(dataMin, suggestedMin)
    suggestedMin: 30,

    // the data maximum used for determining the ticks is Math.max(dataMax, suggestedMax)
    suggestedMax: 50,
  }
}
```

is right?

**Comment by grisharav** [comment]
Yes, thanks, correct!

**Comment by ArgoZhang** [comment]
@grisharav can you give this project a star? thank you.
