### ISSUE TITLE
Camera 组件的若干问题

### ISSUE THREAD

**Issue by sunjie19880719** [dotnetcore/BootstrapBlazor#3902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1、Camera  视频尺寸和下载图片尺寸 可分别 对参数进行适配
2、Camera 拍照成功回调方法 OnCapture ，在对Camera.Capture()成功调用后，未进行回调。
3、Camera 在进行保存下载 Camera.SaveAndDownload($"capture_{DateTime.Now:hhmmss}.png"); 时，手机端下载图片 超时下载失败。

### .NET Version

8.7.3

**Comment by sunjie19880719** [comment]
1、Camera 视频尺寸和下载图片尺寸 可分别 对尺寸参数进行适配

**Comment by sunjie19880719** [comment]
![Uploading 2.png…]()

**Comment by ArgoZhang** [comment]
@sunjie19880719 已更新文档移除 `OnCapture` 组件无此回调方法
