### ISSUE TITLE
bug(AutoFill): 设置OnCustomFilter后，此时输入字符筛选下拉列表，筛选完成后回车，此时无法选中下拉列表中的行。

### ISSUE THREAD

**Issue by DebugClown** [dotnetcore/BootstrapBlazor#4008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![1723195554173](https://github.com/user-attachments/assets/7ceb981f-cdc1-4069-818c-4524b20ac9e2)

查看了AutoFill的源码，发现：
自定义筛选方法后，输入字符后回车，无法选中第一行。
此时下拉列表中的数据是通过OnCustomFilter筛选出来的，但是回车后此处却调用FindItem，FindItem通过OnGetDisplayText无法筛选得到想要的数据。
![image](https://github.com/user-attachments/assets/da90e961-476a-46be-9de9-13caf2f937b8)

例如：
我有列表 ： personList =new List<string>{ "张三","李四"}
我的OnCustomFilter：
return   personList.Where(i => i.Contains(searchText) || i.(获取拼音码).Contains(searchText)).ToList();

当我输入：“张三”，按下回车，此时可以选中张三
当我输入：“zs”，此时出现问题

查看源码，实际代码中执行了FindItem方法，返回Items.Where(s => OnGetDisplayText(s).Contains(_inputString, comparison)) :
没有根据OnCustomFilter返回数据。

**Comment by ArgoZhang** [comment]
@DebugClown 请提供复现例子？或者帮忙来个 PR 修复一下。谢谢啦
