### ISSUE TITLE
DropdownList的OnSelectedItemChanged产生了死循环。（bootstrapBlazor版本5.0.7和3.1.30）

### ISSUE THREAD

**Issue by splo2a** [dotnetcore/BootstrapBlazor#41]
<DropdownList Data="@Items"
              @bind-Value="@SelectedItem"
              OnSelectedItemChanged="@(new Action<int>(v => {result = v;}))"
              TextField="Text"
              ValueField="Value">
</DropdownList>

<div class="form-control">双向绑定对象值：@SelectedItem</div>

@code{
    private int SelectedItem { get; set; } = 2;

    int result = -1;
    IEnumerable<Item> Items = Enumerable.Range(1, 100).ToList().Select(c => new Item() { Value =  c, Text = "Text" + c });
    public class Item
    {
        public int Value { get; set; }
        public string Text { get; set; }
    }
}

**Comment by ArgoZhang** [comment]
@splo2a 大佬帮忙点个 star，谢谢啦，我正在复现这个问题

**Comment by ArgoZhang** [comment]
@splo2a 无法复现，提供的代码有错误

**Comment by ArgoZhang** [comment]
@splo2a 根据提供的示例文件复现此问题，已经修复啦，请使用 5.0.8-beta09 版本测试每周五发布正式版
