### ISSUE TITLE
bug(AutoComplete): not support Tab when set IsPopover to true

### ISSUE THREAD

**Issue by Ddd-Jw** [dotnetcore/BootstrapBlazor#4152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Dropdown list in an AutoComplete field does not appear when navigating to the field using the Tab key even after typing, although it works correctly when the field is focused via a mouse click. 

### Expected Behavior

Dropdown list in an AutoComplete field appear when navigating to the field using the Tab key or when user starts typing in the field. 

### .NET Version

8.0.300

### Anything else?

Running latest BB stable version.

**Comment by Ddd-Jw** [comment]
Minimalistic repro:
[https://github.com/Ddd-Jw/MinRepro.git](url)

**Comment by ArgoZhang** [comment]
@Ddd-Jw thank you for contacting us. could you give this project a star?

**Comment by Ddd-Jw** [comment]
@ArgoZhang Auh, I thought I already did. Done, and thank you.
