### ISSUE TITLE
bug: Collapse can not be folded again

### ISSUE THREAD

**Issue by zhongfang2018** [dotnetcore/BootstrapBlazor#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Collapse can be displayed correctly. After I click the title , it can be spreaded. 
But after I click the title again, it can not be restored

就是展开后不能还原。

### Expected Behavior

- click the first time, it can be spreaded.
- click again, it can not be restored just like it first rendered
- I want it can be restored while I click at the second time.

### Steps To Reproduce

- click the first time, it can be spreaded.
- click again, it can not be restored just like it first rendered.

### .NET Version

7.0

**Comment by ArgoZhang** [comment]
@zhongfang2018 Thank you for submit reporting. Automatic close this Issue cause by no feedback
