### ISSUE TITLE
Translate the docs to english

### ISSUE THREAD

**Issue by ArgoZhang** [dotnetcore/BootstrapBlazor#42]
### Is your feature request related to a problem? Please describe.
translate the docs to english

### Describe the solution you'd like
- open json file in to ~/BootstrapBlazor.Shared/Locales
- update the docs under ~/BootstrapBlazor.Shared/Pages folder content

### Additional context
- [x] Alerts
- [X] Anchors
- [x] AutoCompletes
- [x] Avatars
- [x] Badges
- [x] BarcodeReaders
- [x] Breadcrumbs
- [x] Buttons
- [x] Calendars
- [x] Cameras
- [x] Capthcas
- [x] Cards
- [x] Carousels
- [x] CheckboxLists
- [x] Checkboxs
- [x] Circles
- [x] Collapses
- [x] Coms
- [x] Consoles

**Comment by ArgoZhang** [comment]
@pomeara 
hi, could you join this work?

**Comment by georgeemr** [comment]
Hi, this can be perfect, I try to implement the library but it's too complicated with no English documentation. I was looking for a blazor bootstrap 4 library and as far I can found this is the most complete.

**Comment by ArgoZhang** [comment]
@georgeemr hi，thank you for replay. could you join us for the translate work?

**Comment by georgeemr** [comment]
Hi @ArgoZhang , sure, I will fork the project and do it in my free time. English is not my primary language but I will try it.

**Comment by ArgoZhang** [comment]
@georgeemr thank you for reply. translate work is a huge work. maybe we should redesign the docs system. do you have any suggestion?

**Comment by pomeara** [comment]
@ArgoZhang hey let me know when you need some English translation assistance, I am happy to help out as usual

**Comment by ArgoZhang** [comment]
@pomeara thanks. the docs need follow this

- open json file in to ~/BootstrapBlazor.Shared/Locales
- update the docs under ~/BootstrapBlazor.Shared/Pages folder content

**Comment by pomeara** [comment]
@ArgoZhang are we using .resx files for the translations, this appears to be the best practice from MS for .net apps

**Comment by ArgoZhang** [comment]
@pomeara i'm very sorry for that this project use json resource file. but it support .resx format. cause by my environment is on mac. so can't edit .resx format file. json is better

**Comment by densen2014** [comment]
i am coming

**Comment by pomeara** [comment]
@densen2014 great stuff, @ArgoZhang  I start a mini break for two weeks from tomorrow so I will have some time to help out then

**Comment by densen2014** [comment]
@pomeara Nice to meet you, iam chinease, vivo en madrid , ;->

**Comment by ArgoZhang** [comment]
@pomeara great! @densen2014 thanks for you contribution

**Comment by ahmetkocadogan** [comment]
I can help to translate to Turkish language if you like but i need an English version for that.

**Comment by ArgoZhang** [comment]
@ahmetkocadogan that's great! the English version resource is ready. you can check it out from https://github.com/dotnetcore/BootstrapBlazor/blob/main/src/BootstrapBlazor/Locales/en.json

**Comment by DominicSaladin** [comment]
> @ahmetkocadogan that's great! the English version resource is ready. you can check it out from https://github.com/dotnetcore/BootstrapBlazor/blob/main/src/BootstrapBlazor/Locales/en.json

Is that the correct link? And what is that for:
https://github.com/dotnetcore/BootstrapBlazor/blob/main/src/BootstrapBlazor.Shared/Locales/en.json

Do you need any help with translating at the moment?

**Comment by DominicSaladin** [comment]
@ArgoZhang Also, is there a reason why the complete code documentation is in chinese and not in english?
![image](https://user-images.githubusercontent.com/43037258/185968007-c46934d8-e943-4ccc-b8ed-f988b61a2e13.png)

Is it planned to change this to english in the future?

**Comment by DominicSaladin** [comment]
@ArgoZhang Would be nice to know :)

**Comment by ArgoZhang** [comment]
> @ArgoZhang Also, is there a reason why the complete code documentation is in chinese and not in english? ![image](https://user-images.githubusercontent.com/43037258/185968007-c46934d8-e943-4ccc-b8ed-f988b61a2e13.png)
> 
> Is it planned to change this to english in the future?

sorry for the delayed reply. this is need help too.

**Comment by pomeara** [comment]
@ArgoZhang  pull translations from here https://github.com/pomeara/BootstrapBlazor/commit/c287e5a3eec7ea0ec899bfee9dacb5256478a359

**Comment by pomeara** [comment]
@ArgoZhang please get many commits from here all for the translations

![image](https://user-images.githubusercontent.com/8163710/193433873-b10f2766-9e2d-4ddb-a9af-5170b8e10012.png)

**Comment by ArgoZhang** [comment]
@pomeara it's cool. great works. thank you very much. I merged it into my repo. later will release

**Comment by pomeara** [comment]
@ArgoZhang please grab some more translations from the same branch

**Comment by ArgoZhang** [comment]
@pomeara Great! thank you very much. 

BTW: delete the branch after I merged and recreating a branch is better

**Comment by pomeara** [comment]
@ArgoZhang more translations (in a new branch)

https://github.com/pomeara/BootstrapBlazor/tree/new-translations

**Comment by ArgoZhang** [comment]
@pomeara great job thank you very very much

BTW: better steps

1. delete the branch after merged
2. sync repo from `https://github.com/dotnetcore/BootstrapBlazor`
3. create a new branch from `main` branch

**Comment by pomeara** [comment]
@ArgoZhang please grab this branch also https://github.com/pomeara/BootstrapBlazor/tree/translations-2

i did the 3 steps you mentioned also

**Comment by ArgoZhang** [comment]
@pomeara Thank you very much for your work. I think maybe my expression is wrong. the branch `translations-2` can't merged into main because too many conflict.

I notice that you merge the Main branch into your translations-2. it's a bad idea. 

https://github.com/pomeara/BootstrapBlazor/commit/76706d78e29bc2751e66654c0b61de7c07da4790

the better step is

1. delete branch translatons-2
2. create a new branch from main (sync bootstrapblazor main branch) named 'doc-trans'
3. update the docs

**Comment by pomeara** [comment]
@ArgoZhang I added you to the repo please work your magic would love to see all the translations make it into the master

**Comment by ArgoZhang** [comment]
@pomeara done! thank you for doing this work again. it's very cool.
