### ISSUE TITLE
bug(): 高级搜索时，列表搜索框的Bug

### ISSUE THREAD

**Issue by youthalan** [dotnetcore/BootstrapBlazor#4207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

搜索有bug，触发步骤为：
    1、在搜索框内输入想要搜索的内容，结束时不是点击右上角的清空搜索而是点击输入框内右边的“x”按钮
    2、这时输入框内容会清掉，但是页面并没有重新刷新，再次点击搜索框，这时只有刚刚搜索出来的钢卷号
    3、上面可以通过再次在输入框输入内容手动删掉，即可恢复
    4、如果跳过步骤3，点击下方表格排序等位置，表格也会显示正常，但是点击搜索框依然只有一条内容
    5、综上，搜索框的清空功能异常

登录账号：SuperAdmin
登录密码：111111

Demo为：
[Uploading ThingsGateway_20240904153031.zip…]()

**Comment by ArgoZhang** [comment]
@youthalan Issue 不合规范，建议百度一下最小复现工程的意思，尽量减少干扰因素
