### ISSUE TITLE
Table 控件默认删除按钮报错

### ISSUE THREAD

**Issue by jimsun268** [dotnetcore/BootstrapBlazor#4222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Table 控件使用默认删除按钮会报错，但是自定义删除按钮功能正常.
![001](https://github.com/user-attachments/assets/a5d2ed82-80a6-458b-b362-8104c10ef38f)

[BlazorApp1.zip](https://github.com/user-attachments/files/16907309/BlazorApp1.zip)

### .NET Version

8.0.400

**Comment by ArgoZhang** [comment]
@jimsun268 感谢提交 Issue 能否帮忙右上角点一下 star 感谢感谢。我下载例子看看

**Comment by ArgoZhang** [comment]
@jimsun268 如果操作？请写清楚操作步骤

**Comment by jimsun268** [comment]
好的，稍晚我点，现在我Github上不去了。



兴凯湖农场高标办公室 孙立军


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/BootstrapBlazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月7日(星期六) 上午10:42
***@***.***&gt;;
抄送:&nbsp;"兴凯湖农场 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/BootstrapBlazor] Table 控件默认删除按钮报错 (Issue #4222)





 
@jimsun268 感谢提交 Issue 能否帮忙右上角点一下 star 感谢感谢。我下载例子看看

**Comment by jimsun268** [comment]
https://github.com/user-attachments/assets/2df2e5e5-95fc-4c22-a779-d11da76a5611
没有什么特别操作，就是基本操作

**Comment by ArgoZhang** [comment]
@jimsun268 代码不对，请认真查看例子 

![image](https://github.com/user-attachments/assets/9896d021-8737-484c-9265-3ce618d05944)

这里连删除回调代码都没有给，你视频录像中添加了多个。你仅添加一个就不会出错。试试看

**Comment by jimsun268** [comment]
![b01](https://github.com/user-attachments/assets/1d2e67f4-d23f-4db3-a356-29ae83576ea5)


![b02](https://github.com/user-attachments/assets/a87fe312-3f26-48e8-b12a-76d7fe83995d)

是这个意思吗？可还是一样的错误

**Comment by ArgoZhang** [comment]
@jimsun268 我懂你的意思了。你的点是在那个 js 报错上。那个是 bootstrap.js 内部的一个错误，你先忽略，先保证功能正常。等 bs 更新后就正常了

**Comment by jimsun268** [comment]
好的，谢谢！




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/BootstrapBlazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月7日(星期六) 下午3:40
***@***.***&gt;;
抄送:&nbsp;"兴凯湖农场 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/BootstrapBlazor] Table 控件默认删除按钮报错 (Issue #4222)





 
@jimsun268 我懂你的意思了。你的点是在那个 js 报错上。那个是 bootstrap.js 内部的一个错误，你先忽略，先保证功能正常。等 bs 更新后就正常了

**Comment by ArgoZhang** [comment]
@jimsun268 晚点我发布一个 8.9.1 版本，您更新一下这个脚本错误我会修复的。`tooltip` `popover` 相关的这个问题都是 bs 导致的。他们在修复，估计下个版本会更好

**Comment by jimsun268** [comment]
收到，十分感谢你的帮助。




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/BootstrapBlazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月7日(星期六) 下午4:19
***@***.***&gt;;
抄送:&nbsp;"兴凯湖农场 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/BootstrapBlazor] Table 控件默认删除按钮报错 (Issue #4222)





 
@jimsun268 晚点我发布一个 8.9.1 版本，您更新一下这个脚本错误我会修复的。tooltip popover 相关的这个问题都是 bs 导致的。他们在修复，估计下个版本会更好
