### ISSUE TITLE
关于Table行内按钮操作时间过长，导致刷新的问题

### ISSUE THREAD

**Issue by youthalan** [dotnetcore/BootstrapBlazor#4269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

当Table行内按钮的操作时间过长时，会导至刷新异常。
比如说，我需要将当前的行显示并高亮到最前面的时候，会出现不一至的问题。

代码：
[BootstrapBlazorApp1_20240911122737.zip](https://github.com/user-attachments/files/16957884/BootstrapBlazorApp1_20240911122737.zip)

**Comment by youthalan** [comment]
项目工程：
[BootstrapBlazorApp1_20240911164113.zip](https://github.com/user-attachments/files/16961252/BootstrapBlazorApp1_20240911164113.zip)

**Comment by ArgoZhang** [comment]
duplicate #4275
