### ISSUE TITLE
bug(Select): IsClearable 没触发 OnSelectedItemChanged 回调方法

### ISSUE THREAD

**Issue by youthalan** [dotnetcore/BootstrapBlazor#4279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 触发步骤为：
1、在搜索框内输入想要搜索的内容，结束时不是点击右上角的清空搜索而是点击输入框内右边的“x”按钮
2、这时输入框内容会清掉，但是页面并没有重新刷新，再次点击搜索框，这时只有刚刚搜索出来的钢卷号
3、上面可以通过再次在输入框输入内容手动删掉，即可恢复
 4、如果跳过步骤3，点击下方表格排序，表格也会显示正常，但是点击搜索框依然只有一条内容
 5、综上，搜索框的清空功能异常

![image](https://github.com/user-attachments/assets/d5eb27b5-d959-40d7-9d0a-36357fa75717)

![image](https://github.com/user-attachments/assets/54eecc5a-9fa9-48e3-bf67-f8ff81d178b0)

![image](https://github.com/user-attachments/assets/9dfdcee7-5654-4828-bebe-91f6fa7de948)

![image](https://github.com/user-attachments/assets/083af1bf-ed24-471d-8935-1852e9785daa)

![image](https://github.com/user-attachments/assets/df2943b3-7fed-463a-b4e0-d7c055e3cba6)

![image](https://github.com/user-attachments/assets/941e6f56-2233-43df-b075-6f30920c0e0f)

![image](https://github.com/user-attachments/assets/58eb8aec-6be9-4380-a181-4d50acf76943)

![image](https://github.com/user-attachments/assets/95e4948e-4b32-4c7d-8a12-cb24f447cd60)

测试代码：
[BootstrapBlazorApp1_20240911215934.zip](https://github.com/user-attachments/files/16964878/BootstrapBlazorApp1_20240911215934.zip)

### Expected Behavior

希望能解决这个刷新问题。

**Comment by ArgoZhang** [comment]
@youthalan 感谢提交 Issue 有复现例子就非常快解决问题啦。这个是 bug 已经发包 `v8.9.2-beta07`
