### ISSUE TITLE
bug(Cascader): 最大高度样式没有生效

### ISSUE THREAD

**Issue by AiYuZhen** [dotnetcore/BootstrapBlazor#4281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## 最大限制高度没有生效，导致 `Cascader` 组件滚动条没有生效。
![image](https://github.com/user-attachments/assets/4d5d10ad-b131-4296-8a38-0d15b8d9a0d5)

### Steps To Reproduce

[Test.zip](https://github.com/user-attachments/files/16965463/Test.zip)

**Comment by ArgoZhang** [comment]
@AiYuZhen 这个组件是横向扩展的，你给了滚动条就无法展开了。TBD
