### ISSUE TITLE
Layout Page with Multitab mode， can not  navigate to  authentication/login. and menu url cannot  match  route 

### ISSUE THREAD

**Issue by geffzhang** [dotnetcore/BootstrapBlazor#43]
### Describe the bug
Use Layout Page with Multitab mode， can not  navigate to  authentication/login. and menu url cannot  match  route parameters 

### To Reproduce
 This is a sample https://github.com/geffzhang/Abp.BootstrapTheme,  run Abp.BootstrapTheme.Blazor.Host、Abp.BootstrapTheme.HttpApi.Host and Abp.BootstrapTheme.IdentityServer 。

Blazor.Host Project  Index page click  Login  can't navigate to  authentication/login  Layout Page with Multitab mode .  swaitch to single page . It can be navigate to  authentication/login. 

 
### Further technical details
- BootstrapBlazor 5.0.12
- Include the output of `dotnet --info`
 C:\Users\geffzhang>dotnet --info
.NET SDK (反映任何 global.json):
 Version:   5.0.102
 Commit:    71365b4d42

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.1.812 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

**Comment by ArgoZhang** [comment]
fixed by version 5.0.13-beta05
