### ISSUE TITLE
feat(ValidateForm): add ShowAllInvalidResult parameter

### ISSUE THREAD

**Issue by celadaris** [dotnetcore/BootstrapBlazor#4301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to make it so tooltips don't show on invalid submission. The reason being that I have a big form I want to validate when the page loads, and I don't like all the tooltips appearing at once, its too annoying/overwhelming.

### Describe the solution you'd like

I would prefer to have a bool in the ValidateForm to be able to choose whether or not to focus on the invalid elements inside the form.

but also being able to modify the popper configuration would be really nice (more on that in additional context)

### Additional context

I have tried to work around this by completely changing the popper configuration in JavaScript so that the trigger becomes hover only, but there are two problems with that:

1. Any changes made to the Popper config files get overwritten on the next invalid submission and I don't think there's an event that I can subscribe to, in order to quickly/consistently override those changes.

2. Not all elements that have validation can be modified because they return a null popper configuration. I'm not sure if that is a bug or if these elements are designed in a different manner.
_note: the only one that I've discovered to produce this behavior is AutoComplete, I didn't thoroughly test other elements_

the video below shows the demo project I made, this project gets the validation tooltip of all elements with the `data-tag="validation"` attribute using JavaScript. It then attempts to add a new configuration to the element and it pretty much only changes the toggle to hover only. In the video you can see that when it iterates through all of the elements it sees, it can find the configuration for the first one, but as I mentioned before the autocomplete element will return a null configuration.

here is the project:
[PopperConfigFinder.zip](https://github.com/user-attachments/files/16999685/PopperConfigFinder.zip)

https://github.com/user-attachments/assets/d1ac8500-0779-4409-8cd8-8a3456546cd3

**Comment by ArgoZhang** [comment]
@celadaris hi. sorry for the delayed reply. I am in a vacation. 

If add a `ShowAllInvalidResult` parameter to control whether to show the all validation result prompts, does it meet your needs?

**Comment by celadaris** [comment]
It should, im seeing you added the parameter but will finish the functionality later? well either way you should enjoy your vacation. Thank you!

**Comment by ArgoZhang** [comment]
@celadaris try `v8.9.2` i think it should be works

**Comment by celadaris** [comment]
for me, im seeing strange behaviour:

1. when i click submit, at least one of them will show the tooltip, its not clear which one will show it, sometimes its the one on top, sometimes its the one on bottom.
2. then if i hover over the elements to clear the tooltip and then click submit, the tooltips dont show.
3. if i type something into the elements and submit sometimes ill get the javascript error.

_i havent tested anything ouside of this project so far._

the test project:
[testing new feature.zip](https://github.com/user-attachments/files/17004431/testing.new.feature.zip)

https://github.com/user-attachments/assets/abe6120f-df2e-413b-86a9-e8166ef905b3

**Comment by ArgoZhang** [comment]
@celadaris Hi. could you try the `fix-validate` branch? if it meet your required. I will merge to main

**Comment by celadaris** [comment]
It looks good! the javascript error still appears, ive tested almost all the elements that can be validated with the exception of Select-Table because i had a hard time setting it up, but they all behave correctly, the only problem is when you input data and submit, you might get that javascript error on some elements, that really needs to be fixed, but other than that it looks good!

i cant upload the whole repo because its too large, but here is the modified Index.razor page that i used to test with, i tested this on the  BootstrapBlazor.Server project
[Index.zip](https://github.com/user-attachments/files/17008299/Index.zip)

**Comment by ArgoZhang** [comment]
@celadaris i am sorrty for the wrong code pushed

ValidateForm the condition should check `ShowAllInvalidResult` is false. please try again.
```
if (!ShowAllInvalidResult && !string.IsNullOrEmpty(_validationResult.Id))
{
    await InvokeVoidAsync("update", Id, _validationResult.Id, _validationResult.ErrorMessage);
    _validationResult = default;
}
```

**Comment by celadaris** [comment]
the javascript error doesnt happen as often but it still happens, in my tests i see it most often appear in floatinglabeltext im not sure why, and it seems that the tooltip appears on at least one of the elements.
https://github.com/user-attachments/assets/e36bd5ed-dfa2-4b17-ab53-e1d497501e91

**Comment by ArgoZhang** [comment]
@celadaris ok. now it's very clear. please check this issue 

https://github.com/twbs/bootstrap/issues/37474

We have tried to fix this problem many times. However, it still occurs occasionally.

**Comment by celadaris** [comment]
well i tried to run a different test, this one is with 2 elements, and you can see at least one of the two tooltips show, with the occasional javascript error:

https://github.com/user-attachments/assets/e908b6b4-f08a-478b-99ed-d71b52b2fcb6

and in this test im just using a single element and the tooltip shows, sometimes not even submitting the element, but clicking away from it causes the javascript error:

https://github.com/user-attachments/assets/a102a890-e739-4a5c-be17-2576fd260de1

**Comment by celadaris** [comment]
if i click on the input while its red, type then click away to unfocus, it shows the error i think everytime.

**Comment by ArgoZhang** [comment]
@celadaris I watched the video many times, but I still don't know how to reproduce this error. but I strongly recommend not using vs to debug js. We can check the console in the browser's developer mode.


https://github.com/user-attachments/assets/09323d3e-ce21-4aa5-8961-3f5b5738811b

**Comment by celadaris** [comment]
https://drive.google.com/file/d/1lFNF0gVeRj3xvOBm2zPf6V1koNNmOcEK/view?usp=sharing

**Comment by celadaris** [comment]
I was using .net 8, blazor server project. Did u get the bug?

**Comment by ArgoZhang** [comment]
@celadaris not yet. There are no errors in the console

**Comment by celadaris** [comment]
1. I cant access the pc that was giving me trouble until later today

2. When uploading the project that I sent you via google drive to another pc I don't see the JavaScript errors.
 
3. When testing validation on all the elements starting from the fresh updated branch on this other pc, everything seems to be functioning as it should without errors.
 
4. Its making me think maybe my other pc is broken haha.


https://github.com/user-attachments/assets/a6a7505f-4e48-484f-b79b-5358c0356348

**Comment by ArgoZhang** [comment]
@celadaris hahaha

I think it might be caused by browser cache.

**Comment by celadaris** [comment]
Ohh that might be it! ill check when i can

**Comment by ArgoZhang** [comment]
@celadaris i had merged into main. we can create a new issue if have any question.

try check this `disable cache`
![image](https://github.com/user-attachments/assets/109ef2ce-1e78-4abe-9ab2-167dab2f18c5)

**Comment by celadaris** [comment]
okay, will do! Thanks a ton!! very sorry that I didn't do that already 🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by celadaris** [comment]
its so odd that im seeing the tooltips again OnSubmit/OnValidate, it seems that at least one element shows a tooltip per `<ValidateForm>` and its very noticeable when you have many `<ValidateForms>` with only one or few elements.

[tooltiptester.zip](https://github.com/user-attachments/files/17017672/tooltiptester.zip)

https://github.com/user-attachments/assets/da7ca350-6cd9-497f-a988-02710356f230

**Comment by celadaris** [comment]
I was just asking, in case you weren't aware, but if you're making changes and will fix later then do what u got to do first, no worries!

**Comment by celadaris** [comment]
i didnt realize, the changes are in main, i thought  they would somehow be in v8.9.2 ooooops forget the last 2 comments.

**Comment by ArgoZhang** [comment]
@celadaris I'm sorry that I haven't released a new package yet. So 8.9.2 doesn't include our new changes. If you want to continue testing your requirements, you can only refer to the main branch source code.
