### ISSUE TITLE
bug(SortableList): 克隆拖拽后 呈现额外的 克隆dom元素

### ISSUE THREAD

**Issue by AApuci** [dotnetcore/BootstrapBlazor#4312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

当option 设置 Clone = true时，且使用 items 来呈现 画面时，
拖拽会出现额外的克隆dom元素，
此时，items 变更 除了会呈现 items对应的元素外，还会常驻显示 克隆元素。

以下代码在 BootstrapBlazor.Server\Components\Samples\SortableLists.razor 中可重现问题

[SortableLists_ex.zip](https://github.com/user-attachments/files/17006106/SortableLists_ex.zip)

### Expected Behavior

拖拽后，页面上的 克隆dom元素 不应被保留

### Steps To Reproduce

1. 将被拖拽方  option 中 Clone = true,
2. 拖拽双方设置同一个 Group 名称 与同一个 RootSelector
3.  双方都使用 数据对象 来实现【拖拽元素】的渲染，而非直接 <div class="sl-item"></div>

**Comment by AApuci** [comment]
3. 双方都使用 数据对象 来实现【拖拽元素】的渲染，而非直接写 div 标签的拖拽元素

**Comment by ArgoZhang** [comment]
@AApuci 提交复现工程不是提交一个 razor 文件，换位思考一下。都这样提交一个 razor 我们需要自己创建工程，再改造你的 razor 当代码跑起来。这本身就丢了很多关键信息？比如你时那个版本，你 blazor 运行再什么模式下？不仅给我们增加了额外的工作量，还不能正确的反应问题。为什么这么简单的道理都想不明白呢？

**Comment by AApuci** [comment]
抱歉，造成了困惑与耽误时间，我上传了复现工程 与 视频。

https://github.com/user-attachments/assets/e479ee73-a0a5-4bdc-abc7-22c36042412b

[Aapuci - sortableList.zip](https://github.com/user-attachments/files/17009924/Aapuci.-.sortableList.zip)

**Comment by AApuci** [comment]
我在另外一issue 里面提供了或许能解决问题的代码，希望对于修改这个BUG有所帮助。
https://github.com/dotnetcore/BootstrapBlazor/issues/4316

![image](https://github.com/user-attachments/assets/f432d882-40dc-4772-8d05-8cf6738025d0)

**Comment by ArgoZhang** [comment]
@AApuci 收到，我马上修复一下，感谢提交详细信息
