### ISSUE TITLE
Table ShowCopyColumn 功能不应该复制明细行内容

### ISSUE THREAD

**Issue by sundows** [dotnetcore/BootstrapBlazor#4321]
### Which class is this unit test associated with?

https://github.com/user-attachments/assets/05559ef7-ae9e-4bb1-b1ad-1a30fe69f81a
![24}XQ0I`_HZZ@$48`WYXN$S](https://github.com/user-attachments/assets/a79a40d2-020b-45aa-bf89-6d5254482ef4)

在使用 Table 组件的复制列名（ShowCopyColumn）的功能时，发现一个现象（详看上面附加的视频），如果父行有明细行，展开明细行后，再使用父行的复制列名的功能时，会把明细行的内容也复制到剪贴板中，不知这是不是正常的现象？

**Comment by ArgoZhang** [comment]
@sundows 感谢提交问题，应该是 bug 不应该复制明细行的内容

**Comment by ArgoZhang** [comment]
@sundows 经过测试目前程序就是不会拷贝明细行内的数据的
