### ISSUE TITLE
feat(ListView): 使用了ItemTemplate后 选中 点击事件无效

### ISSUE THREAD

**Issue by wenlino** [dotnetcore/BootstrapBlazor#4346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

ListGroup 使用了ItemTemplate后 选中 点击事件无效
OnClickItem 事件无效，选中 Value也不会变化。
我不清楚是故意如此设计的还是其他，但是出于使用，此处还是需要增加好一点。

同样希望listview也增加选中 高亮，或者选中值。

### Describe the solution you'd like

```
<div @attributes="AdditionalAttributes" class="@ClassString">
    @if (HeaderTemplate != null)
    {
        @HeaderTemplate
    }
    @if (!string.IsNullOrEmpty(HeaderText))
    {
        <div class="list-group-header">@HeaderText</div>
    }
    <div class="list-group-body scroll">
        @foreach (var item in Items)
        {
            @if (ItemTemplate != null)
            {
                //此处也需要将模板包裹在 div中
                <div @key="item" class="@GetItemClassString(item)" @onclick="() => OnClick(item)">
                    @ItemTemplate(item)
                </div>        
            }
            else
            {
                <div @key="item" class="@GetItemClassString(item)" @onclick="() => OnClick(item)">@GetItemText(item)</div>
            }
        }
    </div>
</div>

```

**Comment by j4587698** [comment]
这个就是故意设计成这样的，你不能假定别人使用了Template以后还需要外层包裹class以及需要实现OnClick。使用Template以后所有的样式还有点击事件都要由你自己来处理了。因为做加法好做，做减法不容易做啊

**Comment by wenlino** [comment]
您说的很对。我思考，能不能设计成，增加一个参数，可以指定事件由系统处理，自己处理这两种了，我在实际使用中，感受到，要是每次都要自己处理点击选中事件，感觉相当繁琐，有些只是一个简单模板。可以减少使用代码量。我只是在多个使用中的感受。

**Comment by j4587698** [comment]
选中事件你只需要把
```
<div @key="item" class="@GetItemClassString(item)" @onclick="() => OnClick(item)">
                    @ItemTemplate(item)
                </div>    
```
这个部分放到你的模板里就可以了啊，这个onclick你导出到你自己的OnClick事件即可，如果你要同时处理css的话可能代码稍微多一点，但是事件一点都不麻烦啊

**Comment by wenlino** [comment]
您可能没理解我的意思，本来 @bind-Value 就可以获取选中数据，若是需要自行处理点击事件，那相当于，自己还要处理selected item 。还得再赋值到value中，而且这个赋值，并没有真实含义，只是还需要一个处理过程。并且其他获取还是需要自行操作逻辑，当然，这里，不处理，组件也是能正常使用的。只是麻烦一点。
