### ISSUE TITLE
bug(ValidateForm): MetadataType 方式如果继承了 IValidateCollection 概率不显示单属性错误提示

### ISSUE THREAD

**Issue by AiYuZhen** [dotnetcore/BootstrapBlazor#4359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

使用 MetadataType 方式附加的类型如果继承了 IValidateCollection，特定情况下不显示对单个属性的验证错误信息。

### Expected Behavior

正确显示属性验证错误信息。

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

[Test.zip](https://github.com/user-attachments/files/17140275/Test.zip)
### 示例中限制了不能输入 0 ，打断点验证代码也执行并正确返回了，但还界面还是显示验证通过了
![image](https://github.com/user-attachments/assets/5110b136-f906-46c3-8e25-7b8c59dd2253)
![image](https://github.com/user-attachments/assets/b3958b67-cf4a-4d64-be64-7bda5cc039c5)

### 但如果把上面的 【地块面积（亩）】也加入验证，则就能正确显示错误了
![image](https://github.com/user-attachments/assets/534234b8-e8fd-4713-b594-14cf42af5790)
![image](https://github.com/user-attachments/assets/ca4938fd-cfc1-42f4-ab18-7008927236dc)

### .NET Version

vs2022 17.11.4   .net 8.0

**Comment by ArgoZhang** [comment]
@AiYuZhen 代码中并没有限制不能输入零
