### ISSUE TITLE
DialogService设置ShowCloseButton=false无效

### ISSUE THREAD

**Issue by Wenchel** [dotnetcore/BootstrapBlazor#4386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

使用DialogService，设置option的ShowCloseButton属性无效。设置为ShowCloseButton=false时还是显示关闭按钮。

### Expected Behavior

置为ShowCloseButton=false时，对话框底部不显示关闭按钮。

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

nothing

### Exceptions (if any)

nothing

### .NET Version

8.0

### Anything else?

nothing

**Comment by ArgoZhang** [comment]
@Wenchel 未复现
