### ISSUE TITLE
Table does not fully support RTL. In Version 8.10.2

### ISSUE THREAD

**Issue by NabaviFard-Mahdi** [dotnetcore/BootstrapBlazor#4470]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Table does not fully support RTL. Especially search , filter and pagination

### Expected Behavior

Support RTL Or any built in ways

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

<html lang="ar" dir="rtl" translate="no">

ShowToolbar="true"
ShowSearch="true"
IsPagination="true"

### .NET Version

8.0.403

### Anything else?

VS 2022
Windows 10
Chrome Version 129.0.6668.101 (Official Build) (64-bit)

**Comment by ArgoZhang** [comment]
@NabaviFard-Mahdi Unfortunately, our component library does not inherit the RTL style library. So you need to manually add the rtl style library to your project.

### Step 1
download `bootstrap.rtl.min.css` from `bootstrap` website

### Step 2
add link on your page.

`<link rel="stylesheet" href="bootstrap.rtl.min.css" />`

There are still some issues that require updating our component library, please wait for the next version
