### ISSUE TITLE
feat(SelectedItem): 希望选项值可以支持 TValue 而不仅仅是文本

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#4497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

类似 SegmentedOption 的 Value ,是不是场景更广,用户也不用自己转类型

```
/// <summary>
/// 选项类
/// </summary>
public class SelectedItem
{
    /// <summary>
    /// 获得/设置 选项值
    /// </summary>
    public TValue? Value { get; set; }
}
```

**Comment by ArgoZhang** [comment]
@densen2014 

### 设计

1. 增加 `SelectedItem<T>` 泛型类

```
public class SelectedItem<T> : SelectedItem
{
    /// <summary>
    /// 获得/设置 泛型值
    /// </summary>
    public new T? Value { get; set; }
}
```

`Value` 为泛型支持复杂类

2. `Select` 组件增加 `ValueEqualityComparer` 用户可以自定义判断两个泛型对象相等规则（用于高亮、选中项判断）
```
/// <summary>
/// 获得/设置 比较数据是否相同回调方法 默认为 null
/// <para>提供此回调方法时忽略 <see cref="CustomKeyAttribute"/> 属性</para>
/// </summary>
[Parameter]
public Func<TValue, TValue, bool>? ValueEqualityComparer { get; set; }
```

3. `Select` 组件增加 `CustomKeyAttribute` 用于指定泛型对象相等规则默认属性（用于简化用户代码）
如用户未提供 `ValueEqualityComparer` 回调参数时，自动查找 `CustomKeyAttribute` 值用于判定选中项

4. 以上参数均未给定时检查对象是否继承 `IEqualityComparer` 接口，执行其判定方法
5. 以上参数均未符合时使用 `object.Equals` 方法判定
