### ISSUE TITLE
Table组件表头不能水平滚动

### ISSUE THREAD

**Issue by Jiang2020426** [dotnetcore/BootstrapBlazor#4574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Table组件，当设置IsFixedHeader=true及ShowCardView=true时，切换至Card模式，再切换回Table模式，表头在水平方向不能滚动，或消失(切换至Card模式，且垂直方向移动一定像素，再切换会Table模式)

### Expected Behavior

模式切换后，水平方向内容过多，表头应该随内容滚动

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

![PixPin_2024-10-30_13-59-40](https://github.com/user-attachments/assets/b7f0d53c-66e0-4cd7-9ff6-44f031b4e038)
![PixPin_2024-10-30_14-00-39](https://github.com/user-attachments/assets/ef3d852d-3489-4d27-af27-ac35395268f3)
[HiPrintBlazorDemo-master.zip](https://github.com/user-attachments/files/17567366/HiPrintBlazorDemo-master.zip)

### .NET Version

NET8

**Comment by ArgoZhang** [comment]
@Jiang2020426 复现例子不正确
