### ISSUE TITLE
bug(Handwritten): 组件不能正常手写

### ISSUE THREAD

**Issue by Jiang2020426** [dotnetcore/BootstrapBlazor#4590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

在弹窗情况下，Handwritten不能手写（页面中可以）

### Expected Behavior

弹窗手写组件无法手写

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

![11111](https://github.com/user-attachments/assets/399ac086-396f-4599-a27a-78780e519b53)
[BootstrapBlazorApp4.zip](https://github.com/user-attachments/files/17597068/BootstrapBlazorApp4.zip)

### .NET Version

NET8

**Comment by ArgoZhang** [comment]
@Jiang2020426 这个组件不维护了。统一使用 `BootstrapBlazor.SignaturePad` 组件
