### ISSUE TITLE
gitee 扩展服务示例工程链接全都是404

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#46]
扩展服务示例

https://gitee.com/LongbowEnterprise/BootstrapBlazor/wikis/Table%20%E7%BB%84%E4%BB%B6%E6%95%B0%E6%8D%AE%E6%9C%8D%E5%8A%A1%E4%BB%8B%E7%BB%8D?sort_id=3207977

PetaPoco 工程链接
FreeSql 工程链接
EFCore 工程链接

**Comment by ArgoZhang** [comment]
@densen2014 
改好啦。
