### ISSUE TITLE
Table EditTemplate 畫面刷新問題

### ISSUE THREAD

**Issue by a0926019412** [dotnetcore/BootstrapBlazor#462]
請問, 我想在edittemplate 裡面刻動態畫面
ex 兩個下拉選單 A,B (select), A下拉式選單 根據B下拉式選單選擇項目產生不同的項目

我有試著使用StateHasChanged 但編輯頁面的內容似乎無法更新
有建議的做法嗎? 或只能自己刻component 放在edittemplate 中?

謝謝

**Comment by ArgoZhang** [comment]
@a0926019412 对的只能自己做 `Component` 放到 `EditeTemlate` 中
