### ISSUE TITLE
bug(AutoFill): 组件只响应主键盘区的Enter按键，不响应小键盘区的Enter按键 

### ISSUE THREAD

**Issue by DebugClown** [dotnetcore/BootstrapBlazor#4622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

神奇的bug：AutoFill输入后按下小键盘区Enter，无响应，但此时按下主键盘区Enter，有响应。
确认小键盘区Numlock灯亮，排除人为操作问题
多台电脑全部出现这个问题，排除硬件问题
![image](https://github.com/user-attachments/assets/16b9a850-0770-4ada-af17-9193314937b6)

### Expected Behavior

应该响应小键盘区Enter

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

无

### .NET Version

.net 8

**Comment by ArgoZhang** [comment]
@DebugClown 不神奇，因为我键盘没有小键盘。没写小键盘的值

**Comment by DebugClown** [comment]
@ArgoZhang 原来是这样。。。麻烦请增加上小键盘响应吧。

**Comment by DebugClown** [comment]
@ArgoZhang   关于AutoFill，如果过滤文本框保持为空，此时直接在组件上按下回车键，会自动把列表第一项选中，我认为这是一个问题。

例如：在某实际业务中，用户此时通过回车按键从上一个组件跳转到这个组件，他并不想选择，按下回车准备跳转到下一个组件。
而此时组件就自动选中第一个项目了。

我不确定这是否算是bug：如果一定要这样设计界面功能，这个问题无法绕过。我是否可以单独提交一个bug？
