### ISSUE TITLE
Question(Editor): how do you customize Editor to do these things...

### ISSUE THREAD

**Issue by celadaris** [dotnetcore/BootstrapBlazor#4626]
### Which class is this unit test associated with?

in the editor view, the enter key inserts a paragraph but i want it to change it to insert something else, maybe something like `\n<br>` but im not sure if i can? im aware that using shift+enter will do this, but I want just the enter key to do this.

Also is it possible to change the theme of the codeview? summernote has the possibility of doing this, i just dont know how to do it in bootstrapblazor or if its possible.
```[tasklist]
### Tasks
- [ ] https://github.com/dotnetcore/BootstrapBlazor/issues/4632
```

**Comment by celadaris** [comment]
i made a project, its not the best code ill admit, but basically it creates a summernote editor, and for some reason it creates it within the editor? i dont know why, but anyway if you delete the code in the first summernote editor by editing it in the code view then switch into editormode, then type, press enter, and just play with it to get the idea of the functionality then you'll see the effect that i want, its basically the same as pressing shift and enter, but at least you can see the code, not sure if that helps.

[summernoteEnter.zip](https://github.com/user-attachments/files/17684146/summernoteEnter.zip)

**Comment by celadaris** [comment]
actually I think this one works better, basically it works like this:

1. when checking text, only check in the same line of text, use newlines to verify
2. ignore html tags when checking if there is text
3. if there is text before the cursor and text after the cursor then use one br element
4. if there is no text after the cursor, but there is text before the cursor then use two br tags
5. if there is no text after or before the cursor then only use one `<br>` element
6. put the cursor after the second generated `<br>` element if there is a second one, if not use the first `<br>` element

I used claude.ai to generate the code I'm not gonna lie. still the generated `<p></p>` are getting in the way and `&nbsp;` characters are annoying
[summernoteEnter.zip](https://github.com/user-attachments/files/17684896/summernoteEnter.zip)

**Comment by ArgoZhang** [comment]
@celadaris thank you for submit issue.

1. custom action
So far there is no code or design to provide custom behavior functionality like convert `enter` to `br`.

2. theme
not yet. this can be put on the next milestone

**Comment by celadaris** [comment]
Would it be possible to add that kind of functionality? Because if not, then there is a good chance it won't work for my project getting the spacing right is very important 🙇‍♂️

**Comment by ArgoZhang** [comment]
@celadaris sure. Let's try it

**Comment by ArgoZhang** [comment]
@celadaris To be honest, this issue should be fixed by `summernote`

**Comment by ArgoZhang** [comment]
@celadaris 

add `dark` theme for `editor`. does it meet your needs?

![image](https://github.com/user-attachments/assets/df6f9d1d-b26f-4eea-83e5-e368a86e83c7)

**Comment by celadaris** [comment]
it looks good, but i was wondering if there was a chance you could implement a light mode for the code editor itself, kind of like how it appears in:
https://summernote.org/examples/

when you click the code eitor button, it has that white background and black text, with text highlighting the code is green, but a white background with black text is okay if its possible.

and as for switching enter to function as <br> maybe ill ask summernote, im not too sure what to ask for but ill give it a try.

**Comment by ArgoZhang** [comment]
@celadaris hi. i had bump `9.0.0-beta04` for support `onEnter` callback.

[summernoteEnter.zip](https://github.com/user-attachments/files/17688037/summernoteEnter.zip)

```
window.BootstrapBlazor.SummerNote.callbacks.push({
    id: 'testEditor',
    onEnter: onEnter
});
```

this is a new feature for handler summernote callbacks. for now. i only support the `onEnter` callback. If you need more callbacks, you can submit a PR.

**Comment by celadaris** [comment]
its not so much about the theme choices, while it would be nice to choose different themes im more focused on having the white background and black text when pressing on the code editor button, its available on the default theme in summernote, so i think it can be used in bootstrapblazor maybe?

![image](https://github.com/user-attachments/assets/a1eda82a-694a-44e2-a324-03028842d759)

**Comment by ArgoZhang** [comment]
@celadaris The example on summernote's official website uses the bootstrap3 style. Our component uses bootstrap5 so it looks different. It is also difficult for us to create a separate 3 style for this component. If you really want the style of their official website, I personally suggest you put the style into your own project

**Comment by celadaris** [comment]
ah, gotcha. Thank you
