### ISSUE TITLE
feat(Layout-Tab模式): 希望可以增加Layout的Tab模式时可以获取到Tab组件的对象

### ISSUE THREAD

**Issue by chendx-github** [dotnetcore/BootstrapBlazor#4627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

我想要实时修改Tabitem的标题，但是没有方法可以修改

### Describe the solution you'd like

我希望可以获取到Tab的对象这样就可以操作tab的功能，包括标题

**Comment by ArgoZhang** [comment]
@chendx-github https://www.blazor.zone/tab

**Comment by chendx-github** [comment]
![image](https://github.com/user-attachments/assets/29748200-8631-4fd5-8334-7ad1683ceaea)
感谢！
