### ISSUE TITLE
feat(Editor): onInit callback

### ISSUE THREAD

**Issue by celadaris** [dotnetcore/BootstrapBlazor#4643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hi i mentioned earlier that i wanted to change `<p>` to `<br>` `onEnter` and it seemed to work great, but I also need `onInit` to be exposed too. I dont really know how to create a PR to be completely honest 

### Describe the solution you'd like

here is my implementation of what the change would look like
[Editor.razor.js.zip](https://github.com/user-attachments/files/17694688/Editor.razor.js.zip)

### Additional context

here is a sample project of it in action
[BootstrapBlazor.OnlyServer1.zip](https://github.com/user-attachments/files/17694706/BootstrapBlazor.OnlyServer1.zip)

**Comment by ArgoZhang** [comment]
@celadaris bump version `9.0.0-beta06`

**Comment by celadaris** [comment]
After further testing I noticed there was a memory leak, I asked claude.ai to work its magic and its working well for me so far, please carefully examine the code to make sure it works okay.

files that need to be changed:
[LeakFix.zip](https://github.com/user-attachments/files/17705649/LeakFix.zip)

sample project of it in action:
[BootstrapBlazor.OnlyServer1.zip](https://github.com/user-attachments/files/17705811/BootstrapBlazor.OnlyServer1.zip)

**Comment by ArgoZhang** [comment]
### quest 1
```
const editorClickHandler = async () => {
    editor.tooltip.hide()
    option.placeholder = editor.editorElement.getAttribute('placeholder')
    const toolbar = await invoker.invokeMethodAsync('GetToolBar')
    // ...
}
```
there is no `invoker` define. 

### quest 2 
can you explain in detail how to cause a memory leak and how it is caused in the code?

### qest 3
how to fixed this leak?

**Comment by celadaris** [comment]
quest 1:
i really honestly have no idea how summernote really works, ive been using claude for just about all of this, check out the last responses i hope it helps

[Claude-Identifying and Fixing Memory Leaks.md](https://github.com/user-attachments/files/17710251/Claude-Identifying.and.Fixing.Memory.Leaks.md)

quest 2:
i was only having problems on a server at work, which was why it took time between the first post and my suggested second post to see anything wrong, I dont know how to reproduce the memory leak on my work pc or my home pc, only on the work server when its deployed. i can give it a shot but it would have to be over the weekend because im too busy during the week. i can try to give you code.

the problem was something like i had a summernote Editor being launched in a Dialog and for some reason loading it would make [mjml.net](https://github.com/SebastianStehle/mjml-net) render inconsistent results, it felt like a memory leak, and when i asked claude.ai to fix memory leaks they were gone.

quest 3:
i have no idea, but the code from the LeakFix.zip sure does work for me! Lmao, im at home right now i cant access my other code right now. but i didnt really change anything from LeakFix.zip, its been working well so far. it might have problems im not sure...

**Comment by celadaris** [comment]
okay, after reviewing the code i was using in my project i forgot to use the changed Editor.razor.cs file! And everything seems to be working so i guess there's no problems!

So because i am using an unchanged file and im not seeing any problems i guess im good 😅

I personally need light mode for my project because my users request it, so i will be using the summernote editor from the source code (just like how i have it in the project below) and will be exposing onEnter and onInit myself, however it would still be cool to see those callbacks exposed in the official bootstrapblazor.summernote project, i think they were removed from the latest src files, anyway i think that's all i dont know if this answers questions? please let me know if you need anything, if not you can close this...
[BootstrapBlazor.OnlyServer1.zip](https://github.com/user-attachments/files/17788016/BootstrapBlazor.OnlyServer1.zip)

**Comment by celadaris** [comment]
my apologies i didnt see this line of code yesterday:
``` cs
const reloadCallbacks = (id, option) => {
    const events = ['Blur', 'BlurCodeview', 'Change', 'ChangeCodeview', 'DialogShown', 'Enter', 'Focus', 'ImageLinkInsert', 'ImageUploadError', 'Init', 'Keydown', 'Keyup', 'Mousedown', 'Mouseup', 'Paste', 'Scroll'];

    events.forEach(event => {
        option.callbacks[`on${event}`] = function () {
            const callbacks = window.BootstrapBlazor?.SummerNote?.callbacks;
            const cb = callbacks?.find(i => i.id === id);
            cb?.[`on${event}`]?.apply(this, arguments);
        };
    });
}
```
ive tested how it works with my project and it works great! if there are no questions than this can be closed.

**Comment by celadaris** [comment]
i think there is a small problem in the latest 9.0.0 when `ShowSubmit="false"` the value associated with `@bind-Value` isnt being changed and the `OnValueChanged` callback isn't being triggered.

[SummernoteTest.zip](https://github.com/user-attachments/files/17792575/SummernoteTest.zip)

**Comment by ArgoZhang** [comment]
@celadaris Thanks for submitting the issue. I will reproduce the issue later and try to fix it.

**Comment by ArgoZhang** [comment]
@celadaris bump version `9.0.1`

https://www.nuget.org/packages/BootstrapBlazor.SummerNote/9.0.1

please let me know if you have any questions.
