### ISSUE TITLE
feat(IEnumerable<DynamicObject>.Sort): Using Sort function on IEnumerable<DynamicObject> returns unsorted list

### ISSUE THREAD

**Issue by cervinkamichal0** [dotnetcore/BootstrapBlazor#4647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In my project I am using a Table that uses DynamicContext. When I tried to implement the sorting logic, I used the Sort function on the IEnumerable<DynamicObject>, since thats what represent rows in my table. This function always returns the same unsorted List that was given to it.  

### Expected Behavior

The Sort function should return a List that is sorted by the arguments given to it.

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

[REPRODUCTION REPO](https://github.com/cervinkamichal0/SortBugReproduction)

The reproduction code is all located in the Home.razor. The method that test Sort function is ran in OnInitialized method and the results are visualized on the site using ListViews

### .NET Version

8.0.4

### Anything else?

ASP.NET Core 8.0.8
Visual Studio 2022

dotnet --info otput:

NET SDK:
 Version:           9.0.100-rc.1.24452.12
 Commit:            81a714c6d3
 Workload version:  9.0.100-manifests.67cd1eb6
 MSBuild version:   17.12.0-preview-24422-09+d17ec720d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [maui-windows]
   Installation Source: VS 17.12.35323.107, VS 17.11.35312.102
   Manifest Version:    9.0.0-rc.1.24453.9/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.maui\9.0.0-rc.1.24453.9\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.12.35323.107, VS 17.11.35312.102
   Manifest Version:    17.5.9270-net9-rc1/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.maccatalyst\17.5.9270-net9-rc1\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.12.35323.107, VS 17.11.35312.102
   Manifest Version:    17.5.9270-net9-rc1/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.ios\17.5.9270-net9-rc1\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.12.35323.107, VS 17.11.35312.102
   Manifest Version:    35.0.0-rc.1.80/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.android\35.0.0-rc.1.80\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: VS 17.12.35323.107, VS 17.11.35312.102
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      9.0.0-rc.1.24431.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  8.0.400 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.6.24328.19 [C:\Program Files\dotnet\sdk]
  9.0.100-rc.1.24452.12 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.1.24431.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24327.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by cervinkamichal0** [comment]
Link to the repro project: [REPRODUCTION REPO](https://github.com/cervinkamichal0/SortBugReproduction)

**Comment by ArgoZhang** [comment]
@cervinkamichal0 hi

```
private void TestSort()
{
    
    Unsorted = DataTableDynamicContext.GetItems();

    //Trying to simulate sorting IEnumerable<DynamicObject> in a Table
    SortedById = Unsorted.Sort("ID", SortOrder.Asc);

    SortedByName = Unsorted.Sort("Name", SortOrder.Asc);
}
```

In this code, the type `Unsorted ` is `IDynamicObject`. There is no Property name of `Id` or `Name`. So the `Sort` extension method should not work as expected.

**Comment by cervinkamichal0** [comment]
Hello @ArgoZhang ,
thank you for your response. 

I am a bit confused now. When I debug the code I see, that there are properties `ID `and `Name`:

![image](https://github.com/user-attachments/assets/87cf29b2-d3e4-4521-8c3d-3ef3e8f841f8)

Or am I missing something?

**Comment by ArgoZhang** [comment]
@cervinkamichal0 The `Sort` is an extension method. the real work code is below

https://github.com/dotnetcore/BootstrapBlazor/blob/b73c3ec300793f524f53d0e316f36101e694f93d/src/BootstrapBlazor/Extensions/LambdaExtensions.cs#L453

```
var pi = typeof(TItem).GetPropertyByName(propertyName);
if (pi != null)
{
    var methodName = sortOrder == SortOrder.Desc ? nameof(OrderByDescendingInternal) : nameof(OrderByInternal);
    ret = query.AsQueryable().InvokeSortByPropertyInfo(methodName, pi);
}
```

the `TItem` in your code is `IDynamicObject` so there is no `Id` or `Name`

but the VS debug window shows a dynamic emit generate class. so there is an `Id`.

Thanks for your question, I will try to make it work later.

**Comment by ArgoZhang** [comment]
@cervinkamichal0 hi

I looked at your example. You should sort first, then generate DataTable, and then generate DataTableDynamicContext. What do you think?

**Comment by ArgoZhang** [comment]
@cervinkamichal0 

will be released in the next version.

![image](https://github.com/user-attachments/assets/da6ec26b-95ec-4f1b-91db-c1569caaadb2)

**Comment by ArgoZhang** [comment]
@cervinkamichal0 please try `9.0.2-beta01`

**Comment by cervinkamichal0** [comment]
Hello @ArgoZhang ,
thank you very much for a quick solution. It seems to be working great now.
