### ISSUE TITLE
bug(Table): 编辑弹出框，列选被遮挡

### ISSUE THREAD

**Issue by Jiang2020426** [dotnetcore/BootstrapBlazor#4654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Table组件，当设置ScrollingDialogContent="true"时，编辑弹出框的列选会被遮挡，底部按钮的padding值也会变大

### Expected Behavior

能否不遮挡列选，底部按钮样式不变

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

![PixPin_2024-11-14_10-11-29](https://github.com/user-attachments/assets/e6f645e5-d750-482e-b469-7b8856afff1c)
![PixPin_2024-11-14_10-12-36](https://github.com/user-attachments/assets/20f1290b-9a0e-45d1-a653-820eacd619ee)
[BootstrapBlazorApp7.zip](https://github.com/user-attachments/files/17741925/BootstrapBlazorApp7.zip)

### .NET Version

NET9

**Comment by ArgoZhang** [comment]
`IsPopover` 这个问题都快被问烂了吧
