### ISSUE TITLE
 bbapp-per 下的布局控件下的 ShowCollapseBar 无效

### ISSUE THREAD

**Issue by wgh2019** [dotnetcore/BootstrapBlazor#4662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

通过命令
`dotnet new bbapp-per`
创建的项目布局异常

 bbapp-per 下的布局控件下的 ShowCollapseBar、UseTabSet   无效

### Expected Behavior

 bbapp-per 下的布局控件下的 ShowCollapseBar  UseTabSet无效

### Interactive render mode

Interactive Auto (Server, then client)

### Steps To Reproduce

 bbapp-per 下的布局控件下的 ShowCollapseBar  UseTabSet无效

### Exceptions (if any)

 bbapp-per 下的布局控件下的 ShowCollapseBar 无效

### .NET Version

9

**Comment by wgh2019** [comment]
![C79EAC1B-250F-4fa7-A243-5DE391F8BE4C](https://github.com/user-attachments/assets/3b056260-9f7f-4ef5-8c44-fd9317958bb7)

**Comment by ArgoZhang** [comment]
@wgh2019 感谢提交 issue 能否帮忙点一下右上角 `star` 正在复现修复这个问题

**Comment by ArgoZhang** [comment]
@wgh2019 已修复 更新 `v9.0.3` 即可，需要稍等更新 `BootstrapBlazor` 组件库 `9.0.1`

**Comment by wgh2019** [comment]
要等9.0.3版本修复吗
&nbsp;


尘土飞扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Argo ***@***.***&gt;; 
发送时间: 2024年11月23日(星期六) 下午3:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dotnetcore/BootstrapBlazor]  bbapp-per 下的布局控件下的 ShowCollapseBar 无效 (Issue #4662)














 
@wgh2019 已修复 更新 v9.0.3 即可，需要稍等更新 BootstrapBlazor 组件库 9.0.1
