### ISSUE TITLE
甘特图在Docker环境下启动的程序无法使用

### ISSUE THREAD

**Issue by chendx-github** [dotnetcore/BootstrapBlazor#4690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/9a8d952d-9c83-4fcb-b646-71b60ac6b3b1)

同一次编译的代码放在windows上是可以正常执行的

我使用的 docker镜像是 bitnami/aspnet-core:8

### Expected Behavior

应该正常渲染内容

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

 bitnami/aspnet-core:8

### .NET Version

8

### Anything else?

1

**Comment by chendx-github** [comment]
我刚刚又测试了一次使用的是Deepin系统还是有问题，说明至少在Ubuntu下面是这样的，可能所有Linux下都有这个问题
![image](https://github.com/user-attachments/assets/c4d4182b-6ca4-4a34-a35c-e6c4ad7233e0)
![image](https://github.com/user-attachments/assets/74def2e5-f430-4ab7-b88f-1d07a8c31ed4)

**Comment by chendx-github** [comment]
应该是我配置问题，我昨天晚上使用示例的代码再试是没问题的，只有在我自己的项目中才会这样

**Comment by ArgoZhang** [comment]
@chendx-github 我感觉是不是被干扰了。需要复现搭建环境，我这里没有这些条件

**Comment by chendx-github** [comment]
我使用了模版(RenderFragment)的方式解决了这个问题，但是这个问题确实在windows上存在着差异具体内容如下：
出现问题的地方：
![image](https://github.com/user-attachments/assets/7fce2248-986f-4570-84a5-a7cbbdafbf2c)
原来直接将甘特图放在html中 如果是直接使用固定的内容例如示例中的那种方式则不会出现问题
![image](https://github.com/user-attachments/assets/83020607-6235-4181-8edd-d19ddac8171f)
如果是使用 protected override async Task OnInitializedAsync() 进行加载然后给 Items赋值的情况下，Linux中就会出现我那种情况
解决方法：
使用了模版(RenderFragment)的方式
@gantt
然后在 protected override async Task OnInitializedAsync() 加载完数据之后再直接将内容显示在界面上则不会出现问题
![image](https://github.com/user-attachments/assets/9200e8c5-d18c-4592-b168-f2ea8d7a7687)

**Comment by chendx-github** [comment]
我无法在新的项目复现这个问题了

**Comment by ArgoZhang** [comment]
@chendx-github 感谢感谢，我也研究一下。看看能否改进一下
