### ISSUE TITLE
bug(Checkbox): Checkbox在WebAssembly模式下不显示选中状态

### ISSUE THREAD

**Issue by LeiLei-Liu** [dotnetcore/BootstrapBlazor#4710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Checkbox在Server模式显示正常，在WebAssembly模式下不显示选中状态。

### Expected Behavior

修复Bug。

### Interactive render mode

Interactive Auto (Server, then client)

### Steps To Reproduce

复现工程见附件，步骤如下：
1. 运行工程，点击Counter，此时渲染模式为Server，点击页面中的测试Checkbox，显示正常；
2. 点击浏览器刷新按钮，此时渲染模式为WebAssembly，测试的Checkbox数据绑定正常，但不显示选中状态。

![1](https://github.com/user-attachments/assets/6792e2a2-b7dc-450b-a52d-29c957332d8c)
![2](https://github.com/user-attachments/assets/c7156e42-3940-4a35-9839-1b6862e10284)

[Demo.zip](https://github.com/user-attachments/files/17838484/Demo.zip)

### .NET Version

.Net 9.0

**Comment by ArgoZhang** [comment]
@LeiLei-Liu 已修复，稍等发包 `v9.0.1`

**Comment by LeiLei-Liu** [comment]
@ArgoZhang 经测试，已修复，感谢！
