### ISSUE TITLE
表格的分组功能不生效。

### ISSUE THREAD

**Issue by susan-ontrack** [dotnetcore/BootstrapBlazor#4712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

table里我使用了group name和grouporder，但在编辑模式下，只会显示一个第一个分组。但我设置了三个分组。

### Expected Behavior

显示三个分组

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

 <Table @ref="MainTable" TItem="CustomerViewModel"
        IsPagination="true"
        PageItemsSource="@PageItemsSource"
        IsStriped="true"
        IsBordered="true"
        ShowToolbar="true"
        ShowSearch="true"
        ShowExtendButtons="true"
        ShowEditButton="false"
        ShowDeleteButton="false"
        ShowRefresh="true"
        UseColumnGroups="true"
        OnQueryAsync="@OnQueryAsync"
        OnSaveAsync="OnSaveCustomerAsync"
        OnDeleteAsync="DeleteCustomerAsync">
     <TableColumns>

         <TableTemplateColumn Text="Basic Information" Visible="false" GroupName="basic" GroupOrder="1" />
         <TableColumn @bind-Field="@context.Id" Text="Company Id" Searchable="true" Ignore="true" GroupName="basic">
         </TableColumn>
         <TableColumn @bind-Field="@context.CustomerName" Text="Name" Searchable="true" GroupName="basic" />
         <TableColumn @bind-Field="@context.WorkPhone" Text="Work Phone" IsVisibleWhenEdit="true" IsVisibleWhenAdd="true" GroupName="basic" />

         <TableTemplateColumn Text="Address" Visible="false" GroupName="address" GroupOrder="2" />
         <TableColumn @bind-Field="@context.Street" Text="Street" Visible="false" IsVisibleWhenEdit="true" IsVisibleWhenAdd="true" GroupName="address"/>
         <TableColumn @bind-Field="@context.Suburb" Text="Suburb" Visible="false" IsVisibleWhenEdit="true" IsVisibleWhenAdd="true" GroupName="address" />

         <TableTemplateColumn Text="Bank" Visible="false" GroupName="bank" GroupOrder="3" />
         <TableColumn @bind-Field="@context.BankName" Text="Bank Name" Visible="false" IsVisibleWhenEdit="true" IsVisibleWhenAdd="true" GroupName="bank" />
         <TableColumn @bind-Field="@context.BranchName" Text="Branch Name" Visible="false" IsVisibleWhenEdit="true" IsVisibleWhenAdd="true" GroupName="bank" />  
     </TableColumns>
 </Table>

### .NET Version

9.0.1

**Comment by ArgoZhang** [comment]
@susan-ontrack 请提交复现工程，否则无法确定是否 bug
