### ISSUE TITLE
右键菜单无法生效

### ISSUE THREAD

**Issue by javazfj** [dotnetcore/BootstrapBlazor#4720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

右键菜单无法生效

### Expected Behavior

右键菜单生效

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

[BootstrapBlazorApp2.zip](https://github.com/user-attachments/files/17866179/BootstrapBlazorApp2.zip)

### Exceptions (if any)

运行项目，点击左边菜单Index，ListView中的Card右键失效

### .NET Version

8

**Comment by ArgoZhang** [comment]
@javazfj 不是这样用的吧。建议认真看看文档先。

https://www.blazor.zone/context-menu
