### ISSUE TITLE
AutoFill 控件在搜索的时候会无限执行OnCustomFilter事件

### ISSUE THREAD

**Issue by zhangtuoyu** [dotnetcore/BootstrapBlazor#4729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

AutoFill  第一次控件获取焦点的时候,会不断的执行 OnCustomFilter 事件,searchText 参数是为null.
如果数据量在500以内,界面上不会有卡顿的感知
如果数据量在3000左右的时候,会明显的卡顿.
选择完成后,便不会继续执行 OnCustomFilter 事件

<AutoFill DisplayText="客户" TValue="ItemModel" Value="Customer" Items="CustomerItems" Debounce="10" OnCustomFilter="OnCustomFilter" class="mb-3" OnGetDisplayText="OnGetDisplayText">
                    <Template>
                        <div class="d-flex">
                            <div class="ps-2">
                                <div>@context.FNumber</div>
                            </div>
                            <div class="ps-2">
                                <div>@context.FName</div>
                            </div>
                        </div>
                    </Template>
                </AutoFill>
                
    private Task<IEnumerable<ItemModel>> OnCustomFilter(string searchText)
    {
        var items = string.IsNullOrEmpty(searchText) ? CustomerItems : CustomerItems.Where(i => i.FName!.Contains(searchText) );
        return Task.FromResult(items);
    }

### Expected Behavior

AutoFill 中的输入值有变化的时候才应该触发 OnCustomFilter 事件

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

无

### Exceptions (if any)

没有异常报出,就是会无限循环

### .NET Version

9.0

### Anything else?

BootstrapBlazor 版本是最新的9.0.1版本

**Comment by densen2014** [comment]
测试代码
```
    public static List<Foo> GenerateFoo(IStringLocalizer<Foo> localizer, int count = 3000) => Enumerable.Range(1, count).Select(i => new Foo()
    {
        Id = i,
        Name = localizer["Foo.Name", $"{i:d4}"],
        DateTime = System.DateTime.Now.AddDays(i - 1),
        Address = localizer["Foo.Address", $"{Random.Next(1000, 6000)}"],
        Count = Random.Next(1, 3000),
        Complete = Random.Next(1, 3000) > 50,
        Education = Random.Next(1, 3000) > 50 ? EnumEducation.Primary : EnumEducation.Middle,
        ReadonlyColumn = Random.Next(10, 50)
    }).ToList();
```

页面
```
    <AutoFill TValue="Foo" Value="Model" Items="Items" OnCustomFilter="OnCustomFilter"
              OnSelectedItemChanged="OnSelectedItemChanged" OnGetDisplayText="OnGetDisplayText" class="mb-3" >


    [NotNull]
    private IEnumerable<Foo>? Items { get; set; }

    protected override void OnInitialized()
    {
        base.OnInitialized();

        Items = Foo.GenerateFoo(LocalizerFoo);
        Model = Items.First();
    }

    private Task<IEnumerable<Foo>> OnCustomFilter(string searchText)
    {
        var items = string.IsNullOrEmpty(searchText) ? Items : Items.Where(i => i.Count > 50 && i.Name!.Contains(searchText));
        System.Console.WriteLine($"{searchText}=>count {items.Count()}");
        return Task.FromResult(items);
    }
```
执行

![image](https://github.com/user-attachments/assets/b235e54f-d825-4e59-aa96-6348ff1b4e64)


结论: 未能复现所描述问题

**Comment by zhangtuoyu** [comment]
感谢.是我调试的时候,页面会不断的刷新重新获取焦点导致的问题.非常感谢解答.
