### ISSUE TITLE
feat(Popover): 能否实现点击按钮弹出 Popover 弹出框后，失去焦点时自动关闭？

### ISSUE THREAD

**Issue by huangyy21** [dotnetcore/BootstrapBlazor#4734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

点击激活弹出框后，点击其他地方自动关闭弹出框

**Comment by ArgoZhang** [comment]
@huangyy21 

···
/// <summary>
/// 获得/设置 弹窗触发方式 默认 click 可设置 hover focus
/// </summary>
[Parameter]
public string? Trigger { get; set; }
···

`hover focus` 方式无法交互，适合仅信息

**Comment by huangyy21** [comment]
请问有办法在可交互的情况下实现吗？
