### ISSUE TITLE
How to check if Table is in Edit Mode / OnCancelSave callback?

### ISSUE THREAD

**Issue by EliasIsmail** [dotnetcore/BootstrapBlazor#4749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am currently using the Table component with the Edit functionality for the rows. I want to be able to know when a row in the table is currently being edited, which would correlate to the entire table being in edit-mode, since only one row can be edited at a time.

I currently have a global bool **TableIsInEditMode**, that gets set to true, every time the _OnEditAsync_ callback is called for the table. This bool is then set to false in the _OnAfterSaveAsync_ callback. This works fine. However, if the user decides to cancel the editing, instead of saving, the **TableIsInEditMode** bool is never set to false.

Therefore, my question is: Is there any way of knowing when the Table component is in Edit Mode? Alternatively, is there any way to access/control the callback that happens after the user cancels the edit? (I.e. clicks the "Cancel" extend button, instead of the "Save" extend button)

### Expected Behavior

That the Table component contained a "IsInEdit" field, or a AfterCancelSaveAsync (or similar) callback was available.

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

Create a Table and use Edit functionality.

### .NET Version

8.0.400

**Comment by ArgoZhang** [comment]
@EliasIsmail could you submit a repro project? I wanna see the whole logic about this

**Comment by EliasIsmail** [comment]
Hi Argo, 

Would the below suffice? It is just the logic containing the Edit functionality. As you can see here, I have a Switch that should be disabled, when the Table is in Edit Mode. I have tried to use the AfterModifyAsync callback as well, but this does not trigger when user cancels a row edit.


```
<Table TItem="RowObject" @ref="_table" class="object-table"
            ShowExtendButtons="true" EditMode="EditMode.InCell" @onkeydown="PreventSubmit"
            IsPagination="true" PageItemsSource="@_pageItemsSource"
            IsStriped="false" IsBordered="true" ShowLoading="true" DoubleClickToEdit="@ShouldBeAbleToEdit()"
            ShowToolbar="true" ShowLineNo="true" LineNoText="No." ShowSkeleton="true"
            SortAscText="Sorting by: Asc" SortDescText="Sorting by: Desc" UnsetText="Sorting by: N/A"
            ShowDefaultButtons="true" ShowExtendDeleteButton="false" EditDialogLabelAlign="Alignment.Left"
            ShowExtendEditButton="@ShouldBeAbleToEdit()" IsMultipleSelect="true" ShowDeleteButton="true"
            IsAutoRefresh="true" AutoRefreshInterval="@_autoRefreshInterval"
            EmptyText="@_tableEmptyText" ShowEmpty="true" ShowToastAfterSaveOrDeleteModel="false"
            ShowEditButton="false" ShowAddButton="false"
            OnQueryAsync="@(o=>OnQueryAsync(o, _selectedObjects, RowObjectType))"
            OnDeleteAsync="OnDeleteAsync"
            OnSaveAsync="OnSaveAsync"
            OnEditAsync="OnEditAsync"
            OnAfterSaveAsync="OnAfterSaveAsync"
            OnAfterModifyAsync="OnAfterModifyAsync"
            SelectedRowsChanged="OnSelectedRowsChanged">
            <TableToolbarTemplate>
                @if (ShowTableModeSwitch())
                {
                    <div class="d-inline-block me-5" style="vertical-align: -48%">
                        <div>
                        <label>Table Mode</label>
                    </div>

                    <Tooltip Placement="Placement.Left" Title="@TooltipText.TableModeHtml" IsHtml="true" Sanitize="false">
                        <Switch IsDisabled="@TableIsInEditMode()" @bind-value="_isOnPremMode" OnValueChanged="OnModeChanged" ShowLabel="false" OnColor="Color.Success" OffColor="Color.Primary" OnText="On-Prem" OffText="Cloud"></Switch>
                    </Tooltip>
                </div>
                }
</TableToolbarTemplate>
</Table>
    
@code {
     private bool _isInEditMode = false;

     private Task OnEditAsync(RowObject rowObject)
    {
        _isInEditMode = true;
        _currentlyEditedObject = rowObject;
        return Task.CompletedTask;
    }

    private Task OnAfterModifyAsync()
    {
        _isInEditMode = false;
        return Task.CompletedTask;
    }

    private Task OnAfterSaveAsync(RowObject rowObject)
    {
        _isInEditMode = false;
        ToastService.ShowInfo("Row was successfully updated.");
        return Task.CompletedTask;
    }

    private bool TableIsInEditMode()
    {
        return _isInEditMode;
    }
}
```

**Comment by ArgoZhang** [comment]
@EliasIsmail thank you for the reply. table component provider a parameter `EditDialogCloseAsync`

```
[Parameter]
public Func<TItem, bool, Task>? EditDialogCloseAsync { get; set; }
```

you can check the second parameter for `Cancel` or `Save`. anyway I think if provide an OnCancalCallback method, that would meet your needs, right?

**Comment by EliasIsmail** [comment]
Hi Argo,

I saw that you added the **OnAfterCancelSaveAsync** to one of the new betas. Unfortunately, this callback is not fired (as I expect was the idea) when the **Cancel** button is pressed, in Inline edits. Could it be that the callback is bound to the wrong button event?

![image](https://github.com/user-attachments/assets/760585ae-4fc9-4688-acbf-0ced6344769d)

**Comment by ArgoZhang** [comment]
@EliasIsmail  sure. work on it.

**Comment by ArgoZhang** [comment]
@EliasIsmail bump version `9.1.3-beta03`

**Comment by EliasIsmail** [comment]
It works perfectly! Thank you Argo!!
