### ISSUE TITLE
bug(Select): 切换下拉框的选项不生效

### ISSUE THREAD

**Issue by Idle-wang** [dotnetcore/BootstrapBlazor#4765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

razor代码：
![image](https://github.com/user-attachments/assets/2abdfa35-d007-4c86-b428-9ca2240f8378)
C#获取select数据源代码
![image](https://github.com/user-attachments/assets/131d0d7f-6e71-4512-aa1c-914037a7fe48)
页面首次加载时，切换下拉框的选项不生效，需要第二次才能生效；如果不添加空值，则可以正常切换选项
![image](https://github.com/user-attachments/assets/71bfffb2-3644-482d-9e43-b838ab3ee37f)

**Comment by ArgoZhang** [comment]
@Idle-wang 请按照 issue 要求提供复现工程

**Comment by Idle-wang** [comment]
[Demo.zip](https://github.com/user-attachments/files/17971625/Demo.zip)
table页面，新建或搜索时，姓名列第一次无法选中
![image](https://github.com/user-attachments/assets/8c15f32c-c446-4874-a2a4-cd3c9385b6af)

**Comment by ArgoZhang** [comment]
@Idle-wang 提示有病毒

**Comment by Idle-wang** [comment]
> @Idle-wang 下载包提示有病毒

我不知道为什么会提示病毒，我用的公司电脑打包上传的，不过代码很简单
在模板中，首先将实体类中Name改为下拉框呈现
  [Required(ErrorMessage = "{0}不能为空")]
  [AutoGenerateColumn(Order = 10, Filterable = true, Searchable = true ,ComponentType=typeof(Select<string>))]
  [Display(Name = "姓名")]
  public string? Name { get; set; }
然后再设置下拉框的数据源
`<Table TItem="Foo" AutoGenerateColumns="true" class="table-demo"
       IsPagination="true" PageItemsSource="PageItemsSource"
       IsStriped="true" IsBordered="true"IsMultipleSelect="true"
       ShowSkeleton="true" ShowToolbar="true" ShowSearch="true" ShowExtendButtons="true"
       OnQueryAsync="OnQueryAsync" OnSaveAsync="OnSaveAsync" OnDeleteAsync="OnDeleteAsync">
    <TableColumns>
        <TableColumn @bind-Field="@context.Name" Items="GetNames(context)" />
        <TableColumn @bind-Field="@context.Hobby" Items="GetHobbys(context)" />
    </TableColumns>
</Table>
  private IEnumerable<SelectedItem> GetNames(Foo item) => new[]
  {
      new SelectedItem ("", "請選擇..."),
      new SelectedItem ("Beijing", "北京"),
      new SelectedItem ("Shanghai", "上海"),
  };
`

**Comment by densen2014** [comment]
![image](https://github.com/user-attachments/assets/cffd8640-0b98-4bf5-ab89-7dfa67da0d92)

**Comment by Idle-wang** [comment]
[Demo.zip](https://github.com/user-attachments/files/18034116/Demo.zip)
看看这个能不能行吧，要是还报病毒我也没办法了

**Comment by ArgoZhang** [comment]
@Idle-wang 这个可以的，我试试看，如果是 bug 我修复一下

**Comment by Idle-wang** [comment]
这个问题已经修复了吗，我更新到9.1.2的版本试了一下，发现当满足以下条件的时候，下拉框第一次还是无法切换
1.设置自动生成表单维护 UI并设置组件类型为Select
  [AutoGenerateColumn(Order = 10, Filterable = true, Searchable = true,ComponentType=typeof(Select<string?>))]
  [Display(Name = "姓名")]
  public string? Name { get; set; }
2.设置下拉框的数据源，且数据源中包含空值
<TableColumn @bind-Field="@context.Name" Items="GetNames(context)" />
private IEnumerable GetNames(Foo item) => new[] { new SelectedItem ("", "請選擇..."), new SelectedItem ("Beijing", "北京"), new SelectedItem ("Shanghai", "上海"), }; 

然后我使用EditTemplate设置下拉框时就没有这个问题，但是使用EditTemplate的时候，TableColumn的IsReadonlyWhenEdit属性不生效,就达不到在新建时可以维护，在编辑时只读的效果了。

**Comment by ArgoZhang** [comment]
@Idle-wang 已经修复了啊。例子我试了一下是可以的

**Comment by Idle-wang** [comment]
@ArgoZhang 怎么我这边看起来还是不太行，编辑的时候可以，但是新建和搜索的时候还是不行。我还以为是.net 版本的问题换成9还是不行

**Comment by ArgoZhang** [comment]
@Idle-wang 再来复现例子吧
