### ISSUE TITLE
feat(RadioList): support generic SelectedItem

### ISSUE THREAD

**Issue by BrandonStudio** [dotnetcore/BootstrapBlazor#4773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In following demo, the value of `RadioList` is set to `ChartType.Line`.

.razor:
```cshtml
@{
  var types = new List<SelectedItem<ChartType>>
  {
    new() { Value = ChartType.Bar, Text = "柱状图" },
    new() { Value = ChartType.Pie, Text = "饼图" },
  };
}
<RadioList TValue="ChartType" Items="types" IsButton="true" @bind-Value="@ChartType"></RadioList>
```

.razor.cs:
```csharp
private ChartType ChartType { get; set; } = ChartType.Bar;
```

## Cause
When checking current and default value, it is checking whether `SelectedItem.Value` which is of type `string` rather than generic type `TValue`, resulting in inequality (L73) and `null` return value of `FirstOrDefault()` (L75).
![image](https://github.com/user-attachments/assets/f028fa92-f74b-4937-9484-d901439b1750)
ref: https://github.com/dotnetcore/BootstrapBlazor/blob/b9869e917adb443b409a29c4e3ce36f3af822357/src/BootstrapBlazor/Components/Radio/RadioList.razor.cs#L73-L76

### Expected Behavior

`if` expression in L73 is `false`.
Even when it is `true` (current value has not been set), L75 should return `ChartType.Bar`, which is the first value of the given list.

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

Use `List<SelectedItem<ChartType>>` as source of `RadioList`.

.razor:
```cshtml
@{
  var types = new List<SelectedItem<ChartType>>
  {
    new() { Value = ChartType.Bar, Text = "柱状图" },
    new() { Value = ChartType.Pie, Text = "饼图" },
  };
}
<RadioList TValue="ChartType" Items="types" IsButton="true" @bind-Value="@ChartType"></RadioList>
```

.razor.cs:
```csharp
private ChartType ChartType { get; set; } = ChartType.Bar;
```

### .NET Version

8

**Comment by ArgoZhang** [comment]
@BrandonStudio 这个组件还不支持泛型数据源

```
@{
    var types = new List<SelectedItem>
    {
        new() { Value = "Bar", Text = "柱状图" },
        new() { Value = "Pie", Text = "饼图" },
    };
}

<RadioList TValue="ChartType" Items="types" IsButton="true" @bind-Value="@ChartType"></RadioList>

@code {
    private ChartType ChartType { get; set; } = ChartType.Bar;
}
```

这样即可

**Comment by ArgoZhang** [comment]
@BrandonStudio `SelectedItem<>` 是前两天加的功能。以前只有 `SelectedItem`

**Comment by ArgoZhang** [comment]
没时间弄这个细节。会支持的。只是时间的问题而已。类似组件还有好几个呢。

**Comment by j4587698** [comment]
这个TValue是微软要求的，blazor本身要求的，不是我们做的。它要求你必须有个泛型在这里，你没有就不行。你但凡看看blazor基础也不会有这个问题

**Comment by j4587698** [comment]
这里不是微软写的，但是本身Radio不止支持string，懂吗？radio还可以支持枚举，以及其他一些可以转换的类型。这里有TValue不代表什么都可以用，而代表支持不止一种，这个能明白嘛？

**Comment by ArgoZhang** [comment]
@BrandonStudio 不需要纠结这个了。以前老版本确实要必须写，现在都可以智能推断了

```
<RadioList Items="types" IsButton="true" @bind-Value="@ChartType"></RadioList>
```

这样写也毫无问题

**Comment by j4587698** [comment]
写之前先看例子，例子里不支持，就不要自己想着加。按照例子做你就遇不到问题了，你遇到的所有问题都是因为你没看例子，自己臆想的然后就开始做，然后回过头来又说自己遇到问题。
本来我们的RadioList就支持枚举，你按照例子的枚举用100%没问题的，你非要自己臆想一个做法，你不遇到问题谁遇到问题呢？

**Comment by j4587698** [comment]
没事，你慢慢黑着，但是这是我们的组件库，你拉黑也不影响我继续发issue。难受吧？

**Comment by ArgoZhang** [comment]
@BrandonStudio 已经实现了啊
