### ISSUE TITLE
bug(ExportPdfButton): 导出pdf控件的数据会丢失

### ISSUE THREAD

**Issue by oneguester01** [dotnetcore/BootstrapBlazor#4841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://www.blazor.zone/export-pdf-button
这个网页上导出pdf按钮，文本框、日期类型等控件数据都不能导出成pdf

### Expected Behavior

控件中的数据应该能导出pdf文件中

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

https://www.blazor.zone/export-pdf-button

### .NET Version

NET8.0

**Comment by ArgoZhang** [comment]
@oneguester01 已复现，我再研究一下想想办法
