### ISSUE TITLE
bug(Dropdown): 组件设置IsDisabled=true之后，再设置IsDisabled=false。下拉框无法弹出

### ISSUE THREAD

**Issue by PengYuee** [dotnetcore/BootstrapBlazor#4842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Dropdown组件设置IsDisabled=true之后，再设置IsDisabled=false。下拉框无法弹出

### Expected Behavior

恢复正常

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

1.在home页面，点击"测试"按钮
2.点击下拉框
[BlazorApp2.zip](https://github.com/user-attachments/files/18124475/BlazorApp2.zip)

### .NET Version

NET9.0

### Anything else?

![image](https://github.com/user-attachments/assets/3942b0de-e514-422b-817b-0b4dda4f062f)

**Comment by ArgoZhang** [comment]
@PengYuee 感谢提交 Issue 帮忙右上角点一下 star 支持一下项目。我来看看复现例子，如果是 bug 我修复一下

**Comment by ArgoZhang** [comment]
@PengYuee 确认是 bug ，已修复。稍后发包
