### ISSUE TITLE
bug: RepositoryUrl does not exist in WebsiteOptions

### ISSUE THREAD

**Issue by DanPFW** [dotnetcore/BootstrapBlazor#486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'WebsiteOptions' does not contain a definition for 'RepositoryUrl' and no accessible extension method 'RepositoryUrl' accepting a first argument of type 'WebsiteOptions' could be found (are you missing a using directive or an assembly reference?)	BootstrapBlazor.WebAssembly.ClientHost	C:\Users\\Documents\GitHub\BootstrapBlazor\src\Wasm\BootstrapBlazor.WebAssembly.ClientHost\ServicesExtensions.cs	51	Active

### Expected Behavior

successful compile

### Steps To Reproduce

clone repo and attempt rebuild all

**Comment by ArgoZhang** [comment]
@DanPFW Thank you for filing this issue. we will repro and fix it
