### ISSUE TITLE
bug(DockViewV2): Pin bug

### ISSUE THREAD

**Issue by celadaris** [dotnetcore/BootstrapBlazor#4886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

having the settings: `ShowPin="false"` and `ShowFloat="true"` doesn't show the float button

### Expected Behavior

the float button should appear, while the pin button shouldn't

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

```cs
<div style="height: calc(100vh - 100px);">
    <DockViewV2 Name="sampleName" IsLock="true" ShowPin="false" ShowFloat="true">
        <DockViewContent Type="DockViewContentType.Row">
            <DockViewComponent Key="tab1" Title="title1" ShowClose="false">
                @* something *@
            </DockViewComponent>
            <DockViewComponent Key="tab2" Title="title2" ShowClose="false">
                @* something else *@
            </DockViewComponent>
        </DockViewContent>
    </DockViewV2>
</div>
```

### .NET Version

NET8.0

**Comment by ArgoZhang** [comment]
@celadaris hi. The pin function is still under development and is not fully developed. There are indeed bugs.

**Comment by ArgoZhang** [comment]
@celadaris working on it

**Comment by ArgoZhang** [comment]
@celadaris bump version `9.0.2`
