### ISSUE TITLE
doc(Table): null exception when use complex model

### ISSUE THREAD

**Issue by Lekco1320** [dotnetcore/BootstrapBlazor#4907]
### Is there an existing issue for this?

- [x] I have searched the existing issues

## English
**Error Message**:
    `NullReferenceException`

**Souce Code**:
  Attached below.

**Error Occurrence**:
    During rendering `Table`, the `Items` is empty, and `TableColumn` references a property of a reference type in `TItem` that has a default `null` value.

**Stack Trace**:
    Table.cs, line 5736: `__builder2.AddContent(9, TableColumns?.Invoke(CreateTItem()));`
    RenderTreeBuilder.cs, line 67: `fragment(this);`

**Cause Analysis**:
    During the rendering process of the `Table` component tree, `TableColumns` calls `CreateTItem()`, which constructs a `TItem` object with a reference property that is `null`. This object is passed into `TableColumn` and then accessed by `Field`, causing a `NullReferenceException`.

**Additional Information**:
    Is this due to improper use of the `Table` or a component bug? Why does it instantiate a new `TItem` and pass it to all TableColumns here? Must all reference-type properties of `TItem` referenced by `TableColumn` be instantiated at the time of `TItem`'s construction? If it is improper usage, I hope the author can note this in the documentation. Thank you!

## 中文
**复现工程**：
	见下方附件

**异常信息**：
	`NullReferenceException`

**报错时机**：
	`Table` Render过程中，`Items`内容为空，且`TableColumn`引用了`TItem`具有默认`null`值的引用类型属性

**堆栈跟踪**：
	Table.cs, line 5736: `__builder2.AddContent(9, TableColumns?.Invoke(CreateTItem()));`
	RenderTreeBuilder.cs, line 67: `fragment(this);`

**原因分析**：
	在`Table`渲染组件树的过程中`TableColumns`调用了`CreateTItem()`，实例化了一个引用属性为空的`TItem`对象，该对象被传入`TableColumn`，并且值为`null`的属性的字段被`Field`取值，引发`NullReferenceException`

**其他**：
	请问这是`Table`使用不当还是组件`Bug`？为什么这里会实例化一个新的`TItem`并传入所有`TableColumn`？`TableColumn`引用`TItem`的所有引用类型属性都必须要在`TItem`构造时提供默认实例化吗？如是使用不当，希望作者能在`Document`中加以注明，感谢！

### Expected Behavior

To avoid this exception to ensure that fields of `TItem` with default `null` property can be referenced by `TableColumn`.

规避该异常，使得具有默认`null`值引用类型的`TItem`的属性的字段能被`TableColumn`引用。

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

直接运行即可。

[BootstrapBlazorBug.zip](https://github.com/user-attachments/files/18217282/BootstrapBlazorBug.zip)

### .NET Version

NET8.0

**Comment by ArgoZhang** [comment]
@Lekco1320 这个不是 `bug`

你用的时复杂类型，如果你要写 `context.Xoo.Info` 这种表达式，就要保证 `Xoo` 新建时不为空，否则 `Xoo.Info` 就报错了。

 这部分逻辑组件无法完成，所以调用 `CreateItemCallback` 你需要完善这部分逻辑

麻烦帮忙在使用者的角度帮忙晚上一下文档提交 PR 给我，这样更符合其他初学者的逻辑思维

**Comment by Lekco1320** [comment]
好的，我尽快修改并提交文档PR。非常感谢！

**Comment by ArgoZhang** [comment]
@Lekco1320 感谢感谢，由使用者写的文档才能更加贴近使用者，更容易让使用者理解

**Comment by ArgoZhang** [comment]
@Lekco1320 巨佬的 PR 太标准了啊。格式也非常非常非常符合要求，太贴心了。感谢感谢

**Comment by ArgoZhang** [comment]
@Lekco1320 巨佬方便的时候可以加一下我 QQ 或者 VX 都是 5196060
