### ISSUE TITLE
bug(): TableColumn的LookupServiceKey不起作用

### ISSUE THREAD

**Issue by SteelTeng** [dotnetcore/BootstrapBlazor#4942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

TableColumn的LookupServiceKey设置后不起作用，与此同时，TableColumn的Filter组件中也缺少了可选项

### Expected Behavior

TableColumn的LookupServiceKey设置后不起作用，与此同时，TableColumn的Filter组件中也缺少了可选项

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

具体可见 官方Demo中 https://www.blazor.zone/table/lookup 页面的”是/否“列

### .NET Version

NET8.0

### Anything else?

![image](https://github.com/user-attachments/assets/62533f7d-7922-44a5-ad15-2fde89699e61)

**Comment by SteelTeng** [comment]
这个Bug是在9.1.8中发现的，

现在看到9.1.9 beta06已修复

**Comment by ArgoZhang** [comment]
duplicate #4939
