### ISSUE TITLE
bug(Tooltip): IsHtml 为 true 时，style 设置宽度不起作用

### ISSUE THREAD

**Issue by AiYuZhen** [dotnetcore/BootstrapBlazor#4945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`IsHtml = true` 时，通过 `style` 设置宽度不起作用。
`$"<div style=\"width:300px;\"><p>设备：{name}[{devId}]</p><p>ID：{tripId}</p></div>"`

### Expected Behavior

可以正确渲染通过 `style` 设置的宽度。

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

[Test.zip](https://github.com/user-attachments/files/18242810/Test.zip)

### .NET Version

NET8.0

**Comment by ArgoZhang** [comment]
@AiYuZhen 

```
<Tooltip Title="@GetTripTooltip()" IsHtml="true" Sanitize="false">
    <h3 class="mx-2">@Index1</h3>
</Tooltip>
```
