### ISSUE TITLE
feat(Drawer): add `Component` attribute just like `dialog` does.

### ISSUE THREAD

**Issue by ice6** [dotnetcore/BootstrapBlazor#4961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

as title described, I think a `consistent api design` can reduce mental burden.
now the `ChildContent` is really hard to use.

### Describe the solution you'd like

as title described.

### Additional context

noop

**Comment by ArgoZhang** [comment]
@ice6 working on it

**Comment by ArgoZhang** [comment]
@ice6 

add `Component` parameter on `DrawerOption`

```
/// <summary>
/// 获得/设置 自定义组件
/// </summary>
public BootstrapDynamicComponent? Component { get; set; }
```
