### ISSUE TITLE
refactor(AutoComplete): redesign for improve performance

### ISSUE THREAD

**Issue by ArgoZhang** [dotnetcore/BootstrapBlazor#4972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

dialog support ESC key

**Comment by ice6** [comment]
@ArgoZhang it is really glad to see that you are going to redesign this component. can you make the `Items` parameter support `async`. It will be much more useful. And I am quite confuse about the `MeiliSearch` package. Is it a component like other component listed on the `https://www.blazor.zone/`. or it is just a component for the site's global search?

**Comment by ArgoZhang** [comment]
@ice6 

Meilisearch is a website global search component, just like our official website can realize the whole website search, but this component requires third-party support

**Comment by ice6** [comment]
@ArgoZhang thank you for the clarification. I have not found the doc for `meilisearch`. so I am confused. Let me wait to see the final release.

 another thing make me confuse: the latest release in github is [v9.1.8](https://github.com/dotnetcore/BootstrapBlazor/releases/tag/v9.1.8),  but in the top right corner of the site(https://www.blazor.zone/) is v9.1.9.
