### ISSUE TITLE
feat(Input): add Clearable parameter

### ISSUE THREAD

**Issue by ice6** [dotnetcore/BootstrapBlazor#4990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to provide a `clear` function to user, but I have to implement it myself.

### Describe the solution you'd like

just like this: https://element-plus.org/zh-CN/component/input.html

**Comment by ArgoZhang** [comment]
@ice6 sure. working on it

**Comment by ice6** [comment]
@ArgoZhang so effective! 👍

**Comment by ice6** [comment]
for `consistency`, `IsClearable` is a better name for this.

**Comment by ArgoZhang** [comment]
@ice6 done!
