### ISSUE TITLE
bug(Dialog): 设置可拖动后超高弹窗无法显示标题栏

### ISSUE THREAD

**Issue by Ye1105** [dotnetcore/BootstrapBlazor#4994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

9.2版本的弹窗,当弹窗高度超过视高，向上滑动，滑不到弹窗标题的位置，就卡住了

### Expected Behavior

可以看到标题

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

[BootstrapBlazorApp1.zip](https://github.com/user-attachments/files/18271596/BootstrapBlazorApp1.zip)

### .NET Version

NET9.0

**Comment by ArgoZhang** [comment]
`IsDraggable` 参数导致
