### ISSUE TITLE
bug(MindMap): 切换标签页导致 UI 显示空白

### ISSUE THREAD

**Issue by 759423682** [dotnetcore/BootstrapBlazor#4999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

版本号（v9.1.9）首次点击思维导图选项卡，加载成功后，切换到其他选项卡再切换回来，思维导图就显示不出来了。

### Expected Behavior

暂无

### Interactive render mode

Interactive Server (Interactive server-side rendering (interactive SSR) using Blazor Server)

### Steps To Reproduce

https://www.blazor.zone/mind-map

### .NET Version

NET9.0

**Comment by densen2014** [comment]
按重置按钮呢？ 坐标漂移了吧。 请提供复现工程

**Comment by ArgoZhang** [comment]
@759423682 Issue 格式不合规，尽快更正。否则自动关闭啦

**Comment by 759423682** [comment]
> 按重置按钮呢？ 坐标漂移了吧。 请提供复现工程

点击复位按钮和重新设置数据都不起作用，我是在咱们已经发布的组件库就有这个问题。

**Comment by densen2014** [comment]
> > 按重置按钮呢？ 坐标漂移了吧。 请提供复现工程
> 
> 
> 
> 点击复位按钮和重新设置数据都不起作用，我是在咱们已经发布的组件库就有这个问题。

看不懂你说的是什么意思 “我是在咱们已经发布的组件库就有这个问题”

**Comment by 759423682** [comment]
> > > 按重置按钮呢？ 坐标漂移了吧。 请提供复现工程
> > 
> > 
> > 点击复位按钮和重新设置数据都不起作用，我是在咱们已经发布的组件库就有这个问题。
> 
> 看不懂你说的是什么意思 “我是在咱们已经发布的组件库就有这个问题”

https://www.blazor.zone/mind-map
访问这个页面，首次访问了这个思维导图页面，示例是能正常显示出来的，然后咱们切换到其他组件再切换回思维导图页面，原本的示例就不能显示出来了。点击“例子1”、“一周安排”、”复位“按钮，都是不起作用的。

**Comment by densen2014** [comment]
试试这个


https://blazor.app1.es/MindMaps

**Comment by 759423682** [comment]
> 试试这个
> 
> https://blazor.app1.es/MindMaps

谢谢你帮助我。
我刚才测试了，这个页面也是一样的情况，首次打开可行，但只要把这个标签页关了重新从左边点开，思维导图就加载不出来了。

**Comment by ArgoZhang** [comment]
@759423682 稍后这个组件会重写
