### ISSUE TITLE
DateTimeRange组件棒棒哒! 顺便来点小小建议.

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#51]
### Is your feature request related to a problem? Please describe. 
1.DateTimeRange组件建议选择开始时间后,如果不选结束时间,end.value直接等于start.value,
2.建议加入[今日]按钮,对于我这种时间日期盲,会比较好操作
3.建议加一个 OnClear,取消日期选择也需要回调后台查询,不想再点击一次查询按钮. 我非常懒.

### Describe the solution you'd like
1. 这样可以选单日, 而不是返回 0001-1-1后台查询会报错
`value.End==new DateTime (1,1,1,0,0,0)? value.Start: value.End`

2.如图
![加入今日按钮](https://user-images.githubusercontent.com/8428709/106403093-1b582700-642d-11eb-8c99-ee7496ef62f3.jpg)

**Comment by ArgoZhang** [comment]
马上安排

**Comment by ArgoZhang** [comment]
1. 双击即开始时间与结束时间一致
2. OnClear 有回调委托了
3. 明天帮你增加个今天

**Comment by ArgoZhang** [comment]
今天按钮已经添加
