### ISSUE TITLE
FileViewer 文件预览器  

### ISSUE THREAD

**Issue by dadazxy** [dotnetcore/BootstrapBlazor#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

预览表格时间转换错误  展示界面错乱

### Expected Behavior

   at NPOI.SS.UserModel.DateUtil.GetJavaCalendar(Double date, Boolean use1904windowing, TimeZone timeZone, Boolean roundSeconds)

### Steps To Reproduce

![Uploading 1676280377006.jpg…]()
[reviewsss.xlsx](https://github.com/dotnetcore/BootstrapBlazor/files/10720671/reviewsss.xlsx)

### Exceptions (if any)

   at NPOI.SS.UserModel.DateUtil.GetJavaCalendar(Double date, Boolean use1904windowing, TimeZone timeZone, Boolean roundSeconds)

### .NET Version

6.0

**Comment by densen2014** [comment]
谢谢反馈

**Comment by dadazxy** [comment]
以后能解决吗

**Comment by densen2014** [comment]
据其他成员说是js转换时间格式的问题。目前还在计划中。

**Comment by dadazxy** [comment]
有大概时间吗

**Comment by densen2014** [comment]
> 有大概时间吗

我看看月底有没有时间弄

**Comment by gitlsl** [comment]
@densen2014 @ArgoZhang 
能否加个 组件用于编辑文本文件【支持格式化高亮】，
用途是  查看服务器上的文本文件内容【比如查看运行日志之类的】，简单的编辑【比如修改json配置】

**Comment by ArgoZhang** [comment]
@gitlsl 我项目上没有这个需求，得全靠自己业余时间来完成，还有就是思路，跟具体需求也不了解。

`编辑文本文件` 这六个字博大精深

**Comment by densen2014** [comment]
> @gitlsl 我项目上没有这个需求，得全靠自己业余时间来完成，还有就是思路，跟具体需求也不了解。
> 
> 
> 
> `编辑文本文件` 这六个字博大精深

宝塔blazor重制版

**Comment by densen2014** [comment]
@dadazxy 你的截图没传完毕我看不到错误, 我这里实际测试没报错,只是排版乱了, 原因是原始excel文件列宽就是那样的. 
 
调整后的文件

[reviewsss.xlsx](https://github.com/dotnetcore/BootstrapBlazor/files/10766020/reviewsss.xlsx)

调整后的渲染

![image](https://user-images.githubusercontent.com/8428709/219631540-28b9503e-e99d-4e20-8ab6-363ab3ca19fd.png)

**Comment by densen2014** [comment]
排版错乱是因为原始xlsx文件列宽不够. 时间格式问题是依赖库导致,已修复

**Comment by densen2014** [comment]
@gitlsl 新版发包了. 关闭issue
