### ISSUE TITLE
decimal?字段自动生成的table编辑界面保存不了

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#56]
### Describe the bug
decimal?字段自动生成的table编辑界面保存不了

类字段定义
 
```
        [AutoGenerateColumn(Order = 29, Filterable = true, Sortable = true)]
        public decimal? Prepaid { get; set; }
```
生成的html
`<input type="number" id="bb_15798577_Prepaid" class="form-control valid">
`

![QQ图片20210205031520](https://user-images.githubusercontent.com/8428709/106980421-7016dd00-6760-11eb-867f-b3e7b6887501.png)

**Comment by ArgoZhang** [comment]
Bug 石锤了

**Comment by ArgoZhang** [comment]
已修复
