### ISSUE TITLE
Toasts progress-bar not displayed

### ISSUE THREAD

**Issue by SeeMeBE** [dotnetcore/BootstrapBlazor#562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The toast progress-bar is not displayed when autohide is used.

### Expected Behavior

The display of the bar

### Steps To Reproduce

The Style that manipulate the width of the progress bar is using local formating number (French env., where the coma is used by default for decimal separator instead of english dot), that is not a valid number formatting.

![image](https://user-images.githubusercontent.com/126031798/220492075-24a31b93-7e3d-4294-a37b-e3bdd559a6f1.png)

Debug error spotted : 
![image](https://user-images.githubusercontent.com/126031798/220492209-339ea2bc-6d39-44b1-b016-9e7e90b5fe95.png)

**Comment by ArgoZhang** [comment]
@SeeMeBE 

```
width: 69.999%
```

should be `DOT` not `COMMA`

**Comment by SeeMeBE** [comment]
> @SeeMeBE
> 
> ```
> width: 69.999%
> ```
> 
> should be `DOT` not `COMMA`

Indeed, but I didn't place this percentage, its in the inner mechnism of the Toast componant. And I don't know how to fix it properly. The problem is coming from the creation of the Style="width: {value}", where value is the decimal number that is converted automaticaly into a string. Doing it like this use the local machine representation of decimal separator that is the COMA on my system, and the the DOT as needed by HTML. 
The problem may arise something else has the program doesn't seems to take this into account.
