### ISSUE TITLE
 [AutoGenerateColumn(Width = 80)] 宽度设置好像是失效的,或者我用得不对?

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#58]
![QQ截图20210205035734](https://user-images.githubusercontent.com/8428709/106983686-9c355c80-6766-11eb-86f4-29dcebfb9da0.jpg)
![QQ截图20210205035909](https://user-images.githubusercontent.com/8428709/106983688-9ccdf300-6766-11eb-96e5-2fad23901c34.jpg)
![QQ截图20210205035928](https://user-images.githubusercontent.com/8428709/106983690-9d668980-6766-11eb-8def-1f2b4c78733e.jpg)

**Comment by ArgoZhang** [comment]
我看了一下生成的 html 宽度是生效的
