### ISSUE TITLE
Component Select

### ISSUE THREAD

**Issue by gmondin** [dotnetcore/BootstrapBlazor#590]
### Which class is this unit test associated with?

I'm using the component Select, but I'm having some problems, I have 5 selects on a modal, where one after other is changing by the selection before, the first time works well, but at the second time, the component comes with a item selected and doesn't call the method Selected, because its the same item selected before, I cleaned the list, the items, etc, but still with this problem, also if I call manually, doesnàt show the options on the other select.
Thank you

**Comment by ArgoZhang** [comment]
@gmondin hi, could you provider a sample project for repro this?

**Comment by ArgoZhang** [comment]
@gmondin  auto close issue
