### ISSUE TITLE
TableToolbarPopconfirmButton 建议增加 IsEnableWhenSelectedOneRow属性

### ISSUE THREAD

**Issue by liaozb** [dotnetcore/BootstrapBlazor#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

未选中不可点击

**Comment by ArgoZhang** [comment]
@liaozb 建议合理，稍等加一下这个属性，未选中行时，带二次确认的弹窗按钮也不可用对吧

**Comment by liaozb** [comment]
> @liaozb 建议合理，稍等加一下这个属性，未选中行时，带二次确认的弹窗按钮也不可用对吧

对的

**Comment by liaozb** [comment]
@ArgoZhang 建议一些通用类 单独发一个包  例如QueryPageOptions，AutoGenerateColumn标记
因为我在abp项目中Application.Contracts层无法使用

**Comment by ArgoZhang** [comment]
@liaozb 没懂这个单独发包，是为啥什么，我们群里有几个用 abp 的都用了 BB 作为 UI 我自己没用 abp 有些东西我不了解也无法做出来

**Comment by densen2014** [comment]
估计为了减少体积只要bb的特性吧，但其实bb也不大啊，这就很迷

**Comment by ArgoZhang** [comment]
我就没发现比 BB 再小的了，同时支持 `net5` `net6` `net7` 一共才 `1.86M`

`MudBlazor` 支持 `net6` `net7` `3.83M`
`Radzen.Blazor` 支持 `standard2.1` `net6` `net7` `4.1M`

**Comment by densen2014** [comment]
所以早上看了我不太确定要怎么回复

**Comment by ArgoZhang** [comment]
@liaozb 发了新包 `7.4.1-beta03`

**Comment by liaozb** [comment]
![image](https://user-images.githubusercontent.com/12622501/222994061-b089e033-56e3-45f0-ba0f-ff5e05370116.png)
应用服务层无法使用这些类  ，netstandard无法引用BootstrapBlazor，我意思是把BootstrapBlazor拆封成两个包，一个包通用类方法，一个是组件包。

**Comment by densen2014** [comment]
那估计兼容各框架要写死了，只会越来越复杂
