### ISSUE TITLE
bug: could not load content for bootstrap.bundle.min.js.map

### ISSUE THREAD

**Issue by aaron6925** [dotnetcore/BootstrapBlazor#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

BootstrapBlazor 7.4.0

DevTools failed to load source map: Could not load content for http://localhost:53189/_content/BootstrapBlazor/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

![image](https://user-images.githubusercontent.com/5062850/223013844-0b036173-1b8c-45d7-89da-6b002b097cac.png)

![image](https://user-images.githubusercontent.com/5062850/223013818-e041e992-578a-4d31-8a8a-fb7c959ba987.png)

### Expected Behavior

直接使用模板產生出來的專案後執行

### .NET Version

.NET 7.0

**Comment by ArgoZhang** [comment]
@aaron6925 will be remove the map link later. thank you for contact us.
