### ISSUE TITLE
feat: <右键菜单>表格组件增加右键菜单，方便方便表格组件对复杂业务的处理

### ISSUE THREAD

**Issue by lvjunlei** [dotnetcore/BootstrapBlazor#666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

表格组件增加右键菜单，方便方便表格组件对复杂业务的处理

**Comment by densen2014** [comment]
参考现成右键组件自己试试加进table。 你说的这个基本bb今年是不会做了。

**Comment by ArgoZhang** [comment]
@lvjunlei 感谢提交 Issue 联系我们，目前 `Menu` 组件想重构，然后才能实现这个右键菜单，这个右键菜单怎么跟 Table 联动还没有好的思路，所以暂时没有计划，如果您有什么好的建议或者解决方案，我们可以讨论

**Comment by ArgoZhang** [comment]
@lvjunlei 请帮忙点一下右上角 star 谢谢啦

**Comment by lvjunlei** [comment]
谢谢回复，已经Star
