### ISSUE TITLE
/_content/BootstrapBlazor/js/bootstrap.bundle.min.js.map 404 

### ISSUE THREAD

**Issue by a0926019412** [dotnetcore/BootstrapBlazor#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

版本7.4 有在issue list裡面找到該錯誤
因為專案不能偵錯, 所以想退到舊的版本

目前我已經嘗試退到7.1.8, 不過還是會發生一樣的錯誤 導致無法偵錯
請問目前正常可以使用的版本是哪一版呢?

### .NET Version

6.0

**Comment by ArgoZhang** [comment]
@a0926019412 尽量提供截图画框标注箭头

**Comment by a0926019412** [comment]
您好
我目前重新拉下程式後沒發生問題了
看起來不是貴方套件的問題
暫時無法重現問題

之後有再觀察到相同情況我再詳細截圖回報給您

**Comment by a0926019412** [comment]
[visualstudio-js-debugger.txt](https://github.com/dotnetcore/BootstrapBlazor/files/10989365/visualstudio-js-debugger.txt)
![image](https://user-images.githubusercontent.com/4286244/225584198-5db68e1c-782d-47fc-bba2-0d6b1109f78c.png)

附帶visual studio debug log 
檔案中第220列顯示 404錯誤

組件當前版本為7.2.2

**Comment by ArgoZhang** [comment]
@a0926019412 好的。感谢提交 Issue 联系我们，后续有问题再创建 Issue

这 js.map 文件一般来讲是浏览器请求的。组件并不使用
