### ISSUE TITLE
Table的EditMode为EditForm模式时，Column的Editable无效

### ISSUE THREAD

**Issue by houlongchao** [dotnetcore/BootstrapBlazor#75]
问题：Table EditForm模式自动会自动生成Editable=false的列
期望：EditForm模式也可以正确识别Editable等属性设置

**Comment by ArgoZhang** [comment]
收到，我测试一下哈

**Comment by ArgoZhang** [comment]
@houlongchao 确认，正在修复

**Comment by ArgoZhang** [comment]
@houlongchao 最新版没有这个 bug，您使用的是那个版本

**Comment by houlongchao** [comment]
> @houlongchao 最新版没有这个 bug，您使用的是那个版本

@ArgoZhang  5.0.22

**Comment by ArgoZhang** [comment]
复现代码方便贴一下吗？




| |
Argo
|
|
***@***.***
|

Signature is customized by Netease Mail Master

在2021年03月26日 18:02，houlongchao 写道：

@houlongchao 最新版没有这个 bug，您使用的是那个版本

@ArgoZhang 5.0.22

**Comment by houlongchao** [comment]
@ArgoZhang 
下面三张图为测试效果，附件zip为demo源码
![image](https://user-images.githubusercontent.com/13547836/112619087-d7e4cc80-8e61-11eb-8487-8e027923ead2.png)
![image](https://user-images.githubusercontent.com/13547836/112618912-9f44f300-8e61-11eb-93db-331f50ccb362.png)
![image](https://user-images.githubusercontent.com/13547836/112618919-a4a23d80-8e61-11eb-903f-dad21e9d9550.png)
![image](https://user-images.githubusercontent.com/13547836/112618934-aa981e80-8e61-11eb-82b5-64820aae2d51.png)


[BootstrapBlazorApp.zip](https://github.com/dotnetcore/BootstrapBlazor/files/6211089/BootstrapBlazorApp.zip)

**Comment by ArgoZhang** [comment]
@houlongchao 非常抱歉，是我没有认真审题，EditForm 模式下复现啦。我马上修复一下

**Comment by ArgoZhang** [comment]
@houlongchao 已经修复啦。发布新版本 5.0.23-beta05
