### ISSUE TITLE
Table小屏幕卡片模式时自定义显示/隐藏列无效

### ISSUE THREAD

**Issue by houlongchao** [dotnetcore/BootstrapBlazor#80]
![image](https://user-images.githubusercontent.com/13547836/113239046-777be200-92dc-11eb-98d9-aeb316e39897.png)

**Comment by ArgoZhang** [comment]
收到，下个版本修复一下

**Comment by ArgoZhang** [comment]
@houlongchao 已经修复啦，5.0.24-beta01
