### ISSUE TITLE
 Unable to reference to .net standard 2.1

### ISSUE THREAD

**Issue by abbaskizildag** [dotnetcore/BootstrapBlazor#83]
What would you suggest me to do?

![image](https://user-images.githubusercontent.com/58951278/113520806-5813dc00-959e-11eb-8c04-7488a8cf6eab.png)

**Comment by densen2014** [comment]
hello,it only support net5.0 now

**Comment by ArgoZhang** [comment]
hi，
the version of 5.0.X only support NET 5.0 framework. if you wanna use `BB` in netstandard 2.1, you can get the version of 3.0.X


Have a nice day




| |
Argo
|
|
***@***.***
|

Signature is customized by Netease Mail Master

On 04/05/2021 07:37, alex chow wrote:

hello,it only support net5.0 now

**Comment by abbaskizildag** [comment]
ArgoZang thanks. it is working now. this package is amazing :).
![image](https://user-images.githubusercontent.com/58951278/113546987-c5069080-95f5-11eb-8838-67c141285e5a.png)

![image](https://user-images.githubusercontent.com/58951278/113547088-ebc4c700-95f5-11eb-8b4a-6d8e6fae85e8.png)

**Comment by ArgoZhang** [comment]
@abbaskizildag thanks for your reply. This project need partners to translate together. you can submit some translation work if you have time. see #42

**Comment by ArgoZhang** [comment]
@abbaskizildag BTW. the version of 3.1.30 is long time ago. it's a out of date version. strongly recommend you upgrade to NET5

**Comment by ehlkara** [comment]
It's nice work thank you for help :)

**Comment by abbaskizildag** [comment]
> @abbaskizildag thanks for your reply. This project need partners to translate together. you can submit some translation work if you have time. see #42

Argo my english not very well. sorry for not translate helping.
