### ISSUE TITLE
bug(Table): always edit first row in Excel mode

### ISSUE THREAD

**Issue by ArgoZhang** [dotnetcore/BootstrapBlazor#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
<Table TItem="T1" OnQueryAsync="OnQueryAsync" IsExcel="true" OnSaveAsync="OnSaveAsync"
       AutoGenerateColumns="false">
    <TableColumns>
        <TableColumn @bind-Field="context.id"></TableColumn>
        <TableColumn @bind-Field="context.Text"></TableColumn>
    </TableColumns>
</Table>
```

**Comment by seasontian** [comment]
@ArgoZhang issue still exists when show Excel mode table in popup dialog

https://github.com/user-attachments/assets/0e8dd95c-35fa-4f6b-9595-3299453c871a
