### ISSUE TITLE
bug(QRCode): not support Chinese and Number

### ISSUE THREAD

**Issue by azlis** [dotnetcore/BootstrapBlazor#879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

QRCoder 组件实用中文加数字生成二维码会抛出异常
![O6K~3JAPTM_08XJ`T{ORP80](https://user-images.githubusercontent.com/33386249/227967497-8a23cd73-982f-46e0-9347-1a79e78a60e0.png)

![U)H{O3JC$)1~$QX@_28U9R3](https://user-images.githubusercontent.com/33386249/227967533-a4f4881c-424f-4895-a916-bad871de2615.png)

**Comment by ArgoZhang** [comment]
@azlis please check this [qrcode#link105](https://github.com/davidshimjs/qrcodejs/blob/master/qrcode.js#L105)

**Comment by azlis** [comment]
@ArgoZhang I suggest adding a Length Validate to the component

**Comment by densen2014** [comment]
👍
