### ISSUE TITLE
bug: BootstrapInputNumber 判斷有效值異常

### ISSUE THREAD

**Issue by aaron6925** [dotnetcore/BootstrapBlazor#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

設定MIN=0.0001, UI 輸入 0.01 卻無法輸入

<img width="725" alt="image" src="https://user-images.githubusercontent.com/5062850/227984210-8ba9938f-dc40-4897-960e-79c50652e820.png">
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/5062850/227984352-54cff36f-78de-4142-841e-53b54d6b22fd.png">

**Comment by j4587698** [comment]
你设置了步长为1，然后输入0.01肯定不可以啊，步长为1则你只能输入整数，如果想输入0.01可以定义步长为0.01

**Comment by azlis** [comment]
Because you set the step size value to 1, this conflicts with a min of 0.0001.

**Comment by aaron6925** [comment]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/5062850/228232109-8a1e3e9e-d75f-4ee0-abcb-079489701a50.png">
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/5062850/228232216-c79adc8b-3142-4813-bfb1-b7f906458e60.png">
跟Step 沒有關係喔，我最初沒有用step也是會錯的，用step是方便user按鈕時可以整數加1

**Comment by azlis** [comment]
完全正常
![image](https://user-images.githubusercontent.com/33386249/228402375-f5d0a148-48f5-4d84-9419-0c138f029bfd.png)

![image](https://user-images.githubusercontent.com/33386249/228402427-aaeb581a-98eb-4252-8a60-f5b0dc9fe403.png)

**Comment by azlis** [comment]
你是不是给你绑定的字段加了Validate

**Comment by aaron6925** [comment]
> 你是不是给你绑定的字段加了Validate

<img width="518" alt="image" src="https://user-images.githubusercontent.com/5062850/228413286-e1ae9991-5b88-4ff0-9440-d56ee52dbf4f.png">

沒有加Validate

**Comment by aaron6925** [comment]
> 完全正常 ![image](https://user-images.githubusercontent.com/33386249/228402375-f5d0a148-48f5-4d84-9419-0c138f029bfd.png)
> 
> ![image](https://user-images.githubusercontent.com/33386249/228402427-aaeb581a-98eb-4252-8a60-f5b0dc9fe403.png)
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/5062850/228413879-d584ad85-cc6d-4c9b-9ba4-43eadac39813.png">

我看你跟我的程式差異為 TValue=double

我也補上了，還是不行，我的是decimal。

**Comment by aaron6925** [comment]
> https://www.blazor.zone/inputnumbers#Step 自己看下例子，然后对应的写好step就行了，例子里就可以0.1

跟步長一點關係都沒有

**Comment by ArgoZhang** [comment]
@aaron6925 

<img width="875" alt="image" src="https://user-images.githubusercontent.com/22001478/228415009-35e7b814-b36b-4571-b63b-79b6e4c94517.png">

这个弹窗是浏览器自己的弹窗无组件无关，请查阅一下 浏览器 对 `Step` 的定义，这个组件无能为力的。或者有什么好的解决办法可以 PR 给我们

**Comment by aaron6925** [comment]
了解，原本以為是控件內的檢查，如果是瀏覽器的問題，就只能傳STEP=強制改0.0001

**Comment by aaron6925** [comment]
我是用Chrome

**Comment by aaron6925** [comment]
也許可以在 BootstrapInputNumber 判斷MIN的小數點位，如果 STEP沒有傳入為NULL，自動調整為該小數位的1
ex: MIN = 0.0005 STEP=NULL => STEP=0.0001
      MIN = 0.05 STEP = NULL => STEP 0.01
