### ISSUE TITLE
Layout 在 Blazor Server 含 Authentication 的專案下沒有作用

### ISSUE THREAD

**Issue by carlcyber** [dotnetcore/BootstrapBlazor#90]
你好，

使用 Blazor Server 不含 Authentication 時，Layout 運作正常，Header、Main、Footer 都有顯示。
使用 Blazor Server 含 Authentication (Individual accounts) 時，Layout 沒有作用，只會出現 Main 的內容。

代碼如下
```
<Layout SideWidth="0" IsPage="true" IsFullSide="true" IsFixedHeader="false" IsFixedFooter="false" ShowFooter="true">
    <Header>
        <div class="text-center header">Header</div>
    </Header>
    <Main>
        <div class="text-center main">Main</div>
    </Main>
    <Footer>
        <div class="text-center footer">Footer</div>
    </Footer>
</Layout>
```

**Comment by ArgoZhang** [comment]
@carlcyber 你好，首先请帮忙点一下右上角 star，第二能否提供一下您说的含 Authentication 时，的代码，最好给我一个例子工程

**Comment by carlcyber** [comment]
@ArgoZhang 好的，請查收附件。

[BootstrapBlazorLayoutReport.zip](https://github.com/dotnetcore/BootstrapBlazor/files/6529428/BootstrapBlazorLayoutReport.zip)

**Comment by ArgoZhang** [comment]
@carlcyber 收到。我先看看代码

**Comment by ArgoZhang** [comment]
@carlcyber 我看了 `Layout` 组件代码，内部有判断如果是未登录用户就是直接显示 Main 区域的，如果是已登录用户才会显示其他区域

**Comment by carlcyber** [comment]
@ArgoZhang  謝謝解答，這樣的話要用 Layout 組件在未登入情形下應如何顯示全部內容? 若沒有辦法的話是否能新增一個 [Parameter] 來啟用/停用這個控制。

**Comment by ArgoZhang** [comment]
@carlcyber 好的。我设计一个 `[Parameter]` 来控制一下这个，您看可以吗？

**Comment by carlcyber** [comment]
好的，剛閱讀源碼了，`NotAuthroized` 應無法達到需求，已如您建議的建一個新元件來實現此功能。

但還是希望此需求能整合到函式庫。這個行為應該也會讓新的使用者感到困惑，畢竟網站沒有說明到，若要使用在基底版面配置的話就會在登入前無法完整顯示。

**Comment by ArgoZhang** [comment]
@carlcyber 感谢您的意见。正在修复这个问题

**Comment by ArgoZhang** [comment]
@carlcyber 已经修复，发布了 5.0.32-beta03 版本。请帮忙测试一下下

**Comment by carlcyber** [comment]
@ArgoZhang 測試正常，謝謝修改。
