### ISSUE TITLE
blazorboilerplate ui

### ISSUE THREAD

**Issue by pomeara** [dotnetcore/BootstrapBlazor#93]
# UI Boilerplate addon

Hi @ArgoZhang I've been away for a while but now that I'm back I see a fantastic boilerplate project which would benefit from the features of BootstrapBlazor.

There is a structure for providing different UI libraries and the author of this project is looking to move away from the current MattBlazor so I thought adding in BB would help to increase the reach of your great project and also help to mature it to work with other frameworks

[BlazorBoilerPlate](https://github.com/enkodellc/blazorboilerplate)
[Issue where I mentioned BB](https://github.com/enkodellc/blazorboilerplate/issues/618)

**Comment by ArgoZhang** [comment]
great! later I will take a look at this repo. thanks

**Comment by ArgoZhang** [comment]
@pomeara hi, what's is this BlazorBoilerPlate? how to use it? I can't find the install docs

**Comment by gitlsl** [comment]
@ArgoZhang 是的 ，增加一个后台管理系统， 即开即用， 大家都很喜欢呀，  类似你的  `https://github.com/ArgoZhang/BootstrapAdmin`

**Comment by ArgoZhang** [comment]
@gitlsl 大佬帮忙 star 一下吧，哈哈，BootstrapAdmin 跟 Blazor 求赏星星

**Comment by gitlsl** [comment]
@ArgoZhang 已点， 加油

**Comment by ArgoZhang** [comment]
@gitlsl thanks!!!
