### ISSUE TITLE
render current tab only

### ISSUE THREAD

**Issue by AndyBianco** [dotnetcore/BootstrapBlazor#94]
Hi,
Currently, the complex custom components are rendered one time when the component with tab is loaded.
Is it possible to add a feature (optional or not) to render only the current tab ?

Exemple : 
```
<Tab>
    <TabItem Text="tab1">
        <CustomComponent1></CustomComponent1>
    </TabItem>
    <TabItem Text="tab2">
        <CustomComponent2></CustomComponent2>
    </TabItem>
</Tab>

```

current code in tab :
```
  <div class="tabs-body">
            <CascadingValue Value="this" IsFixed="true">
                @foreach (var item in Items)
                {
                    <div @key="@item" class="@GetContentClassString(item)">
                        @item.ChildContent
                    </div>
                }
            </CascadingValue>
        </div>

```

the idea :
```
  <div class="tabs-body">
            <CascadingValue Value="this" IsFixed="true">
               <div @key="@ActiveTab" class="@GetContentClassString(ActiveTab)">
                    @ActiveTab.ChildContent
               </div>
            </CascadingValue>
        </div>
      
```

Best regards.

**Comment by ArgoZhang** [comment]
@AndyBianco thank you for contacting me. did you have a try use your idea code? current tab will keep the ChildContent state by design. it will always reload the tab if use your code.

**Comment by ArgoZhang** [comment]
@AndyBianco sorry for the delayed reply. I'm on a business trip.

**Comment by ArgoZhang** [comment]
@AndyBianco what do you think that add a OnlyRenderActiveTab parameter on Tab component?

**Comment by AndyBianco** [comment]
> it will always reload the tab if use your code.

That's the purpose, to be able to use a standalone custom component with the blazor events (OnInitialized(), OnAfterRender(bool firstRender), and so on) into tabs without adding specific code to take advantage of event implementations when the user clicks on the item tab (e.g: get last data).

> what do you think that adds an OnlyRenderActiveTab parameter on the Tab component?

@ArgoZhang It's perfect, thanks

**Comment by ArgoZhang** [comment]
@AndyBianco it's ok, now that one thing we need declares, the content of Tab will not keep state if set OnlyRenderActiveTab to true.

**Comment by ArgoZhang** [comment]
@AndyBianco bump version to 5.0.37

**Comment by AndyBianco** [comment]
@ArgoZhang Thank you for your responsiveness, it works perfectly ! 👍
