### ISSUE TITLE
navigation wish list

### ISSUE THREAD

**Issue by DanPFW** [dotnetcore/BootstrapBlazor#95]
I'm changing my comment to a "wish" since I can't delete the original.

I'd like to see a few things enhanced related to the menus.

1.  Add a separate NavMenu class to the template generated project.
2. include the Accordian/Expand All feature to the menu.
3. integrate security into menu
4. use a json/xml file, similar to the old SiteMap.xml to generate the menu from file.  Also support creating search engine site maps from this file.

**Comment by ArgoZhang** [comment]
@DanPFW 
1. Add a separate NavMenu class to the template generated project.

can you show some sample code? sorry I don't understand.

**Comment by ArgoZhang** [comment]
@DanPFW 

2. include the Accordian/Expand All feature to the menu.

now all side menu has Accordion/Expand feature.

**Comment by ArgoZhang** [comment]
@DanPFW 

3. integrate security into menu

security is what means?

**Comment by ArgoZhang** [comment]
@DanPFW 

4. use a json/xml file, similar to the old SiteMap.xml to generate the menu from file. Also support creating search engine site maps from this file.

do you read the data from json/xml transform to IEnumerable<SelectedItem>?

**Comment by ArgoZhang** [comment]
no response close Issue
