### ISSUE TITLE
Dropdown的Color="Color.None"不起作用

### ISSUE THREAD

**Issue by tchivs** [dotnetcore/BootstrapBlazor#96]
## razor
```c#
 <Dropdown TItem="LanguageInfo" Color="Color.None" Items="@LanguageInfos"></Dropdown>
```
## html页面
``` html
<button type="button" class="btn dropdown-toggle btn-primary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">简体中文</button>
```
在页面中变成btn-primary了
![image](https://user-images.githubusercontent.com/20809329/124407985-d0de2c00-dd77-11eb-8ada-192fb5941e73.png)

**Comment by ArgoZhang** [comment]
@tchivs 内部有判断如果是 None 默认就是 Primary，你的需求就是不要颜色对吗？

**Comment by tchivs** [comment]
> @tchivs内部有判断如果是无默认就是主要，你的需求就是不要颜色对吗？

是的如果有颜色放在navbar当下拉菜单感觉不太好，所以只能手动改成这样子了……
![image](https://user-images.githubusercontent.com/20809329/124415616-d04d9180-dd87-11eb-9c9a-d585d7e45192.png)

**Comment by ArgoZhang** [comment]
@tchivs 需要我怎么做呢？

**Comment by tchivs** [comment]
> @tchivs 需要我怎么做呢？

按理来说，如果我不指定的话可以默认primary，但是我指定了是None的话应该不要加上btn-primary。只使用btn dropdown-toggle就可以了

**Comment by ArgoZhang** [comment]
这是一个不可为空的枚举类型，不指定默认就是Primary，如果只写btn 按钮是不全的样式，现在如果按照你的思路改会影响很多老用户，非常抱歉，还有什么好办法吗？这个影响到你的工作了吗？可以自定义样式覆盖掉primary吗？

**Comment by tchivs** [comment]
> 这是一个不可为空的枚举类型，不指定默认就是Primary，如果只写btn按钮是不全的样式，现在如果按照你的想法改会影响很多老用户，非常抱歉，还有好办法吗？这会影响到你的工作吗？可以自定义样式覆盖掉原色吗？

好吧， 那只能自己重写一下样式了
