### ISSUE TITLE
bug: 时间选择范围控件显示异常且侧边栏没有显示出来

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

时间选择范围控件显示异常：
1、侧边栏没有显示出来
2、控件界面显示诡异

           ` <DateTimeRange @bind-Value="@dateTimeRangeValue" ShowSidebar="true" />`

![image](https://user-images.githubusercontent.com/14847818/230319687-934f6bfa-8e33-4306-a577-07ce5d93217a.png)

**Comment by ArgoZhang** [comment]
@bigsinger 看起来是样式被污染了，需要 F12 自己排查一下

**Comment by bigsinger** [comment]
> @bigsinger 看起来是样式被污染了，需要 F12 自己排查一下
F12显示这个，能看出来什么问题吗？
![image](https://user-images.githubusercontent.com/14847818/230326339-82edcab6-a20c-4320-aa30-ffcac2890ab3.png)

**Comment by bigsinger** [comment]
@ArgoZhang 没有解决哦，新版本也有这个问题。

**Comment by ArgoZhang** [comment]
@bigsinger 跟版本无关。应该是你本地项目的问题

**Comment by bigsinger** [comment]
我用新建的blazor server项目下面的`wwwroot`里的文件做了替换， 发现并没有什么变化，也即这块没有动过。
```
site.css
bootstrap
open-iconic
```
![image](https://user-images.githubusercontent.com/14847818/232357562-d6ba75b7-4122-4a2a-ba3c-cd90ed2e31bb.png)

还有其他可能的原因吗？帮忙给一些方向。(我用的是NET7)
@ArgoZhang

**Comment by densen2014** [comment]
请提供复现项目zip

**Comment by bigsinger** [comment]
@ArgoZhang @densen2014 
解决了。在`_Host.cshtml`文件里不能出现：
`<link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />`
这会和下面出现冲突：
```
    <link href="_content/BootstrapBlazor.FontAwesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="_content/BootstrapBlazor/css/bootstrap.blazor.bundle.min.css" rel="stylesheet">
    <link rel="stylesheet" href="_content/BootstrapBlazor.Chart/css/bootstrap.blazor.chart.bundle.min.css" />
```

**Comment by bigsinger** [comment]
> @ArgoZhang @densen2014 解决了。在`_Host.cshtml`文件里不能出现： `<link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />` 这会和下面出现冲突：
> 
> ```
>     <link href="_content/BootstrapBlazor.FontAwesome/css/font-awesome.min.css" rel="stylesheet">
>     <link href="_content/BootstrapBlazor/css/bootstrap.blazor.bundle.min.css" rel="stylesheet">
>     <link rel="stylesheet" href="_content/BootstrapBlazor.Chart/css/bootstrap.blazor.chart.bundle.min.css" />
> ```

@ArgoZhang   这个问题我发散一下：
BootstrapBlazor在设计原则上是否可以和bootstrap库保持兼容和一致？

这个想法是从最近几天你们的反馈来看一直强调图表要和chart.js保持一致。那么是否和bootstrap库保持一致？
如果是，是否有必要解决这个冲突问题。    

在混用的情况下，你们的出发点是怎样的？

**Comment by ArgoZhang** [comment]
@bigsinger 我们组件库内置了 `Bootstrap` 样式，而且是版本是最新的，文档中也强调了，微软的模板加载的 `Bootstrap` 样式库比较老，**必须移除掉**

### 为什么移除掉

因为 `CSS` 加载顺序我们组件无法控制，不知道使用者是如何写的，所以必须移除掉，避免不必要问题

我们就是保持一致的，是微软的模板没有及时更新（他们也无法做到及时更新）

**Comment by bigsinger** [comment]
> @bigsinger 我们组件库内置了 `Bootstrap` 样式，而且是版本是最新的，文档中也强调了，微软的模板加载的 `Bootstrap` 样式库比较老，**必须移除掉**
> 
> ### 为什么移除掉
> 因为 `CSS` 加载顺序我们组件无法控制，不知道使用者是如何写的，所以必须移除掉，避免不必要问题
> 
> 我们就是保持一致的，是微软的模板没有及时更新（他们也无法做到及时更新）

get
