### ISSUE TITLE
在abp的blazor项目中引用组件后本地化冲突

### ISSUE THREAD

**Issue by tchivs** [dotnetcore/BootstrapBlazor#97]
abp默认的blazor项目使用的是blazorise，我想替换成本项目，但是在替换之后发现本地化失效。BootstrapBlazor组件本地化是有效的，但是abp里面的json资源就不行了。应该是BootstrapBlazor的IStringLocalizer把abp的给覆盖了吧。怎样才能二者共存……

![image](https://user-images.githubusercontent.com/20809329/124447743-410aa300-ddb4-11eb-9c3c-dc02be78c7d8.png)

AddBootstrapBlazor后：

![image](https://user-images.githubusercontent.com/20809329/124447915-6f887e00-ddb4-11eb-9d8d-096d0ab21102.png)

razor:
![image](https://user-images.githubusercontent.com/20809329/124448323-e3c32180-ddb4-11eb-8c0e-019f2b60966f.png)
json:
![image](https://user-images.githubusercontent.com/20809329/124448685-4c120300-ddb5-11eb-8471-6b96153ce538.png)

abp框架的本地化：https://docs.abp.io/zh-Hans/abp/latest/Localization

**Comment by ArgoZhang** [comment]
@tchivs 对的，以前有人跟我提过这个 Issue 我不会 abp 所以我不知道怎么解决这个问题。您的推断是对的，BB 组件的本地化覆盖了 abp 的。主要问题是 aspnetcore 框架里 `IStringLocalizerFactory` 只有一个最后一个生效，都是互相覆盖

**Comment by ArgoZhang** [comment]
@tchivs 能否配合一下把这个问题修复。可以加一下我的群 675147445

**Comment by tchivs** [comment]
> @tchivs 能否配合一下把这个问题修复。可以加一下我的群 675147445
demo已上传，readme里面有简单的说明
[AbpDemo.zip](https://github.com/dotnetcore/BootstrapBlazor/files/6781234/AbpDemo.zip)

**Comment by ArgoZhang** [comment]
@tchivs 怎么启动这个啊

**Comment by tchivs** [comment]
> @tchivs 怎么启动这个啊

1首次使用项目需要运行AbpDemo.DbMigrator初始化数据库（使用的是LocalDb）

2启动AbpDemo.Blazor即可

在这里添加了bb后本地化失效
AbpDemo.Blazor>ConfigureBlazorise>context.Services.AddBootstrapBlazor();

json路径：
AbpDemo.Domain.Shared\Localization
同时AbpDemo.Domain.Shared项目引用的所有.Domain.Shared程序集下的Localization目录均有json文件。abp组合了它们

**Comment by ArgoZhang** [comment]
@tchivs 已经修复了
