### ISSUE TITLE
alternate MultiHeaderTemplate behavior

### ISSUE THREAD

**Issue by DanPFW** [dotnetcore/BootstrapBlazor#98]
Can you alter the table base class to support using a custom header row along with column, filterable, sortable column headers?

Right now, if MultiHeaderTemplate is included, the custom column header code is bypassed.

![image](https://user-images.githubusercontent.com/5921104/124513057-85d80f00-dd9f-11eb-8b69-31a464c23c7f.png)

**Comment by ArgoZhang** [comment]
@DanPFW yes. this is an issue. need to add some code to keeping the filterable sortable in the header. good idea thanks, bro.

**Comment by DanPFW** [comment]
> @DanPFW yes. this is an issue. need to add some code to keeping the filterable sortable in the header. good idea thanks, bro.

one other wish I forgot about.  would it be possible to add a vertical scrolling feature to the table so the header stops at the top of the page.  Something like jquery stickyTableHeaders, which I've used in the past.

**Comment by ArgoZhang** [comment]
@DanPFW set the `Height` will be fixed in the table header. you can check this https://www.blazor.zone/tables/header

**Comment by ArgoZhang** [comment]
@DanPFW now. I add a separate row for the customer header and keep the original header for filterable sortable etc.

![image](https://user-images.githubusercontent.com/22001478/124750033-8e734580-df57-11eb-88e5-5f26975c588b.png)

**Comment by ArgoZhang** [comment]
@DanPFW bump version 5.0.38-beta06
