### ISSUE TITLE
doc: 网站页脚的传送门更新记录链接跳转后内容不对

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#980]
### Document describing which component

Add sample code for {Component}

传送门跳转到：https://gitee.com/LongbowEnterprise/BootstrapBlazor/wikis/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97?sort_id=4062034

实际上这个更新日志的版本跟官网显示不一致，建议匹配上。

**Comment by ArgoZhang** [comment]
@bigsinger 已经更新好啦
