### ISSUE TITLE
bug(SelectTree): SelectTree has a value, the corresponding node is not selected

### ISSUE THREAD

**Issue by Vision-Zhang** [dotnetcore/BootstrapBlazor#988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

SelectTree has a value, the corresponding node is not selected

**Comment by densen2014** [comment]
use `IsLoading` to control render SelectTree 

```
@page "/"
@attribute [TabItemOption(Text = "Index", Closable = false)]
<PageTitle>Index</PageTitle>

@if (!IsLoading)
{
    <SelectTree ShowLabel="false" TValue="string" Items="@ModuleTreeItems" @bind-Value="@ParentId" />
}

@code
{
    private string ParentId = "3";

    private void LoadTree()
    {
        ModuleTreeItems = new()
    {
            new TreeViewItem<string>("0")
            {
                Text = "顶级栏目(Root)",
                IsExpand = true,
                HasChildren = true,
                Items = new List<TreeViewItem<string>>()
            {
                    new TreeViewItem<string>("1")
                    {
                        Text = "栏目1"
                    },
                    new TreeViewItem<string>("2")
                    {
                        Text = "栏目2"
                    },
                    new TreeViewItem<string>("3")
                    {
                        Text = "栏目3"
                    },
                }
            }
        };

        StateHasChanged();
    }

    private List<TreeViewItem<string>> ModuleTreeItems { get; set; } = new();
    bool IsLoading { get; set; } = true;

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();

        // 等待1秒模拟网络请求，如果注释掉这段就可以选中
        await Task.Delay(1000);

        LoadTree();

        IsLoading = false;
    }


}
```

**Comment by tiansfather** [comment]
请问下这个问题是修复了吗？我用最新版9.1.1的包仍然有这个问题
`@page "/"
@attribute [TabItemOption(Text = "Index", Closable = false)]

<SelectTree Items="BindItems" Value="@("文件一")"></SelectTree>
@code{
    private List<TreeViewItem<string>>? BindItems { get; set; } = new List<TreeViewItem<string>>();

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        //没有下面这行就能显示选中值
         await Task.Yield();
         LoadData();

    }

    private void LoadData()
    {
        BindItems =
        [
          new TreeViewItem<string>("目录一")
          {
              Text ="目录一",
              Icon = "fa-solid fa-folder",
              ExpandIcon = "fa-solid fa-folder-open",
              Items =
              [
                  new TreeViewItem<string>("子目录一")
                  {
                      Text ="子目录一",
                      Icon = "fa-solid fa-folder",
                      ExpandIcon = "fa-solid fa-folder-open",
                      Items =
                      [
                          new TreeViewItem<string>("文件一") { Text = "文件一", Icon = "fa-solid fa-file" },
                          new TreeViewItem<string>("文件二") { Text = "文件二", Icon = "fa-solid fa-file" }
                      ]
                  }
              ]
          }
      ];
    }
}`
