### ISSUE TITLE
localize table header tooltips

### ISSUE THREAD

**Issue by DanPFW** [dotnetcore/BootstrapBlazor#99]
the tooltips for sorting/filtering appear to be in a javascript file.  is there a way to localize these?

var tooltipTitle = { unset: "点击升序", sortAsc: "点击降序", sortDesc: "取消排序" };

and

BootstrapBlazor.Components.FilterLogic
public enum FilterLogic
    {
        /// <summary>
        /// 并且
        /// </summary>
        [Description("并且")]
        And,

        /// <summary>
        /// 或者
        /// </summary>
        [Description("或者")]
        Or
    }

**Comment by ArgoZhang** [comment]
@DanPFW fixed. bump version to 5.0.38-beta05. thank you for your contribution

**Comment by ArgoZhang** [comment]
@DanPFW BTW. you can visit https://www.blazor.zone instead of https://argozhang.github.io
